gakonst/ethers-rs

ethers-contract/ethers-contract-abigen/src/contract.rs

disable clippy warnings for solidity contracts with non-standard names (yvVaults, console, etc)
```
❯ cargo check
warning: type `console` should have an upper camel case name
--> bindings/src/console.rs:26:16
|
26 |     pub struct console<M>(ethers::contract::Contract<M>);
|                ^^^^^^^ help: convert the identifier to upper camel case (notice the capitalization): `Console`
|
= note: `#[warn(non_camel_case_types)]` on by default
```
add `allow(non_camel_case_types)` to binding namespace

fix(abigen): clippy warnings on solidity bindings

---

ethers-solc/src/compile/project.rs

remove redundant `with_base_path` call, `Settings::with_base_path` is called as part of `CompilerInput::with_base_path`

chore: remove redundant call

---

Cargo.lock
Cargo.toml
ethers-contract/Cargo.toml
ethers-etherscan/Cargo.toml
ethers-middleware/Cargo.toml
ethers-providers/Cargo.toml
ethers-signers/Cargo.toml
ethers-solc/Cargo.toml

make tokio non optional in non wasm32 targets 
* remove unused tokio-util dep
* bump tokio 0.18 everywhere
* make ethers-providers/tokio obsolete

chore(deps): make tokio required dependency

---

CHANGELOG.md
ethers-core/src/types/i256.rs

Add the arithmetic shift right operation for I256 type.
Add a function to perform asr.

Add Arithmetic Shift Right operation for I256

---

ethers-solc/src/artifacts/mod.rs

Fix 1-3 issues raised here #1325

fix(solc): improve contract metadata bindings

---

ethers-solc/src/artifact_output/configurable.rs
ethers-solc/src/artifacts/bytecode.rs

Ref https://github.com/foundry-rs/foundry/issues/1736
emit an empty bytecode object if file doesn't contain any contract definitions, same behavior as solc does with interfaces.

fix(solc): emit empty bytecode objects for standalone sol files

---

ethers-providers/src/log_query.rs
examples/paginated_logs.rs

`from` and `to` both blocks are inclusive in the filter range which leads to double loading of boundary blocks on pagination.
Load next page from `last + 1` to `last + 1 + page_size`

`get_paginated_logs` fixes and refactoring

---

ethers-contract/ethers-contract-abigen/src/multi.rs

re: #1319 
eg: `console` and `shared_types` were out of order and fail rustfmt check
```diff
❯ cargo +nightly fmt --all -- --check
Diff in ./lib.rs at line 5:
//! These files may be overwritten by the codegen system at any time.
pub mod abstract_strategy;
pub mod account;
+pub mod console;
pub mod contract_test;
pub mod ds_test;
pub mod erc165;
Diff in ./lib.rs at line 21:
pub mod pool;
pub mod safe_helper;
+pub mod shared_types;
pub mod tick_math;
pub mod vault;
Diff in ./lib.rs at line 27:
-pub mod console;
-pub mod shared_types;
```

fix(abigen): non-snake-case modules out of order

---

ethers-solc/src/compile/project.rs

Ref https://github.com/foundry-rs/foundry/issues/1776
this removes the `compile_exact` restriction, which after some investigation can cause some issues in following circumstances:
* paths (or keys) of the contracts in the output differ from the input keys on windows
* if we failed to resolve the complete graph properly (likely due to some parser limitations) this can filter out those contracts we missed but solc includes in the output.

fix(solc): remove compile_exact restriction

---

ethers-contract/ethers-contract-abigen/src/contract.rs

Allows end-users to work around https://github.com/gakonst/ethers-rs/issues/867
This makes it possible to refer directly to generated types when they have the same name (as occurs with event filter types when one contract inherits another).

make abigen-ed modules pub

---

ethers-solc/src/artifact_output/configurable.rs
ethers-solc/src/artifacts/mod.rs

Ref https://github.com/gakonst/ethers-rs/issues/1325#issuecomment-1146226072
use an empty vec for artifacts without any contract definitions instead of default `null`

fix(solc): emit empty vec for empty artifacts

---

ethers-solc/src/artifact_output/mod.rs
ethers-solc/src/artifacts/bytecode.rs

Same as #1253 but for deployed bytecode

feat: source map getters for deployed bytecode

---

ethers-providers/src/call_raw.rs
ethers-providers/src/pending_escalator.rs
ethers-providers/src/pending_transaction.rs
ethers-providers/src/stream.rs

gets rid of a flaky test as seen here https://github.com/gakonst/ethers-rs/runs/6740032643?check_suite_focus=true
by explicitly setting the nonce
there's a possible race condition rn on anvil if multiple tx without nonce are sent via `eth_sendTransaction` because the next nonce is determined by `onchain +num(pool)`
however if multiple tx are sent at the same time they might get the same nonce if the `nextNonce` for an additional tx is determined before the previous was added to the pool.
https://github.com/foundry-rs/foundry/blob/25241a63db896c88b1717c5522ac284724003eb8/anvil/src/eth/api.rs#L547
https://github.com/foundry-rs/foundry/blob/25241a63db896c88b1717c5522ac284724003eb8/anvil/src/eth/api.rs#L569
this could be prevented via an import lock or some additional check against the …

test: set nonce explicitly

---

ethers-providers/src/provider.rs

test: update test with changed state on forked tests

---

ethers-core/src/types/chain.rs
ethers-etherscan/src/lib.rs

add missing id for anvil/hardhat
Ref https://github.com/foundry-rs/foundry/issues/1866

feat: add anvil hardhat chain id

---

ethers-solc/src/artifacts/mod.rs
ethers-solc/tests/project.rs

Fix fields in `UserDoc` and `DevDoc`.
1. Add missing `errors` and `events` fileds for both `UserDoc` and `DevDoc`.
2. Fix `DevDoc`'s `return` field. The name should be `returns` instead of `return`, and the type should be a `BTreeMap<String, String>` instead of `Option<String>`.

fix(solc): fix fields for `UserDoc` and `DevDoc`

---

ethers-providers/src/provider.rs
ethers-solc/src/config.rs

Currently, our convention on foundry is to have scripts in the `script/` folder. However, the folder does not actually belong to the project. It may lead to weird issues, if there's contracts declared inside when verifying contracts.
Alternatively, we could also add a more generic `additional_sources` where by default we add the `script/` folder.

feat(solc): add script/ to project paths

---

ethers-core/src/abi/mod.rs

reexport ethabi as module, this is helpful when there's a clash of names `ethers::AbiError` vs `ethabi::AbiError`

chore: reexport ethabi module

---

ethers-providers/src/provider.rs

Currently `Provider::<Ws>` only exposes `connect` from `Ws` module.
This pull request exposes the `connect_with_auth` function added on #829 .

feat(provider): add option to create ws provider with auth

---

CHANGELOG.md
ethers-solc/src/artifact_output/configurable.rs
ethers-solc/src/artifacts/contract.rs
ethers-solc/src/artifacts/mod.rs
ethers-solc/src/artifacts/serde_helpers.rs
ethers-solc/tests/project.rs

Closes #1325
add an additional `rawMetadata:String` field to artifact output which preserves solc's metadata string

feat(solc): emit additional raw metadata field

---

ethers-providers/src/transports/retry.rs

add traces, useful for debugging whether we're sleeping for a looong time or what (ratelimit) errors we're catching

chore(providers): add traces to retry provider

---

Cargo.lock
ethers-providers/Cargo.toml
ethers-providers/src/pending_escalator.rs
ethers-providers/src/pending_transaction.rs

the wasm delay returns an `io::Error` on `poll`

chore: silence wasm warnings

---

Cargo.lock
ethers-etherscan/Cargo.toml

add getrandom js so it compiles for wasm target

chore: make ethers-etherscan compile for wasm32

---

ethers-solc/src/artifacts/contract.rs
ethers-solc/src/artifacts/mod.rs
ethers-solc/src/compile/output/contracts.rs
ethers-solc/src/compile/output/mod.rs
ethers-solc/tests/project.rs

Adds missing remove functions that make it easier to get a contract via path + name combination
Ref https://github.com/foundry-rs/foundry/pull/2072

feat!(solc): add additional remove functions

---

ethers-providers/src/transports/retry.rs

previously backoff scaled exponentially with number of concurrent request, that grows large very quickly as seen https://github.com/foundry-rs/foundry/issues/2094 where we have backoff timeouts of 20-30seconds
use compute units approach to distribute requests in slots of 1 second (the unit requests are measured in). this should divide requests evenly based on when they were issued, their position in the queue.
@meetmangukiya wdyt?

feat(retry): more sensible backoff calc

---

CHANGELOG.md
ethers-core/src/types/transaction/eip2718.rs

#1400
Make methods like `set_from()` return  `&mut Self` in TypedTransaction

TypedTransaction methods into builder style

---

ethers-contract/ethers-contract-abigen/src/contract/structs.rs
ethers-contract/ethers-contract-derive/src/call.rs
ethers-contract/ethers-contract-derive/src/event.rs
ethers-core/src/abi/human_readable/lexer.rs
ethers-core/src/abi/human_readable/mod.rs
ethers-core/src/abi/struct_def.rs
ethers-core/src/types/block.rs
ethers-core/src/types/trace/mod.rs

Depends on #1416 
Replace `ethabi::Reader::read` with `HumanreadableParser::parse_type` which has better tuple parsing
there's still some potential to unify `AbiParser` and `HumanreadableParser`, reason why they're different types, is that `AbiParser` can resolve custom struct types

refactor(abigen): replace ethabi::Reader

---

ethers-solc/src/artifacts/bytecode.rs

Closes #1422
adds custom serialization for `Bytecode` objects that omits the `0x` prefix. This way the artifact types used by Forge (ConfigurableArtifact) are not affected and will still be output with 0x prefix

fix: remove 0x bytecode object prefix for CompilerOutput

---

CHANGELOG.md
ethers-core/src/types/block.rs
ethers-core/src/types/mod.rs
ethers-core/src/types/other.rs
ethers-core/src/types/transaction/response.rs

Closes #1420
See docs
*  Add `OtherFields` types that will capture unknown fields and provide util functions to deserialize values

feat: capture unknown fields

---

ethers-providers/src/stream.rs

instead of waking up the task when we do a state transition, we poll the next state directly.
Replace `cx.waker().wake_by_ref();` with a loop. This way, the next state is polled immediately and we don't have to rely on the task being polled again right away.

perf(providers): replace wake_by_ref with loop

---

ethers-solc/src/compile/output/info.rs
ethers-solc/src/compile/output/mod.rs
ethers-solc/tests/project.rs

add util function to remove a `Contract` via `ContractInfo`, used in forge's cli args that follow the `<path>:<contractname>` pattern

feat(solc): add remove_contract util function

---

CHANGELOG.md
ethers-solc/src/config.rs
ethers-solc/src/lib.rs

I would like to be able to configure the output directory of the hh style bulidinfo files so that tooling that expects the build info files to be in a specific directory can just work.
Allows for the build info output directory to be configured. It should be backwards compatible by using the same directory that it currently uses by default. Will require a follow up PR in foundry to pass through the config value

feat(ethers-solc): configurable build-info output dir

---

ethers-providers/src/transports/mod.rs
ethers-providers/src/transports/quorum.rs

exports trait and also make default generic type ` Box<dyn JsonRpcClientWrapper>`

chore: export quorum's JsonRpcClientWrapper

---

Cargo.lock
ethers-signers/Cargo.toml

Bump coins-ledger to using hidapi-rusb docs fixes

chore(ethers-signers): bump coins-ledger to 0.6.1

---

Cargo.lock
ethers-core/Cargo.toml
ethers-core/src/types/signature.rs

Deriving fastrlp `Encodable` and `Decodable` traits for types that contain `Signature` would not be possible without implementing `Encodable` and `Decodable` for `Signature`.
* Add `fastrlp` as a dependency to `ethers-core`, meaning this conflicts with #1443 for the time being
* Implement `Hash` on `Signature` (just a convenience impl, not related to fastrlp traits)
* Implement RLP encoding and decoding for `Signature`. This does not encode or decode a RLP header for a signature type, since types that would contain a signature (for example a [signed transaction](https://github.com/ethereum/devp2p/blob/master/caps/eth.md#transaction-encoding-and-validity)) are usually encoded as `[...rest of object, v, r, s]` rather than `[...rest of object, [v, r, s]]`.

Implement fastrlp traits for Signature

---

Cargo.lock
ethers-core/Cargo.toml
ethers-core/src/types/bytes.rs

Many types in ethers and foundry contain the `Bytes` type, implementing fastrlp traits on any of them would be more convenient if `Bytes` implemented fastrlp traits.
`Encodable` and `Decodable` are already implemented for `bytes::Bytes`, we can just defer to those implementations.

Implement fastrlp traits for Bytes

---

ethers-solc/src/artifact_output/mod.rs
ethers-solc/src/artifacts/contract.rs
ethers-solc/src/compile/output/contracts.rs
ethers-solc/src/compile/output/mod.rs
ethers-solc/tests/project.rs
examples/contract_human_readable.rs

unify API to get/remove a contract/artifact for all types that contain mappings for `file -> name -> contract`
* `{find,remove}_first(name)`
* `{find,remove}(file, name)`
* `{find,remove}_contract(ContractInfo{path?, name})`

refactor(solc): unify find/remove api

---

ethers-solc/src/remappings.rs

ensure we print `/` on windows

fix(solc): use path slash for remapping display on windows

---

ethers-core/src/types/transaction/eip2930.rs

To derive `Encodable` and `Decodable` for types that contain `AccessList` and `AccessListItem`, we need to implement them on `AccessList` and `AccessListItem`.
* derive `Encodable` and `Decodable` for `AccessListItem`
* derive `Encodable` and `Decodable` for `AccessList`
* impl Hash for `AccessListItem` (convenience)
* impl Hash for `AccessList` (convenience)

impl fastrlp traits for AccessList

---

CHANGELOG.md
Cargo.toml
scripts/examples.sh
src/lib.rs

Closes #1457
* make optional
* update features, add cfgs

chore: make ethers-solc optional

---

ethers-core/src/types/chain.rs
ethers-etherscan/src/lib.rs

This [PR](https://github.com/gakonst/ethers-rs/pull/1467) contains ci error.
I modified test code.
- Add Unsupported value , Morden(chain id = 2)
- Using Morden in test.

For fix test code, Added morden to chainid as a Mock-like value.

---

ethers-solc/src/artifacts/mod.rs
ethers-solc/src/artifacts/serde_helpers.rs
ethers-solc/src/report/mod.rs

Closes #1473
the `raw_metadata` string was serialized incorrectly, as `String::serialize` will escape.
correct way is `serializer.serialize_str()`

fix(solc): serialize metadata as raw string

---

ethers-providers/src/provider.rs

Authorization is current always `use`d when the target is not `wasm32`, but it's only actually used in the code when the `ws` feature is also enabled.  This causes an annoying error when i `cargo clippy`.
```rs
warning: unused import: `Authorization`
--> <redacted>/ethers-rs/ethers-providers/src/provider.rs:11:25
|
11 | use crate::transports::{Authorization, HttpRateLimitRetryPolicy, RetryClient};
|                         ^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
```
See the code, make it only import when needed
Have not used `#[cfg(...)]` a lot, might've done it a bit more verbose than necessary?

fix unused warning

---

ethers-providers/src/transports/retry.rs
ethers-providers/tests/provider.rs

Closes https://github.com/foundry-rs/foundry/issues/2318
because we previously always serialized `params` in the `RetryProvider`, zero sized types like `()`, which are skipped by `Request` ended up as `params: "null"`, instead of being empty which is incompatible with hardhat for example.
so instead of `{"id":1,"jsonrpc":"2.0","method":"eth_chainId"}` the retry provider was sending `{"id":1,"jsonrpc":"2.0","method":"eth_chainId", "params": "null"}`
add zero size check and delegate to wrapped provider

fix(providers): handle zst params in retry provider correctly

---

ethers-solc/src/config.rs
ethers-solc/src/utils.rs

add `_iter` functions for finding sol/yul files
this allows us to cheaply check if the project has no files

perf(solc): add iterator function for finding sol files

---

CHANGELOG.md
ethers-contract/src/event.rs

Event builder stream & subscribe always discards metadata. This sucks :)
Add a near-identical functions that retain metadata

feature: allow event builder to stream with meta

---

ethers-contract/ethers-contract-abigen/src/contract/common.rs
ethers-core/ethers-derive-eip712/src/lib.rs
ethers-core/src/types/transaction/eip712.rs
ethers-core/src/utils/mod.rs

Closes #1484
* use `Option` for attribute parsing
* use reexported hex in generated code
* reexport `serde_json` and use in generated code

fix(eip712): improve argument parsing

---

ethers-middleware/Cargo.toml
ethers-middleware/src/transformer/ds_proxy/factory.rs

for some reason, when used with rust-analyzer, RA expands the crate that's using `ethers` from another path which leads to wrong crate imports `ethers_core` instead of `ethers::core`. This happens only inside of RA and does not affect `cargo build` but has an effect on intellisense etc...
This issue appears to be due to usage of `EthEvent` derive in `ethers-middleware`, using the expanded code for the event makes RA happy...
Closes #1205
Closes #940
use expanded code instead of using derive macro

refactor: use expanded EthEvent impl

---

CHANGELOG.md
ethers-contract/ethers-contract-abigen/Cargo.toml
ethers-contract/ethers-contract-abigen/src/contract.rs
ethers-contract/ethers-contract-abigen/src/lib.rs
ethers-contract/ethers-contract-abigen/src/multi.rs
ethers-contract/ethers-contract-abigen/src/util.rs
ethers-contract/tests/abigen.rs
ethers-contract/tests/contract.rs

Some contract names [(such as Enum.sol in gnosis)](https://github.com/safe-global/safe-contracts/blob/main/contracts/common/Enum.sol) are rust reserve words that cause invalid bindings to be generated.

fix(abigen): contract names can be reserve words

---

ethers-etherscan/src/account.rs

Ref #1492
@matilareo wasn't able to reproduce this, maybe just a flake? this test works if a working API key is set, could you try on your end with the account in question?
* add working avalanche test

test: add avalanche test

---

CHANGELOG.md
ethers-core/src/types/txpool.rs
ethers-providers/tests/txpool.rs

The previously used type didn't match the type returned by https://geth.ethereum.org/docs/rpc/ns-txpool#txpool_content a 100%
especially the tx hash
use new type that represents it completely

fix: use correct model for txpool_content endpoint

---

CHANGELOG.md
ethers-solc/src/artifact_output/mod.rs
ethers-solc/src/compile/output/contracts.rs
ethers-solc/src/lib.rs
ethers-solc/tests/project.rs

Closes #1487
this changes how output files are computed and now takes possible conflicts into account.
this doesn't change how artifacts were emitted up to now and only adds extra logic if there are conflicting files.
maybe there'll be some edge cases with caching, but hard to anticipate at this point.
this also passes all existing foundry tests with a patched version
change emit logic:
1. compute all output files as before but keep track of conflicting contracts
2. adjust conflicting paths by finding a unique alternative path, traversing the sol file and prepending the parent dir(s) to the output file. this will always find a unique output path

feat(solc): handle conflicting artifacts properly

---

ethers-solc/src/artifacts/mod.rs
ethers-solc/test-data/foundryissue2462.json

Closes https://github.com/foundry-rs/foundry/issues/2462
the storage layout fields are not really documented but were missing some common fields, the other HashMap should catch everything else

fix(solc): make StorageLayout json parsing lossless

---

CHANGELOG.md
ethers-etherscan/src/account.rs

Etherscan supports querying 1155 token transfer events: https://docs.etherscan.io/api-endpoints/accounts#get-a-list-of-erc1155-token-transfer-events-by-address. However, this was missing from the etherscan client.
Added a function `get_erc1155_token_transfer_events` to query this. There is already the corresponding functions for ERC20 and ERC721.

feat(etherscan): erc1155 token transfer events endpoint

---

ethers-contract/ethers-contract-abigen/src/contract/events.rs
ethers-contract/ethers-contract-abigen/src/contract/methods.rs
ethers-contract/ethers-contract-derive/src/abi_ty.rs
ethers-contract/ethers-contract-derive/src/abigen.rs
ethers-contract/ethers-contract-derive/src/call.rs
ethers-contract/ethers-contract-derive/src/codec.rs
ethers-contract/ethers-contract-derive/src/event.rs
ethers-contract/tests/it/common/derive.rs

Closes #1526
use fully qualified path for Result to prevent clash if a struct is named `Result`

fix: use fully qualified path for Result

---

ethers-core/src/types/serde_helpers.rs
ethers-etherscan/src/account.rs
ethers-etherscan/src/gas.rs
ethers-etherscan/src/transaction.rs

Closes #1507
the etherscan API returns numbers as strings 
```json
{
"blockNumber": "2228258",
"timeStamp": "1473433992",
"hash": "0x5f2cd76fd3656686e356bc02cc91d8d0726a16936fd08e67ed30467053225a86",
"nonce": "10",
"blockHash": "0x466dbced0a98e1b0490f787b51570850c8347960a4e92bd89acf85299e4cb9dc",
"from": "0x4e83362442b8d1bec281594cea3050c8eb01311c",
"contractAddress": "0xecf8f87f810ecf450940c9f60066b4a7a501d6a7",
"to": "0xac75b73394c329376c214663d92156afa864a77f",
"value": "101000000000000000000",
"tokenName": "",
"tokenSymbol": "",
"tokenDecimal": "1",
"transactionIndex": "10",
"gas": "1000000",
"gasPrice": "20000000000",
"gasUsed": "93657",
"cumulativeGasUsed": "684715",
"input": "deprecated",
"confirmations": "13002487"
}
```
wich results in wrong values

fix(etherscan): support stringified numbers in response

---

CHANGELOG.md
ethers-solc/src/artifacts/output_selection.rs

It is a property on the deployed bytecode object
on the compiler output. This is the precursor for
`forge inspect <contract-name> immutableReferences`.
See https://docs.soliditylang.org/en/v0.8.15/using-the-compiler.html?highlight=immutable#output-description

ethers-solc: add immutableReferences output selector

---

Cargo.lock
Cargo.toml
ethers-contract/Cargo.toml
ethers-contract/ethers-contract-abigen/Cargo.toml
ethers-contract/ethers-contract-derive/Cargo.toml
ethers-core/Cargo.toml
ethers-core/ethers-derive-eip712/Cargo.toml
ethers-etherscan/Cargo.toml
ethers-middleware/Cargo.toml
ethers-providers/Cargo.toml
ethers-signers/Cargo.toml
ethers-solc/Cargo.toml
examples/ethers-wasm/Cargo.toml

reverts 97bdcb9d826d5636c99dc97d6a625b30014354c0 that somehow removed all dev-deps

revert: add back dev-deps

---

ethers-providers/src/transports/retry.rs

add some minor retryclient docs

docs: some additional retry docs

---

ethers-providers/src/transports/http.rs

uses `resp.bytes()` instead of `resp.text()` 
[text](https://docs.rs/reqwest/latest/reqwest/struct.Response.html#method.text) decodes the body and scans the entire body. this is a bit redundant for json since deserialization is expected to fail if anyway
reqwest's [json](https://docs.rs/reqwest/latest/reqwest/struct.Response.html#method.json) function is also just this:
```rust
pub async fn json<T: DeserializeOwned>(self) -> crate::Result<T> {
let full = self.bytes().await?;
serde_json::from_slice(&full).map_err(crate::error::decode)
}
```
get bytes and deserialize from_slice, and only convert to String in error case

perf(providers): get response as bytes

---

CHANGELOG.md
ethers-core/src/types/chain.rs
ethers-etherscan/src/lib.rs

Missing support of [Aurora](https://aurora.dev/) in Foundry.
Added Aurora and Aurora Testnet to the list of known chains.
Documentation about aurora: https://doc.aurora.dev/getting-started/network-endpoints

Add support to Aurora network

---

ethers-signers/src/wallet/mod.rs

I implemented `Signer`, but realized that I had to copy a large amount of code (Wallet and more) just to get a working implementation.
A plain constructor for `Wallet` allows other implementation of `Signer` to use this code.

Add a simple constructor for Wallet

---

ethers-contract/ethers-contract-abigen/src/contract/methods.rs
ethers-contract/tests/it/abigen.rs
ethers-contract/tests/solidity-contracts/LargeStruct.json

Closes #1509
resolve output types correctly when we expand the function output params

fix(abigen): resolve output struct types correctly

---

CHANGELOG.md
ethers-contract/ethers-contract-abigen/src/contract.rs
ethers-contract/ethers-contract-abigen/src/contract/common.rs
ethers-contract/ethers-contract-abigen/src/contract/errors.rs
ethers-contract/ethers-contract-abigen/src/contract/methods.rs
ethers-contract/ethers-contract-abigen/src/contract/structs.rs
ethers-contract/ethers-contract-abigen/src/lib.rs
ethers-contract/ethers-contract-derive/src/calllike.rs
ethers-contract/ethers-contract-derive/src/error.rs
ethers-contract/ethers-contract-derive/src/lib.rs
ethers-contract/ethers-contract-derive/src/utils.rs
ethers-contract/src/error.rs
ethers-contract/src/lib.rs
ethers-contract/tests/it/abigen.rs
ethers-contract/tests/it/common/derive.rs
ethers-core/src/abi/human_readable/lexer.rs
ethers-core/src/abi/human_readable/mod.rs
ethers-core/src/abi/mod.rs

Add support for custom errors
* introduce new `EthError` trait, basically same as `EthCall` with derive impl
* unify some derive code for `EthCall` and `EthError` in `calllike` 
* support human readable error parsing
* generate bindings for custom solidity errors, if there are more than 1 error in the abi, we generate an error enum `enum <name>Errors {..` see Seaport test

feat: add EthError trait and derive

---

ethers-providers/src/provider.rs
ethers-providers/src/transports/http.rs

expose the `Url` for HTTP provider, this way we can get and adjust the URL the Http connects to
ideally this should be included in the general abstraction, ref #1267

feat(provider): expose url for http

---

ethers-providers/src/pending_transaction.rs
ethers-providers/src/provider.rs

ref https://github.com/foundry-rs/foundry/pull/2579
Pending transaction was not respecting the provider interval duration.

fix(provider): use provider interval on PendingTransaction

---

ethers-core/src/types/chain.rs
ethers-providers/src/lib.rs
ethers-providers/src/provider.rs
ethers-providers/src/stream.rs

moved from https://github.com/foundry-rs/foundry/pull/2559
* add `ProviderExt` trait for `HttpProvider`
this is currently sealed to prevent impl outside of ethers until we finalize https://github.com/gakonst/ethers-rs/pull/1267

feat: add ProviderExt trait

---

CHANGELOG.md
Cargo.lock
ethers-contract/ethers-contract-abigen/Cargo.toml
ethers-contract/ethers-contract-abigen/src/filter.rs
ethers-contract/ethers-contract-abigen/src/lib.rs
ethers-contract/ethers-contract-abigen/src/multi.rs

Add filtering support for `MultiAbigen`
Ref https://github.com/foundry-rs/foundry/issues/2605
* Add helper struct(s) to create inclusion/exclusion filters by exact name or regex

feat(abigen): add contract filter

---

ethers-solc/src/project_util/mod.rs
ethers-solc/tests/project.rs

In `add_basic_lib` and `add_basic_source` functions, the `format!` parameters are written in the wrong order. This creates contracts with "pragma solidity Contract.sol" and declared "contract ^0.8.0 {}".
Swap the two parameters (after the string literal) passed to the `format!` macro in the mentioned functions.
This is just a bug fix, so I don't think adding docs and updating changelog is necessary. If they are, please let me know.

solc: fix bug in basic lib and basic contract generation

---

ethers-core/src/types/trace/mod.rs

Would be cleaner if foundry used the same type for ```trace_replayTransaction``` but it doesn't implement Deserialize.
Implement Deserialize.

feat(TraceType+Deserialize): added Deserialize to TraceType

---

Cargo.lock
ethers-solc/Cargo.toml

svm 0.2.15 and svm-builds 0.1.7 were published after having update the solc binaries for 0.8.15 and 0.8.16 to support Z3 SMT solver but with statically linked Z3. This will resolve issues experienced by Foundry users who do not have Z3 installed, due to Z3 previously being dynamically linked for the solc builds.

chore: update svm and svm-builds

---

ethers-solc/src/compile/mod.rs
ethers-solc/src/compile/project.rs
ethers-solc/src/config.rs
ethers-solc/src/lib.rs
ethers-solc/src/resolver/mod.rs
ethers-solc/src/utils.rs
ethers-solc/tests/project.rs

Closes https://github.com/foundry-rs/foundry/issues/2706
Resolve absolute imports like `src/interfaces/File.sol` in nested libs.
try to find the existing file be scanning the `cwd` until we reach the `lib` folder, see docs

feat(solc): resolve absolute imports in libraries

---

ethers-solc/src/lib.rs

ensure that the `--base-path` is not also used for `--include-path`

fix(solc): ensure base-path is not include-path

---

Cargo.lock
ethers-core/Cargo.toml

https://github.com/rust-ethereum/ethabi/pull/276 landed in `17.2.0`

chore: bump ethabi

---

ethers-providers/src/ens.rs
ethers-providers/src/provider.rs

ref https://github.com/foundry-rs/foundry/issues/2764
> seems like the domain ox63616e.eth has its resolver set to the WETH contract, ultimately leading to decoding a '0x' address
Make sure that the resolver set is a valid one that supports `name(bytes32)` or any other selector that might be passed.

fix(providers): validate address resolver

---

ethers-core/src/types/filter.rs

I was getting some errors when using the `go-ethereum/ethclient` with Anvil/Foundry ; the issue was that when calling `eth_getLogs` with no `topics` set, `go-ethereum` would still pass the `topics` set to `null`: cf. https://github.com/ethereum/go-ethereum/blob/c4ab7d229117fdaa24292d84c1d450a727cb3e9f/ethclient/ethclient.go#L393
Wrapping the topics in the Filter deserialize method in another `Option<..>` fixes the issue ; an added test ensures it does.

fix(ethers-core): Deserialize a Filter request with `topics == null`

---

ethers-contract/tests/it/abigen.rs

comment out the test that relies on etherscan API key env var which is very annoying, especially for new contributors because this will lead to compiler errors if not set or if the API is not responding

test: comment out etherscan abigen! test

---

ethers-providers/src/lib.rs

It is hard to create a wrapper error type containing errors returned from a `LogQuery`. The `LogQuery` type is public and accessible through `ethers::providers::LogQuery`, but the `LogQueryError` type is not. It can in principle be accesses through the `Stream` trait as such:
```
type LogQueryError<'a> = <LogQuery<'a> as Stream>::Item::Error;
```
but that introduces an unnecessary lifetime parameter and feels pretty hacky.
```
pub use log_query::{LogQuery, LogQueryError};
```

Export LogQueryError

---

ethers-core/src/types/proof.rs

make EIP1186ProofResponse fields public 
change nonce type to U64, which matches geth
https://github.com/ethereum/go-ethereum/blob/23ac8df15302bbde098cab6d711abdd24843d66a/ethclient/gethclient/gethclient.go#L93-L94

chore: make proof response fields pub

---

ethers-core/Cargo.toml
ethers-core/src/utils/mod.rs

Closes https://github.com/foundry-rs/foundry/issues/2830
* use `Decimal::Ten.pow()` instead of `10u64.pow`

fix: support formatting large units

---

ethers-core/src/types/filter.rs

Add `Filter::events(iter)` to set [A,B,..] for topic0

feat: add events function to set multiple event filter

---

ethers-solc/src/error.rs
ethers-solc/src/resolver/mod.rs

improve the `"Failed to resolve file: does not exist...` error with file path and import path

chore(solc): improve file not found error

---

ethers-contract/src/call.rs
ethers-middleware/src/signer.rs
ethers-providers/src/lib.rs
ethers-providers/src/provider.rs

Cf. discussion in https://github.com/foundry-rs/foundry/pull/2839 
I think that the automatic generation of access-list isn't a wanted feature, for a couple of reasons:
1. There is no way to disable it when using a compatible tx type (if it's set to empty it's always queried)
2. There is no good solution to compare the gas usages. As per other implementations (Geth, Nevermind), the returned GasUsed is the actual transaction gas usage, and not the gas estimation (which wouldn't include saved gas from using AL).
Thus I think it should be a manual step.
Disable the automatic fetching of AL when filling a transaction.
I also added an optional block parameter to the gas estimation methods, since it's available on every node implementation. It also rightly use it when a block is passed to …

Don't auto-generate an AccessList when sending/filling a tx

---

CHANGELOG.md
ethers-solc/src/artifact_output/mod.rs
ethers-solc/src/cache.rs
ethers-solc/src/compile/output/contracts.rs
ethers-solc/src/compile/project.rs
ethers-solc/src/lib.rs
ethers-solc/tests/project.rs

Closes https://github.com/foundry-rs/foundry/issues/2843
There was the possibility of a conflict upon a partial recompile, since weren't aware of already existing (conflicting) artifacts.
So for a layout like:
```text
src
├── a.sol
└── inner
└── a.sol
```
we first created output:
```text
out
├── a.sol/A.json
└── inner
└── a.sol/A.json
```
but if we recompiled with only `inner/a.sol` changed it would land at `out/a.sol/A.json`, overwriting the conflicting file
introduce `OutputContext` that contains the cache, this way we can lookup if a file already has a artifact. this way we ensure we have consistent output paths even if we only recompile a single file.
added test and confirmed with patched forge: https://github.com/montyly/foundry-collision

fix(solc): use cache context when determining artifact files

---

ethers-core/src/types/mod.rs
ethers-core/src/types/syncing.rs
ethers-providers/src/lib.rs
ethers-providers/src/provider.rs

Closes #1623
geth returns additional fields which broke the untagged deserialize
* move `SyncingSatus` to ethers-core
* add `SyncProgress`  that captures geth's additional fields
* manual serde impl

fix: extend eth_syncing response type and serde

---

ethers-providers/src/pubsub.rs
ethers-providers/src/transports/ws.rs

add some helpful traces used while debugging https://github.com/gakonst/ethers-rs/issues/1620

chore: add some traces

---

ethers-solc/src/artifact_output/files.rs
ethers-solc/src/artifact_output/mod.rs
ethers-solc/src/compile/output/contracts.rs
ethers-solc/tests/project.rs

Followup to https://github.com/gakonst/ethers-rs/pull/1621
As reported here https://github.com/foundry-rs/foundry/issues/2843#issuecomment-1221326854
there still can be conflicts for cases like `a.sol` and `inner/A.sol`, this was because we used  `PathBuf` as the key which is case sensitive.
* add new helper type `MappedArtifactFiles` that now uses lowercase(PathBuf.to_string()) as the key type so that we treat the output candidate `a.sol/A.json` and `A.sol/A.json` as the same file. (`a.sol/a.json`)

fix(solc): consider case sensitive conflicting artifact paths

---

Cargo.lock
ethers-middleware/Cargo.toml
ethers-middleware/src/gas_oracle/gas_now.rs
ethers-middleware/src/gas_oracle/middleware.rs
ethers-middleware/src/gas_oracle/mod.rs
ethers-middleware/src/gas_oracle/provider_oracle.rs

This adds the `ProviderOracle` that allows runtime selection between provider gas methods and gas oracles. Such runtime selection is very useful for building stacks that work on multiple chains, such as production and local test.
~~It also adds a `default_for_chain` constructor that looks at the `chain_id` and tries to build a sensible default. This is a bit proof-of-concept. It would be nice to add a builder pattern where you can provide api-keys.~~
Architecturally this all feels a bit off to me. `ProviderOracle` exists basically because `GasOracle` and `Middleware` overlap in functionality. The `Provider` implementation also does quite a bit of magic under the hood to get EIP1559 estimates. IMHO it would be cleaner if this was all done through something like GasOracle's. But simply …

More gas oracles

---

ethers-providers/src/transports/retry.rs

Ref https://github.com/foundry-rs/foundry/issues/2755
currently, the `RetryProvider` only retries based on the policy which is considered to application-specifc (mainly rate limit for various providers).
errors due to timed out requests are not automatically retried.
Since errors due to connection errors don't really fit the `Policy`, the provider now supports a separate `timeout_retries` that targets `reqwest::TimedOut` or other connection related status code errors, (same as cargo does) https://github.com/rust-lang/cargo/blob/a77ed9ba87bfeaf3c2758a5b291876c65f734c39/src/cargo/util/network.rs#L77

feat: support retrying connection errors

---

ethers-providers/src/transports/http.rs
ethers-providers/src/transports/retry.rs

the `JsonRpcClient::Error` is already `Into<ProviderError>`, which we can use to simplify retry error handling, no need for downcasting which might not return the right result if wrapped in another enum
this also converts the `HttpErr(reqwest)` into the corresponding `ProviderError::Http(reqwest)` variant

fix: handle provider error correctly

---

ethers-providers/src/transports/mock.rs
ethers-providers/src/transports/quorum.rs

Currently the `QuorumProvider` fails for the very simple case of `provider.request("eth_blockNumber", ())`.
Example code which fails:
```rs
use ethers::prelude::{Http, JsonRpcClient, Quorum, QuorumProvider, WeightedProvider, U64};
#[tokio::main(flavor = "current_thread")]
async fn main() {
let provider1 = "http://127.0.0.1:8545".parse::<Http>().unwrap();
let provider2 = "http://127.0.0.1:8545".parse::<Http>().unwrap();
let provider3 = "http://127.0.0.1:8545".parse::<Http>().unwrap();
let quorum_provider = QuorumProvider::builder()
.add_providers(
[&provider1, &provider2, &provider3]
.into_iter()
.cloned()
.map(WeightedProvider::new),
)
.quorum(Quorum::Majority)
.build();
let block_number: U64 = quorum_provider
.request("eth_blockNumber", ())
.await
.expect("Failed to get block number"); …
```

fix(providers): QuorumProvider zero-parameter json Value handling

---

ethers-core/src/types/transaction/response.rs

Ref https://github.com/foundry-rs/foundry/issues/2888
apparently the `to` field should be `null` or an address
geth also does not omit it if empty 
https://github.com/ethereum/go-ethereum/blob/81bd998353789980a6ef3e493b3562750b416d96/core/types/transaction_marshalling.go#L43

fix: dont skip null to field

---

CHANGELOG.md
ethers-core/src/types/mod.rs
ethers-etherscan/src/account.rs

The response to the `get_transactions` method on the etherscan client has a number of issues:
1. `methodId` and `functionName` fields are missing.
2. A number of fields are of the type `GenesisOption`, but from my investigations only `hash` and `from` can have this format.
3. `input` does not need to be wrapped in an option. From my investigation, the response from etherscan is always `"0x"` for empty input, and the serde implementation for the `Bytes` type will process this as an empty byte array.
1. Add the missing fields.
2. Replace `GenesisOption` with `Option` on fields that cannot start with `GENESIS`.
3. Remove the option wrapper for the `bytes` field.

Fix 'get_transactions' response.

---

CHANGELOG.md
ethers-etherscan/src/account.rs
ethers-etherscan/src/contract.rs
ethers-etherscan/src/gas.rs
ethers-etherscan/src/lib.rs
ethers-etherscan/src/source_tree.rs
ethers-etherscan/src/transaction.rs

Derive Debug, Clone and Copy on all appropriate Structs and Enums.
I needed to be able to clone `TxListParams` and noticed that a lot of the structs and enums in ethers-etherscan do not implement Debug, Clone and Copy.
Derive the above traits as appropriate.

ethers-etherscan: derive debug, clone and copy

---

ethers-core/src/types/chain.rs

Whenever `Chain` enum is matched, all its variant should be handled explicitly. This will help developers get assistance from the compiler to figure out all places that they need to take care if a new chain is added.
Avoid wildcard pattern (`_`) while matching chain.

nit: Explicitly handle all chains on match

---

CHANGELOG.md
ethers-contract/ethers-contract-abigen/src/contract/methods.rs
ethers-contract/ethers-contract-abigen/src/contract/types.rs
ethers-contract/tests/it/abigen.rs
ethers-core/src/abi/codec.rs
ethers-core/src/abi/human_readable/lexer.rs
ethers-core/src/abi/mod.rs
ethers-core/src/types/mod.rs
ethers-core/src/types/uint8.rs

Closes #1636
* add `Uint8` wrapper type, that's only used for `[Uint8; <>] arrays

feat: add uint8 type

---

ethers-contract/src/lib.rs
ethers-contract/src/multicall/mod.rs
ethers-contract/src/multicall/multicall_contract.rs
ethers-contract/tests/it/contract.rs
ethers-contract/tests/solidity-contracts/Multicall.sol
ethers-contract/tests/solidity-contracts/SimpleRevertingStorage.sol

feat(contract): update Multicall to Multicall3

---

ethers-contract/tests/it/abigen.rs
ethers-core/src/utils/anvil.rs
ethers-middleware/tests/signer.rs
examples/contract_human_readable.rs
examples/contract_with_abi.rs
examples/contract_with_abi_and_bytecode.rs
examples/ethers-wasm/tests/contract_with_abi.rs
examples/local_signer.rs

anvil now enforces chain id https://github.com/foundry-rs/foundry/pull/2995, whereas ganache does not.
this broke the tests
hardhat also enforces correct chain id, https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md 
implemented [_validateTxV](https://github.com/ethereumjs/ethereumjs-monorepo/blob/2d60261422437c2353e5b547dbde610494d37c5e/packages/tx/src/legacyTransaction.ts#L361)
added test to confirm that
* set chain id where required
* expose `Anvil::chain_id`
it'd be nice if the `Anvil` instance could just return a Wallet directly, but this is currently not possible since `Wallet` is not part of the core crate...
perhaps moving  + feature gating would be possible, but a bit of a hassle...

fix: set chain id explicitly

---

ethers-contract/src/multicall/mod.rs
ethers-core/src/types/chain.rs
ethers-etherscan/src/lib.rs

This adds support for Optimism Goerli now that Optimism Kovan will be deprecated.
Add OptimismGoerli object and respective chain id, 420

feat: add support for Optimism Goerli

---

ethers-contract/ethers-contract-abigen/src/contract/methods.rs
ethers-contract/ethers-contract-abigen/src/util.rs
ethers-contract/tests/it/abigen.rs
ethers-contract/tests/solidity-contracts/large-array.json

Closes #1640
this adds a check whether default can be derived for a call/output struct
rust-std auto derives default only for arrays len <=32
I think it's fine to skip the derive if not possible, since this generates code, the user still can implement it manually
skip `derive(Default)` of a type contains a fixed array with more than 32 elements

fix(abigen): only derive default of no arrays len > 32

---

ethers-core/src/types/transaction/response.rs

Closes https://github.com/foundry-rs/foundry/issues/3045
continues https://github.com/gakonst/ethers-rs/pull/1631
> While testing with brownie I came across this issue when using anvil. Basically it's the same as [in this ethereum.stackexchange question](https://ethereum.stackexchange.com/questions/127948/deploy-smartcontract-to-local-hyperledger-besu-network-using-brownie).
As described in the link, anvil isn't following the [standard JSON-RPC API](https://eth.wiki/json-rpc/API#eth_gettransactionbyhash). Pending transactions should return the fields blockNumber, blockHash and transactionIndex with a value of null, but they are not present. The to field correctly exists in my tests with a value of null though.
use `serde(default)` and remove the skip

fix: emit null transaction fields

---

CHANGELOG.md
ethers-core/src/types/bytes.rs

Debug output for `Bytes` (eg calldata) currently looks like `Bytes(b"|\x02R\0\0\x93")` while debug format for other core types (eg Address) show a hex literal. This can make for a painful debugging experience when using external tools.
Use hex literal output in `Bytes` `Debug` implementation eg `Bytes(0xdead)`

feat(core): improved debug format for Bytes

---

CHANGELOG.md
ethers-core/src/types/transaction/response.rs

RLP encoding for `TransactionReceipt` is broken, since it directly encoded the `status` field, which is an optional.
Use `rlp_opt` instead of `rlp_append` for the `status` field.

fix: incorrect encoding on TransactionReceipt

---

ethers-solc/src/artifacts/mod.rs

https://github.com/gakonst/ethers-rs/pull/1655 introduced `MetadataSettings.via_ir`, which should be optional, since it doesn't exist in older versions, hence some test broke

fix(solc): via-ir should be optional

---

ethers-solc/src/artifact_output/mod.rs
ethers-solc/src/cache.rs

manually identified that reading cached artifacts is a big part of pre-processing.
```console
2022-09-04T23:21:01.777551Z TRACE compile: ethers_solc::cache: reading artifacts from cache...
2022-09-04T23:21:03.309518Z TRACE compile: ethers_solc::cache: read 68 artifacts from cache
```
* read artifacts in parallel
* Add Send+Sync restriction to `trait Artifact`, which shouldn't have any downsides

perf(solc): read artifacts in parallel

---

CHANGELOG.md
ethers-contract/src/multicall/mod.rs
ethers-contract/tests/it/contract.rs

`Multicall` has some extra helper methods such as `getBlockHash` or `getBlockNumber`.
Add these methods to `Multicall` in the same style of the already present `eth_balance_of`. Decided against adding the `allow_failure` param on most of these helper calls as they are base opcodes included in all EVM implementations (except `BASEFEE`) so they shouldn't fail if we're using the base Multicall contract.
Also did some small docs changes and refactoring.

feat(contract): add extra Multicall helper methods

---

CHANGELOG.md
ethers-core/src/types/transaction/response.rs

`Transaction` is improperly decoding legacy transactions as it assumes that transactions are always inside of 2718 envelopes.
Check if the `transaction_type` field is `None` (signifying a legacy tx). In this case the full tx bytes should be passed to the decoder without snipping the first byte as is done for 2718 style txs.

fix: legacy transaction rlp decoding

---

ethers-core/src/utils/units.rs

Currently it's not possible to pass `ethers_core::utils::Units` to its own `parse_units` due to the Copy trait bound
Add derives for Units as well as some missing impls

fix(core): add derives, impls for Units

---

CHANGELOG.md
ethers-core/src/types/trace/geth.rs

Geth debug_traceTransaction was originally implemented in the following [commit](https://github.com/gakonst/ethers-rs/commit/cb7e58664576c220ed656bfa191ac4065a052cce). Types implemented for ```memory``` and ```stack``` where both ```strings``` when they should have been ```H256``` and ```U256``` respectively. This wasn't a breaking issue at the time as everything technically worked perfectly fine with ```strings```.  There is currently no unit tests for this tracing as per the original pull [request](https://github.com/gakonst/ethers-rs/pull/1469) this would require an rpc connection that supports the ```debug_traceTransaction``` method. About a month later the following [commit](https://github.com/gakonst/ethers-rs/commit/7c265500646c301b12a6a1fe00eec032b1908396) was pushed which added a …

fix: geth trace types

---

ethers-solc/src/artifacts/mod.rs

address https://github.com/foundry-rs/foundry/issues/3173
Omit `remappings` & `revertStrings` for yul compiler input

fix(solc): omit `remappings` & `revertStrings` for yul compiler input 

---

ethers-core/src/utils/anvil.rs

reading from stderr and stdout continuously is surprisingly hard because both are blocking operations.
this will inherit stderr to at least show the panic message if it panics, alternatively we could spawn an stderr reader to another thread and read the stderr output there, but this will also block and hang if anvil never prints to stderr, so unsure if worth it to have a background thread that may live for the entire program just for monitoring the anvil launch...

chore: inherit stderr for anvil

---

ethers-core/src/types/trace/geth.rs

we went from `Vec<u8>` to `Vec<H256>` here https://github.com/gakonst/ethers-rs/pull/1682 but the actual data is a 32byte string containing memory chunks of 32byte:
https://github.com/ethereum/go-ethereum/blob/366d2169fbc0e0f803b68c042b77b6b480836dbc/eth/tracers/logger/logger.go#L450-L452

fix: geth structlog memory

---

ethers-solc/src/config.rs
ethers-solc/src/lib.rs

currently, the default `include_path`s contain the sources, test & script dirs, which lead to the possibility of ambiguous imports like `import 'interface/IContract.sol';` given the project tree
```text
- src
-- Contract.sol
-- interface
--- IContract.sol
```
while it is possible to make the `Graph` resolve such import paths properly, it leads to ambiguity while trying to reconstruct sources for standard json input, since the same node can be imported as `interface/IContract.sol` and `src/interface/IContract.sol`
more info [here](https://docs.soliditylang.org/en/v0.8.13/path-resolution.html#initial-content-of-the-virtual-filesystem)
remove default include paths since they are all covered by the base path

fix(solc): remove default include paths

---

ethers-providers/src/transports/retry.rs

we saw the `header not found` error more frequently,
```console
JsonRpcError(
JsonRpcError {
code: -32000,
message: "header not found",
data: None,
},
)
```
there's a long history in this metamask issue https://github.com/MetaMask/metamask-extension/issues/7234
the infura forum has some threads for this error as well but no solution, apparently this is linked to load balancing.
this fix will retry this errors again, tested locally and it prevents these issues on infura

feat: retry infura's header not found

---

ethers-core/src/types/trace/geth.rs

https://github.com/foundry-rs/foundry/issues/3206
Left – ours, right – geth
Left – ours, right – geth

fix(core): GethTrace shouldn't have 0x prefix for return_value

---

CHANGELOG.md
ethers-providers/src/provider.rs

Upon testing using a newer version of `ethers-rs`, I ran into issues estimating gas for Optimism chains (i.e. mainnet & optimism kovan). After some digging, it seem like this PR https://github.com/gakonst/ethers-rs/pull/1619 made a change to the way `eth_estimateGas` RPCs are constructed that breaks gas estimation for Optimism chains.
Previously, no block ID was provided when estimating gas, and this resulted params length of 1, where the element at index 0 was the tx to estimate. E.g. this works as expected against Optimism / OptimismKovan (this is just estimating a DAI transfer on mainnet Optimism):
```
$ curl -H "Content-Type: application/json" --data "{\"jsonrpc\":\"2.0\",\"method\":\"eth_estimateGas\",\"params\":[{\"from\":\"0x82e64f49ed5ec1bc6e43dad4fc8af9bb3a2312ee\",\"to\":\"0xDA10 …
```

fix(providers): don't default to "latest" block ID for `eth_estimateGas`

---

ethers-providers/src/transports/retry.rs

adds another retry error for infura:
```
JsonRpcClientError(JsonRpcError(JsonRpcError { code: -32005, message: "daily request count exceeded, request rate limited", data: Some(Object({"rate": Object({"allowed_rps": Number(1), "backoff_seconds": Number(30), "current_rps": Number(1.0666666666666669)}), "see": String("https://infura.io/dashboard")})) }))
```
https://github.com/foundry-rs/foundry/actions/runs/3073310479/jobs/4965399038
this error contains the requested `backoff` in the error response.
Added `RetryPolicy::backoff_hint` to try to extract the requested backoff from an error and use that instead

feat: detect requested backoff

---

CHANGELOG.md
ethers-core/src/types/signature.rs

Lack of clarity around safety of casting `sig.v` from `u64` to `u8`.
Add comment explaining why it's safe :)

docs: add comment about safety of u8 -> u64 cast in signature

---

ethers-core/src/utils/anvil.rs

To close #1660. Anvil's startup time may exceed 5000 millisecond and cause timeout because of additional task to setup a fork.
Double the startup time as the same as geth. If still cause panic, it should be other problem.

feat(ethers-core): double anvil startup time

---

Cargo.lock
ethers-core/ethers-derive-eip712/Cargo.toml
ethers-core/ethers-derive-eip712/src/lib.rs
ethers-core/ethers-derive-eip712/tests/derive_eip712.rs

Should close https://github.com/gakonst/ethers-rs/issues/1713
depend on `ethers_contract_derive` crate instead and rm unused crates
@DaniPopes could you please check this?

chore: trim eip712 deps

---

ethers-solc/src/artifact_output/mod.rs
ethers-solc/src/compile/output/contracts.rs
ethers-solc/src/compile/output/mod.rs

add another wrapper helper type for handling artifacts
this gets rid of a lot of `BTreemap<ArtifactId` pollution in foundry's codebase

chore(solc): add another artifacts helper type

---

ethers-contract/ethers-contract-abigen/src/contract/common.rs
ethers-contract/src/contract.rs
ethers-contract/src/multicall/multicall_contract.rs
ethers-core/src/types/i256.rs
ethers-signers/src/ledger/app.rs

`Contract`'s getters are bound to the `Middleware` trait which blocks `Debug` from being derived automatically for structs that hold abigen'd contracts, eg:
```rust
abigen!(MyContract, "...")
// Clone works fine
// Cannot derive Debug: 'M: Middleware is not satisfied'
#[derive(Clone, Debug)]
struct<M> MyStruct<M> {
contract: MyContract<M>
}
```
Move to new impl block

fix(contract): relax Middleware trait bound for getters

---

Cargo.lock
ethers-contract/Cargo.toml
ethers-contract/tests/it/abigen.rs
ethers-contract/tests/it/contract.rs
ethers-signers/Cargo.toml
ethers-signers/src/ledger/app.rs
ethers-signers/src/trezor/app.rs

https://github.com/gakonst/ethers-rs/issues/1713#issuecomment-1250400755
- contract: Remove middleware, not needed since accounts are unlocked on Anvil
- signers: contract import was used only for the derive macros

fix(contract, signers): cyclic deps

---

ethers-core/src/types/transaction/request.rs

followup for #1733 
use correct field constant, celo feature

fix: use correct tx field const

---

ethers-core/src/types/transaction/response.rs

Closes #1732
fixed remaining issues in `Transaction::decode`:
* decode signature correctly (odd_y_parity as bool)
* extract chain id for legacy tx

fix: transaction object rlp decoding

---

ethers-solc/src/artifacts/bytecode.rs

Closes https://github.com/foundry-rs/foundry/issues/3339
standalone sol files (without any contracts) were assigned the default `Bytecode` object, which was `Unlinked`. This should just be an empty `Bytes` object

fix(solc): use empty bytecode as default instead unlinked

---

ethers-core/src/types/serde_helpers.rs
ethers-core/src/types/transaction/eip712.rs

Closes https://github.com/foundry-rs/foundry/issues/3409
use correct decoding for chain id, in `EIP712Domain` which can also be a string

fix: support eip712 domain chain ids as string

---

ethers-contract/ethers-contract-abigen/src/contract.rs
ethers-contract/ethers-contract-abigen/src/contract/structs.rs
ethers-contract/ethers-contract-abigen/src/lib.rs
ethers-contract/src/lib.rs
ethers-core/src/abi/mod.rs
ethers-core/src/abi/raw.rs
ethers-etherscan/src/contract.rs
ethers-etherscan/src/utils.rs

high priority since cast interface stuff is broken @gakonst thx ser
- move (only) rawabi as raw.rs to core::abi, testdata not moved (abi jsons and contracts)
- revert etherscan parsing as Abi, add methods to conditionally parse as RawAbi or Abi

fix(core, etherscan): RawAbi and Abi

---

ethers-core/src/utils/anvil.rs

Fixes #1758
Drop stdout to match the behavior documented in comment above "stdout redirected to /dev/null".
Keeping it around can cause problems when many logs are generated.

Drop anvil subprocess stdout

---

ethers-solc/src/artifact_output/mod.rs
ethers-solc/src/utils.rs

This is weird filesystem permissions bug https://github.com/foundry-rs/foundry/issues/3268 that somehow is limited to the artifacts folder that occurs when artifacts are written.
this will create the artifacts folder _before_ files are written.
I haven't found the root cause for this yet, but this could be related.

chore(solc): create artifacts folder on output

---

ethers-contract/ethers-contract-abigen/src/contract/common.rs

Closes #1763
explicitly annotate the json str with ` #[rustfmt::skip]` to prevent string formatting which can break json.

fix: skip json abi formatting

---

ethers-core/src/abi/human_readable/mod.rs
ethers-etherscan/src/lib.rs
ethers-etherscan/src/utils.rs
ethers-middleware/src/gas_escalator/linear.rs
examples/abigen.rs

chore(clippy): make clippy happy

---

ethers-solc/src/artifact_output/mod.rs
ethers-solc/src/compile/project.rs
ethers-solc/src/lib.rs

this should finally close https://github.com/foundry-rs/foundry/issues/3268
thanks to @CarterAppleton for sharing logs.
this bug happened because `conflict_free_output_file` wasn't tested against absolute paths. so if there are duplicate contracts the previous implemented could end up prefixing the entire path with `_1` which is used to find a new unused path...
fixes by stripping the output path and treating it relatively as intended.
added new test to confirm

fix(solc): handle absolute paths properly on conflict

---

ethers-core/src/types/mod.rs
examples/remove_liquidity.rs

It would be convenient to be import H128 in other projects that use ethers through a re-export.
Re-exports H128 like the other `ethereum-types` types.

feat(core): re-export H128

---

ethers-contract/src/multicall/mod.rs

Just some typo: `annonated` in docs.
Change `annonated` to `annotated`.

docs: fix typo annonated to annotated

---

ethers-core/src/types/block.rs
examples/subscribe_logs.rs

Add safe and finalized block tagsa to `BlockNumber`
```rust
pub enum BlockNumber {
/// Latest block
Latest,
/// Finalized block accepted as canonical
Finalized,
/// Safe head block
Safe,
/// Earliest block (genesis)
Earliest,
/// Pending block (not yet part of the blockchain)
Pending,
/// Block by number from canon chain
Number(U64),
}
```

add safe and finalized  tag to BlockNumber

---

Cargo.lock
ethers-core/Cargo.toml
ethers-core/src/types/bytes.rs
ethers-core/src/types/signature.rs
ethers-core/src/types/transaction/eip2930.rs

closes #1785, forked fastrlp 0.1.2 here https://github.com/gakonst/open-fastrlp. @shekhirin let's separately investigate using `ruint` for `fastrlp`?

release: switch to apache fastrlp

---

ethers-contract/src/call.rs

Continuation of #1797.
Implement `IntoFuture` trait for `ContractCall`.
Defaults to calling `ContractCall::call()`.

Impl `IntoFuture` for `ContractCall`

---

ethers-middleware/src/signer.rs

If you try to use SignerMiddleware on chains that don't support EIP-1559 (Optimism, BSC, etc), you'll get an error. Client code has to check the chain id everywhere, which is fragile and annoying. The middleware should automatically handle this, especially since the chain information is already stored in ethers-rs.
Parse Chain from chain_id. Check if it's a "legacy only" chain. If so, convert the transaction to a legacy transaction as part of the fill logic.
-   [] Updated the changelog  --> not sure what to do here?

enhance signer middleware to automatically switch legacy

---

CHANGELOG.md
ethers-providers/src/log_query.rs
ethers-providers/tests/log_query.rs

`provider.get_logs_paginated` would try to fetch more blocks than are available, because it only considers `page_size` when fetching blocks.
Only fetch up to `from_block + page_size` or the last block available, whichever is lower.

fix: get_logs_paginated fetches past latest block

---

ethers-core/src/types/chain.rs

Closes https://github.com/foundry-rs/foundry/issues/3560
add "gnosis" alias

chore: rename xdai gnosis

---

ethers-contract/src/lib.rs

Addressing the issue #1676
The event builder type is part of the [builders mod in lib.rs](https://github.com/gakonst/ethers-rs/blob/a07581489a12b1007c3a261dc8df2bbdc4e27918/ethers-contract/src/lib.rs#L44) which has the `#[doc(hidden)]` attribute. Moving Event into scope generates docs for the Event type and fixes the [dead Event type link](https://docs.rs/ethers-contract/0.17.0/ethers_contract/struct.Contract.html#method.event) under the Contract documentation. 

docs: fix Event type not pointing to docs 

---

ethers-solc/Cargo.toml
ethers-solc/benches/read_all.rs
ethers-solc/src/artifacts/mod.rs

also tested the sync vs. par file reading on solmate which has 50 source files in range of >4kb and par is only marginally faster:
```console
read solmate/sequential time:   [707.99 µs 713.80 µs 719.63 µs]                                    
Found 2 outliers among 10 measurements (20.00%)
2 (20.00%) high severe
read solmate/parallel   time:   [489.61 µs 515.83 µs 537.40 µs]                                 
Found 1 outliers among 10 measurements (10.00%)
1 (10.00%) high mild
```
this is still µs, so I think we can disable this par threshold altogether

chore(solc): always use sync sources reading

---

ethers-core/src/types/transaction/response.rs

See #1848, some transactions (specifically type 1 or EIP2930 transactions) would fail RLP decoding.
The `gas` field was being decoded twice in a row, which caused all EIP2930 transaction decoding to fail. Removing the second decode call fixes the issue.
Fixes #1848

fix(core): stop decoding gas twice for 2930 txs

---

Cargo.lock
ethers-middleware/Cargo.toml

Closes #1824
turns out futures-locks has a default tokio feature, somehow this did not affect the wasm example
cc @ncitron

fix: disable futures-locks tokio feature

---

ethers-contract/ethers-contract-abigen/src/contract/methods.rs
ethers-contract/tests/it/abigen.rs

Fixes a bug discovered in foundry CI where params of overloaded functions are not matched correctly.
Keep track of all params already identified as diff when comparing two overloaded functions.
This prevents false positive where (`string`, `string`, `string`) compared to (`string`, `string[]`) resulted in no diffs because we used `iter::all()` as a comparator.

fix: improve overloaded param diff matching

---

CHANGELOG.md
ethers-core/src/types/i256.rs

…c types on the right shift operator
Discussion with @prestwich on telegram around [issue](https://github.com/gakonst/ethers-rs/issues/1840). Documentation was chosen over hidden breaking changes.
Update documentation I256 on calling out the inconsistency between its right shift operator and standard numeric types.
-   [X] Added Documentation
-   [X] Updated the changelog

I256 asr doc

---

examples/paginated_logs.rs
examples/subscribe_logs.rs

There is a separate function that does exactly same thing.
Replaced:  
```rs
topic0(ValueOrArray::Value(H256::from(keccak256(...))))
```
with
```rs
event()
```

docs: updated logs event filtering for examples with new syntax

---

CHANGELOG.md
ethers-core/src/types/trace/example-trace-str.rs
ethers-core/src/types/trace/example-traces-str.rs
ethers-core/src/types/trace/mod.rs
ethers-core/src/types/trace/opcodes.rs

Addresses #1857
I needed to do comprehensive tx analysis by using `vmTrace` to retrieve and inspect the executed opcodes to a transaction. The vmTrace log type [ethers::core::types::VMOperation](https://docs.rs/ethers/0.17.0/ethers/core/types/struct.VMOperation.html) does not contain a field for the executed opcode. 
Created an `OpCode` enum at [ethers-core/src/types/trace/opcodes.rs](https://github.com/mouseless-eth/ethers-rs/blob/vmTrace/add_op_codes/ethers-core/src/types/trace/opcodes.rs) that holds all evm opcodes.
Add an `op` field to VMOperation that is of type `OpCode`.
To [test](https://github.com/gakonst/ethers-rs/blob/921dfa6b1c5ad9ba5f24033a414041f04da624ad/ethers-core/src/types/trace/mod.rs#L197) deserializing this new type, …

Add `op` field to `VMOperation` to determine executed opcode

---

CHANGELOG.md
Cargo.lock
ethers-contract/ethers-contract-abigen/Cargo.toml
ethers-contract/ethers-contract-abigen/src/multi.rs

currently when abigen generates a new crate. it uses the git version of the repo. However this is wrong as if someone set there ethers-rs dep to version 1.0.0, if they generated a crate for bindings. it would be the git version causing a dependency conflict 
to fix this problem we simply read from the cargo manifest directory and then parse what version the bindings are being generated from and use that over the default hardcoded version

fix: generated crate not using generated version

---

CHANGELOG.md
ethers-core/src/types/i256.rs
ethers-core/src/types/mod.rs
ethers-core/src/utils/mod.rs
ethers-middleware/tests/signer.rs

Close [#842](https://github.com/gakonst/ethers-rs/issues/842)
Updated the `format_units` to take in a numeric that can be Into'd the enum. This should be a pretty transparent change for users, however the `From<&str> for U256` support will be dropped by the function. Given the existing tests cases I would suspect this doesn't impact a lot of users as they would be transforming into a U256 first before calling this function.
`format_units` also required to expose a `twos_complement` method on the I256 type. I thought of re-using the abs functions and taking one of the tuple results however throught this would enable better readability and help with presenting an API for I256 which a user would expect.
Tried to make the user updates required for `parse_units` as painless as possible by the …

I256 parse support

---

.github/workflows/ci.yml

Windows build failures on main line.
Rust seems to already be installed on the platform, therefore rustup just exits. Moved to rustup update instead.
-   [-] Added Tests
-   [-] Added Documentation
-   [-] Updated the changelog

Rust already exists on the platform - update it instead

---

ethers-contract/ethers-contract-abigen/src/multi.rs

the previous fix used CARGO_MANIFEST_DIR however this turns out to return the crate directory rather than the dependant crate directory making this impl wrong 
use the cwd instead. This doesn't cover all cases but is better than the current which misses all the cases

Fix: use cwd manifest

---

Cargo.lock
ethers-core/src/types/block.rs
ethers-signers/Cargo.toml

Fix CI issues.
Bump to trezor.
Please note requires: https://github.com/joshieDo/rust-trezor-api/pull/5 in order to get the new version of Trezor and fix the CI issues around primitive-types.

chore: bump trezor, fix clippy

---

examples/gas_price_usd.rs

Gas price retrieval in USD base currency can be quite interesting. Connection to on-chain price oracles can bring developers to imagine a wider set of `ethers-rs` use cases. That's why this new example.
I added a new example that illustrates:
* How to integrate a Chainlink oracle via `abigen`
* How to retrieve current gas price from a `Provider`
* How to retrieve ETH/USD price from Chainlink
* Convert `wei` price in `USD`

Examples: Get gas price in USD using a Chainlink oracle

---

ethers-contract/src/multicall/multicall_contract.rs

Fixes #1883
during doc publishing the find `ethers_crate` hack has some issues apparently: https://docs.rs/crate/ethers/1.0.1/builds/679442
this replicates the `ethers` mod layout, so no matter what crates will be used this should guarantee they'll be found

fix: mock ethers mod layout

---

ethers-contract/ethers-contract-abigen/src/multi.rs

Fixes an issue overlooked in https://github.com/gakonst/ethers-rs/pull/1869/files and https://github.com/foundry-rs/foundry/pull/3742
if there's no Cargo.toml yet, use default dependency

fix: handle non existing Cargo.toml edge case

---

examples/subscribe_events_by_type.rs
examples/subscribe_logs.rs

The examples pipeline gets stuck due to  active event subscriptions
I limited the subscriptions to take at most 2 items

fix: examples pipeline timeout 

---

ethers-core/src/utils/mod.rs

U256::from(u128...);
U256::exp10(x) with x > 77;
also lots of unnecessary calculations and casts

fix(core): format_units overflow

---

CHANGELOG.md
ethers-middleware/README.md
ethers-middleware/src/builder.rs
ethers-middleware/src/lib.rs
ethers-middleware/src/provider_builder.rs
ethers-middleware/tests/builder.rs

The ability to stack different `Middleware`s  is a powerful feature of this library, since it promotes "Single Responsibility", "Open Closed Principle" and other good stuff. 
I think that readability and composability can be further improved. For such reason I propose another approach to build stacked `Middleware`s using a builder struct.
I provided
- A `ProviderBuilder` module under  the `ethers-middleware` lib
- Extensive documentation
- Unit tests
It works as follows 
```rust
fn example() {
let key = "fdb33e2105f08abe41a8ee3b758726a31abdd57b7a443f470f23efce853af169";
let signer = key.parse::<LocalWallet>().unwrap();
let address = signer.address();
let escalator = GeometricGasPrice::new(1.125, 60_u64, None::<u64>);
let provider = …
```

Feat middleware stack builder

---

ethers-core/src/types/txpool.rs

Fixes #1899 
The error occurs due to `TxpoolInspectSummary`'s deserialize method not having a way to parse the following response
```
"0x00000000863B56a3C1f0F1be8BC4F8b7BD78F57a": {
"40": "contract creation: 0 wei + 612412 gas × 6000000000 wei"
}
```
- Add a new match arm to map "contract creation" into None (as specified [here](https://github.com/gakonst/ethers-rs/blob/79e64a8378891df5afc6b83f75059c5afc587ae1/ethers-core/src/types/txpool.rs#L11)) when deserializing  `TxpoolInspectSummary`'s `to` field
- Rewrite tests to account for deserializing and serializing logs that include a contract creation
- `TxpoolInspectSummary`'s serialize method should serialize a `to` field equal to **None** into "contract creation" or "0x" instead of the default value for address type …

fix: txpool_inspect unable to parse contract creations

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.lock
ethers-core/Cargo.toml
ethers-core/src/types/fee.rs
ethers-core/src/utils/genesis.rs
ethers-core/src/utils/geth.rs
ethers-core/src/utils/mod.rs
ethers-providers/Cargo.toml
ethers-providers/src/admin.rs
ethers-providers/src/call_raw.rs
ethers-providers/src/lib.rs
ethers-providers/src/provider.rs

Geth includes an `admin` namespace which is especially useful for querying its p2p details and prompting the node to add or remove peers.
- Add `NodeInfo` for the `admin_nodeInfo` return type
- Add `PeerInfo` for the `admin_peers` return type
- Add the following `admin` namespace RPCs to `Middleware`, implementing them on `Provider<P>`:
- `admin_nodeInfo`
- `admin_peers`
- `admin_addPeer`
- `admin_addTrustedPeer`
- `admin_removePeer`
- `admin_removeTrustedPeer`
This also modifies the `Geth` and `GethInstance` structs to support custom chain ids and running without the `--dev` flag. `--dev`-specific configuration options, and options that are incompatible with `--dev` are kept mutually exclusive with the `PrivateNetOptions` enum. Unless a dev-incompatible option is set, `--dev` mode will …

feat(providers): add a subset of admin namespace

---

CHANGELOG.md
ethers-providers/src/transports/ws.rs
ethers-providers/tests/ws_errors.rs

Some issues have been raised, reporting `WsServer` panics on upstream connection errors. 
#1889 #1815
https://github.com/gakonst/ethers-rs/blob/4b685621ed3a4b827276a13107f30457a19379db/ethers-providers/src/transports/ws.rs#L250-L256
In order to have a simpler and more predictable behavior, I believe the application should directly handle reconnections (also stated [here](https://github.com/snapview/tokio-tungstenite/issues/101)), avoiding recovery mechanisms at the transport layer.
Instead of crashing the program, we gracefully close all active subscriptions. Clients will then observe the end of their streams and issue proper actions.
What do you guys think?

Fix: handle panic on Ws error 

---

ethers-core/src/utils/geth.rs

If another process is already using the default p2p port, disabling discovery will cause the geth instance to crash because it will start with p2p enabled. Even if it doesn't crash, the p2p port will not be visible from the `GethInstance` created when geth is spawned. Instead, it would be `None`.
Always set the p2p port if geth is in non-dev mode, using `unused_port` if the p2p port is not explicitly set.

fix(core): always set p2p port in non-dev mode

---

CHANGELOG.md
ethers-providers/src/lib.rs
ethers-providers/src/provider.rs

Cannot convert `ProviderError` to arbitrary middleware error
Add an associated function that converts by going down the middleware type stack to the root provider

feature: providererror conversion to middleware error

---

README.md

The link to the abigen test file in the top level readme points to the wrong path resulting in 404 Error page.
Fix the path to point to the correct test file.
-   [ x ] Added Documentation

docs: Fix Dead Link to abigen test in README

---

Cargo.toml
ethers-addressbook/Cargo.toml
ethers-contract/Cargo.toml
ethers-contract/ethers-contract-abigen/src/multi.rs
ethers-core/Cargo.toml
ethers-etherscan/Cargo.toml
ethers-middleware/Cargo.toml
ethers-providers/Cargo.toml
ethers-signers/Cargo.toml
ethers-solc/Cargo.toml
examples/ethers-wasm/Cargo.toml

IntoFuture was implemented in #1826, which means the MSRV should be 1.64
Update `rust-version` in `Cargo.toml`

docs: update MRSV to 1.64

---

ethers-core/src/types/transaction/eip1559.rs

Added missing new line in rust docs (my 2 cents)

docs: typo in EIP-1559 

---

ethers-contract/ethers-contract-abigen/src/contract/errors.rs
ethers-contract/ethers-contract-abigen/src/contract/methods.rs

instead of byte array, generate selector as hex for docs.
all clippy stuff fixed here https://github.com/gakonst/ethers-rs/pull/1923

chore: generate selector as hex in docs

---

Cargo.lock
ethers-core/Cargo.toml
ethers-core/src/utils/geth.rs

Previously, spawning Geth with disabled discovery would not actually set the p2p port in the returned GethInstance. This is because it would only pass the port to the geth command. If the value started as None, it would remain to be None in the GethInstance even though a port was passed to the command.
Return the p2p port by the `match` statement that handles setting the p2p port if `Geth` is in `PrivateNetMode`. This port is then set and returned in the `GethInstance`.
* adds tests for the existence of ports in GethInstance

fix(core): set `GethInstance` p2p_port in spawn

---

CHANGELOG.md
ethers-contract/src/multicall/mod.rs

fix(contract): allow 16 calls in multicall

---

ethers-core/src/types/transaction/eip1559.rs
ethers-core/src/types/transaction/mod.rs
ethers-core/src/types/transaction/request.rs
ethers-core/src/types/transaction/response.rs

Currently `Transaction`s do not decode correctly if they are contract creation transactions. This is when the `to` field is `None`, which is encoded in RLP as `0x80`. 
Refactor the `decode_to` method to instead return `Result<Option<Address>, DecodeError>`, and use it when decoding `Transaction`s, not just transaction requests.
Add a test from #1393 that passes with the changes.
Fixes #1939

fix(core): decode to correctly in Transaction

---

ethers-middleware/README.md
ethers-middleware/src/builder.rs
ethers-middleware/src/gas_escalator/mod.rs
ethers-middleware/src/gas_oracle/blocknative.rs
ethers-middleware/src/gas_oracle/cache.rs
ethers-middleware/src/gas_oracle/eth_gas_station.rs
ethers-middleware/src/gas_oracle/etherchain.rs
ethers-middleware/src/gas_oracle/etherscan.rs
ethers-middleware/src/gas_oracle/gas_now.rs
ethers-middleware/src/gas_oracle/median.rs
ethers-middleware/src/gas_oracle/middleware.rs
ethers-middleware/src/gas_oracle/mod.rs
ethers-middleware/src/gas_oracle/polygon.rs
ethers-middleware/src/gas_oracle/provider_oracle.rs
ethers-middleware/src/transformer/ds_proxy/factory.rs
ethers-middleware/tests/builder.rs
ethers-middleware/tests/gas_escalator.rs
ethers-middleware/tests/gas_oracle.rs
ethers-middleware/tests/nonce_manager.rs
ethers-middleware/tests/signer.rs
ethers-middleware/tests/stack.rs
ethers-middleware/tests/transformer.rs

Old / non functioning API URLs
- Replace gas_now url (old redirected to new)
- [deprecate eth_gas_station](https://twitter.com/ETHGasStation/status/1597341610777317376) and replace it in docs and tests with gas_now
- temporarily ignore etherchain tests which is failing in builds due to 404
- clean up parsing and gas calculation since every oracle was different
- add some `Default` impls and other derives
- export internal Response structs which were exposed in the query functions but were not exported at mod level
- add common Result type alias for gas_oracle
- add missing tests for oracles
- big tests diffs are just removing indentation from removing unnecessary `mod tests`
- add missing fields in gas_now Response
- make file structure consistent with each other (imports -> definitions …

fix(middleware): oracles, tests

---

CHANGELOG.md
Cargo.toml
ethers-contract/ethers-contract-derive/Cargo.toml
ethers-middleware/Cargo.toml

I was working on a project with requirement to use OpenSSL, so I added this:
```
ethers = { version = "1.0.2", default-features = false, features = ["ws", "openssl"] }
```
But I noticed that `rustls` was still building.
The problem was that `ethers-middleware` was explicitly using `reqwest` with `rustls-tls` enabled, so I added `rustls` and `openssl` feature flags to it.

fix: Add `openssl` and `rustls` feature flags in ethers-middleware

---

Cargo.lock
ethers-core/Cargo.toml
ethers-core/src/types/chain.rs

Too much repetition
- macros for everything
- removed manual FromStr, Display and TryFrom<u64> impls;
- added strum::AsRefStr which is also used in Display and Serialize (so Serialize doesn't allocate before call)
- manually added the aliases as #[strum(serialize = "...")] (see diff below)
- added strum::EnumString for FromStr
- added [num_enum](https://docs.rs/num_enum)::TryFromPrimitive for TryFrom<u64>
- only drawback is that the error type can contain only a u64 so when trying to convert from a bigger number the error message will be incorrect
- added macro_rules for implementing other conversions
- added derive(PartialOrd, Ord)
- exhaustive `is_legacy` util + added comment about exhaustiveness
- updated comment on how to add new Chain variants
Diff (1st block is Display, 2nd is …

feat(core): chain macros and impls

---

ethers-solc/src/artifact_output/configurable.rs
ethers-solc/src/artifacts/ast/lowfidelity.rs
ethers-solc/src/artifacts/ast/mod.rs
ethers-solc/src/artifacts/mod.rs
ethers-solc/test-data/ast/ast-erc4626.json

This reverts parts of #1943 because that PR did not pass all checks and will likely cause a lot of issues in foundry just because there are a lot of different version-specific variants which are likely not covered.
My suggesting is:
1. partially revert #1943 breaking changes with this PR
2. fix tests first
3. more tests for all versions
4. reconsider replacing Ast with SourceUnit
Since the AST is not of interest in most cases, we ca also handle it similar to Metadata where we just use the `Json` and add a separate function to deserialize the `SourceUnit` this makes it less error prone for foundry use case and you can still get the deserialized object via an additional call if you need that.
wdyt @iFrostizz ?
- …

revert: Ast Artifact

---

ethers-contract/ethers-contract-abigen/src/multi.rs

currently there's no publicly exposed way to set the multiabigen rustfmt value

fix(contract): add setter for MultiBindings' rustfmt

---

CHANGELOG.md
ethers-core/src/types/trace/geth.rs
ethers-middleware/Cargo.toml
ethers-providers/src/lib.rs
ethers-providers/src/provider.rs
examples/geth_trace_call.rs

Minimal implementation of #1801 `debug_traceCall`.
Similar implementation to `debug_traceTransaction`.
`stateoverrides` and `blockoverrides` trace options were not implemented.

feat: debug_traceCall

---

ethers-providers/src/provider.rs

Allow user to set tip without setting base fee, and avoid overriding any user-set tip or basefee
instead of overriding, use the `Option::get_or_insert`

fix: don't override user-set 1559 attributes

---

ethers-contract/src/multicall/mod.rs

Fixes https://github.com/gakonst/ethers-rs/issues/1984 regarding `Multicall::call_array`
Change `.call` to `call_array` which is the function the docs are referencing.

fix: doc typo regarding Multicall::call_array

---

CHANGELOG.md
ethers-signers/src/wallet/private_key.rs

There was no way to initialize a new Wallet from a byte slice.
I added a `from_bytes` associated function for the `Wallet` type. The function  initializes a new `SignerKey` from a byte slice and uses the key to create a new wallet.
```rust
impl Wallet<SigningKey> {
//--snip--
pub fn from_bytes(bytes: &[u8]) -> Result<Self, WalletError> {
let signer = SigningKey::from_bytes(bytes)?;
let address = secret_key_to_address(&signer);
Ok(Self { signer, address, chain_id: 1 })
}
}
```

added `from_bytes` for `Wallet` type

---

ethers-core/src/utils/mod.rs

The structs contained in `Genesis` were not public, so they could not be set explicitly, for example if configuring a private network with Clique.
Expose `GenesisAccount`, `CliqueConfig`, and `EthashConfig` (even though it's empty).

feat(core): expose all genesis related structs

---

ethers-signers/src/aws/mod.rs

Signed-off-by: Gyuho Lee <gyuho.lee@avalabs.org>

ethers-signers/aws: sighash on the inner/updated tx object

---

ethers-core/src/utils/geth.rs
ethers-providers/src/lib.rs
ethers-providers/src/provider.rs

In reth, we will be using a clique geth instance to produce blocks, which we will then peer with and test IBD / sync. To get geth to produce blocks after importing a clique signing key, we need to enable the miner.
Add support for the following APIs:
- `eth_mining`
- `miner_start`
- `miner_stop`
The `miner` namespace is also enabled in `Geth`.

feat(providers): add mining related apis

---

ethers-core/src/utils/geth.rs

The `GethInstance` logs are useful for understanding what geth is doing, and there is currently no way to extract the `pid.stderr` so the logs can be read.
Implement a `stderr` method on `GethInstance` that uses `take()` to return a `ChildStderr`, which can then be read with a `BufReader` or other methods.

feat(core): add ability to take geth stderr

---

ethers-middleware/tests/nonce_manager.rs
ethers-providers/src/provider.rs

CI breaks on NonceManager test on the Goerli network.
Switched the network from Goerli to Anvil to work in a sand-box.

ci: fix nonce manager test

---

ethers-contract/ethers-contract-abigen/src/contract/events.rs
ethers-contract/ethers-contract-abigen/src/contract/methods.rs

Some tests broke due to `ethers` paths now being global (prefixed by `::`)
Prefix expected paths in tests with `::`

fix(abigen): tests

---

ethers-core/src/types/chain.rs
ethers-etherscan/src/lib.rs

This adds support for Arbitrum Nova chain.
Add ArbitrumNova to Chain enum with chain id: 42170

feat: Add arbitrum nova api and chain id 42170

---

Cargo.lock
ethers-signers/Cargo.toml

Disable default native-tls feature on rusoto

fix: disable native-tls on rusoto

---

ethers-core/src/types/chain.rs

`pub use TryFromPrimitiveError as ParseChainError` for backwards compatibility
closes #1993

chore(core): alias&export error as ParseChainError

---

.github/workflows/book.yml
book/getting-started/intro.md

1. This is a  followup to [THIS](https://github.com/gakonst/ethers-rs/pull/2003#issuecomment-1370207486) message, where I had recommended the addition of the addons in this PR. 
2. In order to increase the comprehension and readability of the manual, the presence of callouts and diagrams would be a good idea
This PR has the following two mdbook addons 
1. [`mdbook-mermaid`](https://github.com/badboy/mdbook-mermaid) - Ability to add code driven diagrams via [`mermaid-js`](https://mermaid.js.org/#/)
2. [`mdbook-admonition`](https://github.com/tommilligan/mdbook-admonish) - Ability toa dd colorful callouts
Note
1. In addition to adding the addons , I have also actually implemented both of them in the `intro.md`, after running the tests on a local branch, the artifacts created now contain the …

mx - CI - mdbook addons - admonition(callouts) and mermaid (code driven diagrams) with example implementation

---

ethers-middleware/tests/signer.rs

https://github.com/gakonst/ethers-rs/actions/runs/3865018418/jobs/6588238571
> err: max priority fee per gas higher than max fee per gas: address 0x212af5Bc0CC34CAAb9E25fb46A8A1E3f91e07f57, maxPriorityFeePerGas: 3000000000, maxFeePerGas: 74084601 (supplied gas 15010499)
For some reason the priority fee gets hardcoded at 3 gwei?

fix: signer test

---

ethers-etherscan/src/account.rs

The `"to"` field of the response to `get_transactions()` is set to `""` for contract creation transactions. This wasn't handled resulting in a deserialization failure.
Added `#[json_string]` macro.

etherscan: fix deserializing contract creation NormalTransaction objects

---

ethers-providers/src/transports/common.rs

chore: clippy

---

ethers-core/src/types/chain.rs
ethers-providers/src/transports/common.rs
ethers-solc/src/sourcemap.rs
ethers-solc/src/utils.rs
examples/providers/examples/retry.rs

For situations where we want to iterate through all `Chain` variants.
We are already using `strum`, so just adding `EnumIter` & `EnumCount` is enough.

feat(core): add `strum::EnumIter` and `strum::EnumCount` to `Chain`

---

CHANGELOG.md
ethers-contract/src/contract.rs
ethers-contract/src/multicall/mod.rs
ethers-contract/tests/it/contract.rs

2 year-old TODO comment from #107
```txt
TODO: Can we make this return a PendingTransaction directly instead?
Seems hard due to `returns a value referencing data owned by the current function`
```
The only data that `PendingTransaction` has to hold a reference to is `M::Provider`. which we can get with `Arc::as_ref` but this is currently not exposed
add `client_ref` method that returns `Arc::as_ref(self.client)` for `Contract`
return `PendingTransaction` in `Multicall::send`

feat(contract): return multicall pending transaction

---

CHANGELOG.md
ethers-signers/src/wallet/private_key.rs

I wanted to be able to use private keys that have `0x` prefix, without stripping it manually.
Remove prefix in `Wallet<SigningKey>::from_str`.

feat(signers): Allow parsing of private key that has `0x` prefix

---

Cargo.lock
ethers-core/Cargo.toml

@gakonst  version 0.5.8 of num_enum was pulled so now all builds on the most recent version fail due to an invalid dep

fix: revert to old version

---

ethers-contract/ethers-contract-abigen/src/contract.rs
ethers-contract/tests/it/abigen.rs

The `new` methods generated by `abigen!` create an underlying `Contract` with the correct ABI, but the generated `From` impls simply wraps a source `Contract`, which could have a completely different ABI. In effect this was an unsafe cast, and indeed was observed to trigger a "method not found (this should never happen)" panic for subsequent method lookups.
Implementing `From` in terms of `new` fixes this, at the cost of an extra `Arc::clone()` (which I can't see how to eliminate without piercing the `ethers::contract::Contract` public API).

fix(abigen): ensure correct ABI in `From` impl

---

ethers-solc/src/config.rs

Fix `can_autodetect_dirs` solc test failing on MacOS (#1895).
The test was failing for two reasons on macOS:
1. The build info directory was not created during the test.
2. Temporary directories are created with symbolic links on macOS and the path canonicalization returns the given path if it doesn't exist.
This lead to a mismatch between the project root's canonical path (which did exist and thus was a real path after canonicalization) and the build info directory's canonical path (which did not exist and was a symbolic link after canonicalization).
The fix is to create the build info directory to make sure its canonical path matches the project root's canonical path.
-   [ ] Added Tests **(n/a)**
-   [ ] Added Documentation **(n/a)**
-   [ ] Updated the changelog **(n/a)**
-   [ ] …

fix: failing can_autodetect_dirs solc test (#1895)

---

ethers-solc/src/artifact_output/configurable.rs

Closes https://github.com/foundry-rs/foundry/issues/4093
Add missing/wrongly configured `ir`. only `ir_optimized` was supported as file output.

fix(solc): add missing ir option

---

ethers-contract/ethers-contract-abigen/src/filter.rs
ethers-contract/ethers-contract-abigen/src/lib.rs
ethers-contract/src/multicall/mod.rs
ethers-etherscan/src/account.rs
ethers-providers/src/transports/quorum.rs
ethers-solc/src/artifacts/mod.rs
ethers-solc/src/filter.rs
ethers-solc/src/resolver/tree.rs

chore: fix clippy

---

Cargo.lock
ethers-solc/Cargo.toml
ethers-solc/src/resolver/parse.rs

chore(deps): bump solang-parser 0.2.1

---

ethers-contract/ethers-contract-derive/src/abi_ty.rs

https://github.com/gakonst/ethers-rs/issues/2053
Replace unwrap with safer method

remove EthAbiType derive generated unwrap

---

Cargo.lock
Cargo.toml
ethers-core/src/utils/genesis.rs
ethers-core/src/utils/geth.rs
examples/geth_clique.rs

Allows instantiating Geth in Clique mode when provided with a `SigningKey`.
Extracts the logic from https://github.com/paradigmxyz/reth/pull/623/files#diff-99e7bcdfb85c75ffe5fb2ccfbc5fd8234fced6704c34b622fbf24289b8522515R210
cc @Rjected

feat(core/geth): enable Clique mode 

---

ethers-core/Cargo.toml
ethers-core/src/utils/geth.rs

Previously, if multiple instances of geth were spawned concurrently, only one directory would be used to populate geth's `genesis.json`. This can lead to a race condition where the `genesis.json` would be re-written by a second instance, before the first instance reads the `genesis.json` for populating its db and genesis block with the `geth --init` command. this was possible because directory returned by `std::env::temp_dir()` is often shared.
This fixes the race condition by using `tempfile::tempdir()`, which creates a unique directory per call to `tempdir()`.

fix(core): fix geth --init temp dir race condition

---

ethers-etherscan/src/lib.rs

linked to https://github.com/foundry-rs/foundry/issues/4150
ensures all etherscan URLs have trailing: `/`

fix: ensure urls have trailing /

---

ethers-etherscan/src/utils.rs

Serialized contract (etherscan) info can't be re-deserialized unless Implementation: null is handled.
Accept "null" as None for Option<Address>

Fix to round-trip serialize and deserialize optional address

---

ethers-contract/ethers-contract-abigen/src/contract/structs.rs

Closes https://github.com/gakonst/ethers-rs/issues/2079
adds missing `pub` for tuple fields

fix: add missing pub for tuple structs

---

ethers-contract/ethers-contract-abigen/src/contract/structs.rs

Adds necessary functions to fix https://github.com/foundry-rs/foundry/issues/4039
all current getter functions return the rust type (pascal case) but we want the actual solidity type as well so we can use it to fix https://github.com/foundry-rs/foundry/issues/4039

feat(abi): add helper functions to access solidity types

---

Cargo.lock
ethers-core/Cargo.toml
ethers-core/src/lib.rs

getrandom needs to be enabled with js feature when for wasm target

fix: add getrandom with js feature for wasm

---

ethers-solc/src/artifact_output/configurable.rs
ethers-solc/src/artifacts/output_selection.rs

Closes https://github.com/foundry-rs/foundry/issues/4114
adds `bytecode` and `deployed-bytecode` as additional optional to emit code as separate file
uses the existing selection variants, but adds additional matching for `code` `bin`

feat(solc): support emitting bytecode as extra files

---

ethers-contract/tests/it/abigen.rs
ethers-providers/src/lib.rs
ethers-providers/src/provider.rs
ethers-providers/src/transports/retry.rs
ethers-providers/src/transports/rw.rs

`#[async_trait]` implementations require return types to be `Send`. So except for trivial cases the `JsonRpcClient::request` demanded implementors to be impossibly generic.
Add `Send` bound to the method and follow-up on its callers inside the monorepo.

fix(provider): Add Send bound to return type of JsonRpcClient::request

---

ethers-providers/src/lib.rs

Some methods in `Middleware` were using `ProviderError` rather than the associated error type.
Change the following methods on `Middleware` to use `Self::Error` instead of `ProviderError`:
* `import_raw_key`
* `unlock_account`
* `debug_trace_transaction`
* `debug_trace_call`

fix(providers): use middleware associated err type

---

ethers-core/src/utils/geth.rs

While the `genesis` and `clique_private_key` fields are exposed in `Geth`, they can't be accessed once the `GethInstance` is spawned.
This exposes the `genesis` and `clique_private_key` fields in `GethInstance`.

feat(core): expose genesis and private key in Geth

---

ethers-contract/ethers-contract-abigen/src/contract/common.rs
ethers-core/src/types/bytes.rs

we can make abigen'd contracts' bytecode static slices instead of allocating it at runtime with Lazy, using bytes::Bytes::from_static
see commit list;
technically a breaking change since `#bytecode_name` is not `Lazy<Bytes>` anymore but just `Bytes`, but the interaction should be the exact same since `Lazy` derefs into `Bytes`

refactor/feat(abigen,types): add bytes::Bytes static methods, refactor struct declaration

---

ethers-solc/src/remappings.rs
ethers-solc/src/utils.rs

fixes an autodetection edge case where openzepplin wasn't detected:
https://github.com/ScopeLift/flexible-voting/blob/66bd08b74bf983dcbecc0d806d8d98774a0ecfb4/foundry.toml#L7
updates a check that attempted to find the __first__ `src` dir in a set of candidates to check for the __only__ `src` dir.
the previous check succeeded in opezeppelin dir when it should not.

fix(solc): fix autodetection edge case

---

Cargo.lock
ethers-solc/Cargo.toml

Support Solc v0.8.18
Bump up SVM crates that include solc v0.8.18 support for apple silicon and linux aarch64 architectures.

chore: bump svm crates

---

CHANGELOG.md
ethers-core/src/abi/mod.rs
ethers-core/src/abi/packed.rs

feat(abi): packed encoding

---

CHANGELOG.md
ethers-contract/src/base.rs
ethers-contract/src/call.rs
ethers-contract/src/contract.rs
ethers-contract/src/lib.rs
ethers-contract/tests/it/contract.rs

Contracts currently hold `Arc<M>` and have bound `where M: Middleware` . This requires managing arcs across a codebase, which imposes unpleasant requirements on binaries
- Modify the contract object to be abstract over `B: Borrow<M>` instead of holding an `Arc<M>`. This allows contracts to be used directly with Cows, non-ARCed middleware, Boxes, other smart pointers, and anything else that uses the `Borrow`  trait.
- rename the modified object `ContractInternal` and create a type alias under the old name, for backwards compatibility
Example use case: 
- you can now use a contract directly with a `Lazy<Provider<Http>>` without having to have an arc in the lazy first
While `FunctionCall` and `ContractInstance` may be used with any type is `Borrow<M>`, there are sometimes multiple choices of …

refactor: make contract abstract over Borrow

---

CHANGELOG.md
ethers-core/src/types/signature.rs

Provide an official API to recover signatures on eip-712 objects.
add `Signature::recover_typed_data<T: Eip712>`

feature: allow signature to recover typed_data payloads

---

CHANGELOG.md
ethers-contract/src/contract.rs
ethers-contract/src/factory.rs
ethers-contract/src/lib.rs

Depends on #2082 
- Continue refactoring types that take `Arc<M>` to take `B: Borrow<M>` instead.
- Provide backwards-compatible aliases
- Refactor `ethers_contracts::factory` module to be abstract over B
- provide type aliases 

Refactor factories to use `Borrow<M>`

---

ethers-solc/src/resolver/mod.rs
ethers-solc/tests/project.rs

This fixes a multi version build bug that caused https://github.com/foundry-rs/foundry/issues/4320
the previous graph import resolve step did not take into account that a dependency can be used by multiple versions in the same project.
* process all dependencies of each file regardless if its a file of the project itself or an import. 
* Keep track of handled dependencies for efficiency
With this fix sources are cloned (because they could be used by multiple versions), this is negligible but could be improved by wrapping the file content in an Arc.

fix(solc): process all imports even input files

---

Cargo.lock
ethers-solc/Cargo.toml

Upgrade solang-parser to the latest release to enabled foundry upgrade

dep: solang-parser 0.2.2

---

ethers-contract/ethers-contract-abigen/src/contract/common.rs
ethers-middleware/src/transformer/ds_proxy/factory.rs

when running cargo doc on a project including Abigen'd files, the following warning is emitted:
```
warning: this URL is not a hyperlink
--> src/bindings/uniswap_v2_pair.rs:8:85
|
8 |     //!UniswapV2Pair was auto-generated with ethers-rs Abigen. More information at: https://github.com/gakonst/ethers-rs
|                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://github.com/gakonst/ethers-rs>`
|
= note: bare URLs are not automatically turned into clickable links
= note: `#[warn(rustdoc::bare_urls)]` on by default
```
use automatic link instead

chore(clippy): fix bare urls in abigen

---

ethers-solc/src/artifacts/mod.rs
ethers-solc/tests/project.rs

- extend model checker setting's field to open `invariants` flag.
- [invariants docs](https://docs.soliditylang.org/en/v0.8.18/smtchecker.html#reported-inferred-inductive-invariants) 

feat(ethers-solc): extend model checker setting field

---

ethers-contract/ethers-contract-abigen/src/contract.rs

I have a contract named `DKG` for which the auto-generated code created the following clippy warning:
```
warning: name `DKG` contains a capitalized acronym
--> crates/dkg-cli/src/dkg_contract.rs:25:16
|
25 |     pub struct DKG<M>(ethers::contract::Contract<M>);
|                ^^^ help: consider making the acronym lowercase, except the initial letter: `Dkg`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms
= note: `#[warn(clippy::upper_case_acronyms)]` on by default
```
According to the solidity style guide the name is fine: https://docs.soliditylang.org/en/v0.5.3/style-guide.html#naming-styles
Allow that clippy lint by default
-   [ ] …

contracts: allow upper case acronyms lint

---

ethers-solc/Cargo.toml
ethers-solc/src/artifacts/mod.rs
ethers-solc/src/buildinfo.rs
ethers-solc/src/compile/mod.rs

followup for https://github.com/gakonst/ethers-rs/pull/2136
prevents large String clones by wrapping source in `Arc`, this is useful to make content clones cheap, especially in multi-version builds.

perf(solc): wrap source content in Arc

---

CHANGELOG.md
examples/README.md
examples/events/examples/filtering.rs

Improve the `events` section of `examples` by adding a simple filtering example.
First-time contributor and also new to Rust, so any feedback is greatly appreciated!  I'm happy to add more examples, as I find them very helpful for familiarizing others with the project as well as being great exercises for learning Rust.
Adds a basic event filtering example that also includes parsing log topics.

feat(examples): add basic event filtering example

---

examples/contracts/examples/abigen.rs
examples/middleware/examples/gas_oracle.rs
examples/transactions/examples/call_override.rs

fixes #2151
- abigen example: write bindings `env::tmpdir` and clear if it exists already
- gas oracle: create a client even if no api_key env is set since it's not required; use `Client::from_env`
- call override: skip executing if geth fails / cannot be found; I tried substituting with Anvil but it doesn't seem to work, presumably because the call override feature is missing from Anvil? @mattsse

fix: examples

---

ethers-contract/ethers-contract-derive/src/event.rs
ethers-contract/ethers-contract-derive/src/lib.rs

fix(contract): report all errors during parsing

---

ethers-solc/src/artifacts/mod.rs
ethers-solc/tests/project.rs

- `divModWithSlacks`, `showUnproved` and `solvers` are shown in 0.8.7 in compiler input
- lower the disability of model checker from 0.8.10 to 0.8.7 since options above are implemented.
- eld solver are introduced in 0.8.18. It had been sanitized.
BTW, in future, adding other sanitized rules will able to remove or lower the version of `self.settings.model_checker = None;`

extend model checker options

---

ethers-contract/ethers-contract-derive/src/event.rs
ethers-contract/tests/it/common/derive.rs

Closes https://github.com/gakonst/ethers-rs/issues/2142
use the parsed event name from the `abi` attribute instead of the ident by default.

fix(abigen): use event name from abi attribute

---

ethers-contract/ethers-contract-abigen/src/contract/common.rs
ethers-contract/ethers-contract-abigen/src/contract/errors.rs
ethers-contract/ethers-contract-abigen/src/contract/events.rs
ethers-contract/ethers-contract-abigen/src/contract/methods.rs
ethers-contract/ethers-contract-abigen/src/contract/structs.rs
ethers-contract/ethers-contract-abigen/src/contract/types.rs

This PR aims to move all Solidity -> Rust type expansion into the types module to remove repetition and improve the logic

refactor(abigen): solidity types expansion

---

Cargo.lock
ethers-contract/ethers-contract-derive/Cargo.toml
ethers-contract/ethers-contract-derive/src/abi_ty.rs
ethers-contract/ethers-contract-derive/src/abigen.rs
ethers-contract/ethers-contract-derive/src/call.rs
ethers-contract/ethers-contract-derive/src/calllike.rs
ethers-contract/ethers-contract-derive/src/codec.rs
ethers-contract/ethers-contract-derive/src/display.rs
ethers-contract/ethers-contract-derive/src/error.rs
ethers-contract/ethers-contract-derive/src/event.rs
ethers-contract/ethers-contract-derive/src/lib.rs
ethers-contract/ethers-contract-derive/src/utils.rs

Requires #2149
- Make error handling consistent by using `Result<_, syn::Error>`
- Format `quote!` macro inputs
- Use `syn::Generics::split_for_impl` instead of manually parsing generics
- Use `eyre::Result` (inherited from `ethers_contract_abigen`) instead of `Box<dyn std::error::Error>`

refactor(contract): derive procedural macros

---

ethers-core/src/types/block.rs

Numbers get parsed first as hex, so a decimal number is default treated as hex
only parse as hex if prefixed by 0x
the prefix is handled by `U64::from_str`
only downside to current fix is that a non-prefixed hex gets parsed as decimal, ex: `a` is invalid while `0xa` is valid

fix(core): block FromStr implementation

---

ethers-core/src/utils/genesis.rs
ethers-core/src/utils/geth.rs

The `CliqueConfig` field of a genesis file does not necessarily require both a populated `epoch` and `period` field. This results in a `ChainConfig` like the following to fail to parse:
```json
"config": {
"clique": {
"period": 1
},
"chainId": 7,
"homesteadBlock": 0,
"eip150Block": 0,
"eip155Block": 0,
"eip158Block": 0
},
```
Change the `CliqueConfig` fields to be options, and include `serde(default)` for deserialization.
Add a test for deserializing a `genesis.json` passed from hive, that only has the `period` field.

use Option for CliqueConfig fields

---

ethers-contract/ethers-contract-abigen/src/contract.rs
ethers-contract/ethers-contract-abigen/src/contract/common.rs
ethers-contract/tests/it/abigen.rs

Currently, abigen output includes `bytecode`. However, there are certain use cases when having the `deployedBytecode` is also useful. For example, when using [eth_call state overrides](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-eth), it's useful to inject `deployedBytecode` into an account before executing the call. A common use-case for this is writing a contract with view functions that allow you to batch-read some state onchain in order to reduce the number of RPC calls you make. 
Add functionality to include `deployedBytecode` in the abigen output. 

Include deployed bytecode in abigen output 

---

ethers-core/src/types/chain.rs
ethers-etherscan/src/lib.rs

Include Canto and CantoTestnet as a Chain in the ethers project
Add in Canto and CantoTestnet chain ids (7700 and 740)

chore: added canto network

---

ethers-contract/ethers-contract-abigen/src/multi.rs
flake.lock
flake.nix

The order in which the types in `shared_types.rs` appear is not deterministic. This is can be frustrating if the bindings are committed to version control.
Unfortunately I don't have a simple repro or a test case right now.
The PR also includes some additions (gcc, anvil, geth) necessary to run the tests in the dev shell on NixOS. cc @onsails 
Unfortunately I still can't run clippy, which fails with 
```
/nix/store/ir58ws685pawbh0q3ys66aixy7hnv2vx-devenv-profile/bin/cargo-clippy: error while loading shared libraries: libstd-62c4894b82797b30.so: cannot open shared object file: No such file or directory
```
Instead of using HashMap/HashSet use BTree so that items are iterated over in order.
-   [ ] Breaking …

Make order of types in shared_types deterministic

---

CHANGELOG.md
ethers-contract/Cargo.toml
ethers-contract/ethers-contract-abigen/src/multi.rs
ethers-contract/src/call.rs
ethers-contract/src/lib.rs
ethers-contract/src/multicall/mod.rs
ethers-contract/src/multicall/multicall_contract.rs
ethers-contract/tests/it/contract.rs
ethers-core/src/abi/tokens.rs

Currently, if Multicall version is set to 2 or 3, `.call()`'s result will be a tuple of `(bool, <_>)` where bool is success. This is not the best API since it differs from version 1 and it is likely to throw and error when if the bool success variable is false, since the revert data almost never matches the success data.
This PR addresses this by making use of  the standard `Result` type to represent the call's result, where `Ok` is used when the `success` boolean is true, `Err` otherwise.
Breaking changes:
- `.call()`'s generic result type in all versions is now just the tuple of types, instead of a tuple of `(bool, <_>)` tuples
- `.raw_call()`'s concrete result type was changed from `Vec<Token>` to `Vec<Result<Token, Bytes>>`, explained above
On top of the changes described above:
- …

feat(contract): improve Multicall result handling

---

ethers-core/src/abi/mod.rs
ethers-core/src/types/i256.rs
ethers-core/src/utils/mod.rs

Closes #2174
Add `#[track_caller]` to methods that can panic
Add `#[inline]` or `#[inline(always)]` to all methods
Make methods `const` where possible
Implement `as_*`, `low_*`, `From<*> For I256`, `TryFrom<I256> For *` using a macro
Implement more bit shift methods using usize
Breaking (minor):
Remove bit shift implementations for types >= usize due to panic in U256
Make arithmetic ops generic over `T: Into<I256>` like `U256`

feat(core): improve I256 implementation

---

ethers-core/src/types/i256.rs

Fixes #2183
Doesn't help that doc CI is constantly failing :(

fix(core): i256 docs

---

CHANGELOG.md
ethers-signers/Cargo.toml
ethers-signers/src/ledger/app.rs
ethers-signers/src/ledger/types.rs

makes chunk size dynamic to avoid running into this:
https://github.com/LedgerHQ/app-ethereum/issues/409
https://github.com/foundry-rs/foundry/issues/4362
- find the highest chunk size <= 255 that will not trigger the bug
- drive-by: address some edge cases in payload handling that would have caused panics with incorrect ledger usage
- drive-by: add tracing to ledger app (WIP)
-   [ n/a ] Breaking changes

Workaround for https://github.com/LedgerHQ/app-ethereum/issues/409

---

ethers-contract/ethers-contract-abigen/src/source/online.rs
ethers-core/src/types/chain.rs
ethers-etherscan/src/lib.rs

Title, from `ethers-etherscan` to `ethers-core::types::Chain`, so that all the non-exhaustive chain matches are in the same file.

chore: move etherscan api key env var matching to Chain enum

---

CONTRIBUTING.md
book/getting-started/connect_to_an_ethereum_node.md
book/providers/advanced_usage.md
book/providers/http.md
ethers-contract/src/multicall/mod.rs
ethers-providers/README.md
ethers-providers/src/middleware.rs
ethers-providers/src/rpc/provider.rs
examples/anvil/examples/anvil_fork.rs
examples/contracts/examples/abigen.rs
examples/contracts/examples/events.rs
examples/contracts/examples/events_with_meta.rs
examples/events/examples/filtering.rs
examples/middleware/examples/builder.rs
examples/middleware/examples/gas_oracle.rs
examples/providers/examples/http.rs
examples/providers/examples/retry.rs
examples/providers/examples/ws.rs
examples/queries/examples/paginated_logs.rs
examples/queries/examples/uniswapv2_pair.rs
examples/subscriptions/examples/subscribe_events_by_type.rs
examples/subscriptions/examples/subscribe_logs.rs
examples/subscriptions/examples/watch_blocks.rs
examples/transactions/examples/ens.rs
examples/transactions/examples/gas_price_usd.rs

Replace infura/api_key with [llamanodes](https://llamanodes.com/) rpc and localhost for examples and docs. Test rpcs are being changed in #2189 to local anvil. Infura can rate limit in CI and make example job fail.

chore: replace rpc urls with generic ones

---

ethers-core/src/utils/genesis.rs
ethers-core/src/utils/mod.rs

Previously we were not properly parsing the storage field of GenesisAlloc. The first issue was in using `serde(flatten)`, which is just incorrect because storage is not encoded flattened. The second issue was in the parsing of `H256` keys and values. Some of the storage values in hive genesis examples were encoded in less than 64 hex characters, such as the string `0x22`. This would not succeed normal H256 parsing, but is consistent with [JSON-RPC unformatted encoding](https://ethereum.org/en/developers/docs/apis/json-rpc/#unformatted-data-encoding).
* Introduce `from_unformatted_hex_map` to properly deserialize the storage map.
* Modify existing genesis parsing tests to check parsed storage and code values against expected values.
* Introduce new genesis parsing test from the hive smoke …

fix(core): properly parse genesis alloc storage

---

ethers-contract/ethers-contract-abigen/src/contract/errors.rs
ethers-contract/src/call.rs
ethers-contract/src/error.rs
ethers-contract/src/lib.rs
ethers-contract/tests/it/abigen.rs
ethers-core/src/types/bytes.rs

Followup work to #2172. Allows easier decoding of error types for generated contracts
- Introduce the `ContractRevert` trait
- Auto-derive `ContractRevert` on the error enum in `abigen!` contract modules
- Add `RevertString(String)` to contract error enum in `abigen!` contract modules
- Add `ContractError::decode_contract_revert<Err: ContractRevert(&self) -> Option<Err>`
- (drive-by) add missing `FromIterator` impls to `ethers::core::types::Bytes`
This is a breaing change to `abigen!` generated bindings (again) but i promise this one is also really good :)

feature: contract revert trait

---

ethers-core/src/utils/geth.rs

https://github.com/ethereum/go-ethereum/pull/26413 caused the default clique configuration for the `GethInstance` to fail to start mining, because we did not pass a `--miner.etherbase` flag on startup.
For example, this would cause error logs in reth integration tests when we would try to start mining over RPC:
```
thread 'can_peer_with_geth' panicked at 'called `Result::unwrap()` on an `Err` value: ProviderError(MiddlewareError(JsonRpcClientError(JsonRpcError(JsonRpcError { code: -32000, message: "etherbase missing: etherbase must be explicitly specified", data: None }))))', crates/staged-sync/tests/sync.rs:93:72
```
Adds a `--miner.etherbase` flag with the clique signer address as the argument, when clique is enabled.
Ran reth integration tests multiple times after patching ethers
-   [ …

fix(core): set miner.etherbase in clique mode

---

CHANGELOG.md
ethers-core/src/types/transaction/response.rs

Similar to `Transaction` and `Block`, L2s (particularly Optimism) have custom fields on `TransactionReceipt`. These fields may be necessary in determining the gas cost of a transaction.
Simply added `other: OtherFields` to `TransactionReceipt`, same as existing usage on `Transaction`. I've also confirmed this works on Optimism's custom params.
Please let me know if there was a reason this type was skipped in the initial roll out of `OtherFields`

feat: deseralize other fields on tx receipts

---

ethers-signers/src/aws/mod.rs

fix: udeps

---

ethers-contract/src/lib.rs

Parse log was inadvertently removed from re-export by #2105

fix: parse_log in public interface

---

ethers-core/src/types/i256.rs

This should be less confusing ;)

i256: Fix logical errors in doc comments for is_negative and is_zero

---

Cargo.toml
ethers-contract/Cargo.toml
ethers-contract/ethers-contract-abigen/Cargo.toml
ethers-contract/ethers-contract-derive/Cargo.toml
ethers-contract/src/lib.rs
ethers-core/Cargo.toml
ethers-etherscan/Cargo.toml
ethers-middleware/Cargo.toml
ethers-middleware/src/lib.rs
ethers-providers/Cargo.toml
ethers-signers/Cargo.toml
src/lib.rs

For some reason (I believe because the build process isn't normal and maybe our resolution doesn't work with the given environment) the docs.rs builds always return `ethers` as the crate name (default). Tested multiple times on a local docs.rs instance and I can 99.9999999% confirm that this PR solves it by doing the following:
- re-export the internal crate as `ethers`
- export core, contract and providers at the top level
- rustc flags also have to be set to --cfg docsrs (for `#[cfg(docsrs)]` on the re-exports)
- this is technically not necessary now because I removed the `cfg`s, just to be safe
this needs to be done in every (release) crate that uses a macro that uses `ethers_core::macros::*`, which right now includes contract and middleware.
-   [ ] Added …

fix: docsrs builds final

---

ethers-providers/src/stream/tx_stream.rs

polling a stream after it finished is usually bad.
only poll if not done

fix: dont poll stream again if done

---

ethers-etherscan/src/errors.rs
ethers-etherscan/src/lib.rs

fix possible `result:null` error response, which blockscout apparently returns
ref https://github.com/foundry-rs/foundry/issues/4406

fix(etherscan): support null result

---

ethers-solc/src/cache.rs
ethers-solc/src/compile/project.rs

improve cache traces for debugging 
https://github.com/foundry-rs/foundry/issues/2493

chore(solc): add more cache traces

---

ethers-contract/ethers-contract-derive/src/event.rs
ethers-contract/tests/it/derive.rs

Closes https://github.com/gakonst/ethers-rs/issues/2261
support unit structs in EthEvent
decoding is just checking the signature.

feat(abigen): support empty events

---

CHANGELOG.md
ethers-core/src/types/chain.rs

Refs #2038, https://github.com/gakonst/ethers-rs/pull/2268#discussion_r1138931364
Doesn't fix it because you still need to replace kebab-case to snake_case

feat(core): roundtrip serde + to/from strings

---

ethers-core/src/types/chain.rs

A followup of https://github.com/gakonst/ethers-rs/pull/2268 in the context of https://github.com/gakonst/ethers-rs/pull/2270. I didn't trust myself with the serde and strum configurations so I've added a test checking if they match.

fix: use to_string in mainnet chain variant

---

Cargo.toml
ethers-contract/ethers-contract-abigen/Cargo.toml

Fixes #2271
Fixes #2273
Explicitly specify `resolver = "2"` in the workspace
Add missing features which were getting wrongly compiled in due to resolver defaulting to "1"

fix: feature resolution

---

ethers-core/src/types/trace/geth.rs
ethers-core/src/types/trace/geth/call.rs

The CallLogFrame was not being exported from geth which made it
difficult to store all the logs using the ethers type.
Export CallLogFrame so it's accessible publicly via `ethers::types`.
Also export the internal fields.

fix(core): re-export CallLogFrame from geth types

---

ethers-addressbook/src/lib.rs
ethers-contract/ethers-contract-abigen/src/lib.rs
ethers-contract/ethers-contract-derive/src/lib.rs
ethers-contract/src/lib.rs
ethers-core/src/lib.rs
ethers-etherscan/src/lib.rs
ethers-middleware/src/lib.rs
ethers-providers/src/lib.rs
ethers-signers/src/lib.rs
ethers-solc/src/lib.rs
ethers/src/lib.rs

This doesn't actually fix the doc problem, since it has to be enabled in `generic-array`, but it prevents this happening in the future for our crates
Adds `#![cfg_attr(docsrs, feature(doc_cfg))]` to all workspace crates (minus examples)

fix: enable doc_cfg feature for docsrs

---

ethers-signers/src/aws/utils.rs

A recent PR (https://github.com/gakonst/ethers-rs/pull/2260) broke the AWS KMS signer. With the latest version, using the signer would either result in a panic (in debug mode, for subtraction overflow), or simply wrong signatures. Relevant code:
https://github.com/gakonst/ethers-rs/blob/16f9fab75cb43e2d9e4c2b74b68afde7577f0e2f/ethers-signers/src/aws/utils.rs#L43-L56
Note that `v` is already the recovery ID. There's no need to subtract it by 1 (doing so when `v` is 0 panics). `v` can also only be `0` or `1`, so there's also no need to mod by 2.
Just use `v` directly in `apply_eip155`.

fix: broken eip155 logic in aws signer

---

book/getting-started/start_a_new_project.md

Add dependency for getting-started.md,the sample code cannot run because it is missing this dependency.
Add ‘eyre’ dependency

chore: add eyre dependency

---

ethers-core/src/types/chain.rs
ethers-etherscan/src/lib.rs
ethers/src/lib.rs

new rustc lint dropped, warn level by default

fix: ambiguous_glob_reexports rustc lint

---

ethers-contract/ethers-contract-abigen/src/multi.rs

no that we have auto-releases, we can switch to using crates dep by default for generated bindings.
we can also depend on ethers from crates in foundry from now
wdyt @DaniPopes (harcoding the current major release is probably the easiest solution)
cc @leonardoalt 

chore: use ethers 2 by default when generating bindings

---

ethers-contract/ethers-contract-derive/src/abi_ty.rs
ethers-contract/ethers-contract-derive/src/calllike.rs
ethers-contract/ethers-contract-derive/src/codec.rs
ethers-contract/ethers-contract-derive/src/event.rs
ethers-contract/ethers-contract-derive/src/lib.rs
ethers-core/src/abi/mod.rs
ethers-core/src/abi/tokens.rs

Currently we go straight into decoding which can become expensive when called continuously from a big enum, eg foundry HEVM or HardhatConsole. We have the ParamType to decode so we can calculate very cheaply a minimum bound in bytes to check against
- Add a minimum bound check for the given bytes to early return for in `derive(EthCodec)`
- (drive by) Fix tuple implementations of `Tokenizable`
- these would panic if given a `Token::Tuple` of the wrong length
- also we have ownership of the `Vec` so `into_iter` is better than `drain`

perf: early return in EthCodec derive

---

ethers-core/src/types/transaction/response.rs

Fixes: #1849
As stated in issue #1849, when the function `decode(rlp)` is used to build a transaction from its rlp serialization (i.e. raw transaction) the field `hash` of the resulting `Transaction` is not set (set to default value, hash 0x0).
The `hash` field of the returned `Transaction` is calculated as the `keccak256` of the rlp bytes.   
The test for the correctness of this change can be run with 
```shell
cargo test --package ethers-core types::transaction::response::tests::decode_tx_assert_hash
```

feat(core): `Transaction::decode()` sets the hash

---

ethers-etherscan/src/gas.rs
ethers-etherscan/tests/it/gas.rs
ethers-middleware/src/gas_oracle/etherscan.rs
ethers-middleware/src/gas_oracle/mod.rs

Closes  #2324
This updates the `GasOracle`'s `{safe_gase_price,propose_gas_price,fast_gas_price}` from `u64` to `f64`
BREAKING CHANGE: This considered a public api breaking change, since `f64` and `u64` is not compatible with each other.

fix(etherscan)!: change the `GasOracle` fields to be `f64`

---

ethers-middleware/src/gas_oracle/etherscan.rs
ethers-middleware/src/gas_oracle/mod.rs
ethers-middleware/tests/it/gas_oracle.rs

While working on #2325 I did not notice that `parse_units` will return the correct value and will be no need to multiply the result again with `GWEI_TO_WEI_U256` (`1_000_000_000`) extra zeros! which makes the gas calculations insanely incorrect!
Removing the multiplication process solves that issue.
Edit: actually, there was a method called `from_gwei_f64` that we can use for that.

fix(middleware): no need to multiply again with `GWEI_TO_WEI_U256`

---

ethers-solc/src/artifacts/mod.rs

required for the bug fix for https://github.com/foundry-rs/foundry/issues/3553
can we release a new version after this?

feat(solc): add Settings sanitize

---

ethers-core/src/types/chain.rs

I've noticed reading the source code that in the `Chain::is_legacy` method `FilecoinHyperspaceTestnet` was listed as known EIP-1559 compatible while `FilecoinMainnet` as unknown. 
I've restructured the code to reflect that `FilecoinMainnet` is known to be EIP-1559 compatible as well. This is just a documentation change, since the value returned is `false` in both cases.
Source official [Filecoin blog:](https://filecoin.io/blog/posts/eip-1559-in-filecoin/) "EIP-1559 is implemented and live on the Filecoin mainnet."
-   [ ] Added Tests (n/a)
-   [ ] Added Documentation (n/a)
-   [ ] Breaking changes (n/a)

fix: document FilecoinMainnet as EIP-1559 compatible

---

.github/workflows/deps.yml
deny.toml

- Remove outdated exceptions and `[[license.clarify]]`
- Make config more strict for wildcard and git dependencies
- bad practice, git dependencies are not allowed when published so doesn't hurt adding an extra check
- Add `MPL-2.0` to license allow list since it generates a warning for being copy-left
- Looked to other crates using the `webpki-roots` crate: <https://github.com/hyperium/tonic/blob/master/deny.toml>
The only remaining warnings are for duplicate crates

chore: update deny config

---

ethers-solc/src/artifacts/mod.rs

if we `compile_exact(file)` we should not filter errors because this obfuscates failed compile runs
discovered via:
https://github.com/foundry-rs/foundry/issues/4467

chore: dont retain errors

---

ethers-etherscan/src/account.rs
ethers-etherscan/src/contract.rs
ethers-etherscan/tests/it/account.rs
ethers-providers/src/ext/dev_rpc.rs
ethers-providers/src/middleware.rs
ethers-providers/src/rpc/provider.rs
ethers-providers/src/toolbox/call_raw.rs
ethers-providers/src/toolbox/pending_transaction.rs

Cleaned up doctests with `tokio::main` and `no_run`, and etherscan tests which all had redundant client initializations which are not the focus of the example
I don't believe running async tests in doctests is a great practice
Breaking change in `etherscan::Client::get_ether_balance_multi` because slice of references is not good

docs: update some doctest examples

---

ethers-providers/src/rpc/pubsub.rs

streams only register the waker if they're pending
Returning "pending" when the underlying stream is still ready does not ensure that the rt will poll again. 

fix: poll stream until pending

---

ethers-etherscan/src/gas.rs
ethers-etherscan/tests/it/gas.rs
ethers-middleware/src/gas_oracle/etherscan.rs

Extremely permissive deserializer for etherscan gas units
More complete fix to #2326 #2325 
Introduce a deser that performs the following in order:
- checks for a JSON number, and scales it by WEI_PER_GWEI
- checks for a string, then tries to parse it as a float number of gwei
change the etherscan response object to have `U256` responses that are ALWAYS in `wei` rather than in f64 gwei

feature: very permissive etherscan gwei deser

---

ethers-core/src/types/chain.rs

https://github.com/foundry-rs/foundry/issues/4716
Add Base Goerli as a chain.

feat: add Base Goerli chain

---

CHANGELOG.md
cliff.toml

The `git-cliff` config `ignore_tags` was ignoring *all* `^ethers-.*` tags, which includes the base `ethers-vX.Y.Z`.
Exclude all `ethers-*` tags except for `ethers-vX.Y.Z`, and trim the name in the template

docs: fix git-cliff tag filtering

---

README.md

chore: add viem to wasm section on readme

---

ethers-core/src/types/chain.rs

chore: Add ZKSync into the Chain type

---

ethers-core/src/utils/genesis.rs
ethers-core/src/utils/mod.rs

Previously, we would parse decimal strings like `"100000"` as hex, because they did not match a raw `serde_json::Number` variant in `IntOrHex`. This caused problems when parsing genesis fields with `from_int_or_hex`, for example:
```json
"alloc": {
"0x3E951C9f69a06Bc3AD71fF7358DbC56bEd94b9F2": {
"balance": "1000000000000000000000000000"
},
}
``` 
This would parse `"1000000000000000000000000000"` instead as `0x1000000000000000000000000000`.
This did not fail `U256` parsing because its `FromStr` implementation accepts both `0x`-prefixed and non-`0x`-prefixed strings, and will deserialize both as hex.
Check for `0x` prefixes in `from_int_or_hex` and `from_u64_or_hex` if the value matches a `String` instead of `serde_json::Number`. If there is a prefix, deserialize as hex. Otherwise, the …

fix(core): fix decimal string IntOrHex parsing

---

ethers-core/src/types/fee.rs
ethers-core/src/types/serde_helpers.rs
ethers-core/src/types/trace/geth.rs
ethers-core/src/types/trace/geth/call.rs
ethers-core/src/types/trace/geth/pre_state.rs
ethers-core/src/utils/genesis.rs
ethers-core/src/utils/mod.rs
ethers-providers/src/ext/admin.rs

Some fields were missed for `Genesis` decimal string deserialization.
Followup to #2359, adding remaining deserializers to `Genesis` fields.
This changes usages of `from_int_or_hex` to `deserialize_stringified_numeric`, and removes the `from_int_or_hex` methods.
Modifies `StringifiedNumeric` to support arbitrary precision.

 fix(core): add from_x_or_hex to remaining genesis fields 

---

ethers-core/src/types/chain.rs

Polygon zkEVM is a growing L2 chain that launched recently. It isn't currently supported by ethers-rs.
Add chain information to ethers-core/src/types/chain.rs

Polygon zkevm support

---

ethers-signers/src/wallet/private_key.rs

`LocalWallet::from_str` actually panics if != 32 bytes
Closes https://github.com/foundry-rs/foundry/issues/4772
add check and return error instead

fix: don't panic if hex str too short

---

ethers-solc/src/artifacts/mod.rs
ethers-solc/src/compile/output/mod.rs
ethers-solc/src/compile/project.rs

Monotone color ugly and bad. More colors good.
Tried as much as possible to use the same format as [Solc's formatter](https://github.com/ethereum/solidity/blob/a297a687261a1c634551b1dac0e36d4573c19afe/liblangutil/SourceReferenceFormatter.cpp#L105).
Before:
After (left: `solc --error-codes`, right: this):

feat(solc): color when formatting Error and OutputDiagnostics

---

ethers-solc/src/artifacts/mod.rs
ethers-solc/src/compile/mod.rs

fix bug 2370

---

ethers-signers/src/trezor/app.rs

- Trezor version check works correctly only for Trezor Model T which uses version numbers 2.x.x
- this PR changes the logic so also Trezor One versions are properly handled

fix: correctly handle Trezor One support

---

ethers-providers/src/rpc/provider.rs

Related to #2346 and foundry issue [#4658](https://github.com/foundry-rs/foundry/issues/4658)
`ethers_providers::is_local_endpoint` function would only work with `localhost` and `127.0.0.1` strings.
From substring matching to rust pattern matching based on `URL::parse` result.

fix: ethers_providers::is_local_endpoint with rust matching pattern on URL::parse

---

ethers-contract/ethers-contract-derive/src/display.rs
ethers-contract/ethers-contract-derive/src/lib.rs

docs: update docs and examples on derive macros

---

ethers/Cargo.toml
ethers/src/lib.rs
examples/contracts/Cargo.toml

fix: add back `ethers-solc` feature for `ethers`

---

ethers-core/src/utils/mod.rs

as ethers-rs provide `to_checksum` function, but there not provide a way to verify a checksum-like address.
so I add a utilities function to verify a checksum address is valid.

feat: add fn parse_checksummed

---

ethers-solc/src/artifacts/mod.rs

The `wast` field maybe missing in solc compiler output.
JSON input:
```json
{
"language": "Solidity",
"sources": {
"src/tfuzz.sol": {
"content": "contract T{}"
}
},
"settings": {
"optimizer": {
"enabled": false,
"runs": 200
},
"outputSelection": {
"*": {
"": [
"*"
],
"*": [
"*"
]
}
},
"evmVersion": "london",
"libraries": {}
}
}
```
Output:
```bash
/tmp $ solc --standard-json < compile.json | jq . | grep -C1 wasm
},
"ewasm": {
"wasm": ""
},
/tmp $
```
This is causing failure to deserialize compilers json outputs while the compilation is successful.
As proposed.
No need for tests.
No need for further docs.
This shouldn't introduce any breaking changes.

Fix `wast` field is missing

---

ethers-core/src/types/trace/geth.rs
ethers-providers/src/middleware.rs
ethers-providers/src/rpc/provider.rs

Support for more Geth `debug` methods.
Adds [`debug_traceBlockByNumber`](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugtraceblockbynumber) and [`debug_traceBlockByHash`](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugtraceblockbyhash) RPC methods.

feat: add geth debug_traceBlock methods

---

ethers-contract/ethers-contract-derive/src/codec.rs

https://github.com/grantweii/ethers-macro-bug
Specify the output of the sum to avoid ambiguity when other types implementing `Sum<usize>` are in scope

fix: specify sum type in abigen to avoid ambiguity

---

ethers-solc/src/artifacts/mod.rs
ethers-solc/src/compile/mod.rs

Paris support was added in [0.8.18](https://blog.soliditylang.org/2023/02/01/solidity-0.8.18-release-announcement/), and Shanghai support is on track to be released with [0.8.20](https://github.com/ethereum/solidity/pull/14107).

feat(solc): add support for Paris and Shanghai EVM versions

---

ethers-core/src/types/chain.rs

ZkSync mainnet is among the supported chains, but the testnet is missing.
Added ZkSync testnet to the `Chain` enum.
-   [ ] Added Tests **n/a**
-   [ ] Added Documentation **n/a**

feat: add ZkSync testnet

---

ethers-providers/src/rpc/transports/mock.rs
ethers-providers/src/rpc/transports/mod.rs

The goal is to be able to test any json-rpc errors and consequences afterwards. I needed such modification while writing [test cases](https://github.com/ensdomains/ethers-ccip-read/blob/5c4610dcec7d0fdbcb1886a7cb1a43038159a0fc/src/middleware.rs#L500) for a middleware. 
- Added new enum called `MockResponse`, instead of passing the `Value`, now we pass this enum as a response type. 
- MockProvider now checks the response types with `match` and treats accordingly.
- new fn called `push_response` helps pushing the JsonRpcError as the next response.

add mock response to test json rpc errors

---

ethers-core/src/types/trace/geth.rs

Some types related to the geth-specific. `prestateTracer` were not previously available, which makes using the `prestateTracer` difficult. 
As the types are already created and defined, this PR just makes them available for the crate.

feat(core): export geth trace pre state types

---

ethers-providers/src/rpc/transports/ws/backend.rs
ethers-providers/src/rpc/transports/ws/manager.rs
ethers-providers/src/rpc/transports/ws/mod.rs
ethers-providers/src/rpc/transports/ws/types.rs

Some small fixes found while going through the ws code
- `to_raw_value`helper is slightly more efficient
- ws ping frames are handled transparently by tungstenite

Misc ws fixes

---

README.md

add ccip-read middleware into readme

---

ethers-providers/src/rpc/transports/ws/backend.rs
ethers-providers/src/rpc/transports/ws/manager.rs
ethers-providers/src/rpc/transports/ws/mod.rs
ethers-providers/src/rpc/transports/ws/types.rs

Currently the websocket implementation does not allow to pass in a custom Tungestenite config. For example, its not possible to increase the default msg size over the Tungestenite default, which can lead to `Message Too Long` errors if fetching a lot of events with a lot of fields in them, one case where I've seen this failure in practice is when fetching around 8k events like this one:
```solidity
event TradeRequested(
address indexed tokenIn,
address tokenOut,
uint256 amountIn,
uint256 minAmountOut,
address recipient,
uint256 indexed tradeIndex,
address indexed trader
);
```
This PR adds 2 new methods to the `WsClient` and the `WsManager`:
- `connect_with_config` which is the same as `connect`, but allows taking in a Tungstenite config object
- `connect_with_config_and_reconnects` which …

feat(ws): add methods taking in a tungstenite config

---

ethers-solc/src/compile/mod.rs
ethers-solc/src/error.rs

Ran this while debugging an unrelated issue—I had installed 0.8.20 through an SVM fork and was running into this panic when running foundry. While this is correct and should error due to an unfound checksum (as i wasn't using the canonical svm-rs), this panic should probably be an error cc @mattsse 
Turn this panic into an error, and add a `ChecksumNotFound` variant to `SolcError`.

fix(ethers-solc): Error instead of panic when checking if the checksum was found

---

ethers-etherscan/src/verify.rs
ethers-solc/src/compile/mod.rs

This has to do with https://github.com/foundry-rs/foundry/issues/4909 — the typo on the `constructor_arguments` rename (required due to etherscan) is making blockscout complain. This sets the correct name as a rename and aliases the typo.

fix(`ethers-etherscan`): make typo on verify constructor arguments an alias

---

examples/anvil/Cargo.toml
examples/contracts/Cargo.toml
examples/events/Cargo.toml
examples/geth/Cargo.toml
examples/middleware/Cargo.toml
examples/providers/Cargo.toml
examples/queries/Cargo.toml
examples/subscriptions/Cargo.toml
examples/transactions/Cargo.toml
examples/wallets/Cargo.toml

fix: examples tokio feature

---

ethers-etherscan/src/contract.rs
ethers-etherscan/src/errors.rs

I've been investigating verification issues due to https://github.com/foundry-rs/foundry/issues/4909 — and it turns out that blockscout, unlike etherscan, likes to return `null` on the `result` field sometimes, instead of an empty string on `message` and the actual message on the `result` field, like etherscan. This in turn introduced a bug when detecting if a contract was already verified as it expects that the blockscout format is identical to etherscan's. 
To be a bit more specifc, this format is returned by blockscout when a contract is not verified, and this is _not_ what etherscan returns (see the `null` in result):
```
{
"message": "Contract source code not verified",
"result": null,
"status": "0"
}
```
While making a blockscout verification client might be the "best" fix, this is …

fix(`verify`): make verification result an option to handle blockscout's format

---

ethers-middleware/src/timelag/mod.rs
ethers-providers/src/middleware.rs
ethers-providers/src/rpc/provider.rs

geth recently added [SubscribeFullPendingTransactions](https://github.com/ethereum/go-ethereum/blob/73697529994e14996b7740730481e926d5ec3e40/ethclient/gethclient/gethclient.go#L196)
this PR just adds a new method called ```subscribe_full_pending_txs()```, which instead of streaming hashes, streams
whole tx bodies. the only edit was adding ```true``` as a additional parameter, so ```subscribe([utils::serialize(&"newPendingTransactions"), utils::serialize(&true)])```.

add subscribe_full_pending_txs()

---

ethers-providers/src/rpc/transports/common.rs

This PR creates a Raw Authorization type which allows the user to set the full Authorization header in a websocket request if the server they are connecting to does not conform to Bearer or Basic auth.
-   [trivial change ] Added Tests
-   [x ] Added Documentation
-   [ no] Breaking changes

feat: allow for Authorization header override with raw parameter

---

ethers-core/src/types/chain.rs

We want to better handle EVM discrepancies between different chains (see https://github.com/foundry-rs/foundry/issues/748). One of these things would be a little utility on the `Chain` type to quickly detect if a chain is Shanghai-enabled or not.
Adds the utility
-   [n/a] Added Tests
-   [n/a] Added Documentation
-   [n/a] Breaking changes

feat(core): Utility to detect Shanghai-enabled chains

---

ethers-contract/src/call.rs

Add a helper function to override nonce in contact `FunctionCall`
Currently, there is no way to override nonce from the contract `FunctionCall` struct. It would be useful to make it easier to override nonce too as it is with value, gas and gas price 
I added a helper function to set the nonce, so it can be overridden before a transaction is submitted.

feat: add nonce helper function

---

ethers-core/src/utils/mod.rs

Well, I've just spent 30 minutes trying to understand why I see 0 ETH as the output of my code. Turns out, it was a problem in prase_ether function. Noticed an issue #2356 
Use `parse_units(value, "ether").unwrap();`
We can safely unwrap here, since `parse_units` returns Err only when units >= 77.
-   [ x ] Added Tests
-   [ x ] Added Documentation
-   [ x ] Breaking changes

ethers::utils::format_ether should show decimal places

---

ethers-contract/ethers-contract-abigen/src/contract.rs
ethers-contract/ethers-contract-abigen/src/lib.rs
ethers-contract/ethers-contract-abigen/src/source/mod.rs

... and an `include_bytes!` when not in build scripts. Signals Cargo to rebuild if the source files change.

feat(abigen): emit cargo build script directives

---

ethers-providers/src/middleware.rs
ethers-providers/src/rpc/provider.rs

Geth removed the `threads` arg from `miner_start`, in 1.12.0 with https://github.com/ethereum/go-ethereum/pull/27178 so we remove it as well. The endpoint is still necessary for clique block production.
Remove the argument from `miner_start`

fix: remove deprecated mining threads arg

---

ethers-etherscan/src/contract.rs

Blockscout responses again hide the actual result in the message when it comes to checking if the ABI of the contract exists. This was causing the etherscan verifier to error out instead of bubbling up the expected `ContractCodeNotVerified`:
```Response result is unexpectedly empty: status=0, message=Contract source code not verified```
Bubble up the error if it matches
-   [n/a] Added Tests
-   [n/a] Added Documentation
-   [n/a] Breaking changes

fix(`verification`): bubble up error properly if using blockscout

---

ethers-core/src/types/chain.rs
ethers-middleware/src/signer.rs

Sets Optimism Mainnet / Goerli as an EIP-1559 supporting chain in `chain.rs`.
Optimism Mainnet / Goerli both support EIP-1559 after the Bedrock upgrade.
-   [x] ~~Added Tests~~ Altered existing test
-   [x] ~~Added Documentation~~ n/a

feat(ethers-core): OP Bedrock Upgrade

---

ethers-core/src/types/chain.rs

The blocktime is 2 seconds after the bedrock upgrade. Updates the `Optimism` and `OptimismGoerli` `Chain` structs to return this amount of time.
Update `chains.rs`

ethers-core: update optimism blocktime hint

---

ethers-etherscan/src/verify.rs

So, it turns out that etherscan still has this `constructorArguements` typo and doesn't support the properly spelled version. However, some blockscout instances seem to be be able to parse `constructorArguments` and not `constructorArguements`, so as a workaround for people we're populating both fields and sending them, as the APIs do not discriminate on redundant json fields.
Adds another field `blockscout_constructor_args`, that gets autopopulated with the same info that gets passed in from `constructors_args`. The former will get serialized to `constructorArguments`.
-   [n/a] Added Tests
-   [n/a] Breaking changes
cc @mattsse

fix(`verification`): re-introduce etherscan typo and populate properly-spelled field as backup

---

ethers-contract/Cargo.toml
ethers-contract/ethers-contract-derive/src/abigen.rs
ethers-contract/tests/it/abigen.rs
ethers-contract/tests/solidity-contracts/OverloadedFuncs.json

Added support for array parameters in abigen methods. Closes #2394

fix: allow arrays in abigen 'methods'

---

ethers-contract/src/base.rs

Got hit by a runtime panic on this. Simple fix.

fix: prevent panics decoding too short input

---

ethers-providers/src/middleware.rs
ethers-providers/src/rpc/provider.rs

There's currently no wrapper for the `eth_getTransactionByBlockHashAndIndex` and `eth_getTransactionByBlockNumberAndIndex` RPC calls
implementing them by combining `get_transaction` and `get_uncle`

get_transaction_by_block_and_index

---

ethers-core/src/utils/anvil.rs
ethers-core/src/utils/ganache.rs
ethers-core/src/utils/geth.rs
ethers-core/src/utils/mod.rs

reverts changes from #2189 and only used unused port when required
cc @DaniPopes

refactor: replace unused ports with unused port

---

README.md

Adding bundler to the section "Projects using ethers-rs".
This PR can be ignored if you're not accepting projects to that list.

Add bundler to README.md

---

ethers-middleware/src/gas_escalator/mod.rs
ethers-middleware/src/gas_oracle/polygon.rs

fix(middleware): polygon gas stations

---

ethers-core/src/utils/mod.rs

example didn't compile after changed api

doc: fix doc example

---

ethers-etherscan/src/contract.rs
ethers-etherscan/tests/it/contract.rs

Always finding funny things when playing with Etherscan API, try:
```bash
curl "https://api.etherscan.io/api?module=contract&action=getsourcecode&address=0x68b26dcf21180d2a8de5a303f8cc5b14c8d99c4c"
```
This gives a plain source code mapping in the `SourceCode` field instead of plain source code.
As shown.

Etherscan could also have a plain source mapping

---

ethers-solc/src/artifacts/mod.rs

related to https://github.com/foundry-rs/foundry/pull/5349: 
> More and more people (including myself) are using the magical via-ir to solve the "stack too deep" issue. However, this would cause problems in test coverage as all the optimizations are disabled in test coverage.
> 
> The solidity team suggests working around this issue by enabling "via-ir" with a https://github.com/ethereum/solidity/issues/12533#issuecomment-1013073350
> 
> And this workaround is also recommended in the [FAQ](https://github.com/sc-forks/solidity-coverage/blob/89882a211e9f69ed6b1afc99b2bb9d56b857e686/docs/faq.md?plain=1#L85) of solcoverage.
> 
> In this pr, a new "--ir-minimum" option is added to the coverage subcommand, which enables "via-ir" with a minimum amount of optimization.
And @mattsse  suggests …

feat(ethers-solc): add with_via_ir_minimum_optimization

---

ethers-solc/src/buildinfo.rs
ethers-solc/src/compile/output/mod.rs

Make AggregatedCompilerOutput `Serialize` and `Deserialize`, which should be trivial. Not sure why it wasn't supported before.

Make AggregatedCompilerOutput DeSerialize/Serialize

---

ethers-providers/Cargo.toml
ethers-providers/src/ext/ens.rs

`ens::namehash` doesn't correctly compute nodes for ENS names that contain Unicode characters as documented in [foundry#5386](https://github.com/foundry-rs/foundry/issues/5386)
Currently, when `providers::resolve_name` is called on an ENS name like ret↩️rn.eth, it will produce a flawed node.
`ethers-rs` treats the nodes as sets of 32 decimal values that when converted into their hex equivalent and prepended with `0x`, produce a node which is used to get the resolver contract for the ENS name. 
```bash
[58, 221, 97, 107, 77, 172, 118, 9, 34, 35, 212, 59, 68, 92, 73, 191, 217, 137, 183, 219, 23, 92, 60, 236, 100, 137, 88, 71, 201, 249, 185, 116]
0xadb545a232c011f5aa341c04e144e7ab15be672fe94cfea9138fc0b293229ad5
```
```bash
[61, 229, 244, 192, 45, 182, 27, 34, 30, 125, 231, 241, 196, 14, 41, …
```

fix(providers): `ens::namehash` with Unicode characters

---

ethers-signers/Cargo.toml
ethers-solc/src/config.rs
ethers-solc/src/remappings.rs

solc supports [remapping contexts](https://docs.soliditylang.org/en/latest/path-resolution.html#import-remapping) to limit the scope of remappings to subsets of your project, e.g. libraries you import.
We want this for https://github.com/foundry-rs/foundry/issues/1855
In https://github.com/foundry-rs/foundry/issues/1855 we ideally would want to auto-detect the contexts as well, i.e. limit remappings from libraries to the library roots.
This PR adds support for parsing and serializing remapping contexts, and limits import resolution based on the remapping contexts.

feat: support remapping contexts

---

ethers-signers/src/wallet/private_key.rs

This function is similar to Wallet::new_keystore, but instead of adding the a random private key to the file, it adds a key passed as a parameter.
This is handy when you want to safe an existing private key in an encrypted file.
This can also help with the implementation of https://github.com/foundry-rs/foundry/issues/5057

feat(signers): add Wallet::encrypt_keystore

---

ethers-core/src/types/transaction/eip2718.rs

@cryptoAtWill was testing an API that used `ethers_core::types::TypedTransaction` on the server side to decode the JSON-RPC parameters of an `eth_estimateGas` call sent by Hardhat when he noticed that it was rejected due to the tag not being recognised. The reason was that `ethers` [expects](https://github.com/gakonst/ethers-rs/blob/ethers-v2.0.8/ethers-core/src/types/transaction/eip2718.rs#L43) `"type": "0x02"` while Hardhat sends `"type": "0x2"`. 
I noticed that some of the [tests](https://github.com/gakonst/ethers-rs/blob/ethers-v2.0.8/ethers-core/src/types/transaction/eip2718.rs#L727) actually contain `"0x2"` but it's not used, so I thought this is a bug.
The simple solution in this PR is to add an `alias` to the `TypedTransaction` variants, so both padded and non-padded versions are …

Add aliases for TypedTransaction tags that work with Hardhat

---

ethers-core/src/utils/anvil.rs

fix: parse privat keys correctly

---

ethers-solc/src/cache.rs

Default is 8KiB, bumped to 256KiB for solc cache files since it seems more adequate

perf: buffer writes when serializing json

---

ethers-solc/src/artifact_output/mod.rs
ethers-solc/src/cache.rs

Hot code path that contributes to ~30% of the time spent preparing for a compiler run in forge
cc @mattsse 

perf(solc): memoize `is_dirty` results

---

ethers-solc/src/compile/mod.rs

ref https://github.com/foundry-rs/foundry/issues/5601
https://github.com/alloy-rs/svm-rs/issues/95
> on windows solc downloads are zip files, the checksums are for the zip files
> however, we extract the exe and are hashing this file in ethers-solc
this disables the checksum until we can properly do this, this will make it easier for windows users to use forge without redownloading all files over and over again

fix: skip checksums on windows for now

---

ethers-solc/src/compile/mod.rs

ref https://github.com/foundry-rs/foundry/issues/5601

fix: skip checksums for old windows solc

---

Cargo.toml
ethers-providers/Cargo.toml
ethers-signers/Cargo.toml
ethers-solc/Cargo.toml

Addresses #2564. Note that this doesn't close the issue since `rusoto*` deps would need to be removed, see #2540.

chore(deps): bump all dependencies

---

examples/wasm/Cargo.toml

New `coins-*` patch releases don't enable the `getrandom:"js"` feature anymore.

fix: wasm ci compilation

---

ethers-solc/src/cache.rs
ethers-solc/src/compile/mod.rs
ethers-solc/src/error.rs

When the Solc executable fails and the stderr is empty we throw `Solc error: ` which is not very helpful
cc @mattsse 
Make it print `Solc exited with {output.status}\n{output.stderr || output.stdout || "<empty output>"}`

fix(solc): empty 'Solc error: ' message

---

ethers-core/src/utils/anvil.rs

Fix https://github.com/gakonst/ethers-rs/issues/2568
obtaining `chainId` by reading anvil strings. at fork time, the current chain_id is displayed

fix: anvil invalid chain id

---

ethers-providers/src/rpc/transports/ws/backend.rs
ethers-providers/src/rpc/transports/ws/types.rs

…ng in errors.
json example:
"{"jsonrpc":"2.0","id":268,"result":null,"error":{"code":-32000,"message":"tracing failed: fee cap less than block base fee: address 0x4a4BA8a759e7217a1ff38749Aa6E73564C1D8a01, gasFeeCap: 11470668621 baseFee: 11484931392"}}"
If the json response contains both result and errors, it's better to return errors instead of "response must be a success/error or notification object"
Also, after returning "de::Error::custom", in
```
pub async fn handle_text(&mut self, t: String) -> Result<(), WsClientError> {
trace!(text = t, "Received message");
match serde_json::from_str(&t) {
Ok(item) => {
trace!(%item, "Deserialized message");
let res = self.handler.unbounded_send(item);
if res.is_err() {
return Err(WsClientError::DeadChannel)
}
}
Err(e) => {
error!(e = %e, "Failed …
```

PubSubItem deserialize

---

ethers-contract/src/multicall/middleware.rs
ethers-core/src/types/transaction/eip2718.rs
ethers-core/src/types/transaction/mod.rs
ethers-core/src/types/transaction/optimism.rs
ethers-middleware/src/gas_oracle/middleware.rs
ethers-providers/src/rpc/provider.rs
ethers-signers/src/ledger/app.rs
ethers-signers/src/trezor/app.rs
ethers-signers/src/trezor/types.rs

**Description**
Updates Optimism types to be inline with [op-reth](https://github.com/paradigmxyz/reth/pull/4377).

fix: Update optimism type names to be inline with reth

---

ethers-core/src/types/transaction/response.rs

**Description**
Adds deposit nonce field and l1 block info fields to the rpc transaction receipt.
The deposit nonce field is populated at creation while the l1 block info fields are hydrated for rpc requests.

feat: Optimism Hydrated RPC Receipt Fields

---

ethers-middleware/src/gas_oracle/mod.rs

When converting between gwei and U256 it was rounding to the nearest whole number based on the decimal. For example if you added 2.49, the result would be 20000000 which is not idea
Multiplied the f64 before the rounding occurs
-   [ yes] Added Tests
-   [no ] Added Documentation
-   [no ] Breaking changes

fix(oracle): update helper function to use correct conversion maths

---

ethers-core/src/types/chain.rs

As mentioned [here](https://github.com/gakonst/ethers-rs/issues/2583), Filecoin's Hyperspace testnet has been decommissioned. This PR aims to replace it with the currently supported testnet: Calibration.
This PR replaces all the Hyperspace occurrences with Calibration and adds the relevant RPC and block explorer URLs.  

chore: replace Filecoin Hyperspace testnet with Calibration

---

ethers-solc/src/artifacts/ast/mod.rs
ethers-solc/test-data/ast/bit_not.json
ethers-solc/test-data/ast/modifier_definition.json

Parsing failed on a number of solc contract json outputs found in wild.
Handle null values in some AST structures

Correctly parse null values in 0.7.0 asts

---

ethers-addressbook/src/contracts/contracts.json
ethers-addressbook/src/lib.rs

Adds USDT token address
It's 4x more popular than USDC, I see no reason not to have it
-   [x] Added Documentation (none needed)
-   [x] Breaking changes (none)

Add USDT token address

---

ethers-core/src/types/trace/geth.rs
examples/transactions/examples/trace_call.rs

Fixes #2604 
Allow to override block params for `debug_traceCall` which would in turn allow to trace a pending txn against pending block.
Added BlockOverrides fields which is similar to following impls.
https://github.com/ethereum/go-ethereum/blob/16cd1a7561155a264b1a1a2a5850b11c47dc18d4/internal/ethapi/api.go#L993
https://paradigmxyz.github.io/reth/docs/reth/rpc/types/struct.BlockOverrides.html

added blockoverride field in geth tracing call options

---

ethers-core/src/types/transaction/response.rs

- closes #2615
- rlp decoding order following the [specs](https://github.com/ethereum-optimism/optimism/blob/develop/specs/deposits.md#the-deposited-transaction-type)

fix: rlp decode deposit tx

---

ethers-providers/src/rpc/provider.rs

When running an application in k8s locally it is common to use `localdev.me` domain for ingress, as documented in [ingress-nginx docs](https://kubernetes.github.io/ingress-nginx/deploy/#local-testing). This is a domain owned by Amazon which DNS points to `127.0.01`, can be considered stable. Ethers-rs, however, doesn't recognize this as a local chain. 
My primary motivation here is for polling in foundry to have local polling behavior running against a local k8s cluster.
Update the`is_local_endpoint` rules to recognize `localdev.me` as local chain.
-   [x] Added Documentation (I don't think this is needed)
-   [x] Breaking changes (none)

Recognize localdev.me as "local" domain

---

ethers-core/src/types/chain.rs

Mantle is a growing L2 chain that launched recently. It isn't currently supported by ethers-rs.
Added Mantle, MantleTestnet to the `Chain` enum.

feat(chain): add mantle, mantle-testnet

---

ethers-contract/ethers-contract-abigen/src/multi.rs

This seeks to close #2599 and should link to [Foundry PR #5836](https://github.com/foundry-rs/foundry/pull/5836). The intent is to be able to allow for `serde::{Deserialize, Serialize}` to be derived on contract bindings either via module or crate. 
PR here has the intent of providing support for an additional dependency in the `Cargo.toml` generated when bindings are output as a crate.
This solution here seems a bit simplistic and forcefully assumes the end user will want a specific version of `serde` as an included dependency. It could be good, instead, to:
- Allow for dependencies to be chosen if there are extra derives added to the crate.
- Also forcefully add the `serde` derives to the contract bindings at this level.
- Check for most recent `serde` version or the version used within …

feat: add `dependencies` to `MultiBindingsInner`

---

ethers-core/src/utils/mod.rs

Includes #2632  + a `raw_public_key_to_address`, which does only syntactic checks

More address conversion util methods 

---

ethers-contract/src/multicall/constants.rs

I project I am using uses MulticallV3 across different chains and currently MulticallV3 is deployed on Holesky (https://holesky.etherscan.io/address/0xcA11bde05977b3631167028862bE2a173976CA11) however not listed in ethers-rs.
Added Holesky support to the supported chain id's constant.

Add Holesky to the Multicall supported chain id's

---

ethers-core/src/types/signature.rs

Normalize v was written to return invalid V values 
Fix it to always return a valid value
I chose not to correct the signature of `Signature::recovery_id()` because that would be a breaking change

fix: normalize v always returns a valid value

---

book/events/logs-and-filtering.md
examples/events/Cargo.toml
examples/events/examples/subscribe.rs

adds an example of how to subscribe to EthEvents
I realized the Borrow requirement is really bad DX when using Arc
```rust
fn new<B, M>(filter: Filter, provider: B) -> Event<B, M, Self>
where
Self: Sized,
B: Borrow<M>,
M: Middleware,
{
```

feat: add ws subscribe example

---

ethers-solc/src/config.rs

When using ethers_solc to compile contracts, remappings have an issue with the hardcoded specific fix for an openzeppelin contracts issue. 
I'm not very familiar with the issue described in the doc comments, but it is erroring in situations where it shouldn't be applicable. 
```rust
// we handle the edge case where the path of a remapping ends with "contracts"
// (`<name>/=.../contracts`) and the stripped import also starts with
// `contracts`
if let Ok(adjusted_import) = stripped_import.strip_prefix("contracts/") {
if r.path.ends_with("contracts/") && !lib_path.exists() {
return Path::new(&r.path).join(adjusted_import)
}
}
```
Example import in sol file:
```
import {Math} from "@openzeppelin/contracts/utils/math/Math.sol";
```
Example remapping:
``` …
```

fix(ethers_solc): hardcoded import remapping fix

---

ethers-etherscan/src/account.rs
ethers-etherscan/tests/it/account.rs

The Etherscan API supports querying [Beacon Chain Withdrawals by Address and Block Range](https://docs.etherscan.io/api-endpoints/accounts#get-beacon-chain-withdrawals-by-address-and-block-range) since the Capella hardfork. However, this method is not supported by `ethers-etherscan` yet.
This PR adds the `fn get_beacon_withdrawal_transactions` and `struct BeaconWithdrawalTransaction` type.

feat: support Etherscan beacon withdrawal transactions

---

ethers-solc/Cargo.toml

solang-parser v0.3.3 has been released, which fixes some minor solidity parsing issues.

Update solang-parser to v0.3.3

---

ethers-contract/src/multicall/mod.rs
ethers-providers/src/rpc/provider.rs
ethers-providers/src/stream/mod.rs
ethers-signers/src/wallet/mod.rs

clippy fixes and disable broken tests that are no longer supported by the provider used (llamarpc)

chore: make CI green again

---

Cargo.toml
ethers-core/Cargo.toml
ethers-etherscan/Cargo.toml
ethers-etherscan/src/errors.rs
ethers-etherscan/src/lib.rs
ethers-etherscan/src/stats.rs
ethers-etherscan/tests/it/main.rs
ethers-etherscan/tests/it/stats.rs

The following APIs have been implemented.
- https://docs.etherscan.io/api-endpoints/stats-1
- Get Total Supply of Ether (`ethsupply`)
- Get Total Supply of Ether 2 (`ethsupply2`)
- Get Ether Last Price (`ethprice`)
- Get Total Node Count (`nodecount`)
Thank you for developing such fantastic software. I'm working on a project called "[lazy-etherscan](https://github.com/woxjro/lazy-etherscan)",
and I would like to display statistical information about Ethereum within it.
After reviewing "ether-rs", I noticed that this functionality was not yet implemented,
so I decided to create this pull request.
I have implemented several of the statistical APIs from Etherscan's API documentation (https://docs.etherscan.io/api-endpoints/stats-1),
excluding the PRO features and "Get Ethereum Node Size". I …

feat(etherscan): Implemented Some APIs for `stats`

---

ethers-core/src/types/block.rs

Cancun will introduce new fields in the block, namely `parent_beacon_block_root`, `blob_gas_used`, and `excess_blob_gas`. 
Add the fields to `Block<Tx>`.

feat: add cancun fields to Block

---

ethers-core/src/types/transaction/response.rs

Decoding empty RLP input will cause a panic.
Return an error on empty input instead.

fix: empty input in transaction rlp decoding

---

ethers-core/src/types/chain.rs

Our team would like to have this config within ethers-rs so that we do not have to hardcode it in our rust projects.
Added the Arb sepolia chain config to the types crate
-   [N] Added Tests
-   [N] Added Documentation
-   [N] Breaking changes

feat(arb-sepolia): Add arbitrum sepolia to chain definitions

---

ethers-core/src/types/chain.rs

https://scrollscan.com/api
results in
```
{"status":"0","message":"NOTOK","result":"Invalid API URL endpoint, use https://api.scrollscan.com"}
```
I presume this is why scroll verify is now failing

use https://api.scrollscan.com/ instead

---

ethers-core/src/types/trace/geth.rs

Some fields are missing, if `enable_return_data: Some(true)` at `.debug_trace_call` - return data is not deserialized
Added this fields

feat: Add fields to debug_trace_call

---

ethers-core/src/types/chain.rs

Deployed to Optimism Sepolia using Forge and realized I couldn't verify the contracts.
Add Optimism Sepolia to [ethers-core/src/types/chain.rs](https://github.com/gakonst/ethers-rs/pull/2665/commits/d17a187f909c5f80d18d46afc7cba288911f121d)
Network details: https://community.optimism.io/docs/useful-tools/networks/#op-sepolia

feat(chain): add Optimism Sepolia

---

README.md
ethers-addressbook/README.md
ethers-contract/README.md
ethers-core/README.md
ethers-etherscan/README.md
ethers-middleware/README.md
ethers-providers/README.md
ethers-signers/README.md
ethers-solc/README.md
ethers/src/lib.rs

ethers-rs is being deprecated in favor of Alloy and Foundry. See #2667.
Add deprecation notices to READMEs and crate-level doc comments.

docs: add deprecation notices

---

ethers-core/src/types/serde_helpers.rs
ethers-middleware/Cargo.toml
ethers-middleware/src/gas_oracle/mod.rs
ethers-middleware/tests/it/gas_oracle.rs
ethers/Cargo.toml
ethers/src/lib.rs
examples/middleware/Cargo.toml

No reason to pull in this dep always

chore: make ethers-ethercan optional in ethers-middleware

---

ethers-core/src/types/chain.rs

Adds support for Zora mainnet, testnet (goerli), and sepolia

feat(chain): add zora networks

---

ethers-core/src/types/chain.rs

ppl not providing `--legacy` for metis on foundry will face errors
specify that metis is not 1559 compatible
----
when i run fmt as described on the docs i'm getting a huge amount of changes
That is the reason why i didn't commit the changes.

fix: metis is no 1559

---

ethers-core/src/types/transaction/optimism.rs

The `is_system_tx` field is not being renamed to camel case version like the other fields, and is causing issues since it is renamed in a different part of the code: https://github.com/gakonst/ethers-rs/blob/34030b3e942be619ae180d0f9f0ae9b3121081a3/ethers-core/src/types/transaction/response.rs#L81
Rename to camel case. It brings up a question though which is why we dont by default rename all fields in the struct? I can make this change if that's preferred.
By making this change, it allows the tests in this PR to pass: https://github.com/foundry-rs/foundry/pull/6073
cc @mattsse 
-   [X] Added Tests (in foundry PR)

[fix] Missed renaming a field in camelcase

---

ethers-core/src/abi/codec.rs
ethers-core/src/abi/mod.rs

fixes:
- missing `AbiEncode` implem for tuples of length 16
- unused `num` variable in `impl_abi_codec_tuple` & `impl_abi_type_tuple` macros

fix: missing `AbiEncode` implem for tuples of length 16

---

ethers-contract/ethers-contract-abigen/src/lib.rs
ethers-contract/tests/solidity-contracts/draft-IERCPermit.json

closes https://github.com/foundry-rs/foundry/issues/6010
we were converting the file name to the contract's ident which fails if the file name is not an ident.
better errors and replace commonly used invalid tokens like `-`.

fix: better file name to ident conversion

---

ethers-core/src/types/chain.rs

Adding Scroll's long-term testnet on Sepolia. Also updating incorrect API url for Scroll's Etherscan explorer and an out-of-date API url for Scroll Alpha.

update: add Scroll Sepolia and update Scroll and Scroll Alpha Testnets

---

ethers-core/src/types/chain.rs
ethers-core/src/types/transaction/eip1559.rs
ethers-core/src/types/transaction/request.rs
ethers-core/src/utils/genesis.rs

https://github.com/ethereum/go-ethereum/pull/28078 changed the `go-ethereum` client to send the transaction payload in an `input` field instead of `data`, which is how it's [defined](https://github.com/ethereum/execution-apis/blob/431cf72fd3403d946ca3e3afc36b973fc87e0e89/src/schemas/transaction.yaml#L33-L35) in the API. Apparently most server implementations accept both fields, preferring `input` where both are present at the same time.
The `Eip1559TransactionRequest` has a `data` field, and thus it could not be used to deserialize such requests. 
The PR adds a special deserializer to the `Eip1559TransactionRequest::data` field so that it looks for `input` first, `data` second.

FIX: Accept 'input' or 'data', (but not both), in transaction request

---

ethers-contract/src/multicall/constants.rs

I couldn't use multicall with default constructor on Arbitrum Sepolia network due to this error: `Chain ID 421614 is currently not supported by Multicall. Provide an address instead.`.
Multicall is already deployed on Arbitrum Sepolia: https://sepolia.arbiscan.io/address/0xca11bde05977b3631167028862be2a173976ca11.
Added chain ID to the list of supported chains.

feat(multicall): add support for Arbitrum Sepolia

---

ethers-contract/src/multicall/constants.rs
ethers-core/src/types/chain.rs

There is no support for Base Sepolia as a chain.
Adds Base Sepolia and associated constants to `Chain` , multi-call deployment list.
Also, this PR adds Optimism Sepolia to the supported multicall chains.

feat: add Base Sepolia as a chain

---

ethers-contract/src/multicall/constants.rs
ethers-core/src/types/chain.rs

Newly launched Mode Network is not currently supported in ethers-rs
Adds support for Mode Network's Mainnet & Testnet (https://docs.mode.network)
Also adds Mode Mainnet support for Multicall3.

feat: Add Mode & Mode Sepolia

---

ethers-contract/src/multicall/constants.rs
ethers-core/src/types/chain.rs

There is no support for Blast Sepolia as a chain.
Adds Blast Sepolia and associated constants to `Chain` multi-call deployment list.

Feat: Add Blast Sepolia as a chain

---

ethers-core/src/types/chain.rs

https://polygon.technology/blog/introducing-the-amoy-testnet-for-polygon-pos
Polygon recently gave more information about the polygon amoy chain that will be the new standard testnet while Mumbai is to be deprecated as it will stop working once goerli is deprecated.
- Add the basic chain information to the existing Chain enum

Add polygon amoy to chain definitions

---

ethers-core/src/types/chain.rs

There are no aliases set for Base Mainnet, Sepolia and Goerli.
Add aliases for `Base`, `BaseGoerli` and `BaseSepolia` and related tests.

Add aliases for Base, BaseSepolia and BaseGoerli

---

ethers-providers/src/middleware.rs
ethers-providers/src/rpc/provider.rs

Add support for `eth_getHeaderByNumber` and `eth_getHeaderByHash` endpoints. To be used as follows:
```rust
use ethers_core::types::{BlockId, BlockNumber};
use ethers_providers::Middleware;
use ethers_providers::{Http, Provider};
async fn mytest() {
let provider = Provider::<Http>::try_from("http://localhost:8545").unwrap();
let by_num = BlockId::Number(BlockNumber::Number(18826806u64.into()));
let by_hash = BlockId::Hash(
"0xac45643453aba125a85a779163e7cfa40e4f8898639f1d5249de1c1481817510".parse().unwrap(),
);
// Use by_num or by_hash
let block = provider.get_header(by_hash).await.unwrap();
println!("block: {:?}", block);
}
```
Note that the same type `Block` is used, but non-header fields are left empty.

feat(rpc): add getHeader by number+hash

---

ethers-core/src/types/trace/mod.rs

That will solve when rpc server returns: "output":null, as Nethermind does

Update mod.rs Bytes to Option<Bytes>

---

ethers-core/src/types/chain.rs

There is no support for Blast mainnet.
Add Blast mainnet to `Chain`.

feat(chain): add blast mainnet

---

ethers-core/src/types/chain.rs

There is no support for Degen chain.
Add Degen chain to `Chain`.

feat(chain): add degen chain mainnet
