- README.md
- ethers-providers/src/provider.rs
- ethers-providers/tests/provider.rs
- ethers-signers/src/client.rs
- ethers-signers/tests/signer.rs
Fixes 2 bugs:
1. Previously we'd allow passing a block parameter in `estimate_gas`, which is wrong. The JSON-RPC spec is very misleading here because in the parameters docs it says "look above. The calls which support the default block param are only noted [here](https://eth.wiki/json-rpc/API#the-default-block-parameter)
1. Previously we'd pass additional arguments when watching events (serialization of `()`), which is obviously wrong
1. Remove the block parameter
2. Serialize only 1 param
> Provider Fixes on filters and gas estimation

- LICENSE-APACHE
- LICENSE-MIT
- ethers-contract/Cargo.toml
- ethers-core/Cargo.toml
- ethers-providers/Cargo.toml
- ethers-providers/src/ws.rs
- ethers-signers/Cargo.toml
- ethers/Cargo.toml
Adds an MIT/Apache 2 dual license since that's most adoption friendly and is generally in the spirit of most Rust repositories - h/t @zmanian 
Fixes #26 
Supersedes https://github.com/gakonst/ethers-rs/pull/27
> Dual license under MIT/Apache 2

- Cargo.lock
- ethers-contract/src/contract.rs
- ethers-providers/Cargo.toml
- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
- ethers-providers/src/stream.rs
- ethers-providers/src/transports/common.rs
- ethers-providers/src/transports/http.rs
- ethers-providers/src/transports/mod.rs
- ethers-providers/src/transports/ws.rs
- ethers-providers/tests/provider.rs
- ethers-signers/src/client.rs
- ethers/Cargo.toml
- ethers/examples/watch_blocks.rs
We were missing websockets support.
The new `websocket Provider` does not care about what the internal value will be, as long as it's a Sink/Stream. We use a mutex since we need thread safe interior mutability.
We add convenience instantiation methods using [`async-tungstenite`](https://github.com/sdroege/async-tungstenite/), for `async-std` and `tokio`. If required, we can further extend that in the future. The featrure flags are `async-std-runtime` and `tokio-runtime`.
We also add TLS Websocket support behind another feature flag, `async-std-tls` & `tokio-tls`. I personally found the integration slightly ugly, but couldn't come up with an alternative design other than conditional type aliases.
> Websockets + TLS for Async-Std / Tokio

- ethers-providers/src/pending_transaction.rs
- ethers-providers/src/stream.rs
- ethers-providers/tests/provider.rs
Previously, the `PendingTransaction` struct would spam the chain with calls to get the transaction receipt and the block number, as instructed by the runtime. Similarly to how Filter streams are implemented, the async runtime should not poll more frequently than the block time.
We add an `interval` parameter which makes the future sleep until the interval has passed.
> Add polling interval to pending transactions

- ethers-contract/src/factory.rs
- ethers-contract/tests/contract.rs
- ethers-signers/src/client.rs
- ethers-signers/src/wallet.rs
This allows using Contract either in read-only mode (e.g. for fetching data/events) or for using the accounts on the node as senders
> feat(signers): make Signer on Client optional

- ethers-contract/src/event.rs
- ethers-contract/src/factory.rs
- ethers-contract/tests/contract.rs
Oftentimes, clients will want to get the logs but also check their block number / transaction hash to index them in some way. This information was not exposed before.
Add a `query_with_meta` function which returns a `Vec<(D, LogMeta)>` instead of just `Vec<D>`.
> feat(contract): add helper to query events w/ metadata (block num + tx hash)

- ethers-contract/ethers-contract-abigen/src/contract.rs
- ethers-contract/ethers-contract-abigen/src/contract/common.rs
- ethers-contract/ethers-contract-abigen/src/contract/methods.rs
- ethers-contract/src/call.rs
- ethers-contract/src/contract.rs
- ethers-contract/src/factory.rs
- ethers-contract/tests/common/mod.rs
- ethers-contract/tests/contract.rs
- ethers-providers/src/lib.rs
- ethers-providers/src/pending_transaction.rs
- ethers-providers/src/provider.rs
- ethers-providers/src/stream.rs
- ethers-providers/tests/provider.rs
- ethers-signers/src/client.rs
- ethers-signers/src/lib.rs
- ethers-signers/tests/signer.rs
- ethers/examples/contract.rs
- ethers/examples/ens.rs
- ethers/examples/local_signer.rs
- ethers/examples/transfer_eth.rs
- ethers/examples/watch_blocks.rs
Currently, the Contract struct takes a reference to the Client (https://github.com/gakonst/ethers-rs/blob/master/ethers-contract/src/contract.rs#L166). 
This is done in order to avoid cloning/moving the client everywhere which would be: 
1. inefficient: you should have 1 client which is responsible for creating your requests used by all contract instances!
2. risky: Cloning the client might mean cloning the private key all over your memory. Bad. 
This introduced a lifetime in the Contract struct which can be a huge pain, in particular if you want to put the contract struct inside another struct which you want to do a spawn call for (which requires static bounds).
Replacing the reference with `Arc` does the trick. We get some runtime overheads, but that's acceptable.
Add a default …
> Replace contract client references with Arc

- Cargo.lock
- ethers-contract/Cargo.toml
- ethers-contract/tests/common/mod.rs
- ethers-contract/tests/contract.rs
- ethers-core/src/utils/ganache.rs
- ethers-providers/Cargo.toml
- ethers-providers/src/provider.rs
- ethers-providers/tests/provider.rs
- ethers-signers/src/wallet.rs
- ethers-signers/tests/signer.rs
- ethers/examples/contract.rs
- ethers/examples/local_signer.rs
- ethers/examples/transfer_eth.rs
Previously, we'd hardcode mnemonics, privatekeys and urls. This was making our tests less flexible, and also made us run them serially (or we'd also need to hardcode ports!).
Each time a ganache instance is spawned, it chooses a port dynamically. We also parse the process stdout and extract the private keys from it (up to 10 private keys), and return only after we've seen the `Listening on` line, (this feature is adapted from [Lighthouse](https://github.com/sigp/lighthouse/blob/4331834003a6206283c692fe0d6bfbc3c6cfc868/testing/eth1_test_rig/src/ganache.rs#L57-L82))
> Improve Ganache Flexibility

- ethers-providers/src/pending_transaction.rs
As @roynalnaruto pointed out, the PendingTransaction struct was not Send. Reproduced with https://gist.github.com/roynalnaruto/e9424d8917eaf330d8317d19328586b5#file-sample-rs-L34. This happens because the `BinPoxFut` trait object was not limited to be `Send` (which it should be ).
Add a `Send` trait bound.
> fix(provider): Add Send trait bound to PendingTx state future

- ethers-core/src/utils/mod.rs
Adds wasm compatibility for the `ethers-core` crate.
Core functionality (abi encoding etc) should be usable in more environments (e.g a browser).
1. Update the following constant in `crate::utils`:
- `pub const WEI_IN_ETHER: U256 = U256([0x0, 0x0, 0x0, 0x0de0b6b3a7640000]);`
2. Remove `ganache` and `solc` utils when compiling for wasm32
building this way should work now: 
`$ cargo build --target wasm32-unknown-unknown`
> feature: ethers-core wasm32 arch compatibility

- ethers-core/src/abi/tokens.rs
- ethers/tests/major_contracts.rs
This PR resolves #41 
As described in the issue, tuples did implemented `Tokenize` and `Detokenize`, but not `Tokenizable`.
Due to this, a `Vec<(A, B)>` could not be detokenized.
The changes I made now implement `Tokenizable` trait for all tuples up to length 16. In addition, even the `TokenizableItem` trait is implemented, so that a vector of tuples can also be detokenized.
I have used the `Token::Tuple(Vec<Token>)` type from `ethabi::Token` to represent tokens of tuples.
Effectively, the `Detokenize` trait implementation has been tested in the tests.
> tuples impl Tokenizable instead of impl Tokenize/Detokenize

- Cargo.lock
- ethers-providers/Cargo.toml
- ethers-providers/src/lib.rs
- ethers-providers/src/transports/mod.rs
- ethers/Cargo.toml
As title, in order to make dependencies lighter
> chore(provider): make websockets optional

- ethers-providers/src/pending_transaction.rs
The pending tx object always polled interval using `ready!` before checking the result of any pending API requests. This means that in addition to the rate-limiting behavior, API results would be ignored until the interval elapsed
Add intermediate `Paused` states. These states wait for the interval to elapse, and then kick off a new API request. I left in the immediate non-rate limited transition in checking receipt, as that can trigger at most once.
> refactor: pending txns don't wait to poll futures until interval elapses

- ethers-providers/src/pending_transaction.rs
Updates pending transaction to schedule waking immediately after transitioning out of a paused state
See discussion on #49
> bug: reschedule rewaking when unpausing pending tx future

- ethers-providers/src/transports/common.rs
Close #55.
Skip serializing if `T` is a zero-size type
> bug #55: prevent request from serializing ZSTs as null

- Cargo.lock
- ethers-contract/src/multicall/mod.rs
- ethers-providers/Cargo.toml
- ethers-providers/src/gas_oracle/eth_gas_station.rs
- ethers-providers/src/gas_oracle/etherchain.rs
- ethers-providers/src/gas_oracle/etherscan.rs
- ethers-providers/src/gas_oracle/gas_now.rs
- ethers-providers/src/gas_oracle/mod.rs
- ethers-providers/src/lib.rs
- ethers-providers/tests/provider.rs
- ethers-signers/src/client.rs
- ethers-signers/src/wallet.rs
- ethers-signers/tests/signer.rs
Resolves #54 
A gas oracle is a generic struct that implements the `GasOracle` trait. The method `async fetch` in `GasOracle` allows fetching the gas price data from the underlying oracle as a `Result<U256, GasOracleError>` response.
```rust
use ethers::providers::{
gas_oracle::{EthGasStation, Etherchain, Etherscan, GasOracle},
};
async fn foo() -> Result<(), Box<dyn std::error::Error>> {
let gas_oracle_1 = EthGasStation::new(Some("my-api-key"));
let gas_oracle_2 = EthGasStation::new(None);
let gas_oracle_3 = Etherchain::new();
let data_1 = gas_oracle_1.fetch().await?;
let data_2 = gas_oracle_2.fetch().await?;
let data_3 = gas_oracle_3.fetch().await?;
Ok(())
}
```
* Needed for parsing between types (`String` to `u64`/`f32`) while deserialising
```
serde-aux = "0.6.1"
```
> (feat) gas oracle support

- ethers-core/src/types/chainstate/log.rs
- ethers-providers/src/stream.rs
Fixes #51 
Previously it'd serialize to `["0x123", null, null, null]` which is not spec-compliant behavior. Now we serialize according to [the spec](https://eth.wiki/json-rpc/API#eth_newfilter). In addition we always re-wake to avoid getting stuck in the reactor's multithreaded eloop
> fix(core): serialize filters properly and always rewake

- ethers-providers/src/transports/http.rs
- ethers-signers/Cargo.toml
- ethers-signers/src/client.rs
- ethers-signers/src/lib.rs
- ethers-signers/src/nonce_manager.rs
- ethers-signers/src/wallet.rs
- ethers-signers/tests/signer.rs
It'd be nice if we had a way to sign multiple transactions locally and have the client auto-figure what the nonce for the transactions should be.
Override the default remote nonce logic with a locally managed one, falling back to the on-chain call if there's a nonce mismatch
- Also improves json error messages from the HTTP provider (finally)
> Nonce manager

- ethers-contract/tests/contract.rs
- ethers-providers/src/gas_oracle/etherscan.rs
- ethers-providers/src/pending_transaction.rs
- ethers-providers/src/provider.rs
- ethers-providers/tests/provider.rs
- ethers-signers/tests/signer.rs
Returns `Option<T>` instead of `T` for `Transaction`, `TransactionReceipt` and `Block` in order to avoid deserializing errors when the data requested did not exist
**THIS IS A BREAKING CHANGE**
Driveby: SparkPool seems to work now, closes #60
> fix(BREAKING): return Option for txs/receipts/blocks

- ethers-contract/src/event.rs
- ethers-providers/src/lib.rs
- ethers-providers/src/pending_transaction.rs
- ethers-providers/src/provider.rs
- ethers-providers/src/stream.rs
- ethers-providers/tests/provider.rs
- ethers-signers/src/lib.rs
- ethers/examples/ledger.rs
By passing the provider by reference and explicitly calling `get_filter_changes` inside the future impl we're able to simplify the function signature for anything involving `FilterWatcher`. 
This allows us to remove the `FilterStream` helper trait (which was used to have simpler function signatures).
> fix: replace FilterStream with concrete type

- Cargo.lock
- ethers-contract/ethers-contract-abigen/src/contract/methods.rs
- ethers-core/Cargo.toml
- ethers-core/src/lib.rs
- ethers-core/src/types/crypto/hash.rs
- ethers-core/src/types/crypto/keys.rs
- ethers-core/src/types/crypto/mod.rs
- ethers-core/src/types/crypto/signature.rs
- ethers-signers/src/ledger/types.rs
- ethers-signers/src/wallet.rs
Supersedes https://github.com/gakonst/ethers-rs/pull/67
TODO: Fix ProxyDigest implementation to have byte equality with libsecp sigs
> feat: convert signing to k256

- Cargo.lock
- ethers-core/Cargo.toml
- ethers-core/src/lib.rs
- ethers-middleware/src/client.rs
- ethers-signers/Cargo.toml
- ethers-signers/src/ledger/app.rs
- ethers-signers/src/ledger/types.rs
- ethers-signers/src/lib.rs
- ethers-signers/src/wallet/mod.rs
- ethers-signers/src/wallet/private_key.rs
- ethers-signers/src/wallet/yubi.rs
- ethers/Cargo.toml
- ethers/examples/sign.rs
- ethers/examples/yubi.rs
As title, add some helper methods around `Wallet` to make sure users can easily create instances of YubiHSM2 signers that are compatible with ethers-rs.
TODO: Re-run CI when infura stops rate limiting us
> YubiHSM2 Support

- Cargo.lock
- ethers-contract/tests/common/mod.rs
- ethers-contract/tests/contract.rs
- ethers-middleware/Cargo.toml
- ethers-middleware/src/client.rs
- ethers-middleware/src/gas_escalator/geometric.rs
- ethers-middleware/src/gas_escalator/linear.rs
- ethers-middleware/src/gas_escalator/mod.rs
- ethers-middleware/src/gas_oracle/middleware.rs
- ethers-middleware/src/lib.rs
- ethers-middleware/src/nonce_manager.rs
- ethers-middleware/src/signer.rs
- ethers-middleware/tests/gas_escalator.rs
- ethers-middleware/tests/nonce_manager.rs
- ethers-middleware/tests/signer.rs
- ethers-middleware/tests/stack.rs
- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
- ethers-providers/src/transports/ws.rs
- ethers-signers/Cargo.toml
- ethers-signers/src/ledger/app.rs
- ethers-signers/src/ledger/mod.rs
- ethers-signers/src/lib.rs
- ethers-signers/src/wallet/mod.rs
- ethers/examples/contract.rs
- ethers/examples/ens.rs
- ethers/examples/ledger.rs
- ethers/examples/local_signer.rs
- ethers/examples/yubi.rs
fixes #40 
A new middleware is added which tracks all transactions and bumps their gas price according to an interface & strategy inspired by the pymaker strats gas escalation.
It either bumps txs every N seconds, or on a per block basis, depending on the value of `Frequency` when constructing the struct.
- Also fixes: #77
> feat: Transaction Gas Price Escalator middleware

- ethers-contract/src/base.rs
- ethers-contract/src/contract.rs
- ethers-contract/src/lib.rs
- ethers-contract/src/multicall/mod.rs
- ethers-contract/tests/contract.rs
- ethers-providers/src/lib.rs
- ethers/src/lib.rs
Resolves #80 
Refactors the `Contract` struct by extracting the `abi` into a `BaseContract` struct which does only abi encoding. 
Working on adding human-readable abis.
> refactor: extract minimal features of Contract into BaseContract

- ethers-contract/ethers-contract-abigen/src/contract.rs
- ethers-contract/ethers-contract-abigen/src/contract/common.rs
- ethers-contract/src/base.rs
- ethers-contract/src/call.rs
- ethers-contract/src/contract.rs
- ethers-contract/src/event.rs
- ethers-core/src/abi/human_readable.rs
- ethers-core/src/abi/mod.rs
- ethers/examples/contract.rs
Since https://github.com/gakonst/ethers-rs/pull/88 is now merged, we can start exposing more utility methods for encoding/decoding function calldata which may be useful when e.g. decoding data from the `tx.input` field of a transaction.
> feat: allow encoding/decoding function data

- ethers-core/src/abi/human_readable.rs
Param parsing failed for a param marked as `memory` but without a param name:
```
bytes memory
```
If no param name is found, return the default param name.
> fix: default param name if not found following memory/calldata

- ethers-providers/src/lib.rs
Since `Middleware::Error` does not implement the `std::marker::Sync` trait, a middleware error cannot be converted into `anyhow::Error`. This is for convenience of using the `?` operator for a middleware error being returned.
Add `Sync` trait to `Middleware::Error`
> add Sync trait to middleware error

- ethers-contract/src/base.rs
- ethers-contract/src/lib.rs
- ethers-core/src/types/bytes.rs
- ethers-providers/src/lib.rs
1. Return `Self::Error` from trace* methods so that they can be overriden
1. Replace `impl Trait` syntax with normal generics
1. Only trim the bytes' first 4 bytes if it's an input. Also Error if there was no matching function selector provided
> Misc Fixes

- ethers-providers/src/pending_transaction.rs
- ethers-providers/tests/provider.rs
Fixes https://github.com/gakonst/ethers-rs/issues/102
PR #103 did not address the Future hanging when the receipt was not
immediately available, e.g. in non dev environments
> fix: reschedule waker even if receipt is not available

- ethers-contract/src/call.rs
- ethers-contract/src/contract.rs
- ethers-contract/src/factory.rs
- ethers-contract/src/multicall/mod.rs
- ethers-contract/tests/contract.rs
- ethers-middleware/src/gas_escalator/mod.rs
- ethers-middleware/src/gas_oracle/middleware.rs
- ethers-middleware/src/nonce_manager.rs
- ethers-middleware/src/signer.rs
- ethers-middleware/tests/gas_oracle.rs
- ethers-middleware/tests/nonce_manager.rs
- ethers-middleware/tests/signer.rs
- ethers-middleware/tests/stack.rs
- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
- ethers-providers/tests/provider.rs
- ethers/examples/contract.rs
- ethers/examples/ens.rs
- ethers/examples/ledger.rs
- ethers/examples/local_signer.rs
- ethers/examples/transfer_eth.rs
- ethers/examples/yubi.rs
- ethers/src/lib.rs
Improves the ergonomics of sending & waiting for a transaction to be mined. You can now do
```rust
// Before
let tx_hash = provider.send_transaction(...).await?
dbg!(tx_hash);
let receipt = provider.pending_transaction(tx_hash).await?;
// After:
let receipt = provider.send_transaction(...).await?.await?;
// or:
let pending_tx = provider.send_transaction(...).await?;
dbg!(*pending_tx);
let receipt = pending_tx.await?;
// you can still use the syntax for N confs like so:
let receipt = provider.send_transaction(...).await?.confirmations(6).await?;
```
* If you use previously used the tx_hash in the return values of a send_transaction call, you should deref it since `PendingTransaction` derefs to `TxHash`
* Smart contract calls need to be split in the "create call" and "send call":
```rust
// …
```
> Returning a `PendingTransaction` after sending a tx

- README.md
Title.
The link to the Telegram group added in 959b7fe9cea2c3a18f6735b803d996818e68a9f0 is broken.
Fixed the link.
> Fix broken link to TG group in readme.

- Cargo.lock
- ethers-core/src/types/txpool.rs
- ethers-middleware/Cargo.toml
- ethers-middleware/src/gas_escalator/mod.rs
- ethers-providers/Cargo.toml
- ethers-providers/src/lib.rs
- ethers-providers/src/pending_transaction.rs
- ethers-providers/src/provider.rs
- ethers-providers/src/stream.rs
Fixes #32 
```
running 1 test
2020-12-24T19:25:37.406070+00:00 TRACE rpc{method="eth_gasPrice" params="null"}: tx
2020-12-24T19:25:37.407086+00:00 TRACE rpc{method="eth_estimateGas" params="[{\"from\":\"0x610e31e31cbcf59189e10e1491383beaf9bcce81\",\"to\":\"0x610e31e31cbcf59189e10e1491383beaf9bcce81\"}]"}: tx
2020-12-24T19:25:37.407750+00:00 TRACE rpc{method="eth_getTransactionCount" params="[\"0x610e31e31cbcf59189e10e1491383beaf9bcce81\",\"latest\"]"}: tx
2020-12-24T19:25:39.718431+00:00 TRACE rpc{method="eth_gasPrice" params="null"}: rx=1000000000
2020-12-24T19:25:39.718645+00:00 TRACE rpc{method="eth_getTransactionCount" params="[\"0x610e31e31cbcf59189e10e1491383beaf9bcce81\",\"latest\"]"}: rx=1272
2020-12-24T19:25:39.719980+00:00 TRACE rpc{method="eth_estimateGas" …
```
> feat(providers): add tracing

- Cargo.lock
- ethers-contract/src/base.rs
- ethers-contract/src/factory.rs
- ethers-contract/src/multicall/mod.rs
- ethers-core/Cargo.toml
- ethers-core/src/abi/tokens.rs
- ethers-core/src/types/bytes.rs
- ethers-core/src/types/mod.rs
- ethers-core/src/types/transaction.rs
- ethers-middleware/src/signer.rs
- ethers-providers/Cargo.toml
- ethers-providers/src/provider.rs
Switches to Bytes 1.0. This should make our code more efficient by avoiding redundant clones on large stuff e.g. the input data on txs.
(usual flaky Celo test causes CI failure)
> feat: bytes 1.0

- Cargo.lock
- Cargo.toml
- ethers-middleware/Cargo.toml
- ethers-providers/Cargo.toml
This commit also removes the patch stanza in the top level Cargo.toml as the
older tokio tungstenite (0.12.0) is pulled in when ethers is used as a
dependency on another project.
> Upgrade reqwest to 0.11.0 to ensure only 1 version of tokio used

- Cargo.lock
- ethers-core/src/types/signature.rs
- ethers-signers/Cargo.toml
- ethers-signers/src/wallet/private_key.rs
This PR adds support for [encrypted JSON keystore](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition) in the `Wallet` module in `ethers-signers`.
1. [eth-keystore-rs](https://github.com/roynalnaruto/eth-keystore-rs)
* Create and store a new encrypted JSON keystore
```rust
pub fn new_keystore<P, R, S>(dir: P, rng: &mut R, password: S) -> Result<Wallet, WalletError>
where
P: AsRef<Path>,
R: Rng + CryptoRng,
S: AsRef<[u8]>,
```
* Decrypt an existing encrypted JSON keystore
```rust
pub fn decrypt_keystore<P, S>(keypath: P, password: S) -> Result<Wallet, WalletError>
where
P: AsRef<Path>,
S: AsRef<[u8]>,
```
Since the `eth-keystore-rs` crate has its own tests, I've only tested the scenario where the signature generated by a random new keystore should match the signature …
> Support for encrypted JSON keystore

- ethers-core/src/types/transaction.rs
Adds a quick note to the transaction receipt detailing the presence/absence of status code and intermediate state root
> doc: note EIP-658 in TransactionReceipt

- Cargo.lock
- ethers-signers/Cargo.toml
This PR uses an upgraded version of [eth-keystore-rs](https://docs.rs/eth-keystore/0.2.0/eth_keystore/)
The [upgrade](https://github.com/roynalnaruto/eth-keystore-rs/pull/1) basically replaces the dependency on `rust-crypto` with dependencies that compiles on Apple M1 chips.
> use upgraded version for eth-keystore-rs

- ethers-contract/ethers-contract-abigen/src/contract.rs
- ethers-contract/ethers-contract-abigen/src/contract/events.rs
- ethers-contract/ethers-contract-abigen/src/contract/methods.rs
Each time I run abigen, the generated rust code changes for a same contract abi json.
I'd like to make it reproducible.
Use BtreeMap to hold methods and events definition.
> make generated contract abi code reproducible

- ethers-contract/ethers-contract-abigen/src/source.rs
This PR improves an error message by printing the path that the abigen macro tries to read whenever it fails to do so. This error is triggered when the path does not exist or does not contain valid JSON
I'm unsure the best way to write automated tests for this, but I have confirmed it works great locally by pointing it at `../`
> feature: report path on failed abigen load

- ethers-providers/src/transports/ws.rs
Closes #216.
The independent load and store operations could be interleaved between tasks in a breaking way. 
e.g. 
```
TASK A loads 5
TASK B loads 5
TASK B stores 6 (5 + 1)
TASK A stores 6 (5 + 1)
```
This causes both task A and task B to use the same ID for a WS request, replacing the previous request.
To fix this, we use `fetch_add` to atomically load, increment, and store
> bug: prevent interleaving websocket ID load/store operations

- Cargo.lock
- ethers-contract/Cargo.toml
- ethers-contract/ethers-contract-abigen/Cargo.toml
- ethers-contract/ethers-contract-derive/Cargo.toml
- ethers-core/Cargo.toml
- ethers-middleware/Cargo.toml
- ethers-providers/Cargo.toml
- ethers-signers/Cargo.toml
- ethers/Cargo.toml
Mainly bugfixes.
1. Adds the `std-future` feature to `tracing-futures`, because we were getting the following error:
```
|
120 |           let res = async move {
|  ___________________^
121 | |             trace!("tx");
122 | |             let res: R = self.0.request(method, params).await.map_err(Into::into)?;
123 | |             trace!(rx = ?serde_json::to_string(&res)?);
...   |
126 | |         .instrument(span)
127 | |         .await?;
| |______________^ `tracing_futures::Instrumented<impl futures_core::Future>` is not a future
|
= help: the trait `futures_core::Future` is not implemented for `tracing_futures::Instrumented<impl futures_core::Future>`
= note: required by `futures_core::Future::poll`
```
2. prevent interleaving websocket ID load/store operations #217 (thank you …
> release: 0.2.2

- ethers-core/src/abi/human_readable.rs
- ethers/examples/contract_human_readable.rs
This includes a more sophisticated human readable abi parser that should be on par with `ethers-js`'s interface parser.
The existing parser followed the grammar loosely; 
False positives were possible, so that for example `event SetValue_function_called()` would be detected as `Function`.
All parser function are replaced with a handwritten parser that follows `ethers-js` abi parsing rules.
This also detects `StateMutability` and constructors.
All tests are successfully updated with the new parsers.
* **mandatory `returns` statement**: The new parser will fail if a function lacks a `returns` statement before its outputs. The `contract_human_readable` example did not succeed because a missing `returns` statement (`function getValue() external view (string)`) was detected and fixed in # …
> Refactor human readable abi parsing

- ethers-core/src/abi/error.rs
- ethers-core/src/abi/human_readable.rs
- ethers-core/src/abi/mod.rs
- ethers-core/src/abi/struct_def.rs
This adds support for parsing solidity structs in the humand readable ABI.
A new `AbiParser` can parse structs, turn them into tuples and substitute their references in events and functions.
Also this improves the error handling with textual feedback about the error that occurred.
Additional tests are tests are added as well.
Support for structs in the human readable ABI makes it easier to copy definitions from your solidity contract without further modifications.
The `SolStruct` can parse solidity structs, supported features are:
* elementary datatypes (`ethabi::ParamType`), like `int25 _y;`
* struct references as `String`, like `MyStruct m;` and `MostOuter.Outer.Inner m;`
* struct arrays, fixed and unbounded: `MyStruct[] m;` and `MyStruct[10] m;`
* mappings and nested mappings like …
> feat: add struct parsing support for human readable ABI

- ethers-contract/ethers-contract-derive/src/lib.rs
- ethers-contract/tests/common/derive.rs
In #227 I mentioned a limitation in parser when the provided attribute contains tuples: (`#[ethevent(abi = "Event((string,address),string)")]` which resulted in a failed derivation of the `EthEvent` trait.
This has been fixed by adding an attempt to parse the `abi` input as tuple and validated by a new test
> fix: make EthEvent abi attribute work for tuple inputs

- ethers-contract/ethers-contract-abigen/src/contract.rs
- ethers-contract/ethers-contract-abigen/src/contract/common.rs
- ethers-contract/ethers-contract-abigen/src/contract/events.rs
- ethers-contract/ethers-contract-abigen/src/contract/structs.rs
- ethers-contract/ethers-contract-derive/src/lib.rs
- ethers-contract/src/event.rs
- ethers-contract/tests/abigen.rs
- ethers-contract/tests/common/derive.rs
- ethers-core/src/abi/human_readable.rs
- ethers-core/src/abi/mod.rs
This integrates the `EthEvent` trait in the `abigen` code generation process.
The `EthEvent` makes the output of the `abigen` macro more consistent for events, and allows for generating further helper methods, as mentioned in #228.
Instead of generating the methods `name`, `signature` and `abi_signature` for each event provided in the ABI, the `EthEvent` trait is simply implemented via a `#[derive(EthEvent)]` during the `abigen` workflow. In addition all structs that are declared in the human readable abi are generated aswell. If a solidity event contains variables with solidity structs as tyoe , the generated rust struct variables have the corresponding rust. This has currently a limitation where the build fails if a solidity event has an array of a struct as input, however …
> feat(abigen): include ethevent proc macro in abigen code gen workflow

- ethers-contract/src/call.rs
- ethers-contract/src/event.rs
- ethers-contract/src/factory.rs
- ethers-contract/tests/contract.rs
- ethers-core/src/types/log.rs
- ethers-middleware/src/gas_escalator/mod.rs
- ethers-middleware/src/gas_oracle/middleware.rs
- ethers-middleware/src/nonce_manager.rs
- ethers-middleware/src/signer.rs
- ethers-middleware/src/transformer/middleware.rs
- ethers-middleware/tests/nonce_manager.rs
- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
- ethers/examples/transfer_eth.rs
Related issue: #230
These two EIPs are closely related, and allow for querying the blockchain's state at a specified block hash. Which is quite useful when dealing chain reorgs and allows for more robust clients.
For EIP-234, add method `at_block_hash` for `Event` and `Filter`.
For EIP-1898, modify `Middleware` functions affected by the EIP (that is, most that receive a `BlockNumber`), changing their signatures to receive a `BlockId` instead. Also, change the method `ContractCall::block` to receive a `BlockId`, instead of a `BlockNumber`.
> feat: add support for EIP-234 and EIP-1898

- Cargo.lock
- ethers-core/Cargo.toml
Updates ethabi to address the limitation mentioned in https://github.com/gakonst/ethers-rs/pull/232
> This has currently a limitation where the build fails if a solidity event has an array of a struct as input, however gakonst/ethabi#1 should remove this limitation.
> feat: update ethabi

- ethers-contract/src/multicall/mod.rs
- ethers-core/src/abi/tokens.rs
By using `remove(0)` on a `Vec<Token>` with len == 1 we don't need to clone
> style: remove token instead of cloning them

- ethers-contract/ethers-contract-abigen/src/contract.rs
- ethers-contract/ethers-contract-abigen/src/contract/common.rs
- ethers-contract/ethers-contract-abigen/src/contract/events.rs
- ethers-contract/ethers-contract-abigen/src/contract/methods.rs
- ethers-contract/ethers-contract-abigen/src/contract/types.rs
- ethers-contract/ethers-contract-derive/src/lib.rs
- ethers-contract/src/contract.rs
- ethers-contract/src/event.rs
- ethers-contract/src/lib.rs
- ethers-contract/src/log.rs
- ethers-contract/tests/common/derive.rs
- ethers-contract/tests/common/mod.rs
- ethers-contract/tests/contract.rs
- ethers-contract/tests/decode_logs2.rs
- ethers-middleware/contracts/DsProxyFactory.json
- ethers-middleware/src/transformer/ds_proxy/factory.rs
This follows up on #234 and also provides a solution for #98
The `EthEvent` trait is extended with a method to create an `Event` builder directly (closes #234).
The `EthEvent` proc macro now derives a `decode_log(log: &RawLog)` that parses the log message into an instance of the type it's derived on.
This introduces another trait `EthLogDecode` which only purpose is to create a common `RawLog -> Self` interface for all the generated `EthEvent`s of a contract and the generated enum wrapper that is generated for events that have more than 1 event in their abi (closes #98)
if a contract is created as follows
```rust
abigen!(
SimpleContract,
r#"[
event ValueChanged(address indexed author, string oldValue, string newValue)
event OwnerChanged(address indexed author, address indexed author) …
```
> feat(abigen): extend ethevent trait methods and decoding

- Cargo.lock
- ethers-core/Cargo.toml
- ethers-core/src/utils/mod.rs
- ethers-core/src/utils/setup.rs
- ethers/Cargo.toml
- ethers/examples/contract_human_readable.rs
- ethers/examples/contract_with_abi.rs
This adds async helper functions for compiling contracts and setting up `geth` or `ganache`.
Using the async `compile_and_launch_ganache` will only take as long as the longest running command (`solc`, `ganache-cli` ). 
This will shave off the solidity compile time for the updated examples, because this in those cases the compile time is very short. And it will shave off the `~1.8s` it takes to launch ganache for those cases where `solc` takes longer than that.
Feature gate a `setup` module in `ethers-core` that simply runs `tokio::task::blocking` for the commands (`solc`, `geth`, `ganache`) and join those task when using `compile_and_launch_ganache` or `compile_and_launch_geth`.
By default the `setup` feature of the `ethers-core` crate is enabled in `ethers` exposing those helper …
> feat: add async setup utility functions

- Cargo.lock
- ethers-core/Cargo.toml
- ethers-core/src/types/trace/mod.rs
We maintained a fork of [ethabi](https://github.com/gakonst/ethabi/) since the package was missing a few critical features, but now that there's new maintainers, we can finally use upstream and get rid of the fork.
This is still WIP until there's a release with all the features we need.
> chore: use upstream ethabi

- Cargo.lock
- ethers-core/Cargo.toml
- ethers-core/src/types/i256.rs
- ethers-core/src/types/mod.rs
- ethers-core/src/utils/hash.rs
It's out! https://github.com/rust-ethereum/ethabi/commit/970d47018e0f457440851752a7b46a4dbf793a0b
> chore: use latest ethabi

- ethers-providers/src/transports/ws.rs
I guess it was just the ws provider which had prints, I should have looked deeper before opening #262, missed the tracing usages.
Closes #262
> Replace println usage in ws provider

- Cargo.lock
- ethers-providers/Cargo.toml
- ethers-providers/src/provider.rs
- ethers-providers/src/transports/ipc.rs
- ethers/examples/ipc.rs
Follow up on #106, so that we can support non-Unix sockets in the future, since it's now generic over AsyncRead/AsyncWrite.
FYI @austinabell
> refactor: make IPC generic over AsyncRead/Write

- Cargo.lock
- ethers-contract/ethers-contract-abigen/Cargo.toml
- ethers-contract/ethers-contract-abigen/src/util.rs
Fixes https://github.com/gakonst/ethers-rs/issues/276, re-enables the etherscan abigen tests
> fix: remove depdendency on curl

- ethers-contract/tests/contract.rs
- ethers-core/src/types/signature.rs
- ethers-middleware/tests/signer.rs
derives `Copy` on `Signature`
I'd like `Signature` to be `Copy`
Derive `Copy`
Set network ID in signer in Celo tests
> feature: Signature derives Copy trait

- ethers-contract/src/event.rs
- ethers-contract/src/lib.rs
- ethers-contract/tests/contract.rs
- ethers-core/src/types/mod.rs
The types `LogMeta` and `FilterBlockOption` are not public, and I believe they should be. Also, the `LogMeta` is rather terse, and could use more metadata.
I've exported the two types and added more fields to `LogsMeta`.
However, there's one important consideration on adding more fields. The procedure that maps the type `Log` into `LogMeta` heavily uses `expect` on Option types. This behavior follows what was previously there, just extended to the new fields. If we look at the [json-rpc API](https://eth.wiki/json-rpc/API#eth_getfilterchanges), it says these fields are only `null` when the block is pending. In other words, this is at least as safe it was previously, and it is probably safe. One possible alternative is implementing `TryFrom`, instead of `From`. But maybe this can be done in …
> Expose `LogMeta` type and add more fields, and expose FilterBlockOption

- ethers-contract/ethers-contract-derive/src/lib.rs
- ethers-contract/tests/common/derive.rs
Fixes a bug, that is essentially an off by one error, that resulted in errors when decoding events with no indexed entries. 
Remove the bad `is_empty` requirement and test against real log.
> fix: off by one error during log topic decoding

- ethers-contract/ethers-contract-derive/src/lib.rs
- ethers-contract/tests/common/derive.rs
#298 happened because, the the generated `Tokenizable::from_token` always expected a `Tuple`, however that is not valid for events with a single parameter.
To handle events with zero or one parameters correctly, the macro now checks how many fields the struct with the `EthEvent` derive actually has. 
The code path for a single param looks rather hacky, but holds. it piggybacks on the existing TokenStreams for len > 1.
For events with zero parameters there is a soundness issue with the mandatory `into_token` function. Because there is nothing to encode, I opted for an empty tuple instead of panicing, but maybe a `panic!` would be more appropriate here?
Tested with two new test cases.
Closes #298
> fix: event decoding for events with zero or one parameters

- ethers-providers/src/transports/ipc.rs
The `ipc::subscription` test is unreliable and not deterministic wrt block numbers.  
Use the diff of the `block_num` and the first subscription value as initial offset when comparing the block numbers.
> test: use offset for first block num of subscription

- ethers-core/src/types/i256.rs
- ethers/examples/sign.rs
I'd like to make from_raw() a const fn.
> feat: make I256::from_raw() as const

- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
- ethers-providers/src/pubsub.rs
- ethers-providers/src/stream.rs
Provides support to fetch the respective `transaction`s for all transaction hashes provided by a `Stream<Item=TxHash>`.
Create a new `TransactionStream` type that takes a `Provider` and a `Stream<Item=TxHash>` as input as well as the number  of the maximum allowed active futures at the same time and returns their `Transaction`.
Added a `transactions_unordered` function for the `Filterwatcher<TxHash>` and `SubscriptionStream<TxHash>` types that is intended to be called like:
```rust
provider.watch_pending_transactions().await.unwrap().transactions_unordered(10);
``` 
and 
```rust
provider.subscribe_pending_txs().await.unwrap().transactions_unordered(10);
```
> feat: introduce tx stream

- ethers-middleware/tests/solidity-contracts/DSProxy.sol
> Fix tests failing on solc 0.8.0 or above

- ethers-providers/Cargo.toml
- ethers-providers/src/provider.rs
This removes the `ethers/celo` feature enabled for `celo` which prevent `ethers-providers` to be used as standalone dep. and ignores the celo dependend test by default.
> fix: remove ethers celo feature and ignore celo test

- ethers-providers/src/transports/ws.rs
The problem here is that once a request has error, the transport layer evaulates it eagerly and thinks it's a websocket error.
> per request error shouldn't be eargerly evaulated as a global websocket error

- ethers-core/src/types/log.rs
Makes setting block ranges more convenient by adding a new function (`select`) to the `Filter` struct and convenient `From` impls.
Not sure about:
* the name
* whether to include `From<U256>` since `at_block_hash` does the same already.
> feat: add filter utility function

- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
We would like to have a customized `provider` for Celo so as to add more functions exclusively provided by Celo blockchain.
A new trait `CeloMiddleware` is added to extend the `Middleware` for provider, so that functions in `Middleware` will query APIs compatible with Ethereum while functions in `CeloMiddleware` will query those exclusively in Celo.
The method `get_validators_bls_public_keys()` is added as an example.
> feat: extend Middleware trait customized for celo

- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
A follow up on #314, changed the type of block number to the generic `Into<BlockId>` so that the client can query with the input of type `u64` other than converting `u64` to `BlockId` manually. 
Changed the type of returned public key to `String` since the client cannot deserialize the response data otherwise.
> fix: change the type of block number and pub key

- ethers-contract/src/multicall/mod.rs
Adds the address of the multicall address on xDai, taken from [makerdao/multicall](https://github.com/makerdao/multicall).
I deploy stuff on xDai and I want to lower friction of using the multicall contract on xDai with this crate.
> Add xDai multicall contract address

- ethers-contract/src/factory.rs
- ethers-contract/tests/contract.rs
- ethers-middleware/src/transformer/ds_proxy/mod.rs
- ethers-providers/src/pending_transaction.rs
- ethers-providers/src/provider.rs
- ethers-providers/src/stream.rs
- ethers-providers/tests/provider.rs
- ethers/examples/ens.rs
- ethers/examples/local_signer.rs
closes #326 
- Add 2 new states to the PendingTransaction future
- Change the output type to `Option<TransactionReceipt>`
- `None` is returned when the tx drops from the mempool without confirming
- Refactor `PendingTransaction` internals to prevent repeated cloning of the receipt
- Refactor code that relies on `PendingTransaction` to handle the `None` case
> feature: PendingTransaction returns Option

- Cargo.lock
- ethers-core/Cargo.toml
- ethers-core/src/utils/mod.rs
Resolves #307.
Also added [hex-literal](https://crates.io/crates/hex-literal) as a dev dependency for easier test data construction.
Test vectors obtained from compiling a Solidity contract with a `bytes32` public field, and reading the value with `eth_call`.
> Add util functions for bytes32 string encoding/decoding

- ethers-contract/src/event.rs
- ethers-contract/src/log.rs
- ethers-contract/src/stream.rs
Fixes the repro shown [here](https://github.com/hiddenmemory/minimal-example/) by making the Event Types `Send + Sync`.
Previously, this would not work:
```rust
#[tokio::main]
async fn main() -> AnyError {
tokio::task::spawn(async move {
let ws = Ws::connect("wss://mainnet.infura.io/ws/v3/[API-KEY]").await.unwrap();
let provider = Arc::new(Provider::new(ws).interval(Duration::from_millis(500)));
let address = Address::from_str("0xdac17f958d2ee523a2206206994597c13d831ec7").unwrap();
let contract = token_contract::TokenContract::new(address, provider);
let filter = contract.transfer_filter();
let mut stream = filter.stream().await.unwrap();
while let Some(block) = stream.next().await {
dbg!(block);
}
}).await;
Ok(())
}
```
> fix: make event types thread safe

- ethers-providers/src/pending_transaction.rs
#327 introduced a bug. When the tx has just been broadcast, it may not be available over the `eth_getTransactionByHash` rpc call. This results in the `PendingTransaction` exiting immediately with an incorrect `dropped` message
I added an initial 5 second delay to the `PendingTransaction` loop. I don't like this solution, but it is hard to see a better one 🤔
> feature: initial delay in PendingTransaction

- ethers-middleware/src/signer.rs
- ethers-middleware/tests/signer.rs
Fixes #349
* `send_transaction()` attempts to preserve the from field of a TransactionRequest by forwarding to `inner.send_transaction()` in the case when a from address other than the signer address is specified
* `sign_transaction()` returns a `WrongSigner` error if asked to sign a TransactionRequest with a from address other than the signer specified. 
It might make sense for `sign_transaction()` to sign and replace the from field anyway, since it is explicitly being asked to sign from that address.
> fix: preserve from field in SignerMiddleware

- .github/workflows/ci.yml
- Cargo.lock
- ethers-contract/tests/common/mod.rs
- ethers-contract/tests/contract.rs
- ethers-core/Cargo.toml
- ethers-core/src/types/transaction.rs
- ethers-middleware/Cargo.toml
- ethers-middleware/src/lib.rs
- ethers-middleware/src/signer.rs
- ethers-middleware/tests/gas_escalator.rs
- ethers-middleware/tests/nonce_manager.rs
- ethers-middleware/tests/signer.rs
- ethers-middleware/tests/stack.rs
- ethers-middleware/tests/transformer.rs
- ethers-providers/tests/provider.rs
- ethers-signers/Cargo.toml
- ethers-signers/src/ledger/app.rs
- ethers-signers/src/ledger/mod.rs
- ethers-signers/src/lib.rs
- ethers-signers/src/wallet/mnemonic.rs
- ethers-signers/src/wallet/mod.rs
- ethers-signers/src/wallet/private_key.rs
- ethers-signers/src/wallet/yubi.rs
- ethers/examples/ledger.rs
since latest versions, geth has been rejecting non-eip155 transactions. as a result, we remove the `Option<u64>` and replace it with just `u64`. **This is a breaking change**
The method `address()` was removed from the `Wallet` type, since it's present in the `Signer`. If your code starts erroring out about `address()` not being available, import `ethers::signers::Signer`.
> fix: make chain_id mandatory

- ethers-contract/src/event.rs
- ethers-contract/src/lib.rs
- ethers-contract/src/log.rs
- ethers-contract/src/stream.rs
- ethers-contract/tests/contract.rs
As title, allows one to stream logs with metadata, by calling `with_meta` on the stream before polling it.
> feat: stream_with_meta

- Cargo.lock
- ethers-signers/Cargo.toml
- ethers-signers/src/aws/mod.rs
- ethers-signers/src/aws/utils.rs
- ethers-signers/src/lib.rs
Adds an AWS KMS signer to ethers-signers
Some notes:
1. haven't found a mock KMS that supports ecdsa signing. So can't test this outside of a real aws account
2. It is working with my AWS account
3. added under the `aws` feature
4. The `utils` functions are NOT for general consumption
5. The public key is retrieved on instantiation. ergo, instantiation is async
TODO:
> feature: signer using aws kms

- ethers-signers/src/lib.rs
Re-export the `AwsSignerError`
> chore: re-export aws signer error

- Cargo.lock
- ethers-contract/ethers-contract-abigen/Cargo.toml
- ethers-contract/ethers-contract-abigen/src/lib.rs
- ethers-contract/ethers-contract-abigen/src/util.rs
- ethers-contract/ethers-contract-derive/src/lib.rs
- The `EthEvent` and `EthAbiType` derive macros are usable with `ethers_contract` and `ethers_core` only, therefore it depends on `ethers_core` which requires `use ethers::core as ethers_core;` alias to compile.
- parse the project's `Cargo.toml` and check the dependencies for `ethers` dependency, if the dependency is present then `EthEvent` relies on `ethers::core`.
> feat: detect ethers crate paths in derive macros

- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
- ethers-providers/tests/provider.rs
Thanks for the great library, here's a small PR for a bump that I ran into while trying to modify `mev-inspect-rs` to work on an Erigon archive node.
The Erigon node does not support `parity_getBlockReceipts`, but it does support `eth_getBlockReceipts`. This is listed on the RPC interface at https://github.com/ledgerwatch/erigon/blob/devel/cmd/rpcdaemon/README.md.
Also worth mentioning that this is an open PR at [ethereum/go-ethereum#19721](https://github.com/ethereum/go-ethereum/pull/19721) as well.
Add a few function to the `Middleware` trait that invokes `eth_getBlockReceipts`.
> feat: add support for `eth_getBlockReceipts`

- Cargo.lock
- ethers-core/Cargo.toml
- ethers-core/src/types/block.rs
- ethers-core/src/types/mod.rs
- ethers-core/src/types/transaction/eip2930.rs
- ethers-core/src/types/transaction/mod.rs
- ethers-core/src/types/transaction/request.rs
- ethers-core/src/types/transaction/response.rs
- ethers-middleware/src/signer.rs
- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
* Refactors the tx types to its own subdirectory, to prepare for adding more tx request types / serialization helpers
* Adds `base_fee_per_gas` to `Block`
* Adds `access_list`, `transaction_type`, `max_priority_fee_per_gas`, `max_fee_per_gas` to `Transaction`
* Adds `transaction_type`, `effective_gas_price` to `TransactionReceipt`
* `SignerMiddleware::sign_transaction` now returns an rlp encoded signed transaction instead of a `Transaction`
* `Middleware::send_raw_transaction` now receives a signed rlp transaction instead of a `Transaction`
> feat: eip2930/1559 response type adjustments (part 1)

- Cargo.lock
- ethers-core/src/types/mod.rs
- ethers-core/src/types/transaction/eip1559.rs
- ethers-core/src/types/transaction/eip2718.rs
- ethers-core/src/types/transaction/eip2930.rs
- ethers-core/src/types/transaction/mod.rs
- ethers-core/src/types/transaction/request.rs
- ethers-core/src/types/transaction/response.rs
- ethers-middleware/tests/gas_oracle.rs
* Introduces the eip1559/2930 tx types 
* Introduces a `TypedTransaction` enum w/ `From` implementations for each type, which will replace `TransactionRequest` in the rest of the codebase
* Fixes a bug pointed out by @guanqun on the `AccessList` RLP encoding derivation method
* Adds tests to ensure that RLP encoding and the sighash matches Geth's
> feat: 1559/2930 txs (part 2)

- ethers-contract/Cargo.toml
- ethers-contract/src/call.rs
- ethers-contract/src/contract.rs
- ethers-contract/src/factory.rs
- ethers-contract/src/multicall/mod.rs
- ethers-contract/tests/common/mod.rs
- ethers-contract/tests/contract.rs
- ethers-core/src/types/transaction/eip1559.rs
- ethers-middleware/src/transformer/ds_proxy/mod.rs
- ethers-middleware/tests/transformer.rs
- ethers-providers/src/lib.rs
- ethers-signers/src/aws/mod.rs
* Adds `TypedTransaction` inside the `ContractCall` object
* Uses EIP1559 Transactions by default (Legacy if `legacy` feature flag is on), allows falling back to legacy ones via the `legacy` helper function
* Most tests need to use `legacy()` because ganache does not support Berlin or London yet (?!?)
> feat(ethers-contract): typed txs (part 4)

- ethers-contract/ethers-contract-abigen/src/contract/methods.rs
This is a follow up for #363 which introduced invalid encoding if the function has *not* a single struct parameter.
The reason why this is a bit error prone is due the token flattening that takes place during encoding of the input params where the outmost `Tuple` layer gets removed. This is intentionally because all function arguments are passed to the `method_hash` function as tuple which adds the `Tuple` layer in the first place.
However, if the function input is a single struct, prior to #363 the param would be `((input))` which is not a rust tuple but `input` itself is, so `flatten_tokens` would later strip away the outmost `Tuple` layer of the input itself, instead of the additional `Tuple` layer that would have been added if `((input))` where a rust tuple.
So in #363 I attempted to …
> fix: only wrap single struct param in a tuple

- ethers-core/src/abi/tokens.rs
crash when abigen for opensea contract- 
```
3 | abigen!(WyvernExchange, "etherscan:0x7be8076f4ea4a4ad08075c2508e481d6c946d12b");
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Tokenizable` is not implemented for `[U256; 18]
```
add `impl_fixed_types!(18)`
> add impl_fixed_types!(18) (fixes opensea abigen)

- ethers-core/src/types/transaction/response.rs
- ethers-middleware/tests/gas_oracle.rs
- ethers-middleware/tests/nonce_manager.rs
- ethers-providers/tests/provider.rs
* Gas Price is now Optional for Type 2 transactions
* Adds `chain_id` to the `Transaction`
> fix: make gasPrice optional (since Type 2 transactions)

- ethers-core/src/types/signature.rs
- ethers-signers/src/aws/utils.rs
- ethers-signers/src/ledger/app.rs
- ethers-signers/src/wallet/mod.rs
PR to fix #377 
`r` and `s` fields in `Signature` changed from `H256` to `U256`
> fix: signature fields should be U256 instead of H256

- Cargo.lock
- ethers-contract/ethers-contract-abigen/Cargo.toml
- ethers-contract/ethers-contract-abigen/src/contract.rs
- ethers-contract/ethers-contract-abigen/src/contract/methods.rs
- ethers-contract/ethers-contract-abigen/src/contract/structs.rs
- ethers-contract/ethers-contract-abigen/src/lib.rs
- ethers-contract/ethers-contract-abigen/src/rawabi.rs
- ethers-contract/tests/abigen.rs
- ethers-contract/tests/solidity-contracts/verifier_abi.json
- ethers-core/src/abi/human_readable.rs
- ethers-core/src/abi/struct_def.rs
- ethers/examples/contract_with_abi_and_structs.rs
Currently, parameters of solidity functions that are solidity structures are generated to rust tuples, which then requires some extra boilerplate code if the user wants to use rust structs within the ethers program.
Since solidity 0.5.11 the solidity compiler adds an extra fields `internalType` to the inputs/outputs objects in the JSON ABI, which also contains structs with their qualified path (`struct SomeLibrary.StructName`). We can use this to essentially turn the tuple into a rust struct.
However this is not trivial because `ethabi` strips the internalType field entirely (https://github.com/rust-ethereum/ethabi/issues/230), therefor we need to parse the abi string again but keep the internalType. I made a minimal representation auf the abi (`RawAbi`) which supports that.
Next …
> feat: generate rust structs from solidity JSON ABI

- Cargo.lock
- ethers-core/Cargo.toml
- ethers-core/src/types/transaction/eip2718.rs
- Updated the `TypedTransaction` serde flags to skip serializing the tx type if the `legacy` feature is set
- bumps `ethers-core` to 0.4.7
- adds rustdoc to `TypedTransaction`
this _should_ fix recent problems with view calls and gas estimations on kovan
> bugfix: disable type serialization when legacy feature is set

- ethers-core/src/types/transaction/eip2930.rs
- ethers-signers/src/aws/mod.rs
The latest legacy compat PRs #384 #383 somehow got the `--all-features` CI workflow working again. Attempt at fixing one of its falling tests.
> fix: skip 2930 tests in legacy mode / skip aws test if no id

- ethers-signers/src/wallet/mod.rs
`Wallet` struct implements the `Signer` trait to expose the `sign_transaction()` function which doesn't do any async calls, but it's still exposed through the async interface. This makes it complex to use in environments where there's no async runtime.
Created a new public, sync function and moved the code from the async funtion to this one. Wasn't sure what name to use on the new function, but open to suggestions
> sign_transaction_sync

- ethers-contract/src/stream.rs
Changes `<EventStream as Stream>::poll_next` to properly end the stream when the internal stream ends
Need to consider, how do we pass permanent/temporary failures from `Provider` -> `FilterWatcher` -> `EventStream`
> bug: log streams properly end when internal stream closes

- ethers-middleware/src/gas_oracle/eth_gas_station.rs
- ethers-middleware/src/gas_oracle/etherchain.rs
- ethers-middleware/src/gas_oracle/etherscan.rs
- ethers-middleware/src/gas_oracle/gas_now.rs
- ethers-middleware/tests/gas_oracle.rs
A bunch of fields have been added to gas oracles since EIP-1559. This PR introduces them, as well as re-enables any of the previously ignored tests.
> feat: improve gas oracles

- ethers-contract/tests/contract.rs
- ethers-core/src/utils/mod.rs
- ethers-middleware/src/gas_oracle/eth_gas_station.rs
- ethers-middleware/src/gas_oracle/etherchain.rs
- ethers-middleware/src/gas_oracle/etherscan.rs
- ethers-middleware/src/gas_oracle/gas_now.rs
- ethers-middleware/src/gas_oracle/middleware.rs
- ethers-middleware/src/gas_oracle/mod.rs
- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
- ethers-providers/tests/provider.rs
Fee estimation/recommendation not available for EIP-1559 type transactions
Default estimator is a port of [this](https://github.com/MyCryptoHQ/MyCrypto/blob/master/src/services/ApiService/Gas/eip1559.ts)
* Add `estimate_eip1559_fees` method to `Middleware` and implement in the `JsonRpcProvider`
* I believe none of the Gas oracle APIs support EIP-1559 fee recommendation (so that's simply an Err at the moment)
* Ethers-rs users can even provide their own `fn` to estimate fees using the `base_fee_per_gas` and `fee_history.reward`
> feat: fee estimation with custom/default fn

- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
missing uncle block related api
add uncle block related missing api
> add uncle related missing api

- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
Geth v1.10.6 expects `blockCount` parameter in the RPC call to `eth_feeHistory` to be an unsigned integer, whereas since v1.10.7 it allows both unsigned integer as well as hex encoded uint. Hardhat allows only hex encoded uint.
The response format has also changed in Geth v1.10.7, whereby the field `oldestBlock` is now a hex-encoded uint.
Deserialisation of the `FeeHistory` struct is made backwards-compatible with Geth v1.10.6 as well, and in case the call to Hardhat (or any other client only supporting hex-encoded form for `blockCount` ) fails, we fallback to the unsigned integer serialiastion while making the RPC call.
Note: This is for convenience for more users since a few networks (at this point in time Infura) are running Geth v1.10.6, while others may have upgraded. We don't want …
> fix: backwards compatibility for eth_feeHistory

- Cargo.lock
- ethers-providers/Cargo.toml
- ethers-providers/src/pubsub.rs
- ethers-providers/src/transports/ws.rs
related to #391 
- causes the `WsServer` to drop if the `ws` stream ends
- causes `SubscriptionStream` to end if the internal channel ends
includes refactors to
- handling incoming message types (binary, close, etc)
- handling incoming text (`Incoming` enum)
- handling consumer instruction (`Instruction` enum)
- naming clarity
- enhance `SubscriptionStream` docs
> feature: drop WS server on when WS connection closes

- ethers-providers/src/pubsub.rs
- ethers-providers/src/transports/ws.rs
Refactors the WS server to improve code clarity and naming.
Relies on #396
> Refactor WS handling code

- ethers/Cargo.toml
Fixes #393 
We were bundling deps with `default` features in the `ethers` crate. This meant that IPC was getting included, which does not exist in windows.
We disable all default features by default in `ethers` and expose individual feature flags for each.
> chore: disable all ethers features by default and expose them individually

- ethers-middleware/src/lib.rs
- ethers-middleware/src/policy.rs
Support a way to enforce certain rules for transactions
Add a new `PolicyMiddleware` type which wrapps a middleware and includes an instance of the new `Policy` trait, which is a single function to ensure a transaction is in compliance with this policy.
common use cases could be to look up the receiver in a database and check if its address is whitelisted. Not sure yet what the most flexible implementation would be since a DB adapter is database specific and also how to check for a whitelisted address may be database model specific. So we could abstract basic use cases via some kind of `PolicyBackend` trait or smth which implements common functions for checking `is_whitelist(&self, recv: Address)` and also for checking the calldata maybe. We could also add a default persistent …
> feat: add basic policy middleware

- ethers-contract/ethers-contract-abigen/Cargo.toml
This PR fixes the `once_cell` dependency of `ethers-contract-abigen` which has a dependency on `once_cell::sync`, but doesn't pull in this mod due to the `std` feature being turned off. If this worked before, it's because all of the tests are run using Cargo with `resolver = 1`, which compiles one version of a dependency with all features enabled by all peer dependencies.
> fix: use once_cell with feature=std in abigen

- ethers-providers/src/pubsub.rs
This ensures that `Stream` is implemented for `SubscriptionStream` and `EventStream`.
> fix: add send + unpin to stream type

- ethers-contract/ethers-contract-abigen/src/contract.rs
- ethers-contract/ethers-contract-abigen/src/contract/common.rs
- ethers-contract/ethers-contract-abigen/src/contract/events.rs
- ethers-contract/ethers-contract-abigen/src/contract/methods.rs
- ethers-contract/ethers-contract-abigen/src/contract/structs.rs
- ethers-contract/ethers-contract-abigen/src/contract/types.rs
- ethers-contract/ethers-contract-abigen/src/util.rs
finishes over https://github.com/gakonst/ethers-rs/pull/366 for the datatypes which were not adjusted to be imported with e.g. `ethers_core` instead of `ethers ::core`
> fix(abigen): generate correct imports depending on ethers crate usage

- ethers-providers/src/provider.rs
- ethers-providers/src/transports/mod.rs
- ethers-providers/src/transports/quorum.rs
- examples/quorum.rs
Support multiple provider endpoints
Adds the `QuorumProvider` type that can run internal multiple providers internally and only returns a response if a quorum was reached. The internal providers can be weighted.
This required two Wrapper traits for `JsonRpcClient` `PubsubClient` to get rid of the generic types.
How a quorum is reached can be configured with `Quorum`, default is `Quorum::Majority` which reaches a quorum if >50% of the weighted providers returned the same value
> feat: add quorum provider

- ethers-core/src/types/transaction/response.rs
If a non-legacy transaction was fetched from the mempool and then RLP-encoded for inclusion in e.g. a flashbots bundle, then the bundle would fail because the encoding only worked for legacy transactions. See https://github.com/onbjerg/ethers-flashbots/issues/11#issuecomment-907672337
RLP encode `Transaction` response types based on their `transaction_type`. I'm not super confident about this piece of code since it is a lot of duplicate logic from other files, but I'm not super well known in the codebase yet so I'm not sure what the best way is to improve it. Please let me know if you have any suggestions!
> Correctly encode non-legacy mempool transactions

- ethers-core/src/utils/solc.rs
Currently, the solc bindings ignore the `optimizer` parameter.
Add the optimization arguments to the executed command.
This also adds some options around using the optimizer, some of which may be a little awakward as implemented. Ideally, in addition to enabling the optimizer, users should be able to:
1. Compile without the optimizer
2. Set the optimizer runs
3. Set optimizer runs to 0 (i.e. we can't use 0 as a hack for turning the optimizer off)
As implemented, the current examples will work as expected (with optimization now).
```
Solc::new("./contracts/*").optimizer(200).build()?;
```
However, the optimizer no longer defaults to the optimizer ON with 200 runs (which is what the documentation used to suggest). Also, you now need to know the runs parameter you want to use in order to …
> fix: Enable solc optimization

- ethers-contract/ethers-contract-derive/src/lib.rs
- ethers-contract/tests/common/derive.rs
structs with a single field weren't properly endcoded into a `Token::Tuple`
- always treat `EthAbiType` as tuples 
- Closes #416
> fix: always treat abi type structs as tuples

- ethers-contract/ethers-contract-abigen/src/contract.rs
- ethers-contract/ethers-contract-abigen/src/contract/events.rs
- ethers-contract/ethers-contract-abigen/src/lib.rs
Smart contracts written in Solidity can include methods *and* events with the same name, so long as their signatures are different. 
The `contract` crate provides utilities for generating bindings to a contract's ABI. Because Rust does not support function overloading, these utilities enable the user to add `method_alias`es, which changes the function's name in the generated contract bindings.
The crate did not provide aliasing capabilities for event definitions.
The associated function `add_event_alias` was added to the `Abigen` struct within `ethers-contract::ethers-contract-abigen`.
> Event aliasing for contract bindings

- ethers-contract/ethers-contract-abigen/src/util.rs
Close #430
check if a lock file exists before running cargo metadata and removing it if that's the case.
> fix: cleanup lock file after exec cargo metadata

- CHANGELOG.md
- ethers-providers/src/ens.rs
- ethers-providers/src/lib.rs
Expose ENS module, as it's quite useful already!
> Make 'ens' module public

- ethers-core/src/utils/mod.rs
- examples/permit_hash.rs
- Adds a doctest showing usage of `utils::get_create2_address()` that calculates a UniswapV3 pool address.
- Adds an example showing the generation of an EIP-2612 permit() hash. This shows how to match solidity's `abi.encode()` and `abi.encodePacked()` using ethers-rs.
Partially addresses #432.
> Add usage examples for hashing utilities

- ethers-core/src/utils/mod.rs
- Implements a new utils function `get_create2_address_from_hash()` that takes the pre-computed hash of the init code rather than the init code itself
- Changes `get_create2_address()` to hash the init code and forward to `get_create2_address_from_hash()`
- Tests for `get_create2_address_from_hash()`
- Move create2 address doc example to `get_create2_address_from_hash()` to get rid of the made up init code stuff
Relates to #432.
> core: add utils::get_create2_address_from_hash()

- Cargo.lock
- Cargo.toml
- ethers-contract/ethers-contract-derive/src/abigen.rs
- ethers-core/Cargo.toml
- ethers-core/src/abi/human_readable.rs
- ethers-core/src/utils/solc.rs
* ethabi: Adds support for `internal_type` which we could/should use for abiencoder-v2 support in human readable abi. Also upgrades ethereum-types to 0.12.0.
* solc: allows providing `runtime-bin` as well as skips setting the evm-version on older compilers
> feat: expand solc capabilities / chore: update ethabi

- Cargo.lock
- ethers-contract/src/base.rs
- ethers-core/Cargo.toml
- ethers-core/src/abi/human_readable.rs
Fixes breaking changes from https://github.com/rust-ethereum/ethabi/pull/236
We also need to force enable `serialize` because they removed it upstream, pending fix https://github.com/rust-ethereum/ethabi/pull/239
> fix(ethabi): breaking changes and force enable serialize for eth-types

- Cargo.lock
- ethers-middleware/Cargo.toml
- ethers-middleware/tests/signer.rs
- ethers-providers/src/pending_transaction.rs
Is this the day our tests stop being flaky? Maybe? We now rotate over private keys associated with a mnemonic, instead of having a bunch of keys lying around and hoping we don't duplicate them somewhere & introduce race conditions.
I've pre-funded the wallets generated as documented [here](https://github.com/gakonst/ethers-rs/compare/fix/flaky-tests?expand=1#diff-be734beb2ff927faeaf4f9733808604d8fdf182a633d164c6168247ac475abddR117-R120).
> test: fix duplicate tx flakes by rotating through a list of wallets

- ethers-middleware/src/lib.rs
- ethers-middleware/src/timelag/mod.rs
Provides a TimeLag middleware that offsets tip-related requests by a constant parameter `K`
e.g. `TimelagMiddleware<M, 60>` will modify `eth_call`, `eth_getBlockNumber` and other related parameters to use the current chain tip - 60 blocks
This provides a modicum of protection from reorgs
Please review
- did I miss any requests that ought to be modified?
- is the `Unsupported` behavior reasonable?
- thoughts on the approach?
- double-check normalization logic
> feature: first draft timelag middleware

- ethers-core/src/utils/units.rs
> Change wei from 1 to 0

- ethers-core/src/utils/mod.rs
- Depends on #460 so that it parses `wei` accurately. 
- It converts the number to float, performs the necessary computation, and finally, it returns U256 as it should
- It uses `String` as an intermediate step between `f64` and `U256` .
- I am unsure of the <Box> generic error that it returns. I added that because there are 2 types of Errors it could return (either from parsing string-->Float or from string-->U256).
If we agree with the general approach, I will change `parse_ethers` to be syntactic sugar for: `parse_units` with `ether` as the unit. This will add decimal support for that function as well.
> Add Decimal support to ethers::utils::parse_units

- Cargo.lock
- ethers-core/Cargo.toml
- ethers-core/src/utils/solc.rs
Solc did not support certain `--evm-version` flag values depending on the version used. This PR should address that by normalizing the EVM version depending on the solc version.
> fix(solc): normalize EVM version across solc versions

- src/lib.rs
Link to `ethers-js` is broken on https://docs.rs/ethers/0.5.3/ethers/#complete-ethereum--celo-library-and-wallet-implementation
Fix the link!
> docs: fix broken ethers-js link

- ethers-core/src/abi/human_readable.rs
Allows functions wihtout output args in the human readable ABI, previously it'd throw an error. cc @mattsse @ shekhirin
> fix(human-readable-abi): allow functions without output args

- ethers-contract/ethers-contract-abigen/src/contract/methods.rs
- ethers-contract/ethers-contract-abigen/src/rawabi.rs
- ethers-contract/ethers-contract-abigen/src/source.rs
- ethers-contract/tests/solidity-contracts/verifier_abi_hardhat.json
Resolves https://github.com/gakonst/ethers-rs/issues/476
On compilation, Hardhat emits not just JSON description of the contract's ABI, but also some artifact metadata (see https://hardhat.org/guides/compile-contracts.html#artifacts)
Support Hardhat format deserialization
> feat(contract, abigen): support Hardhat ABI format

- CHANGELOG.md
- ethers-contract/ethers-contract-abigen/src/contract.rs
- ethers-contract/ethers-contract-abigen/src/contract/methods.rs
- ethers-contract/ethers-contract-abigen/src/contract/structs.rs
- ethers-contract/tests/abigen.rs
- ethers-core/src/abi/human_readable.rs
Support custom structs as contract params in human readable abi
* keep track of the function's types (input, output) in the abi parser, this is added on top the existing parser and adds a bit more verbosity in to the param parse functions...
* reuse the existing `InternalStructs` when determine function inputs
> feat: support human readable struct inputs

- ethers-contract/ethers-contract-abigen/src/contract.rs
Resolve https://github.com/gakonst/ethers-rs/issues/476 once again, since https://github.com/gakonst/ethers-rs/pull/478 didn't solve the issue with `abigen!` proc macro.
Make a best-effort coercion of an ABI or an artifact JSON into an artifact JSON (idea from https://github.com/gnosis/ethcontract-rs/blob/5db6ad486256abac7509193649b7bc0f5ed40f96/ethcontract-generate/src/source.rs#L246).
> feat(contract, abigen): support artifact format in proc macro

- ethers-middleware/tests/nonce_manager.rs
Test is failing because account needs to have some ether in it and we got no ether in it, sad. If we'll send some ether to the address used in the test, it'll be drained quickly, no bueno.
Use private key for rinkeby account from environment variable (@gakonst needs to set it for GitHub Actions and send some rinkeby ether to this account)
> test(middleware): get rinkeby private key from env var

- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
Resolve https://github.com/gakonst/ethers-rs/issues/367
Unify `get_block_receipts` for erigon/parity nodes into one method
> feat(providers): unify get_block_receipts for eth/parity RPCs

- ethers-solc/src/cache.rs
- ethers-solc/src/lib.rs
Previously, we'd re-compile ALL files if 1 changed. Now, we only compile the files that changed.
> feat: only compile changed files

- CHANGELOG.md
- ethers-contract/ethers-contract-abigen/src/source.rs
Without this, the error message would literally be "root path '{}' is not absolute" with curly braces in it instead of the root path.
Test plan:
`cd ethers-contract/ethers-contract-abigen`
`cargo check`
`cargo check --target wasm32-unknown-unknown`
> Fix missing fmt argument in error message

- Cargo.toml
- ethers-solc/Cargo.toml
- ethers-solc/src/artifacts.rs
- ethers-solc/src/compile.rs
- ethers-solc/src/error.rs
- ethers-solc/src/lib.rs
- ethers-solc/test-data/test-contract-versions/caret-0.4.14.sol
- ethers-solc/test-data/test-contract-versions/greater-equal-0.5.0.sol
- ethers-solc/test-data/test-contract-versions/pinned-0.4.14.sol
- ethers-solc/test-data/test-contract-versions/range-0.5.0.sol
- ethers-solc/test-data/test-contract-versions/simple-0.4.14.sol
- ethers-solc/tests/project.rs
We port over the logic for detecting and automatically using the right solc version from [dapptools-rs solc](https://github.com/gakonst/dapptools-rs/tree/master/solc), leveraging the SVM and Async features. If these features are disabled, no automatic solc detection will be done, and it will use the solc version as defined in `ethers_solc::Solc`'s rules.
> feat(solc): Multiple Solc Version detection

- CHANGELOG.md
- ethers-signers/src/ledger/app.rs
- ethers-signers/src/wallet/private_key.rs
> (fix): new_keystore returns uuid as well

- CONTRIBUTING.md
- Cargo.lock
- ethers-contract/ethers-contract-abigen/Cargo.toml
- ethers-contract/ethers-contract-abigen/src/contract.rs
- ethers-contract/ethers-contract-abigen/src/contract/common.rs
- ethers-contract/ethers-contract-abigen/src/contract/events.rs
- ethers-contract/ethers-contract-abigen/src/contract/methods.rs
- ethers-contract/ethers-contract-abigen/src/contract/structs.rs
- ethers-contract/ethers-contract-abigen/src/contract/types.rs
- ethers-contract/ethers-contract-abigen/src/lib.rs
- ethers-contract/ethers-contract-abigen/src/util.rs
- ethers-contract/ethers-contract-derive/src/abi_ty.rs
- ethers-contract/ethers-contract-derive/src/call.rs
- ethers-contract/ethers-contract-derive/src/display.rs
- ethers-contract/ethers-contract-derive/src/event.rs
- ethers-contract/ethers-contract-derive/src/utils.rs
- ethers-core/Cargo.toml
- ethers-core/ethers-derive-eip712/Cargo.toml
- ethers-core/ethers-derive-eip712/src/lib.rs
- ethers-core/src/lib.rs
- ethers-core/src/macros/ethers_crate.rs
- ethers-core/src/macros/mod.rs
Currently when wanting to implement the EIP712 derive macro, one has to import `ethers_core` as a separate dependency, or declare it like `ethers::core as ethers_core`.
This is cumbersome and not clean.
By making use of the convenience function in `ethers::contract::abigen::ethers_core_crate()` we can compute a path and show it in the derive macro.
By doing this we can avoid this additional `ethers_core` dependency in external projects.
> Refactor crate determination in new ethers-macro crate

- ethers-core/src/lib.rs
- ethers-core/src/macros/mod.rs
`#[cfg(feature = "macros")]` was applied to the reexports and not the module
> fix: lift macros feature to lib level

- ethers-core/src/lib.rs
- ethers-solc/src/compile.rs
- ethers-solc/src/config.rs
- ethers-solc/src/lib.rs
- ethers-solc/test-data/test-contract-libs/lib1/Bar.sol
- ethers-solc/test-data/test-contract-libs/lib2/Baz.sol
- ethers-solc/test-data/test-contract-libs/src/Foo.sol
Allows providing the `--allow-paths` parameter to Solc. It defaults to `root` if none is found.
> feat(solc): allow providing --allow-args

- ethers-middleware/src/timelag/mod.rs
<h1> Motivation </h1>
`ethers:middleware::TimeLag` missing `fn new(...) -> Self`
<h1> Solution </h1>
Adds function to instantiate new `TimeLag`
> fix: adds TimeLag::new() method

- Cargo.lock
- ethers-solc/src/compile.rs
@frjnn reported an issue:
> I'm working on geth traces, I'm facing the following problem: what should I do to deserialize a big int from the raw trace if it fails with "0x prefix is missing"?
Example from geth's [debug_traceTransaction](https://geth.ethereum.org/docs/rpc/ns-debug#debug_tracetransaction) (values under the `storage` key):
```javascript
> debug.traceTransaction("0x2059dd53ecac9827faad14d364f9e04b1d5fe5b506e3acc886eff7a6f88a696a")
{
gas: 85301,
returnValue: "",
structLogs: [{
depth: 1,
error: "",
gas: 100000,
gasCost: 0,
memory: ["0000000000000000000000000000000000000000000000000000000000000006", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060"],
op: "STOP",
pc: 120,
stack: …
```
> bump `ethereum-types`' `impl-serde` to 0.3.2

- ethers-providers/src/transports/mod.rs
Allow direct wrapping of the Provider to enable (e.g.) providers with exponenital backoff. Because we want to change the functionality of the `request` method, this cannot be a middleware and must be a provider
Exported the un-exported `http::ClientError` and `ws::ClientError` types so that wrapping types can name them
> chore: re-export http client error in providers transports

- Cargo.lock
- Cargo.toml
- ethers-core/Cargo.toml
We bumped `impl-serde` to new version but forgot to do so for `ethers-core` where it's used
1. Bump `ethers-core` and `ethers` versions
2. Publish crate (@gakonst help needed)
> chore: bump ethers-core to 0.5.5

- CHANGELOG.md
- Cargo.toml
- ethers-contract/Cargo.toml
- ethers-contract/ethers-contract-abigen/Cargo.toml
- ethers-contract/ethers-contract-abigen/src/util.rs
Provide a way to disable networking for proc-macro, disable request support with `abigen-offline` macro instead.
close. #575
> feat: make reqwest optional but enabled by default

- ethers-solc/src/remappings.rs
> feat(solc): add from_str for Remapping

- ethers-solc/src/artifacts.rs
- ethers-solc/src/cache.rs
- ethers-solc/src/config.rs
- ethers-solc/src/lib.rs
- ethers-solc/src/remappings.rs
- ethers-solc/test-data/dapp-sample/src/Dapp.sol
- ethers-solc/test-data/dapp-sample/src/Dapp.t.sol
- ethers-solc/test-data/hardhat-sample/contracts/Greeter.sol
- ethers-solc/test-data/out/compiler-out-1.json
- ethers-solc/tests/project.rs
Improved artifacts handling in `Project::compile`
* introduce `ArtifactOutput` trait
* keep mapping contract file -> artrifacts
* ensure artifacts exists when checking cache
* get easy access to `Artifact` from `ProjectCompilerOutput` whether it's unchanged or compiled.
* make `ProjectCompileOutput` a struct
> refactor!: make artifactoutput a trait

- ethers-solc/src/config.rs
Remapping::find_mapping looks through the whole node_modules folder which takes ages.
> chore: don't look for remappings on hardhat

- ethers-solc/src/config.rs
- ethers-solc/src/lib.rs
The parameter is not used in any useful way currently, and it prevents us from using clean installations of SVM
which do not have an instantiated /Users/gakonst/.svm directory
> fix(solc): do not unnecessarily query for solc version

- ethers-middleware/src/timelag/mod.rs
TimeLag middleware parametrizes the lag amount (number of blocks to lag behind) as generic constant. This prevents devs from being able to instantiate the TimeLag's lag amount with a runtime variable.
Replaces the generic const with regular struct field.
> fix: remove generic const from TimeLag

- CHANGELOG.md
- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
`net_version` call was not supported.
add `net_version` in provider.
> add net_version call

- ethers-core/Cargo.toml
for best security ,  the crate of the k256 is support the zeroize trait
> chore: enable zeroize feature for k256

- ethers-solc/README.md
- ethers-solc/src/lib.rs
Add support to enable cargo change detection in build scripts 
https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorerun-if-changedpath
This is useful since cargo may be unaware of changed contracts and won't rerun the build script if there aren't any changes in the rust files.
> feat: add cargo change detection support

- ethers-providers/src/provider.rs
Otterscan's Erigon fork returns `erigon` and not `Erigon` so we lowercase the node client return
> fix: lowercase node client type

- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
recent unified solution prevents the use of rpcdaemon with offline db without running erigon. this commit reverts to previous state as discussed on telegram.
> revert: unify get_block_receipts for eth/parity RPCs

- CHANGELOG.md
- ethers-core/src/utils/mod.rs
parse_units and format_units were not behaving as expected when the decimal number was greater than 15 such as ether amounts
modified parse_units and format_units to use rug::Float of 128bit such that 18 decimal point floats don't get truncated. format_units now returns a rug::Float so that might break code that is using this function however it's an easy fix for such projects.
> Fix parse units

- Cargo.lock
- ethers-solc/Cargo.toml
- ethers-solc/src/compile.rs
- ethers-solc/src/error.rs
- ethers-solc/src/lib.rs
We have noticed scenarios where an ongoing operation was terminated, leading to a corrupted `solc` binary. If this binary (with the appropriate name) is considered OK and used to compile contracts, we end up with errors that are hard to debug.
The proposed solution by @odyslam and @gakonst was to:
> feat: verify checksum before project compilation

- CHANGELOG.md
- ethers-core/src/types/bytes.rs
Addresses #622 
Implement `LowerHex` and `Display` traits for `Bytes`, to display them in hexadecimal format.
> feat: implement hex display for Bytes

- CHANGELOG.md
- ethers-solc/src/lib.rs
- ethers-solc/test-data/cache-sample/NewContract.sol
- ethers-solc/tests/project.rs
If the cache contains some artifacts, but not all, and there are changed files, then the project compiler output does not contain the cached artifacts.
This means when calling `find` or `into_artifacts`, the cached artifacts would not be present in `artifacts`. 
For example, if you run a compile, then create a new contract and run compile again, the `ProjectCompileOutput` 
will not contain the cached artifacts and you have read the cache manually in order to get them. The provided
test covers this scenario. 
This also results in some strange behavior when you run compile multiple times, as the previous cache is overwritten
with a new partial cache covering only the new files.
This originated from using foundry and seeing the above issue when running a newly created test and having it flip …
> fix: pass partial artifact cache to project compiler output

- ethers-solc/src/lib.rs
This seems to be redundant with the code [right below](https://github.com/gakonst/ethers-rs/blob/master/ethers-solc/src/lib.rs#L252-L264)
> fix: remove redundant cache read

- Cargo.lock
- ethers-solc/src/cache.rs
- ethers-solc/src/lib.rs
previously if 1 file changed, it'd overwrite the existing cache on disk with just
that 1 changed file. this change reads the cache from disk and merges it with the new checksums
ref: https://github.com/gakonst/ethers-rs/pull/623
> fix(solc): do not overwrite existing cache

- ethers-solc/src/cache.rs
- ethers-solc/src/lib.rs
- ethers-solc/test-data/cache-sample/Dapp.sol
- ethers-solc/tests/project.rs
When reading from the cache, there may be changed artifacts that need to be recompiled. 
Currently only missing files are removed from the cache metadata struct, but changed files remain.
Since we're now returning the cached artifacts as part of #623 on partial changes and writing new
files to the cache as part of #629, we also need to remove changed files from the cache. 
After getting the changed sources, remove them from the cache metadata (`SolFilesCache`) so
they are no longer returned.
> fix(solc): remove changed artifacts from the cache

- ethers-solc/src/cache.rs
- ethers-solc/src/lib.rs
adds tracing to solc so we know what takes how long etc., good for figuring out places for optimization with `RUST_LOG=ethers_solc=trace`
> solc: add tracing

- ethers-contract/ethers-contract-abigen/src/source.rs
- ethers-contract/ethers-contract-abigen/src/util.rs
- ethers-contract/ethers-contract-derive/src/lib.rs
currently the working directory is used for relative paths in abigen, however rustc makes no guarantees about the current directory when it is running a procedural macro, this also differs when tests are run.
use `CARGO_MANIFEST_DIR` as the default root for relative paths, but keep the fallback for current dir.
> fix: use CARGO_MANIFEST_DIR as root for relative paths in abigen!

- ethers-contract/ethers-contract-abigen/src/contract.rs
- ethers-contract/ethers-contract-abigen/src/source.rs
followup on #631 that prevents path resolution while parsing the path
don't canonicalize local paths like `./testdata/console.json` in `Source::parse`, resolving paths for `Source::Local` happens at a later stage at `Source::get`
> fix: source parsing for local paths

- ethers-solc/src/utils.rs
https://github.com/gakonst/foundry/issues/188 I believe this happened because not all import styles were actually supported
check all variants when scanning import statements
> fix: check all import styles

- ethers-etherscan/src/lib.rs
Otherwise doing `ethers::prelude::*` leaks the exported `Result` type
> chore: makes etherscan::Result pub(crate)

- CHANGELOG.md
- Cargo.toml
- ethers-providers/Cargo.toml
- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
Adds a dev-rpc feature flag to ethers-providers. This gives you a `DevRpcMiddleware` that exposes `evm_snapshot` and `evm_revert` for managing snapshot state.
There are [more](https://github.com/trufflesuite/ganache-cli-archive#custom-methods) methods that may be useful, but there is a bit of a mess to untangle with conflicts between documentation, hardhat, and ganache.
A lighter-weight alternative may be to just expose `provider.request()` for raw requests under a dev-rpc flag.
> Add dev-rpc middleware

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- ethers-solc/Cargo.toml
- examples/ethers-wasm/Cargo.toml
- examples/ethers-wasm/src/lib.rs
- examples/ethers-wasm/src/utils.rs
- examples/ethers-wasm/tests/contract_with_abi.rs
Fix #637
this appears to be a cargo issue that only occurs because the ethers-wasm package was excluded, replicating ethers-wasm outside of the workspace compiled fine, so somehow cargo gets mixed up when pulling in the sha2 crate...
make ethers-wasm a workspace member instead
> fix: make ethers-wasm workspace member

- ethers-providers/src/transports/ws.rs
In cases when the request is out, but cancelled locally before it gets back, then later on, the replied request should be ignored, otherwise, it hits an error and aborts the whole websocket connection.
> fix(provider::ws): ignore the websocket response when the request has been cancelled

- ethers-core/src/types/transaction/eip2718.rs
Adds an implementation of `Default` for the `eip2718::TypedTransaction` struct. This implementation respects the `legacy` feature, and allows blank transactions to more easily be created. Using this bound in my provider work to allow generic instantiation and modification of txns implementing a Transaction trait
> feature: impl Default for eip2718::TypedTransaction

- ethers-solc/src/compile.rs
- ethers-solc/src/error.rs
- ethers-solc/src/lib.rs
- ethers-solc/src/utils.rs
Fix some issues with svm install checking.
if there was another file inside .svm, like .DS_STORE even, then the whole svm install detection failed, resulting in forge installing every required version regardless
make install detection more stable and check for already installed version requirements.
> feat(solc): improve solc detection and reduce install effort

- ethers-providers/src/pending_escalator.rs
This is a complimentary PR to the previous one https://github.com/gakonst/ethers-rs/pull/643
This one solves the same issue but for different providers.
The implemented test is based on: https://github.com/smartcontractkit/chainlink/blob/develop/core/services/eth/errors_test.go#L24-L50
> Fix nonce too low for different providers

- ethers-solc/src/config.rs
https://github.com/gakonst/foundry/issues/198
> add buffer for file reading

- CHANGELOG.md
- ethers-contract/ethers-contract-abigen/src/contract/events.rs
- ethers-contract/ethers-contract-abigen/src/contract/methods.rs
- ethers-contract/ethers-contract-abigen/src/contract/structs.rs
- ethers-contract/src/multicall/mod.rs
- ethers-contract/tests/abigen.rs
- ethers-contract/tests/solidity-contracts/Abiencoderv2Test.sol
- ethers-contract/tests/solidity-contracts/abiencoderv2test_abi.json
- ethers-etherscan/src/gas.rs
- ethers-signers/src/ledger/app.rs
- ethers-solc/src/compile.rs
Closes #661 
substitute output tuples that are structs with rust structs, same as inputs
> feat(abigen): use structs for outputs

- CHANGELOG.md
- ethers-providers/src/provider.rs
Retrieving fee history with, say, a `u64` would serialize the the `block_count` as a number twice, instead of first trying as a `QUANTITY` which is my understanding of what it is meant to do (i.e. hex-encoded string - e.g. `0x42`). This PR aims to fix that.
Instead of serializing the `block_count` that is passed in, it first converts to a `U256` (which serializes as a `QUANTITY`).
> Serialize `eth_feeHistory` block count as `QUANTITY`

- CHANGELOG.md
- ethers-contract/ethers-contract-abigen/src/source.rs
fixes local relative filepath test
A while ago, I added snowtrace and polygonscan to the ehterscan library but I neglected the abigen part
> add support for polygonscan and snowtrace for abigen

- CHANGELOG.md
- ethers-providers/src/provider.rs
**Sorry, there was an issue with #668**
I created the PR too quickly and didn't run `cargo check` :see_no_evil:. It turns out there was an issue where I was moving `block_count` when doing `block_count.into()` and needed to first convert `block_count` to a `U256` to avoid move issues.
Sorry for breaking your `master` builds!
Also, make sure to run check commands:
```
$ cargo check --all-features
$ cargo +nightly fmt --all
$ cargo build --all-features
$ cargo test --all-features
```
> Serialize block count as quantity 2

- ethers-solc/src/artifacts.rs
> fix(solc): skip 0x prefix for deserialize bytes decoding

- CHANGELOG.md
- ethers-solc/src/artifacts.rs
- ethers-solc/src/config.rs
Add more functions for `Artifact` to get access to deployed bytecode
> feat(solc): extend Artifact trait

- ethers-core/src/utils/mod.rs
The recent change to format_units was truncating the leading zeros of the decimal places causing the following output as an example: 1001234567891234567 eth became 1.1234567891234567 when formatted. 
Added zero padding to the decimal numbers when printed.
> format_units return was truncating the decimal places 

- ethers-contract/ethers-contract-abigen/src/util.rs
allow unused for http_get to silence CI
> chore: allow unused http_get

- ethers-solc/Cargo.toml
MSVC is not supported for sha2 asm https://github.com/RustCrypto/asm-hashes/issues/17
We disable asm if the target is msvc
> fix(solc): exclude sha2 asm feature for msvc

- ethers-solc/src/artifacts.rs
- ethers-solc/src/cache.rs
- ethers-solc/src/compile.rs
- ethers-solc/src/config.rs
- ethers-solc/src/error.rs
- ethers-solc/src/hh.rs
- ethers-solc/src/lib.rs
- ethers-solc/src/remappings.rs
- ethers-solc/src/utils.rs
If there was an error due to a `File not found` io::Error then there is no info about the path, because `io::File` and alike consists of file descriptors and lacks file name information.
The general solution to that is to add additional context with anyhow::Context for example.
Add a `SolcIoError` that also holds the path info when doing general io like reading from files
> refactor(solc): add new io error with path info

- Cargo.lock
- Cargo.toml
- ethers-signers/Cargo.toml
- ethers-signers/src/ledger/app.rs
- ethers-signers/src/lib.rs
- ethers-signers/src/trezor/app.rs
- ethers-signers/src/trezor/mod.rs
- ethers-signers/src/trezor/types.rs
- examples/trezor.rs
Ref: #1
Adding trezor signing support, with the end goal of adding it to [foundry/cast](https://github.com/gakonst/foundry/tree/master/cast).
Forked a year old rust client (https://github.com/romanz/rust-trezor-api -> https://github.com/joshieDo/rust-trezor-api) and added the ethereum interface it lacked, along with updating the libusb (+rusb) to be compatible with ethers-rs.  I'm not much experienced in Rust, so an additional pair of eyes in my fork is most welcome.
On the `ethers-signers` implementation, I tried to follow the existing Ledger structure as much as possible.
~~Fixing: Passphrase is being requested on every request~~
I need to understand  EIP712 better from both sides, At first glance, it seems tricky to pass the intended data from `ethers-rs` to the `trezor client`. I was …
> feat: trezor support

- ethers-solc/Cargo.toml
As title, updates svm to have https://github.com/roynalnaruto/svm-rs/pull/9 which makes it windows compatible
> fix: bump svm-rs for windows support

- ethers-signers/src/trezor/app.rs
- ethers-signers/src/trezor/types.rs
I wrongly assumed that a transaction would come with the necessary params (even if 0, or empty), and would only be None, if they were not even necessary.
When adding trezor to foundry, i realized that's not the case.
This PR makes sure the none values are converted into `vec![]` or `0` when necessary.
> fix: handling empty tx parameters on trezor-client

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- ethers-providers/Cargo.toml
- ethers-providers/src/provider.rs
- ethers-providers/src/transports/ipc.rs
- ethers-providers/src/transports/mod.rs
Build on windows targets in CI.
But only builds, for tests, need to figure out how to install ganache and geth on windows
> ci: test on windows targets

- ethers-core/src/types/fee.rs
- ethers-core/src/types/mod.rs
- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
`FeeHistory` is out of place in `ethers-providers`, it should go in `ethers_core::types` with all its typesy friends
Move `FeeHistory` to `ethers-core/src/types/fee.rs` and update imports
> refactor: move FeeHistory to core types

- CHANGELOG.md
- ethers-middleware/src/nonce_manager.rs
- ethers-providers/src/lib.rs
Set nonces properly when filling transactions. Previously, nonces have been set by the node or the nonce manager during `send_transaction` calls. I erroneously assumed that `fill_transaction` would set the nonce. As a result, `send_escalating` never properly sets the nonce. This PR adds two additional places a nonce may be filled
Previously, I wanted to  add a nonce filler to `fill_transaction` however, this would _always_ override the node's suggested nonce when using an RPC signer via `send_transaction`. Instead, I chose to add it to `send_escalating`
- add a nonce check to `send_escalating`
- ensure `NonceManagerMiddleware` fills the nonce from its manager
> feature: set nonce in fill transaction

- ethers-solc/src/cache.rs
removes an assert! that would cause a panic if the project was previously built with hardhat.
it is not required that the format ids match and is currently used to provide a way to distinguish whether the file was previously built with hardhat.
I'm not sure what the most straight forward approach to remove possible friction between ethers-solc/foundry builds and hardhat would be
possible solutions:
* always check for matching ethers format id, treat cache as empty if it was written by hardhat
* use a different cache file than hardhat
* keep it like it is and make `MinimalCombinedArtifactsHardhatFallback` artifact output the default which supports reading hardhat style artifacts
> fix: remove assert to check cache format

- CHANGELOG.md
- ethers-core/src/utils/mod.rs
- ethers-core/src/utils/units.rs
> fix: do not panic on invalid units conversion

- Cargo.lock
- ethers-contract/Cargo.toml
- ethers-core/Cargo.toml
- ethers-middleware/Cargo.toml
- ethers-providers/Cargo.toml
- ethers-signers/Cargo.toml
- ethers-solc/Cargo.toml
Fix #692 
Simple fix by changing `futures-util = { version = "0.3.18" }` to `futures-util = { version = "^0.3" }` only pinning on major and minor version, not the patched version.
> fix: avoid futures-util yanked err

- ethers-signers/src/trezor/app.rs
- ethers-signers/src/trezor/types.rs
To create a contract, it's required to pass the `to` address  as an empty string.
* remove defaulting to the 0x0 address, if no address is passed
* handle `to` as an empty string
It should show on the device:
```
0 Wei ETH
new contract?"
```
> fix: contract creation on trezor

- CHANGELOG.md
- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
See #696 
Implement suggestion 3 from the issue. Move the implementation of `fill_transaction` to the provider, the most-deeply-nested middleware. Change the default impl to simply delegate further within the middleware stack. Middleware that need to modify behavior may do so by delegating before or after modification.
> refactor: move fill_transaction impl to provider rather than default

- ethers-contract/src/factory.rs
It's more of a proposal, which i believe would ease things up when deploying from a ContractFactory.
Right now, `deploy()` seems to assume that the `constructor_args` passed are of the exact type that the constructor expects. So if one passes `deploy((1, "string".to_string()))`   to a constructor that accepts `constructor(uint256 a, string memory b)`, it will fail because it will tokenize `1` as `Int` instead of `Uint`. 
This way, we maintain the method, but add a new one which receives an already ready `Vec<Token>`. Other libs have more freedom on doing their own parsing, and makes things easier if one requires to parse arguments from string. (eg. https://github.com/gakonst/foundry/blob/master/utils/src/lib.rs#L119-L125)
Another option would be  to bring over the code from the above …
> add deploy_tokens to ContractFactory

- ethers-core/src/utils/mod.rs
parse_units was generating an error on some values because of extra decimal places when multiplying by 10^decimals 
added round before converting to U256 to prevent error
> fix: parse_units was generating an error on some values 

- ethers-solc/src/compile.rs
- ethers-solc/src/remappings.rs
Better, faster remappings autodetection with more hardhat layouts in mind
optimize lib folder scanning, unify nested hardhat remappings.
> feat(solc): revamped remapping auto detect

- CHANGELOG.md
- ethers-solc/src/config.rs
- ethers-solc/src/remappings.rs
followup #706 and replace `Remapping::find_many`
> chore: use new remapping detection

- ethers-solc/src/compile.rs
- ethers-solc/src/remappings.rs
consider `~/svm/.global_version` in `Solc::default`
> chore(solc): use svm global_version if it exists and no SOLC_PATH is set

- CHANGELOG.md
- ethers-contract/ethers-contract-abigen/src/contract/structs.rs
- ethers-contract/ethers-contract-derive/src/codec.rs
- ethers-contract/ethers-contract-derive/src/lib.rs
- ethers-contract/src/lib.rs
- ethers-contract/tests/abigen.rs
- ethers-contract/tests/common/derive.rs
- ethers-core/src/abi/codec.rs
Add AbiEncode + AbiDecode implementation for custom structs.
Currently, those get derived for EthCall only.
Add `EthAbiCodec` as a complementary proc macro to `EthAbiType` that derives encode/decode.
The reason why this needs to be separate and not included in `EthAbiType` is because in EthCall we have an additional leading 4byte selector, so `EthCall` needs to implement the codec traits but requires all the tokenized support that `EthAbiType` provides.
So we simply add an additional `EthAbiCodec` derive when we generate AbiEncoderV2 structs within abigen!
> feat(abigen): add EthAbiCodec proc macro

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- ethers-contract/Cargo.toml
- ethers-contract/ethers-contract-abigen/Cargo.toml
- ethers-etherscan/Cargo.toml
- ethers-providers/Cargo.toml
- ethers-solc/Cargo.toml
Some downstream foundry users (https://github.com/gakonst/foundry/issues/229) are experiencing issues installing on different platforms. I suspect it MIGHT be related to the openssl dependency which was being pulled in by `reqwest`. 
We can maybe resolve it by feature gating reqwest's SSL provider everywhere, and importing ethers with the `reqwest/rustls` backend.
Depends on https://github.com/roynalnaruto/svm-rs/pull/11
Also, once https://github.com/seanmonstar/reqwest/pull/1396 is released we should bump reqwest to de-duplicate our certs deps
---
So this seems to address the issues around
1. openssl being pulled in
2. sha2 being pulled in
Open problems:
* <s>For some reason it triggered WASM to start failing, which is odd given the svm-rs PR above does not change much? Maybe it's the …
> fix: configure rustls & openssl via feature flag

- Cargo.lock
- ethers-solc/Cargo.toml
- ethers-solc/src/config.rs
- ethers-solc/src/lib.rs
First observed in this https://github.com/gakonst/foundry/pull/265 PR, related to https://github.com/rust-lang/rust/issues/42869. In the issue's discussion, it was recommended to use https://gitlab.com/kornelski/dunce
> fix: use lib for parsing paths correctly in windows

- ethers-solc/src/remappings.rs
Fix an edge in remapping resolution that made it nondeterministic for layouts like:
```console
ds-test
├── demo
│   └── demo.sol
└── src
└── test.sol
```
favor dapptools style lib paths ("lib"/"src") over others ("demo") with additional check
```console
[ethers-solc/src/remappings.rs:463] Remapping::find_many("git/rust/foundry/integration-tests/testdata/guni-lev/lib") = [
Remapping {
name: "ds-test/",
path: "git/rust/foundry/integration-tests/testdata/guni-lev/lib/ds-test/src/",
},
]
```
> fix(solc): prefere dapptools style remappings

- Cargo.lock
- ethers-solc/Cargo.toml
- ethers-solc/src/remappings.rs
- ethers-solc/src/utils.rs
Better remapping auto detection for both hardhat and dapp
There are quite a few edge cases with certain assumptions based on the dir structure.
Finding remappings works as follows:
1. scan all sub dirs (every dir in a lib like (lib/*, node_modules/*)) for candidates
2. simplify all candidates by looking at their most common ancestor and their surrounding dirs, this has various edge cases, especially in hardhat layouts with `contracts`. This tries its best to anticipate to what dir the remapping should actually point
`dependency/contracts/s.sol` -> `dependency/contracts`
`dependency/contracts/nested/s.sol` -> `dependency/contracts`
`dependency/nested/contracts/s.sol` -> `dependency`
there is probably an easier way to determine this, but for most common cases this should work even though …
> fix(solc): handle more remapping edge cases

- CHANGELOG.md
- ethers-contract/ethers-contract-abigen/src/contract/events.rs
- ethers-contract/ethers-contract-abigen/src/contract/methods.rs
If provided, add the `event_derives` to the event/call enums as well.
> feat(abigen): add provided derives for call and event enums

- .github/workflows/ci.yml
- Cargo.lock
- ethers-core/Cargo.toml
- ethers-core/src/types/signature.rs
- ethers-core/src/utils/ganache.rs
- ethers-core/src/utils/mod.rs
- ethers-core/src/utils/moonbeam.rs
- ethers-signers/Cargo.toml
- ethers-signers/src/aws/mod.rs
- ethers-signers/src/aws/utils.rs
- ethers-signers/src/wallet/mnemonic.rs
- ethers-signers/src/wallet/private_key.rs
- ethers-signers/src/wallet/yubi.rs
New round of crypto crate updates! 
Some breaking changes, with which I hope @tarcieri can give some guidelines on if we've approached them correctly:
> there were some changes to the ecdsa::hazmat APIs that might impact you
> namely RecoverableSignPrimitive and SignPrimitive are now merged into a single trait (and the ecdsa crate finally has fully generic implementations of ECDSA signing/verification)
Checklist
> Update Cryptography crates

- ethers-providers/src/stream.rs
`transactions_unordered()` is not `Send`
mark `TransactionFut` as `Send`
> mark TransactionFut as Send

- CHANGELOG.md
- Cargo.lock
- ethers-contract/ethers-contract-abigen/Cargo.toml
- ethers-contract/ethers-contract-abigen/src/contract.rs
- ethers-contract/ethers-contract-abigen/src/lib.rs
rust-analyzer and intellij still struggle to expand the `abigen!` macro and fail to provide useful intellisense, this makes it harder to get started with `abigen!`and usually requires to expand the macro by hand to see what functions are available.
The new `MultiAbigen` type can be used to create bindings for several contract at once and generate a new module like this: https://github.com/Gearbox-protocol/liquidation-bot/blob/master/src/bindings/mod.rs
This can be used to generate a module like this once, keep that in repository so that intellisense is available and ensure the CI will fail if the generated code is out of date
> feat(abigen): add MultiAbigen to generate multiple contract bindings

- ethers-solc/src/artifacts.rs
- ethers-solc/src/lib.rs
Settings weren't being passed properly into the compiler. For example, the optimization flags were set on the project and cache files, but the actual bytecode was not optimized.
Passed `Settings` into the `CompilerInput` first.
I tried looking into passing `&Settings` instead, but then, the more lifetimes I added, the more it required. If someone has a better way, it's highly appreciated.
> add fn settings on CompilerInput

- CHANGELOG.md
- ethers-contract/src/stream.rs
Combine multiple `EventStream` with different items
> feat: add EventStream::select to combine multiple event streams

- ethers-contract/src/lib.rs
Can not use `MultiAbigen` from `ethers::contract`
export `MultiAbigen` in `ethers-contract/src/lib.rs`
> reexport MultiAbigen

- ethers-solc/src/artifacts.rs
- ethers-solc/src/hh.rs
Fix https://github.com/gakonst/foundry/issues/301
The reason this happened is because solc omits the bytecode if its encountered a stack too deep error, but our `Evm` requires it so it fails to decode and the error gets lost.
now if solc encounters a stack too deep, foundry will display the error correctly:
```console
Error: 
0: 
CompilerError: Stack too deep, try removing local variables.
--> /Users/Matthias/git/rust/foundry-integration-tests/testdata/juice-contracts-v2/./contracts/JBETHPaymentTerminalStore.sol:243:10:
|
243 |         (_preferClaimedTokensAndBeneficiary & 1) == 0,
|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0: 
Location:
cli/src/cmd/build.rs:91
```
Make `Evm::bytecode` optional, this is the only sound solution, since the compiler output also depends on the compiler …
> fix: make evm bytecode optional

- ethers-solc/src/remappings.rs
Fix #728 
New approach to detect remappings for a variety of patterns
* keep track of a valid `window` while recursively scanning dirs for candidates. A new `window`, is opened after a new lib dir was found (`lib`, `node_modules`): `lib/solmate/lib/weird-erc20`, contains 2 windows (`solmate`, `weird-erc20`). this also allows us to merge multiple candidates in the same window like in `oz/{auth, tokens,..}/contracts`  `auth` and `tokens` are contained in the same window `oz` and should be merged to `oz`
This is a better-structured version, which also handles all edge cases we're currently aware of, once we discover new ones, they can be easily added
Integration tests pass on foundry https://github.com/gakonst/foundry/pull/305
> refactor(solc): remappings detection rewrite

- ethers-core/src/types/chain.rs
- ethers-etherscan/src/lib.rs
I want to add Optimism verification support for [foundry](https://github.com/gakonst/foundry), but it turns out foundry depends on this package and optimism is not supported yet. This PR add support for Optimism network.
More information about Optimism:
1. [What is Optimism?](https://help.optimism.io/hc/en-us/articles/4411921295899-What-is-Optimism-)
2. [Optimism Networks and Public RPC Endpoints](https://community.optimism.io/docs/infra/networks.html)
There are two packages that need to be updated:
1. Core: Add chain types
2. Etherscan: add support for `ETHERSCAN_API_KEY` on optimism
> [draft] Add Optimism & OptimismKovan chains

- Cargo.lock
- ethers-signers/Cargo.toml
- ethers-signers/src/trezor/app.rs
- ethers-signers/src/trezor/types.rs
Sessions are used to "keep" the  passphrase on the device in-between different calls. And while it was being reused inside the same `TrezorEthereum` object, once we instantiated a new one, we would lose the session.
For example, different `forge` or `cast` calls would always request the user to insert their passphrase again and again. With this change, it won't.
Relevant information from  [sessions @ docs.trezor.io](https://docs.trezor.io/trezor-firmware/common/communication/sessions.html) :
* `Sessions only exist in RAM and are lost when Trezor is disconnected.`
* `New session is started by calling Initialize with no arguments. The response is a Features message, which contains a 32-byte session_id. All subsequent commands happen within the given session.`
* `To resume a previous session …
> feat/trezor: cache session on filesystem

- ethers-core/src/types/chain.rs
Enables https://github.com/gakonst/foundry/pull/357
Ideally, I would prefer that the default case of the `match` statement is sth like `Chain::UnknownChain`, but I added mainnet for compatibility.
Should we add that to the enum?
> feat: add FromStr impl for Chain

- .github/workflows/ci.yml
- examples/contract_human_readable.rs
We forgot to update one of the examples. I wish we had a better way to catch this in CI. Maybe there's a nice way similar to what @shekhirin did [here](https://github.com/gakonst/foundry/blob/master/.github/workflows/integration-tests.yml#L20-L24) for the foundry integration tests matrix?
> fix(examples): contract with abi test

- ethers-solc/src/config.rs
- ethers-solc/src/utils.rs
> feat(solc): add project path auto detection

- Cargo.lock
- ethers-solc/Cargo.toml
- ethers-solc/src/compile.rs
It seems like `https://binaries.soliditylang.org` is down, so `Releases` requests fail after some time with a DNS lookup error. which highlighted an issue:
a) takes quite a bit of time
b) all checksums fail bc no checksums to compare against
Ref #751
* Add timeout to Releases lookup, 3secs is probably reasonable
* only check checksums of we could lookup releases successfully
> fix(solc): add timeout and error detection for releases lookup

- CHANGELOG.md
- Cargo.lock
- ethers-solc/Cargo.toml
- ethers-solc/benches/read_all.rs
- ethers-solc/src/artifacts.rs
- ethers-solc/src/compile.rs
- ethers-solc/src/config.rs
- ethers-solc/src/lib.rs
- ethers-solc/src/project_util.rs
- ethers-solc/src/resolver.rs
- ethers-solc/src/utils.rs
- ethers-solc/tests/project.rs
Close #739
Add a dependency graph implementation, see resolve.rs for docs.
* add a `Graph` implementation that also resolves all imported dependencies that live outside of the project's configured source dir. This applies the configured remappings during lookup
* Also add those dependencies to the cache file, so changes in a contract/library in the `lib` folder are detected and trigger a rebuild.
* parallelize as much as possible (reading and parsing of source) files. parallelizing import resolving is not trivial because it can result in duplicated lookups (Lib1 imports Lib3, Lib2 imports Lib3)
ToDos
Followup
> feat(solc): add dependency graph implementation

- ethers-addressbook/src/contracts/contracts.json
Arguably the most used token ever and it's not in the address book! Not sure if we should name it WETH or WETH9 - thoughts?
> Add WETH to address book

- ethers-addressbook/src/contracts/contracts.json
Official rinkeby support for MCD has been deprecated a long time ago. Furthermore the rinkeby address in this library is not even a dai.sol implementation - not sure who deployed or maintains this instance.
Instead I would encourage users to utilize the official goerli MCD instance, and the related Dai token for testing, which I have added in this commit.
> remove unofficial testnet dai

- ethers-solc/src/artifacts.rs
Currently `forge` suppresses warnings when building projects (https://github.com/gakonst/foundry/issues/304). This adds relevant methods that we can use to detect warnings there.
> Check for warnings after compilation

- ethers-contract/ethers-contract-abigen/src/contract.rs
- ethers-contract/tests/abigen.rs
Binding generated by AbiGen which bind output of `forge build`  throws this error #683 
But it work If I change the format of ABI json to only be the content of `abi`
> feat: support abi generated from forge

- ethers-solc/src/artifacts.rs
- ethers-solc/src/lib.rs
Following discussion in https://github.com/gakonst/foundry/pull/399 we want to be able to ignore some errors for tests and dependencies, but not for source.
This PR just ignores 2 errors for both tests and dependencies by default: the SPDX and contract size warnings.
> Ignore SPDX and contract size for tests

- ethers-core/src/types/chain.rs
Upstream changes to support feedback at https://github.com/gakonst/foundry/pull/412
cc @mattsse
> feat(chain): enum values + TryFrom<u64>

- ethers-solc/src/cache.rs
- ethers-solc/src/config.rs
- ethers-solc/src/lib.rs
- ethers-solc/src/resolver.rs
- ethers-solc/tests/project.rs
https://github.com/gakonst/foundry/issues/316
the way we checked if we need to recompile a contract was too optimistic and didn't check for their usage properly so in https://github.com/gakonst/foundry/issues/316 we only recompiled the base contract and not the contract that inherits.
This was fixed but should be improved, generally the whole compile <-> cache pipeline is ripe for a v2 rewrite that uses the new dependency path.
I also discovered and fixed the issue that's likely related to #727, we used different keys for the `into_artifacts` iterator, while for cached artifacts we used `<file>:<name>` we only used the name for recompiled assets. but #727 needs an additional test as follow-up.
resolve all imports and check if they were changed.
> fix(solc): invalid cached artifacts

- ethers-solc/src/remappings.rs
https://github.com/gakonst/foundry/pull/297#discussion_r783042214
> feat(solc): relative remappings

- ethers-core/src/abi/human_readable.rs
- ethers-core/src/abi/struct_def.rs
Based on https://github.com/rust-ethereum/ethabi/issues/254 unknown identifiers are now treated as uint8, this broke how the `AbiParser` resolves structs in a human readable ABI. because from pov of ethabi's `Reader`:
```solidity
struct Bar { uint256 x; }
function foo(Bar memory x)
```
type `Bar` in function `foo` is now a `unit8`.
if `ethabi::Reader` returns an `Uint8` check that the input string also includes a `uint8`, otherwise treat it as struct/tuple.
> fix(abi): check for uint8 params in human readable types

- ethers-contract/tests/contract.rs
- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
Implement [trace_callMany](https://openethereum.github.io/JSONRPC-trace-module#trace_callmany)
Actually do this. I will also need to implement `ErigonInstance` so I can add test for this.
Now it actually works with my local node
```sh
◆ ethers-fork git:(master) ✗ ❯❯❯ cargo test -p ethers-providers --lib -- --nocapture provider::tests::test_trace_call_many
Compiling ethers-providers v0.6.0 (/Users/eugene/Developer/rust/ethers-fork/ethers-providers)
Finished test [unoptimized + debuginfo] target(s) in 3.52s
Running unittests (target/debug/deps/ethers_providers-6eb7cba4c6e73967)
running 1 test
[ethers-providers/src/provider.rs:1485] traces = [
BlockTrace {
output: Bytes(
b"",
),
trace: Some(
[],
),
vm_trace: None,
state_diff: Some(
StateDiff(
{
0x0000000000000000000000000000000000000000: …
```
> Implement trace_callMany

- ethers-solc/src/resolver.rs
Nodes were traversed recursively which could Hit a SO on large repos, like https://github.com/fei-protocol/tribe-turbo
Use an iterator `NodesIter` instead that yields all nodes instead
> fix(solc): traverse nodes iteratively

- ethers-core/src/types/chain.rs
- ethers-etherscan/src/lib.rs
Add fantom chain RPCs, chain ids, and etherscan URLs.
To support foundry on fantom
Following solution from https://github.com/gakonst/foundry/pull/412
1.    Core: Add chain types
2.    Etherscan: add support for ETHERSCAN_API_KEY on optimism
> Fantom chain

- ethers-solc/src/compile.rs
We call `Solc::install` and `Solc::blocking_install` elsewhere in `ethers-solc`, and I think that might be causing the issue in https://github.com/gakonst/foundry/issues/442
Moved the lock into those functions instead
> Move solc install lock into install functions

- ethers-solc/src/lib.rs
Should fix https://github.com/gakonst/foundry/issues/322 (?)
> Remove entire cache folder, not just contents

- ethers-solc/src/lib.rs
Reverts gakonst/ethers-rs#820
`self.cache_path()` points to the file `./cache/solidity-files-cache.json`.
> Revert "Remove entire cache folder, not just contents"

- ethers-solc/src/lib.rs
followup #820
Ref https://github.com/gakonst/foundry/issues/322#issuecomment-1017590516
if the cache file was the only file in the dir, remove the parent dir (`./cache/`) as well
> chore(solc): also rm cache dir if empty

- ethers-contract/src/log.rs
Serde `Serialize` and `Deserialize` was not implemented for `LogMeta`. This means, if one queries events with metadata, they cannot dump a serialized form.
Derive `Serialize` and `Deserialize` for `LogMeta`.
> fix: derive serde Ser and De for log metadata

- ethers-providers/src/transports/common.rs
- ethers-providers/src/transports/ws.rs
- ethers-providers/tests/provider.rs
Deserializing a poorly formatted `Incoming` message over websocket fails silently. This is why #684 was mysteriously failing when using a `wss` provider from Infura. Infura streams back messages with an all capitalized `JSONRPC` field which serde chokes over when deserializing into a `Notification`. 
Propagate deserialization errors through `ClientError`.
I think it's fair to support Infura idiosyncrasies considering they're such a prominent provider. With that said, the stable solution is probably using something like `#[serde(case_insensitive)]` (see https://github.com/serde-rs/serde/pull/1902) although this should come with an overhead. In the meantime, this fixes the issue for Infura wss users.
> fix(ws): propagate deserialization errors upstream + infura quickfix

- .gitmodules
- ethers-solc/src/config.rs
- ethers-solc/src/remappings.rs
- ethers-solc/src/utils.rs
Ref https://github.com/gakonst/foundry/issues/583
See new docs, this is a bit ambiguous the correct solution would be to adjust the remappings to `@openzeppelin/contracts/` however this a another edge case that complicates remapping detection quite a bit, as a workaround we check for this common scenario during import resolving
> fix(solc): duplicate contracts segments 

- CHANGELOG.md
- Cargo.lock
- ethers-providers/Cargo.toml
- ethers-providers/src/transports/common.rs
- ethers-providers/src/transports/http.rs
- ethers-providers/src/transports/mod.rs
- ethers-providers/src/transports/ws.rs
This pull request adds basic and bearer authentication for http and non-wasm websockets transport.
Some people operate their node behind a reverse-proxy which uses some form of authentication. This pull request makes it possible to use ethers-rs  in this case.
The solution is to inject auth headers into http requests and the websocket handshake request.
> Add authorization for http and websocket

- CHANGELOG.md
- ethers-core/src/types/chain.rs
- ethers-etherscan/src/lib.rs
As noted in gakonst/foundry#579, BSC mainnet and testnet are missing from the list of networks that do not support EIP-1559 yet. Thus, sending transactions to those networks using [`cast`](https://github.com/gakonst/foundry/tree/master/cast) fails because currently [`Eip1559TransactionRequest` is used to create and submit transactions.](https://github.com/gakonst/foundry/blob/9de25d1928da362cd3b185ebaccc0e3d00aee2c8/cast/src/lib.rs#L234)
Add BinanceSmartChain and BinanceSmartChainTestnet to the `Chain` enum in ethers-core types.
> feat(chain): add BSC and BSC testnet

- ethers-core/src/types/chain.rs
moving this into ethers-rs from foundry so it can be more easily use elsewhere
> feat(types/chain): is_legacy helper

- ethers-solc/src/compile.rs
at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.synchronous tasks.', C:\Users\Ben\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.15.0\src\runtime\enter.rs:39:9
> try and fix thread 'main' panicked 

- ethers-solc/src/artifacts.rs
- ethers-solc/src/config.rs
- ethers-solc/src/hh.rs
- ethers-solc/src/lib.rs
The existing `CompactContract` doesn't have enough information for our needs in foundry. So we write out `CompactContractBytecode` instead which is a slightly stripped down version of `ContractBytecode`. The reason to strip it down is because we lose a decent amount of performance if we write all the other things in `ContractBytecode`. This is a compromise between speed and the needed information.
Write `CompactContractBytecode` instead of `CompactContract`
> write `CompactContractBytecode` instead of `CompactContract`

- CHANGELOG.md
- ethers-solc/src/compile.rs
Add informational messages to solc installation and compilation. 
The compilation of a project could give the appearance of a hanging program because of downloading and installing solc. Informational messages allow the user to know what's happening and why it might take more than expected.
> chore: add info messages to solc install/compile

- CHANGELOG.md
- ethers-core/src/utils/mod.rs
The U256 priority fees were being coerced into u32, which was not big
enough for actual values. The overflow was happening but not checked.
This led to a possible divide-by-zero panic in this code as well.
This change does the math as I256 -- overkill, but it works.
This is a simple bug fix for the issue described above, which could lead in some 
cases to somewhat incorrect gas estimation and the occasional panic.
The fix just uses I256 math instead.
- [ x] Added Tests
- [ x] Added Documentation
- [ x] Updated the changelog
> core: fix overflow and panic in priority fee estimation

- ethers-core/src/types/chain.rs
BSC networks are a part of the Chain, but were still not used on the `is_legacy`
method.
Add the BSC networks to the `is_legacy` Chain method.
> feat(chain): add BSC networks to the is_legacy helper

- ethers-core/src/types/ens.rs
- ethers-core/src/types/transaction/eip1559.rs
- ethers-core/src/types/transaction/eip2718.rs
- ethers-core/src/types/transaction/eip2930.rs
- ethers-core/src/types/transaction/mod.rs
- ethers-core/src/types/transaction/request.rs
- ethers-core/src/types/transaction/response.rs
- ethers-middleware/src/signer.rs
- ethers-middleware/tests/nonce_manager.rs
- ethers-middleware/tests/signer.rs
- ethers-providers/src/lib.rs
- ethers-signers/src/aws/mod.rs
- ethers-signers/src/ledger/app.rs
- ethers-signers/src/wallet/mod.rs
- ethers-signers/src/wallet/private_key.rs
Currently there is no way to decode a transaction from bytes, only encode to bytes.
Implemented the [`Decodable`](https://docs.rs/rlp/latest/rlp/trait.Decodable.html) trait for:
- `TypedTransaction`
- `TransactionRequest`
- `Eip2930TransactionRequest`
- `Eip1559TransactionRequest`
- `NameOrAddress`
- `Transaction`
This change uses `rlp_derive` for the `Decodable` implementation on `AccessListItem` and `AccessList`.
This also adjusts each variant of `TypedTransaction` to contain the `chain_id`, and removes `chain_id` it from the `rlp_signed` and `sighash` functions.
Fixes #561
> Implement RLP decoding for transactions

- CHANGELOG.md
- ethers-solc/src/resolver.rs
- ethers-solc/tests/project.rs
Addresses [foundry #641](https://github.com/gakonst/foundry/issues/641)
The end location of the target replacement is adjusted to be exclusive. That's how it was primarily used during flattening.
> fix(solc): flatten replacement target location

- ethers-solc/src/artifacts.rs
- ethers-solc/tests/project.rs
Apparently the `secondarySourceLocations` only contains a `message` field, which is at odds with the docs https://docs.soliditylang.org/en/v0.8.11/using-the-compiler.html#compiler-api
```text
"secondarySourceLocations": Array([
Object({
"message": String(
"Candidate: function require(bool)",
),
}),
Object({
"message": String(
"Candidate: function require(bool, string memory)",
),
}),
]),
```
Change types so that error can now be parsed correctly
```console
TypeError: No matching declaration found after argument-dependent lookup.
--> /private/var/folders/l5/lprhf87s6xv8djgd017f0b2h0000gn/T/tmp_dapp1Wk7S5/src/Contract.sol:6:13:
|
6 |             require(address(0), "Error");
|             ^^^^^^^
Note: Candidate: function require(bool)
Note: Candidate: function require(bool, string memory) …
```
> fix(solc): can parse secondary source locations

- CHANGELOG.md
- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
Add `eth_syncing` endpoint: https://eth.wiki/json-rpc/API#eth_syncing
Tested it with infure and return `false` successfully, don't have any syncing node to check return when it is syncing.
> add eth_syncing RPC

- ethers-core/src/utils/ganache.rs
Addresses #850. In general, there is probably a less fragile way to launch ganache and decipher the output. Open to suggestions on a possible change to the approach here.
> fix(core): adjust Ganache for new cli output

- ethers-contract/tests/common/derive.rs
- ethers-core/src/abi/codec.rs
> feat(codec): impl codec for Bytes

- CHANGELOG.md
- ethers-contract/ethers-contract-abigen/src/lib.rs
- ethers-contract/ethers-contract-abigen/src/multi.rs
Draft status until I update docs and changelog
- allow distinguishing between binding generation and serialization/write failures by introducing an explicit `build` step
- allow lib generation
- allow building bindings in memory to prevent unnecessary disk usage on `ensure_consistent` 
- refactor of `MultiAbigen`.
- `MultiAbigen` is now a thin vec wrapper that must be explicitly built into a `MultiBindings` (rather than implicit while writing)
- `MultiBindings` holds a map of `contract name -> ContractBinding`
- `MultiBindings` generates file contents in memory, and makes minimal disk writes
- `MultiBindings` no longer writes a tmp dir when running its checks
- `Multibindings::ensure_consistent_crate` and `::ensure_consistent_module` are now available outside of `#[cfg(test)]` as they no …
> refactor: MultiAbigen rework

- ethers-providers/src/provider.rs
The doc test for the `dev_rpc` mod was failing when run directly from `ethers_providers`, because tokio's `rt-multi-thread` feature is not enabled.
Specify the `current_thread` runtime flavor instead.
> fix(providers): doc test for dev_rpc

- CHANGELOG.md
- Cargo.lock
- ethers-contract/ethers-contract-abigen/Cargo.toml
- ethers-contract/ethers-contract-abigen/src/contract.rs
- ethers-contract/ethers-contract-abigen/src/contract/events.rs
- ethers-contract/ethers-contract-abigen/src/contract/methods.rs
- ethers-contract/ethers-contract-abigen/src/contract/structs.rs
- ethers-contract/ethers-contract-abigen/src/contract/types.rs
- ethers-contract/ethers-contract-abigen/src/lib.rs
- ethers-contract/ethers-contract-abigen/src/multi.rs
- ethers-contract/ethers-contract-abigen/src/rustfmt.rs
- ethers-contract/ethers-contract-abigen/src/source.rs
- ethers-contract/ethers-contract-abigen/src/util.rs
As foundry is using eyre, we should transition more crates to use it instead of anyhow
Move the contract abigen crate to eyre
> refactor: replace anyhow with eyre

- Cargo.lock
- Cargo.toml
- examples/abigen.rs
- examples/contract_human_readable.rs
- examples/contract_with_abi.rs
- examples/ens.rs
- examples/ipc.rs
- examples/local_signer.rs
- examples/mnemonic.rs
- examples/moonbeam_with_abi.rs
- examples/quorum.rs
- examples/sign.rs
- examples/transfer_eth.rs
- examples/uniswapv2.rs
- examples/watch_blocks.rs
Slow move from anyhow to eyre throughout the crate
Make examples use eyre.
> dep: replace anyhow with eyre in examples

- ethers-solc/src/artifacts.rs
Adding `storageLayout` to output selection on contracts without any storage variables is triggering the following error:
```
compiling...
Error: 
0: invalid type: null, expected a map at line 1 column 4542
Location:
/rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1911
Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```
Add deserialization method `default_for_null` and apply it to `StorageLayout.types`
> fix storage layout deserialization

- ethers-providers/README.md
Unless it's intentional API key should be kept private?
> Hide Infura API key from docs

- ethers-solc/src/artifacts.rs
- ethers-solc/src/cache.rs
- ethers-solc/src/compile/contracts.rs
- ethers-solc/src/compile/mod.rs
- ethers-solc/src/compile/project.rs
- ethers-solc/src/resolver.rs
improve how versions are autodetected. The old algorithm simply picked the highest compatible version, without considering other source files. So that `A (=0.8.10)` and `B(>0.8.0)` would result in two versions (0.8.10 and 0.8.11). Now we're trying to find a single versions that satisfies all sets, see resolver.rs docs.
limit the `CompilerOutput`'s contracts: solc may include additional contracts in the `CompilerOutput` than were provided in the `CompilerInput` which is not desired in the `ProjectCompiler` since that already provides all contracts, so we simply restrict the `CompilerOutput` to those files provided in the `CompilerInput` `Solc::compile_exact`
> feat(solc): compiler pipeline improvements

- ethers-solc/src/artifacts.rs
Add missing optimizer details types
ref https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-input-and-output-json-description
> feat(solc): add optimizer details

- CHANGELOG.md
- ethers-contract/src/factory.rs
- ethers-contract/tests/contract.rs
I'd like to print the transaction hash when using `forge create` and its just generally
useful to have a reference to the receipt when deploying a contract. Currently
this is not possible due to the interface on the `Deployer`
The `Deployer` is used to deploy contracts and its `send`
function returns an attached instance of a `Contract`.
There is no way to know the transaction hash of the
deployment transaction, so this commit adds another
method `send_with_receipt` that returns an attached
`Contract` as well as a `TransactionReceipt`.
> feat(ethers-contract): add `send_with_receipt` to `Deployer`

- ethers-core/src/types/transaction/eip1559.rs
- ethers-core/src/types/transaction/request.rs
OpenEthereum seems to not have a `chainId` field in its [`TransactionRequest`](https://github.com/openethereum/openethereum/blob/main/crates/rpc/src/v1/types/transaction_request.rs#L32) type.
This PR disables serialization for the `chain_id`, so we don't send it in RPC requests.
Fixes #877
> fix(core): prevent chain_id from serializing for requests

- ethers-providers/src/pending_transaction.rs
I frequently want to print the transaction hash of a pending transaction before it is mined. Currently, this is pretty verbose, because you need a let binding for the transaction:
```rust
let tx = token.transfer(recipient, amt);
let pending = tx.send().await?;
println!("Tx hash: {:?}", *pending);
let mined = pending.await?;
```
Add two convenience methods on the `PendingTransaction<_>` type, `log()` and `log_msg()`.
```rust
let mined = token.transfer(recipient, amt).send().await?.log_msg("Tx hash").await?;
```
Another approach that isn't just for printing might be to add a method to `PendingTransaction<_>` that returns `(TxHash, Self)`, which would turn the above into:
```rust
let (hash, fut) = token.transfer(recipient, amt).send().await?.hash();
println!("Tx hash: {:?}", hash);
let mined …
```
> feat(providers): Log methods for PendingTransaction

- ethers-solc/src/compile/mod.rs
- ethers-solc/src/compile/project.rs
- ethers-solc/src/lib.rs
- ethers-solc/src/report.rs
- ethers-solc/src/resolver.rs
Ref https://github.com/gakonst/foundry/issues/628
Povide a way to emit custom output at certain points in the compiler pipeline
use a global `Reporter` that gets invoked in the code, the `Reporter` can the invoked exactly once `ethers_solc::report::init(BasicStdoutReporter::default());`
> feat(solc): add Reporter type

- ethers-providers/src/pending_transaction.rs
The `log()` and `log_msg()` impls in #884 were missing an extra deref, so they logged the entire `PendingTransaction` struct rather than the transaction hash. Also cleans up the example a bit.
> fix(providers): PendingTransaction::log() missing deref

- ethers-signers/src/wallet/private_key.rs
- ethers-solc/src/cache.rs
- ethers-solc/src/compile/mod.rs
- ethers-solc/src/lib.rs
- ethers-solc/src/report.rs
> chore: fix all warnings

- ethers-solc/src/artifacts/mod.rs
- ethers-solc/src/artifacts/output_selection.rs
- ethers-solc/src/artifacts/serde_helpers.rs
Ref https://github.com/gakonst/foundry/issues/705
Needs followup to add additional ArtifactOutput type
> feat(solc): more options for output selection

- CHANGELOG.md
- ethers-core/src/types/chain.rs
- ethers-etherscan/src/lib.rs
Closes #897 
Currently, to_string and from_str are not mirroring each other, maybe they should.
Overriding the default `Debug`'s impl.
> feat(ethers-core/Chain): make to_string and from_str inverse functions

- Cargo.lock
- ethers-solc/Cargo.toml
- ethers-solc/src/compile/mod.rs
Use new `svm::blocking_*` API introduced in https://github.com/roynalnaruto/svm-rs/pull/21 / https://github.com/roynalnaruto/svm-rs/pull/23
Simplify static `RELEASES`, no timeout necessary offline mode is now possible
> feat(solc): use svm blocking feature

- CHANGELOG.md
- ethers-solc/src/compile/output.rs
I'd like to be able to print off the compiled contract names when running `forge build`.
Addresses https://github.com/gakonst/foundry/pull/682#discussion_r804496272
Add a function `compiled_contracts_by_compiler_version`
to the `ProjectCompileOutput` that returns a `BTreeMap`
that maps the compiler version to a vector of the contract
names and contract structs.
> feat: add getter to `ProjectCompileOutput`

- ethers-etherscan/src/contract.rs
URL Params naming was incorrect according to
https://docs.etherscan.io/tutorials/verifying-contracts-programmatically#4.-configuring-source-code-parameters
> fix(etherscan): url params naming

- ethers-contract/src/multicall/mod.rs
- ethers-contract/tests/contract.rs
Multicall's `add_call` method is capped at 16 calls due to detokenization (tuple) contraints. Such a cap may force users to make more calls than necessary. 
References:  #900 
Expose a new `call_raw` method on the MultiCall interface that skips detokenization. The `call` method can then wrap `call_raw` to avoid code duplication and add in the detokenization. 
- While current tests should ensure no regressions for `call`, only a simple test was added for `call_raw`. This may need to be improved.
- The 16 call limit panic is moved from `add_call` to `call`. As it's a panic, it is not likely to cause issues in current deployments; however, it may be worth pointing out in Changelog in case anyone relied upon it.
- The test cases for `multicall_aggregate` did not appear to be compatible with …
> Expose New `call_raw` API that permits MultiCalls without Detokenization

- ethers-core/src/macros/ethers_crate.rs
- ethers-solc/src/compile/mod.rs
This allows us to generate bindings in projects that do not have a `Cargo.toml`, e.g. in Solidity repositories when using `forge bind` https://github.com/gakonst/foundry/pull/620. Previously, we had to not support it: https://github.com/gakonst/foundry/pull/663
> fix(abigen): do not panic when run on non-cargo projects

- ethers-providers/src/provider.rs
I want to implement a custom MIddleware to call otterscan RPC calls on the node and self implemented ones, currently the `request` function on `Provider<JsonRpcClient>` is private, changing the function to public will allow me to create implementations like this one.
```rs
#[async_trait]
pub trait OtterScanMiddleware: Middleware {
async fn get_api_level(&self) -> Result<U64, ProviderError> {
self.provider().get_api_level().await.map_err(FromErr::from)
}
}
#[async_trait]
impl<P: JsonRpcClient> OtterScanMiddleware for Provider<P> {
async fn get_api_level(&self) -> Result<U64, ProviderError> {
self.request("ots_getApiLevel", []).await
}
}
```
change `request` function to `pub`
> change visibility of request in Provider<JsonRpcClient>

- CHANGELOG.md
- ethers-core/src/types/chain.rs
- ethers-etherscan/src/lib.rs
Missing support of Cronos in Foundry, as the mainnet beta does not support EIP-1559 yet (the latest testnet does). 
Added Cronos and CronosTestnet to the Chain enum in ethers-core types, and marked Cronos in the is_legacy function.
> feat(chain): add Cronos and Cronos testnet

- ethers-solc/src/compile/mod.rs
- ethers-solc/src/resolver.rs
- ethers-solc/tests/project.rs
followup https://github.com/gakonst/ethers-rs/pull/882
off by one while determining the intersection of versions
@lattejed what additional tests do we need?
> fix(solc): off by one error finding version intersection

- ethers-solc/src/utils.rs
Ensure we can parse curly bracket imports via solang and via regex
> test: add curly bracket import test

- ethers-solc/src/remappings.rs
Closes #906
check if currently inside `node_modules`, if so use `@openzeppelin` rather then `@openzeppelin/contracts`
> fix(solc): mimic hardhat import resolver when in node_modules

- ethers-solc/src/lib.rs
- ethers-solc/src/resolver/mod.rs
- ethers-solc/src/resolver/tree.rs
Add dependency tree printing for `forge tree`
> feat(solc): add tree printer implementation

- ethers-solc/src/artifacts/mod.rs
- ethers-solc/src/artifacts/serde_helpers.rs
- ethers-solc/tests/project.rs
Fix https://github.com/gakonst/foundry/issues/787
Always prefix bytecode object with "0x"
> fix(solc): consistent serde for linked and unlinked bytecode

- CHANGELOG.md
- Cargo.lock
- ethers-contract/ethers-contract-abigen/Cargo.toml
- ethers-contract/ethers-contract-abigen/src/contract.rs
- ethers-contract/ethers-contract-abigen/src/lib.rs
- ethers-contract/ethers-contract-abigen/src/multi.rs
- ethers-contract/ethers-contract-abigen/src/rawabi.rs
- ethers-solc/src/artifact_output/configurable.rs
- ethers-solc/src/artifacts/mod.rs
- ethers-solc/src/hh.rs
Close #947 
Close #951
Add `LosslessAbi` type in ethers-solc to mitigate the fact that `ethabi::Abi` is not lossless
support `ethers-solc` -> abigen! with solidity structs
> fix(abigen/solc): make abigen work with ethers-solc and abiencoderv2

- CHANGELOG.md
- ethers-etherscan/src/account.rs
- ethers-etherscan/src/errors.rs
- ethers-etherscan/src/lib.rs
https://github.com/gakonst/ethers-rs/issues/485
Add etherscan.io account endpoints
Added them.
> feat(etherscan): account endpoints

- ethers-providers/src/pending_transaction.rs
`ContractCall::send` returns `PendingTransaction`s, there is no way to access the tx hash since its a private field.
Adding a getter so the user can get a contract call's tx hash.
> feat(ethers-providers): expose pending tx_hash with a getter

- ethers-contract/ethers-contract-abigen/src/contract/methods.rs
- ethers-contract/tests/abigen.rs
Close #958
Previously we used `to_lowercase` as the identifier to determine if there are duplicated function calls, this ignored cases like `fooBar` and `FOO_BAR`. Instead we use snake_case as baseline now to catch these as well.
> fix(abigen): support functions with different casing

- ethers-contract/ethers-contract-abigen/src/source.rs
If no etherscan API key is set, Multiabigen (1+ etherscan sources) fails with "missing field abi" however the etherscan response is "{"status":"0","message":"NOTOK","result":"Max rate limit reached, please use API Key for higher rate limit"}"
Add max rate limit check for better error message
> chore: add rate limit message

- ethers-contract/ethers-contract-abigen/src/contract/methods.rs
- ethers-contract/ethers-contract-abigen/src/util.rs
- ethers-contract/tests/abigen.rs
Closes #967
check if identifiers are valid and prefix with an underscore if they start with a numeric value
> fix(abigen): safe ident underscore followed by numeric

- ethers-core/src/types/chain.rs
Not all that important, just more convenient when you are trying to derive `Default` on structs that may include the `Chain` as one of the fields.
Implementing the `std::default::Default` trait
> feat(ethers-core/Chain): implement Default trait

- ethers-contract/src/base.rs
Adds helpers for decoding function / event data when the type is not know ahead of time (e.g. in CLIs that want to be dynamic over the ABI)
> feat: add contract interface helpers

- CHANGELOG.md
- ethers-contract/ethers-contract-abigen/src/contract/structs.rs
- ethers-contract/tests/abigen.rs
I was generating bindings for a contract that imports [dYdX's I_Solo.sol](https://github.com/dydxprotocol/perpetual/blob/master/contracts/external/dydx/I_Solo.sol) and got an error because `AssetAmount` has a field that is called `ref`.
`ref` is a reserved word, so I use `util::safe_ident` instead of `util::ident` for field names.
> fix(abigen): safe ident field names

- Cargo.lock
- ethers-etherscan/Cargo.toml
- ethers-etherscan/src/contract.rs
- ethers-etherscan/src/errors.rs
- ethers-etherscan/src/lib.rs
- ethers-etherscan/src/source_tree.rs
* Create a source tree of paths and their respective contents from the
ContractMetadata.
This is useful for file level analysis or writing the resulting files to disk.
* Test writing to disk via cargo test
* Test etherscan by uncommenting the ignore on
can_fetch_contract_source_tree_for_multi_entry_contract
and can_fetch_contract_source_tree_for_singleton_contract
> feat(etherscan): source tree support

- CHANGELOG.md
- ethers-providers/src/provider.rs
As specified in https://docs.ens.domains/dapp-developer-guide/resolving-names#reverse-resolution
* I'm not sure where to find a negative test.
> Enforce commutativity of ENS reverse resolution

- ethers-solc/src/config.rs
- ethers-solc/tests/project.rs
https://github.com/gakonst/foundry/issues/811
Moved the insert above the recursive function, which should guarantee that we include a node only once.
Which would prevent `A import B imports A` which would start recursive `flatten_node` at `B` but `A` is not yet included in the imports set so it will be included again.
CC @rkrasiuk
> fix(solc): flatten nodes only once

- ethers-solc/src/resolver/tree.rs
remove wrong indent
on https://github.com/gakonst/dapptools-template :
```console
forge tree --no-dedupe                                                                                  
src/Greeter.sol ^0.8.0
└── lib/openzeppelin-contracts/contracts/access/Ownable.sol ^0.8.0
└── lib/openzeppelin-contracts/contracts/utils/Context.sol ^0.8.0
src/test/Greeter.t.sol ^0.8.0
├── src/test/utils/GreeterTest.sol ^0.8.0
│   ├── lib/ds-test/src/test.sol >=0.4.23
│   ├── src/Greeter.sol ^0.8.0
│   │   └── lib/openzeppelin-contracts/contracts/access/Ownable.sol ^0.8.0
│   │       └── lib/openzeppelin-contracts/contracts/utils/Context.sol ^0.8.0
│   └── src/test/utils/Hevm.sol ^0.8.0
└── src/Greeter.sol ^0.8.0
└── lib/openzeppelin-contracts/contracts/access/Ownable.sol ^0.8.0
└── …
```
> fix(solc): remove unnecessary indent

- ethers-solc/src/cache.rs
- ethers-solc/src/compile/project.rs
- ethers-solc/src/lib.rs
- ethers-solc/src/resolver/mod.rs
- ethers-solc/tests/project.rs
This fixes several issues that were discovered on https://github.com/maple-labs/loan/releases/tag/v3.0.0-beta.0
- don't emit anything (cache/artifacts) if there are errors in the project output
- an erroneous condition when checking allowed-paths
- when filtering `dirty` files, also include their imports in the CompilerInput so that solc doesn't need to look them up
> fix(solc): fix cache and allowed paths bug

- ethers-solc/src/report.rs
Add support for a `scoped` Reporter. This can be used to use custom reporting before invoking `Project::compile()`. For example to add a Spinner to the output.
Add additional Scoped Reporter that takes priority over the global one when the event listeners are invoked.
> feat(solc): add scoped reporter

- ethers-providers/src/transports/ws.rs
In tungstenite 0.17 a change was introduced considering the logic of
`IntoClientRequest`. [Look here](https://github.com/snapview/tungstenite-rs/issues/270)
When using this trait on a `HttpRequest` it just
uses the request without any changes to initiate the websocket
connection. This makes it necessary for the consumer of the api to supply the
correct http headers for initiating a websocket connection when using
`IntoClientRequest` on `HttpRequest`.
This commit adapts the logic in `connect_with_auth` to this new
behavior.
> Fix websocket connection request

- CHANGELOG.md
- ethers-providers/src/transports/mod.rs
I was writing some wrappers and I noticed that `ethers_providers::IpcError` and `ethers_providers::QuorumError` were not exported.
Export them in `pub use`
> fix: Export `ethers_providers::IpcError` and `ethers_providers::QuorumError`

- Cargo.lock
- ethers-middleware/tests/nonce_manager.rs
- ethers-middleware/tests/signer.rs
- ethers-providers/Cargo.toml
- ethers-providers/src/lib.rs
- ethers-providers/src/provider.rs
- ethers-providers/tests/provider.rs
Instead of us getting rate limited on 1 key, introduce a lazy static struct which rotates through a list of API keys to avoid rate limiting during unit testing
> feat: rotating infura keys

- ethers-solc/src/cache.rs
- ethers-solc/tests/project.rs
Fix false positive dirty detection for files that don't emit artifacts
Only check for artifacts if the CacheEntry links to artifacts, so that files like:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/interfaces/IERC165.sol
are skipped when determining the change status of a file
> fix(solc): skip artifacts check for files without artifacts

- ethers-etherscan/src/contract.rs
Ref https://github.com/gakonst/foundry/issues/931
When the constructor args argument comes from an inline `cast abi-encode` output, there's a newline that can break verification.
trim before stripping 0x
> fix(solc/etherscan): trim constructor args

- ethers-solc/src/report.rs
- ethers-solc/src/resolver/mod.rs
To improve user feedback on unresolved imports (indicates misconfigured remappings) also provide the current remappings
> chore(solc): provide remappings on unresolved import message

- ethers-contract/ethers-contract-abigen/src/multi.rs
Ref https://github.com/gakonst/foundry/issues/934
Better error message if bindings outdated
> chore(abigen): improve error message when bindings out of sync

- Cargo.lock
- ethers-solc/src/compile/mod.rs
- ethers-solc/src/resolver/mod.rs
smv-rs now returns the path where a solc was installed.
Use the path instead of the additional `find_installed_version`
> refactor(solc): bump svm-rs and use returned install path

- ethers-solc/src/cache.rs
Closes https://github.com/gakonst/foundry/issues/941
The way the `Cache::retain` function was implemented didn't account for entries without any artifacts such as a errors.sol file, which lead to them being evicted from the cache entry set.
> fix: don't evict cache entries with no artifacts

- ethers-solc/src/artifacts/mod.rs
- ethers-solc/src/cache.rs
- ethers-solc/src/compile/project.rs
- ethers-solc/src/filter.rs
- ethers-solc/src/lib.rs
After #1029 we can extend this output pruning behavior and tell solc to only include output for certain files (test files)
* introduce `FileFilter` trait that is a simple predicate. `TestFileFilter` is such a `FileFilter` that matches `.t.sol` files.
* add `Project::compile_sparse` to only compile those files that match a given predicate and prune all other files, this is intended to be used in `forge test`. not sure about the naming though.
By default, we prune all output from sources that are not _dirty_. the `FileFilter` will extend this to _dirty_ + `FileFilter::is_match`
May need a follow up for ergonomics for interacting with `forge`.
> feat(solc): support customized output selection pruning

- ethers-solc/src/artifacts/mod.rs
- ethers-solc/src/cache.rs
- ethers-solc/src/compile/project.rs
- ethers-solc/src/project_util/mod.rs
- ethers-solc/tests/project.rs
https://github.com/odyslam/foundry-upgrades/tree/feat/core highlighted an issue in which errors went undetected, turns out solc not necessarily emits the exact file name, e.g. `src/utils/upgradeProxy.sol` is emitted as `src/utils/UpgradeProxy.sol` so we ended up swallowing some errors.
needs a followup with some tests.
use lowercase
> fix(solc): use lowercase when comparing paths

- ethers-solc/src/artifacts/mod.rs
Adds `viaIR` optionto `Settings`, stabalized in 0.8.13 
Ref https://docs.soliditylang.org/en/latest/using-the-compiler.html#input-description
> feat(solc): add viaIR option

- ethers-solc/src/report/compiler.rs
- ethers-solc/src/report/mod.rs
Add support for logging the CompilerInput and output.
Additional type that can be invoked by the existing `Reporter` functions and can be configured using env vars.
Needs forge companion
> feat(solc): support for solc io json output

- ethers-contract/tests/abigen.rs
- ethers-core/src/macros/ethers_crate.rs
- ethers-etherscan/src/account.rs
- ethers-etherscan/src/source_tree.rs
- ethers-providers/tests/provider.rs
Make derives work in all crates again
* check against internal crate names when determining ethers' crate idents
* clippy fix
> fix(core): check against ethers internal crate names

- ethers-core/src/abi/codec.rs
- ethers-core/src/abi/error.rs
- ethers-core/src/types/mod.rs
Add codec helper functions to encode/decode hex
> feat(codec): add hex encode and decode functions

- Cargo.lock
- ethers-solc/Cargo.toml
- ethers-solc/src/compile/mod.rs
replace the HTTP request to retrieve the version list with the new svm-builds version list.
> feat(solc): use svm-builds instead of fetching http releases list

- ethers-core/src/types/transaction/eip2718.rs
- ethers-middleware/tests/nonce_manager.rs
- ethers-providers/src/provider.rs
Gas price is `max_fee_per_gas`, not `max_fee_per_gas + max_priority_fee_per_gas`.
> fix(core/TypedTransaction): eip1559 gas price should be max_fee_per_gas

- CHANGELOG.md
- ethers-solc/Cargo.toml
- ethers-solc/src/compile/mod.rs
- ethers-solc/src/compile/project.rs
- ethers-solc/src/error.rs
- ethers-solc/src/lib.rs
- ethers-solc/src/resolver/mod.rs
In #1064 sha2 crate was made optional but it is required by the code enabled by feature/crate svm.
Support for svm now requires svm + svm-builds + sha2, to make cfg easier I bundled this to a new feature "svm-solc"
> fix(solc): bundle new svm-solc feature

- CHANGELOG.md
- ethers-core/src/types/signature.rs
- ethers-core/src/types/transaction/eip1559.rs
- ethers-core/src/types/transaction/eip2718.rs
- ethers-core/src/types/transaction/eip2930.rs
- ethers-core/src/types/transaction/request.rs
- ethers-core/src/types/transaction/response.rs
Txs may not always have the `from` field set, make it optional and add method for being able to recover the same from signature and set it on the tx.
Allow txs that do not have a `from` field by defaulting to `Address::zero()` instead of making it optional to not break compat. Add method to recover the sender from signature and also set the same on the tx.
> Tx optional from

- ethers-etherscan/src/source_tree.rs
Just ensure that any paths with no extension default to a .sol
Tests: cargo test --lib ethers-etherscan -- source_tree
> chore(source_tree): add .sol extension when missing

- ethers-contract/tests/common/derive.rs
- ethers-core/src/abi/codec.rs
- ethers-core/src/abi/mod.rs
Closes #1076
change the type bound from `AbiArrayType` to `AbiType` in the tuple macro
> fix(abi): change abiarraytype type bounds for tuple

- ethers-solc/src/compile/output.rs
We switched out `known_contracts` in Foundry to use `ArtifactId` as a key instead of just the contract name to resolve name collisions. In `forge run` we need both a `BTreeMap<ArtifactId, Artifact>` collection *and* the sources of the project (for source mapping).
Add `ProjectCompileOutput::into_artifacts_with_sources`
> feat: ability to get artifacts + sources

- ethers-solc/src/artifact_output/configurable.rs
- ethers-solc/src/artifact_output/mod.rs
- ethers-solc/src/compile/project.rs
- ethers-solc/src/hh.rs
- ethers-solc/src/lib.rs
Closes #1028
Adds the AST of the source file to the configurable artifact.
this is a bit tricky because ast is a per-file value and inserting this on a per contract/artifact basis is not really ideal.
So currently the `ast` field of an artifact will include the ast for the whole file.
> feat(solc): include source file ast in artifact

- ethers-providers/src/provider.rs
This is useful because 
```
let url = format!("...");
let provider = Provider::try_from(&url);
```
does not work, we can also can't use `TryFrom<T:AsRef<str>>` because of some blanket conflicting impl in rust core that does not allow this.
> feat: add TryFrom String reference for http provider

- .github/workflows/ci.yml
- ethers-solc/src/artifact_output/mod.rs
See https://github.com/gakonst/foundry/issues/1062
Adds `ArtifactId::identifier` which returns a unique identifier for each artifact in the form `<source path>:<name>` e.g. `src/test/MyTest.t.sol:MyTest`
> feat: add `ArtifactId::identifier()`

- CHANGELOG.md
- ethers-signers/src/aws/utils.rs
[This commit](https://github.com/gakonst/ethers-rs/commit/568d9c8697bf6ba4944543a21c9456c0c11f0caf) introduced a bug in use of `k256::ecdsa::Signature::normalize_s` in the aws signer’s utils. The signature for normalize_s now returns an Option<Self>, which is None if no normalization action is taken. Commit maps non-normalized sig to error.
If no normalization occurs (normalize returns `None`), returned unnormalized signature instead of error.
> fix: aws signer does not throw error on unnormalized sig

- ethers-etherscan/src/lib.rs
The `ethers-etherscan` crate constructs string urls with an additional slash, creating an invalid URL. For example, when running a `forge verify-contract`, the generated etherscan url contains an extra slash.
**Example 1**
**Example 2**
Remove the additional slash in the url construction functions returning strings.
❌ (NOT NEEDED) Added Documentation
❌ (`ethers-etherscan` not included in changelog ?) Updated the changelog
> fix(ethers-etherscan): Broken Etherscan URL Construction

- CHANGELOG.md
- ethers-solc/src/compile/project.rs
- ethers-solc/src/report/mod.rs
We'd like to show time spent compiling a project in Forge. Other reporters could probably use this information, too.
Track elapsed compile time as a `std::time::Duration` and pass it through to the configured `Reporter` as an extra arg to `on_solc_success`. See also https://github.com/gakonst/foundry/pull/1145.
> feat(solc): pass compile time to reporter

- ethers-solc/src/artifacts/mod.rs
Add concrete BytecodeHash Variants
> feat(solc): add bytecode hash variants

- ethers-solc/src/cache.rs
- ethers-solc/src/compile/project.rs
- ethers-solc/src/filter.rs
- ethers-solc/src/project_util/mod.rs
- ethers-solc/src/resolver/mod.rs
- ethers-solc/src/resolver/parse.rs
- ethers-solc/tests/project.rs
the current sparse mode filter was too aggressive and didn't take libraries into account.
determine all linkReferences for a file during preprocessing and consider them when applying a custom filter.
this also includes most work for #1102 
Needs some additional manual testing
> fix(solc): extend sparse mode to linked references

- ethers-etherscan/src/contract.rs
- ethers-etherscan/src/errors.rs
- ethers-etherscan/src/lib.rs
- ethers-etherscan/src/transaction.rs
> feat(etherscan): add caching 

- ethers-solc/src/config.rs
- ethers-solc/src/resolver/mod.rs
- ethers-solc/src/resolver/parse.rs
- ethers-solc/tests/project.rs
`forge verify-contract` failed because `flatten` doesn't strip the experimental pragma from imported contracts.
Related issues: 
https://github.com/gakonst/foundry/issues/852
https://github.com/gakonst/ethers-rs/issues/1115
This PR enable `solc.flatten` to strip pragma from all imported contracts.
Fix #1115
> feat(solc): Strip experimental pragma from all imported contracts

- ethers-core/src/types/transaction/eip1559.rs
- ethers-core/src/types/transaction/eip2718.rs
- ethers-core/src/types/transaction/eip2930.rs
- ethers-core/src/types/transaction/mod.rs
- ethers-core/src/types/transaction/request.rs
The transaction RLP decoding logic assumes `to` is present but it's actually not true for contract deployment transactions. The library fails to decode such transactions as a result.
This PR fixes it.
> fix: fix deploy tx RLP decoding

- CHANGELOG.md
- ethers-core/Cargo.toml
- ethers-core/src/types/transaction/eip1559.rs
- ethers-core/src/types/transaction/eip2718.rs
- ethers-core/src/types/transaction/eip2930.rs
- ethers-core/src/types/transaction/request.rs
- ethers-core/src/types/transaction/response.rs
There are often cases where we might have some RLP encoding of a transaction, for example when receiving P2P messages, and want to decode that into a transaction type.
This implements RLP decoding for signed transactions, extracting the signature from the decoding as well as building and returning the transaction. This also recovers the sender from the signature so we can populate the `from` field. This can error, so we introduce new error types (`Eip1559RequestError`, `TypedTransactionError`, `RequestError`) which also wrap errors we might encounter when decoding and recovering the sender.
This also introduces a `hash` method on `TypedTransaction` which returns the hash of the signed transaction's RLP encoding.
> feat(core): implemented signed transaction RLP decoding

- ethers-providers/Cargo.toml
- ethers-providers/src/pubsub.rs
- ethers-providers/src/transports/common.rs
- ethers-providers/src/transports/http.rs
- ethers-providers/src/transports/ipc.rs
- ethers-providers/src/transports/quorum.rs
- ethers-providers/src/transports/ws.rs
Fixes #1119: JSON-RPC error responses are not propagated to (request) callsites for the IPC transport correctly and end up as unhelpful `serde_json` errors.
Tangentially, the internal handling of all JSON values creates a lot of intermediate `serde_json::Value` instances, which is inefficient, since this creates potentially nested `HashMap`s.
Instead of calling `Response::to_value`, which converts both success and error responses into a `serde_json::Value` we call `Response::into_result`, which propagates error responses as `Err` variants.
Internal handling of JSON responses and requests is switched from `serde_json::Value` to `serde_json::value::RawValue`, which does not create any hashmaps.
A potential issue persists, in that internal IPC server errors (such as an unexpected disconnect …
> Fix IPC handling of jsonrpc errors

- ethers-solc/src/artifacts/mod.rs
ipfs as default hash is consistent with solc's defaults
> chore: make ipfs the default bytecodehash again

- CHANGELOG.md
- ethers-etherscan/src/lib.rs
- ethers-solc/src/lib.rs
Two simple fixes:
1. Etherscan address generation was using Address display impl, instead of debug impl. This caused incorrect URL generation with address middles snipped e.g. `https://kovan.etherscan.io/address/0xe03d…98db#code`
2. Solc error had escaped double quotes around a string formatted with Debug impl. This caused `""double double quotes""` in that message. 
Fix some bad forge UX :)
- Use Debug impls for Address
- make etherscan Tx properly use `H256` instead of string
- make etherscan token properly use `Address` instead of string
- remove the extra quotes
> fixes: correct etherscan url address, remove double quotes in solc error

- ethers-solc/src/cache.rs
- ethers-solc/src/compile/project.rs
compute the content hashes for all source sets first so they#re available when filtering individual sets
supersedes #1141
> fix(solc): compute content hashes first

- ethers-middleware/src/timelag/mod.rs
Timelag not lagging behind for normal state queries (calls), only for block indexing.
- Ethers-contract implementation provides [block = None when building a ContractCall](https://github.com/gakonst/ethers-rs/blob/master/ethers-contract/src/contract.rs#L241)
-[ Contract.call() passes tx and block id (set to None) to provider](https://github.com/gakonst/ethers-rs/blob/master/ethers-contract/src/call.rs#L151-L152)
- Provider passes down the stack of inners
- Timelag middleware applies lag by calling normalize_block_number [BUT it is only called if the provided block is Some (call —> normalize_block_id —> normalize_block_number IFF id is Some)](https://github.com/gakonst/ethers-rs/blob/master/ethers-middleware/src/timelag/mod.rs#L60)
- That block field set by the contract was None so the …
> fix(timelag): normalize block if block = None

- ethers-contract/ethers-contract-derive/src/display.rs
- ethers-contract/ethers-contract-derive/src/utils.rs
- ethers-contract/tests/common/derive.rs
support the `Bytes` type in `EthDisplay` and format using hex encode
> fix: support display for bytes

- ethers-core/src/types/log.rs
- ethers-core/src/types/transaction/response.rs
`rlp::Encodable` trait not implemented for `Log` and `TransactionReceipt`.
Implement the trait for the two types, reference:
1. https://github.com/ethereum/go-ethereum/blob/master/core/types/receipt.go#L84-L90
2. https://github.com/ethereum/go-ethereum/blob/master/core/types/log.go#L67-L71
> feat: impl rlp encodable for log and receipt

- ethers-core/src/abi/mod.rs
Followup #1140
@meetmangukiya highlighted that `AbiArrayType` should be implemented for `Vec<T:AbiArrayType>` and tuples are `AbiArrayType`. This PR confirms that, so whatever is causing #1140 is related to a derive macro I think
> test: add type check test for abi array tuples

- ethers-contract/src/factory.rs
> ethers-contract: ContractFactory, set deployer to public so defaults may be overrided. Solves  #1155

- ethers-solc/src/artifacts/mod.rs
Add bindings for missing `debug` info
Ref https://github.com/foundry-rs/foundry/issues/1375
> feat: add debug info bindings

- Cargo.lock
- ethers-solc/Cargo.toml
- ethers-solc/src/artifacts/mod.rs
- ethers-solc/src/artifacts/serde_helpers.rs
- ethers-solc/src/lib.rs
- ethers-solc/tests/project.rs
supersedes #1151
this also makes sure all paths use unix slashes `/` via `path-slash` crate Ref https://github.com/foundry-rs/foundry/issues/1382
sorry to hijack this @pyk 🙈
but I needed this for some verify debugs,
> feat: add standardjson compiler input type

- ethers-core/src/types/log.rs
This is a minor change mainly aimed at making it more convenient to instantiate a `Log` without the need to mark all the optional fields as `None`. For instance:
```rust
let log = Log {
address: Address::random(),
bloom: Bloom(rand_bytes(256)),
topics: vec![H256::random(), H256::random()],
..Default::default()
};
```
Derive `Default` for `Log`
> chore(core): derive default for log

- ethers-solc/src/artifact_output/configurable.rs
https://github.com/foundry-rs/foundry/issues/1380
> feat: abi as an extra file

- ethers-solc/src/config.rs
- ethers-solc/tests/project.rs
Adjust flatten output format so that:
1. no newline at the start of the file, and
2. newline at the end of the last line.
1. Move regex replace out of recursion (could have slight performance improvement).
2. `trim` and append `\n` at the end before returning result.
3. Adjust tests to reflext the new output formats.
> fix(solc): adjust flatten format

- ethers-solc/src/artifacts/mod.rs
- ethers-solc/src/compile/output.rs
include error code in output so they can be easily silenced
> chore(solc): include error code in diagnostic

- Cargo.lock
- ethers-etherscan/Cargo.toml
- ethers-etherscan/src/contract.rs
- ethers-etherscan/src/lib.rs
Use correct fantom API URLs
**NOTE** API env for fantom is now `FTMSCAN_*` or `FANTOM_SCAN`
> fix: proper fantom api urls

- ethers-solc/src/artifact_output/configurable.rs
https://github.com/foundry-rs/foundry/issues/1381
Add it
Also, it seems like the AST is always present and is not configurable - it's not present in `OutputSelection` and is enabled by default.
`ExtraOutputValues::compact_format` also seems to be unused?
> feat: function debug data in extra output

- ethers-solc/src/artifact_output/configurable.rs
- ethers-solc/src/artifacts/ast.rs
- ethers-solc/src/artifacts/mod.rs
- ethers-solc/src/artifacts/serde_helpers.rs
- ethers-solc/src/compile/project.rs
Adds support for capturing the `Ast` object, this only includes `id` + `nodeType`, the rest is captured in `BTreeMap<String, Value>`, so this should be lossless.
> feat: add minimal ast bindings

- Cargo.lock
- ethers-providers/Cargo.toml
- ethers-providers/src/transports/common.rs
- ethers-providers/src/transports/http.rs
- ethers-providers/src/transports/ipc.rs
- ethers-providers/src/transports/ws.rs
ran cargo +nightly fmt
fixes typo
remove some commented out code
The current IPC server code has two issues:
https://github.com/gakonst/ethers-rs/blob/77bd9d49c88ca8bdced37f7554919e3c3d584310/ethers-providers/src/transports/ipc.rs#L163-L186
This is the main IPC server loop (the function is called in a loop). Since the IPC `UnixStream` is split into read & write halves, I assume the intention was to allow reads & writes to happen concurrently, but due to the await in line 169 this is broken: The `await` on the write action (the first arm of the select expression) prevents any reads to be processed while the write is incomplete.
The second issue is in the `handle_request` method itself:
https://github.com/gakonst/ethers-rs/blob/77bd9d49c88ca8bdced37f7554919e3c3d584310/ethers-providers/src/tr …
> refactors ipc transport internals

- ethers-contract/src/event.rs
When doing a transaction, we'd like to know the logs it generated to get the data from those logs. We usually have a `TransactionReceipt` which does contain a vector of `Log`. Unfortunately, the only method available to parse this as the events of one contract is to use `contract.my_event_filter().parse_log()` but this is private.
The other methods like `decode_log` take a `RawLog` and thus can't be used from a TransactionReceipt.
Make `parse_log` public.
> Update event.rs::parse_log to public

- CHANGELOG.md
- ethers-middleware/src/gas_oracle/blocknative.rs
- ethers-middleware/src/gas_oracle/mod.rs
we don't have any 1559 gas oracle
adds blocknative gas oracle
notes-
- this provider requires api key (although it's free) so did not include tests. if we can add one as CI env variable i can update PR with tests
- the response returns some potentially-useful fields that aren't exposed in the `GasOracle` trait- i left the response structs and `request` method public so users can use these themselves if needed
> feat: blocknative gas oracle

- ethers-solc/src/cache.rs
- ethers-solc/src/compile/project.rs
- ethers-solc/src/project_util/mod.rs
Applies the same checks used to determine whether to write artifacts (successful build, no ephemeral) to the cache file.
Likely related https://github.com/foundry-rs/foundry/issues/1244
only write cache file if build was successful
> fix(solc): only write cache file if build was successful

- CHANGELOG.md
- ethers-contract/ethers-contract-abigen/src/contract/common.rs
- ethers-contract/src/call.rs
- ethers-contract/src/contract.rs
- ethers-contract/src/factory.rs
- ethers-contract/src/multicall/mod.rs
- ethers-contract/src/multicall/multicall_contract.rs
- ethers-middleware/src/gas_escalator/mod.rs
- ethers-middleware/src/transformer/ds_proxy/factory.rs
`#[derive(Clone)]` was implementing `Clone` only if `M` was `Clone`, however because of `Arc<M>` this can be relaxed.
I was implementing a `Signer` and I was getting a misleading error because it wasn't clonable.
However since the whole middleware was wrapped in an `Arc`, then `Clone` shouldn't be a requirement.
When `#[derive(Clone)]` is used on a generic struct, then `Clone` is implemented if generic parameters are also `Clone`.
In the case of a middleware we can avoid this because it is always wrapped in an `Arc`.
A solution is to manually implement `Clone` for structs that take `Middleware` as a generic parameter.
> feat: Relax `Clone` requirements when `Arc<M>` is used

- CHANGELOG.md
- ethers-core/src/types/transaction/response.rs
`TransactionReceipt` struct did not include the `to` and `from` properties which is shown in the spec 
- Have added the `to` and `from` 
- Have brought in a test for that struct
> fix: add to and from into the transaction receipt to follow spec

- ethers-solc/src/artifacts/mod.rs
- ethers-solc/src/compile/mod.rs
- ethers-solc/test-data/library-remapping-in.json
- ethers-solc/tests/project.rs
The solc docs say about libraries
```json
"libraries": {
// The top level key is the the name of the source file where the library is used.
// If remappings are used, this source file should match the global path
// after remappings were applied.
// If this key is an empty string, that refers to a global level.
"myFile.sol": {
"MyLib": "0x123123..."
}
},
```
currently we're not able to apply remappings, this adds support for this
Ref https://github.com/foundry-rs/foundry/issues/1338
* add `Libraries` wrapper type with support for applying remappings
* add more tests
> fix(solc): remapping aware libraries

- ethers-solc/src/compile/mod.rs
- ethers-solc/test-data/library-remapping-in-2.json
Adds another test that mimics the compiler input generated in forge
> test(solc): add another link with remapping test

- ethers-signers/src/aws/mod.rs
- ethers-signers/src/ledger/app.rs
- ethers-signers/src/ledger/mod.rs
- ethers-signers/src/trezor/app.rs
- ethers-signers/src/trezor/mod.rs
- ethers-signers/src/wallet/mod.rs
- ethers-signers/src/wallet/private_key.rs
In #805, `chain_id` was removed from the `sighash` method for `TypedTransaction`. This causes issues like #1189, since transactions with an empty `chain_id` would have an incorrect rlp, sighash, and signature. In case the `chain_id` contained in the transaction is `None`, the signer should use its own `chain_id`.
* All signers will now prefer the transaction `chain_id`, using the signer `chain_id` only if the transaction `chain_id` is `None`.
* Remove `InvalidTransactionError` in the private key wallet - this would need to be re-introduced if we want to enforce that transactions have a `chain_id` consistent with signers.
* Refactor the AWS signer's `sign_digest_with_eip155` to include a `chain_id` parameter, rather than using the signer's `chain_id` every time. This way, transactions …
> Use EIP155 for all signers with empty transaction `chain_id`

- ethers-signers/src/ledger/app.rs
Since Ledger only return one byte of `signature.v` as stated in #1198, This issue prevent from sending transaction to chain that has large chain ID, such as, Arbitrum One (chain ID: 42161).
I have derived a part of code from Ledger's JavaScript library and implement it as Rust. This part of code re-calculate signature's `v` value to fit with target chain.
The reference of Ledger's library can be found here: https://github.com/LedgerHQ/ledgerjs/blob/e78aac4327e78301b82ba58d63a72476ecb842fc/packages/hw-app-eth/src/Eth.ts#L298-L314
> Fix: Ledger should have correct signature v value for chains with large chain ID

- examples/decode_tx_input.rs
I wanted to learn how to decode transaction data so I was playing around with this [example](https://github.com/gakonst/ethers-rs/blob/master/examples/decode_tx_input.rs) but I noticed that there was a typo in the output.
`decoded.to` is the recipient of the swap but `to` should be the destination token i.e. `path[1]`.
- [NA] Added Tests
- [NA] Added Documentation
- [NA] Updated the changelog
> fixed typo when determining to token address

- CHANGELOG.md
- ethers-core/src/types/log.rs
The trait `From<H160>` for `ValueOrArray<H160>` is not implemented which prevents compilation when using `pub fn address<T: Into<ValueOrArray<Address>>>(self, address: T) -> Self` for `ethers_core::types::Filter`.
Cargo.toml used in both examples:
```
[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs" }
eyre = "0.6.8"
tokio = { version = "1", features = ["full"] }
```
Example that should compile but doesn't:
```
use ethers::prelude::*;
use eyre::Result;
fn main() -> Result<()> {
let address = "0x1F98431c8aD98523631AE4a59f267346ea31F984".parse::<Address>()?;
let _filter = Filter::new().address(address);
Ok(())
}
```
Compilation error from trying to compile the example above:
```
error[E0277]: the trait bound `ValueOrArray<H160>: From<H160>` is not satisfied
--> …
```
> Adds From<H160> trait to ValueOrArray<H160>

- ethers-providers/README.md
I wanted to use websockets but I kept running into a tungstenite error code 400.
A quick search on the ethers-rs telegram chat provided the [solution](https://t.me/ethers_rs/8557). I've tested the solution locally (with these features enabled) and websockets work as intended so I'm updating the documentation to reflect this.
- [NA] Added Tests
- [NA] Added Documentation
- [NA] Updated the changelog
> update documentation to enable ws & rustls / openssl if user wants to use websockets

- ethers-solc/src/lib.rs
Make sure std json compiler input contains only contains unique sources
> fix(solc): ensure std json sources are unique

- ethers-solc/src/report/compiler.rs
Followup for https://github.com/gakonst/ethers-rs/pull/1214 to log multiple std in/out puts
> feat(solc): support logging multiple files via io logger

- ethers-solc/src/compile/project.rs
- ethers-solc/src/report/mod.rs
Previously the scoped reporter (set in forge) got lost in when compiled in parallel, due to the thread_local! initialisation.
when compiling in parallel clone the current default reporter and use it as the scoped reporter on the rayon thread.
> fix(solc): make scoped reporter work in parallel

- ethers-etherscan/src/contract.rs
* add Deserialize derive
* add notes about applicability of arguments
* skip all optional arguments if None
Ref https://docs.etherscan.io/api-endpoints/contracts#source-code-submission-gist
> chore(etherscan): update VerifyArgs

- ethers-solc/src/config.rs
- ethers-solc/src/resolver/mod.rs
- ethers-solc/src/resolver/parse.rs
- ethers-solc/src/utils.rs
- ethers-solc/tests/project.rs
addresses [foundry#1440](https://github.com/foundry-rs/foundry/issues/1440)
This PR includes: 
- More robust regex for import statement parsing in case of `solang` failure
- Partial support for import aliases: any explicit import alias will be replaced with its original name 
Known Issues: 
- Since alias replacement rewrites the contents of the file, any previous data unit location might be incorrect. This is a temporary solution and is based on the assumption that any usage of an alias happens after all of the import statements.
> fix(solc): flatten import aliases

- ethers-solc/src/lib.rs
Closes #1202
add autodetect check, same as existing `Project::compile`
> fix(solc): respect auto detection in additional compile functions

- ethers-solc/src/artifact_output/configurable.rs
totally forgot about this one, closes #1082
adds support for configuring `generatedSources` and support emitting `sourceMap` as separate file
Ref https://github.com/foundry-rs/foundry/issues/1487
> feat(solc): add missing options for configurable artifact

- ethers-etherscan/src/lib.rs
Ref https://github.com/foundry-rs/foundry/issues/1534
> feat(etherscan): add moonbeam urls

- CHANGELOG.md
- ethers-contract/ethers-contract-abigen/src/contract.rs
- ethers-contract/ethers-contract-abigen/src/contract/events.rs
- ethers-contract/tests/abigen.rs
Closes #1135
Auto aliase overloaded events
> feat(abigen): support overloaded events

- CHANGELOG.md
- ethers-core/src/types/chain.rs
it now supports EIP1559 after the network upgrade at the height 2693800
removed Cronos mainnet beta from `is_legacy`
> fix(core): removed Cronos mainnet beta from `is_legacy`

- ethers-solc/src/artifacts/ast.rs
- ethers-solc/test-data/ast/ast-erc4626.json
Adds the remaining node types based on https://unpkg.com/solidity-ast@0.4.32/types.d.ts
Currently for coverage in Foundry I just use `other` on `Node` to get extra data, but I wonder what the best way would be to add more node-specific data? E.g. see `FunctionDefinition` where the statements in the function are contained in a `block` key (as opposed to `nodes`)
> feat: remaining AST nodes

- ethers-solc/src/artifacts/ast.rs
Not all AST nodes have IDs, apparently
> fix: make ast node ids optional

- ethers-solc/src/artifact_output/mod.rs
- ethers-solc/src/artifacts/bytecode.rs
extend `Artifact` with source map getters
cc @onbjerg
> feat(solc): add source map access functions

- CHANGELOG.md
- ethers-solc/src/artifacts/mod.rs
- ethers-solc/test-data/model-checker-sample/Assert.sol
- ethers-solc/tests/project.rs
Foundry's https://github.com/foundry-rs/foundry/pull/1602 depends on this PR.
This PR adds [Solidity's model checker](https://docs.soliditylang.org/en/latest/smtchecker.html#) options to ethers-solc's settings.
Mainly to allow Foundry users to have direct access to the model checker.
The default case of these options do not enable the model checker since it's opt-in, so the PR shouldn't disturb users who are not interested in the model checker.
Add data structures that represent a basic subset of the [tool's options](https://docs.soliditylang.org/en/latest/smtchecker.html#smtchecker-options-and-tuning).
The 4 added options are the most basic to enable the tool. Other options such as `divModNoSlacks` and `invariants` can be added later on.
> Add basic solc model checker options

- Cargo.lock
- ethers-solc/Cargo.toml
- ethers-solc/src/compile/mod.rs
- ethers-solc/src/utils.rs
- ethers-solc/tests/project.rs
> fix(solc): add `RuntimeOrHandle` & fix solc blocking installation

- ethers-providers/src/transports/common.rs
- ethers-providers/src/transports/http.rs
- ethers-providers/src/transports/ws.rs
I came across an issue in foundry trying to deploy a contract to fantom using the official RPC `https://rpc.ftm.tools/`. A call to `eth_chainId` fails to deserialize, because the sent out request has the ID `zero`, to which the response is `{"jsonrpc":"2.0","id":null,"result":"0xfa"}`. For some reason the server fails to unmarshall the request ID and responds with a `null` ID. When sending a request with a non-zero ID, everything works fine. Strictly speaking, this is an error on their side, since nothing in the JSON-RPC forbids a zero ID and I am not entirely sure why this occurs, since go-opera uses the `rpc` package straight from the go-ethereum repo and I don't think geth exhibits this behaviour. Anyways, the fix is simple and the alternative behaviour is consistent with other eth …
> fix: all request ids start at 1

- .gitignore
- Cargo.lock
- ethers-core/Cargo.toml
- ethers-core/src/types/chain.rs
Opening up a pr to check differences
Related to foundry issue: https://github.com/foundry-rs/foundry/issues/1564
Related pr: https://github.com/foundry-rs/foundry/pull/1581
Current problem is build error:
```sh
➜  ethers-rs git:(add-strum-for-chain) cargo build
Compiling ethers-core v0.6.0 (/Users/m1/CLionProjects/ethers-rs/ethers-core)
warning: unused import: `VariantNames`
--> ethers-core/src/types/chain.rs:6:43
|
6 | use strum::{EnumString, EnumVariantNames, VariantNames};
|                                           ^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
error[E0119]: conflicting implementations of trait `std::str::FromStr` for type `types::chain::Chain`
--> ethers-core/src/types/chain.rs:15:64
|
15  | #[derive(Debug, Clone, Copy, Eq, PartialEq, Hash, …
```
> fix: unify name of supported chains with strum

- CHANGELOG.md
- ethers-core/src/types/block.rs
- ethers-core/src/types/chain.rs
I was getting the following error when calling `get_block(BlockNumber::Pending)`
```
invalid type: null, expected a (both 0x-prefixed or not) hex string with length of 40 at line 1 column 730
```
`miner` field is always `null` on pending blocks, so `author` should be optional.
> fix(core): On pending block `miner` field is always `null`

- ethers-solc/src/cache.rs
- ethers-solc/src/compile/mod.rs
- ethers-solc/src/project_util/mod.rs
- ethers-solc/tests/project.rs
Fixes a bug where changing the pinned solc between two runs resulted in the cached artifacts of the old version also being included in the output of the project compiler.
Ref https://github.com/foundry-rs/foundry/issues/1306
when postprocessing the cached artifacts add another check that the versioned artifact must also be included in the filtered set, which contains the versions that don't need to be compiled. This way we will always purge (Contract, 0.8.10) if we change the pinned version to `0.8.13` and recompile.
> fix(solc): purge obsolete cached artifacts

- CHANGELOG.md
- ethers-etherscan/src/lib.rs
Cronos testnet has now the Etherscan support:  https://testnet.cronoscan.com
Added the respective URLs to the Etherscan chain resolution
> feat(etherscan): added Cronos testnet

- ethers-core/src/types/transaction/eip2718.rs
ref: https://github.com/foundry-rs/foundry/pull/1208#discussion_r872909522
Helpers to unwrap `TypedTransaction` into whichever type the user requires.
> feat(core): add  helpers to unwrap `TypedTransaction`

- ethers-solc/src/compile/mod.rs
make test compile again
use 0.8.14 release.
No breaking changes in [release notes](https://github.com/ethereum/solidity/releases)
> chore: bump latest solc release

- ethers-solc/src/artifacts/mod.rs
- ethers-solc/tests/project.rs
Closes https://github.com/foundry-rs/foundry/issues/1662
turns out tags for constructor are serialized differently on older versions
support `constructor: value` variant
> fix(solc): support constructor user docs

- ethers-solc/src/config.rs
- ethers-solc/tests/project.rs
If any pragma statement is placed after the first import statement, the application will panic.
Replace import and pragma statements in correct order to preserve the offset
> fix(solc): flatten random statement order

- CHANGELOG.md
- ethers-contract/src/factory.rs
> feat(ContractDeployer): add tx builder methods

- CHANGELOG.md
- ethers-providers/src/transports/ws.rs
I noticed that occasionally my program would get stuck with one thread spinning at near 100% CPU. After a bunch of investigation with rust-gdb and tokio-console and stripping it down to a much [smaller program](https://github.com/SatoshiAndKin/web3-proxy/tree/c3d1d14f1628e415729e55809e3037b422ef16ad/web3-proxy-minimal), I narrowed it down to a websocket task being very active doing nothing.
Here you can see the spawned future stuck running:
It is being woken up ~253k times per second, so that explains the 100% CPU:
After some digging, I found this related code:
https://github.com/gakonst/ethers-rs/blob/3df1527cef7a7de8cbb26a8c98de74348203176b/ethers-providers/src/transports/ws.rs#L402-L408
Dropping that error is bad because it might be an `Io(Kind(UnexpectedEof))`. If that's the case, the …
> return instead of ignore error

- ethers-core/src/types/txpool.rs
previously we'd use the default serde derive, now we serialize
it like geth does
> fix: correctly serialize TxPoolInspectSummary

- CHANGELOG.md
- ethers-core/src/types/log.rs
- ethers-providers/src/lib.rs
- ethers-providers/src/log_query.rs
- ethers-providers/src/provider.rs
- examples/paginated_logs.rs
Closes #954 
Implement a new stream that breaks requested block range into smaller pages that are loaded one at a time and streamed to the user.
Note: this only solves block limitations, if an rpc provider limits to 1000 blocks for instance, you could set page size to 1000 to solve it. However, if the limitation is on the number of logs(infura), this can't solve it automatically or completely, can try smaller page sizes but because number of logs in arbitrary block ranges is also arbitrary it can be hard to decide on a page size.
> feat: add paginated logs

- CHANGELOG.md
- ethers-solc/src/cache.rs
- ethers-solc/tests/project.rs
store all paths relative in the cache file
* cache entry objects relative to root, (can be in src, lib, etc..)
* artifacts relative to artifacts output dir
strip paths before saving and join paths before loading
> feat(solc): make cache entries relative to root dir

- ethers-signers/src/wallet/mod.rs
- ethers-signers/src/wallet/private_key.rs
In `sign_transaction_sync`, if a transaction `chain_id` was `None`, the wallet would sign a transaction without serializing the chain id. However, the signature's `v` would encode the proper chain.
Use the signer's `chain_id` if the transaction does not specify one, before hashing the transaction in `sign_transaction_sync`.
Adds a test checking that `sign_transaction_sync` outputs a correct `v` when signing a transaction with an empty chain.
> fix(signer): use wallet chainid for tx signing

- CHANGELOG.md
- ethers-signers/src/aws/mod.rs
AWS signing typed data (for EIP712) currently signs with EIP155. EIP712 includes `chain_id` when signing data already, thus we do not need EIP155 on top of that.
AWS signer `signed_typed_data` signs without EIP155.
> fix(signers): aws eip712 does not use eip155

- CHANGELOG.md
- ethers-solc/src/artifacts/mod.rs
- ethers-solc/src/compile/mod.rs
- ethers-solc/src/compile/output/contracts.rs
- ethers-solc/src/compile/output/mod.rs
- ethers-solc/src/compile/project.rs
- ethers-solc/src/lib.rs
- ethers-solc/src/remappings.rs
- ethers-solc/src/resolver/mod.rs
- ethers-solc/tests/project.rs
Closes #1315
working with paths is hard.
Ideally, we want to work with absolute paths because we resolve them in the Graph anyway and `Project::root` is not guaranteed to be cwd.
however, absolute/relative paths result in different solc metadata, so when invoking solc, we want to be consistent, or rather OS and local disk independent.
with 0.6.9, solc supports a `--base-path` option so we use that instead and also set the cwd of the solc process to `Project::root`.
This also introduces the `CompilerInput::with_base_path` function that will strip `Project::root` from:
* source paths
* output selection
* remappings
> feat(solc): use relative paths and --base-path option
