gakonst/ethers-rs

Cargo.lock, ethers-contract/Cargo.toml, ethers-contract/ethers-contract-abigen/Cargo.toml, ethers-contract/ethers-contract-derive/Cargo.toml, ethers-contract/ethers-contract-derive/src/lib.rs, ethers-contract/src/contract.rs, ethers-contract/src/factory.rs, ethers-contract/src/lib.rs, ethers-core/Cargo.toml, ethers-core/src/lib.rs, ethers-core/src/types/chainstate/log.rs, ethers-core/src/types/chainstate/transaction.rs, ethers-core/src/types/mod.rs, ethers-core/src/utils/ganache.rs, ethers-providers/Cargo.toml, ethers-providers/src/http.rs, ethers-providers/src/lib.rs, ethers-providers/src/provider.rs, ethers-providers/src/stream.rs, ethers-signers/Cargo.toml, ethers-signers/src/client.rs, ethers-signers/src/lib.rs, ethers-signers/src/wallet.rs, ethers/Cargo.toml, ethers/src/lib.rs
As title, also https://docs.rs/ethers/0.1.3/ethers/ is now live!
=> fix intradoc links and add missing cargo metadata

ethers-core/src/types/chainstate/block.rs
Matches the change in https://github.com/celo-org/celo-blockchain/pull/1096
=> feat(core/block): add epochSnarkData to the celo block

ethers-contract/src/call.rs, ethers-contract/tests/contract.rs, ethers-providers/tests/provider.rs
=> add support for gas estimate and calldata from ContractCall

.github/workflows/ci.yml, Cargo.lock, ethers-contract/src/contract.rs, ethers-core/src/types/chainstate/transaction.rs, ethers-core/src/types/crypto/mod.rs, ethers-signers/Cargo.toml, ethers-signers/src/client.rs, ethers-signers/src/ledger/app.rs, ethers-signers/src/ledger/mod.rs, ethers-signers/src/ledger/types.rs, ethers-signers/src/lib.rs, ethers-signers/src/wallet.rs, ethers/examples/sign.rs, ethers/tests/major_contracts.rs
Adds support for Ledger Nano S Eth app (v1.3.7)
- sign message
- sign transaction
- get addresses
- get app version
Ref: https://github.com/gakonst/ethers-rs/issues/1
=> feat: ledger support

.github/workflows/ci.yml, ethers-middleware/tests/stack.rs, ethers-providers/src/provider.rs, ethers-providers/src/transports/mock.rs, ethers-providers/src/transports/mod.rs
Adds a mock transport to help us expand our test coverage in more specific situations
=> feat: add a mock transport

Cargo.lock, ethers-core/Cargo.toml, ethers-core/src/types/signature.rs, ethers-providers/src/pending_transaction.rs, ethers-signers/Cargo.toml, ethers-signers/src/wallet/private_key.rs
Fixes #102 
also updates elliptic-curve/k256/ecdsa/yubihsm deps to latest
=> fix: reschedule waker if receipt is immediately available

Cargo.lock, ethers-contract/tests/contract.rs, ethers-middleware/tests/stack.rs, ethers-providers/Cargo.toml, ethers-providers/src/lib.rs
As title, nice ergonomics upgrade, h/t @vorot93 for https://github.com/auto-impl-rs/auto_impl
=> feat: derives &, Arc and Box for Middleware

ethers-signers/src/lib.rs, ethers-signers/src/wallet/mod.rs
As title, useful for people writing other signers
=> feat: expose to_eip_155

Cargo.lock, ethers-contract/Cargo.toml, ethers-contract/ethers-contract-abigen/Cargo.toml, ethers-contract/src/stream.rs, ethers-core/Cargo.toml, ethers-middleware/Cargo.toml, ethers-providers/Cargo.toml, ethers-signers/Cargo.toml
=> Trim some dependencies

README.md, ethers-contract/src/base.rs, ethers-contract/src/call.rs, ethers-contract/src/contract.rs, ethers-contract/src/event.rs, ethers-contract/src/lib.rs, ethers-middleware/src/gas_oracle/eth_gas_station.rs, ethers-middleware/src/gas_oracle/etherchain.rs, ethers-middleware/src/gas_oracle/etherscan.rs, ethers-middleware/src/gas_oracle/gas_now.rs, ethers-middleware/src/lib.rs, ethers-middleware/src/nonce_manager.rs, ethers-providers/src/lib.rs, ethers-providers/src/pubsub.rs, ethers-providers/src/stream.rs, ethers-signers/src/ledger/types.rs, ethers-signers/src/lib.rs, ethers/src/lib.rs
=> docs: add more docs

Cargo.lock, ethers-contract/ethers-contract-derive/src/abigen.rs, ethers-contract/src/contract.rs, ethers-contract/tests/common/mod.rs, ethers-core/Cargo.toml, ethers-core/src/abi/human_readable.rs, ethers-core/src/types/bytes.rs, ethers-core/src/types/transaction.rs
supersedes:
* https://github.com/gakonst/ethers-rs/pull/134
* https://github.com/gakonst/ethers-rs/pull/133
=> chore: upgrade to latest ethtypes

Cargo.lock, ethers-signers/Cargo.toml
Replace the `github` repo URL with a published crate.
=> Use published crate

Cargo.lock, ethers-contract/Cargo.toml, ethers-contract/ethers-contract-abigen/Cargo.toml, ethers-contract/ethers-contract-derive/Cargo.toml, ethers-core/Cargo.toml, ethers-middleware/Cargo.toml, ethers-providers/Cargo.toml, ethers-signers/Cargo.toml, ethers/Cargo.toml
=> release: bump to 0.2.0

ethers-providers/src/transports/ws.rs
Fixes disconnects with WebSocket subscriptions when Geth sends a `Ping` message.
Reply with a `Pong` message, and ignore `Pong` messages since they can be spuriously generated.
=> Handle ping/pong messages for Ws provider

ethers-core/src/utils/mod.rs, ethers-core/src/utils/units.rs
=> fix: switch between units correctly

Cargo.lock, ethers-core/Cargo.toml, ethers-core/src/abi/tokens.rs, ethers-core/src/types/i256.rs, ethers-core/src/types/mod.rs
Supersedes https://github.com/gakonst/ethers-rs/pull/174, closes #169
=> I256 implementation

ethers-middleware/src/transformer/ds_proxy/mod.rs, ethers-middleware/tests/transformer.rs
This PR adds minor improvements to the DsProxy's `execute` interface.
* We allow users to simply send `Bytes` or `Address` instead of building the `AddressOrBytes` type themselves
* We return a `ContractCall` instead of the tx hash, which no longer requires `execute` to be `async`
=> fix: improvements in DsProxy execute

ethers-contract/ethers-contract-abigen/src/contract/events.rs
#254 
Fixes by simply generating `#[ethevent(indexed)]` within the abigen! macro
=> fix(abigen): add indexed attribute when deriving EthEvent

ethers-core/src/utils/solc.rs
Support the solc contract abi output both as string (solc<=0.7) and array (solc >=0.8)
match against the the `abi` entry in the solc json output and if it's an array convert it to string, in order to not break the `CompiledContractStr`.
Closes #299
=> feat: support parsing solc contract abi output in string and array form

ethers-providers/Cargo.toml, ethers-providers/src/provider.rs
enable block filter tests
use `Geth::new` to spawn a local instance to connect to.
=> test: enable ignored tests with geth

ethers-contract/src/multicall/mod.rs, ethers-contract/tests/contract.rs, ethers-core/src/abi/human_readable.rs, ethers-core/src/types/i256.rs, ethers-core/src/types/log.rs, ethers-core/src/types/signature.rs, ethers-core/src/types/txpool.rs, ethers-middleware/src/gas_escalator/geometric.rs, ethers-middleware/tests/gas_escalator.rs, ethers-providers/src/ens.rs, ethers-providers/src/provider.rs, ethers-providers/src/stream.rs, ethers-providers/tests/txpool.rs, ethers-signers/src/ledger/app.rs
=> chore: fix lints

ethers-core/src/utils/ganache.rs
support additional ganache arguments
mimic the `Command` api to add additional arguments
=> feat: support additional ganache arguments

Cargo.lock, ethers-core/Cargo.toml, ethers-core/src/abi/tokens.rs, ethers-signers/Cargo.toml
=> chore: update deps

ethers-contract/ethers-contract-abigen/src/contract/methods.rs
- single solidity struct arguments resulted in an invalid type check when encoding the function parameters, such as
```solidity
function addLiquidityEthForUniV3(CellarAddParams calldata cellarParams)
```
- Modify the generated function body so that tuples are treated as tuples when `encode_function_data` is invoked internally
-
=> fix: ensure tuple arguments are encoded as tuples

ethers-contract/ethers-contract-abigen/src/contract/common.rs
fixes #360, @prestwich can you confirm this fixes your problem?
=> chore(abigen): allow clippy enum variant names

ethers-contract/src/contract.rs, ethers-contract/tests/contract.rs, ethers-core/src/types/log.rs
As title - fixes #240 (supersedes https://github.com/gakonst/ethers-rs/pull/370 because I couldn't make changes to @sebastinez branch)
=> feat: multiple addresses on Filter

README.md
As title indicates :slightly_smiling_face:
=> Add Flashbots middleware to projects section

Cargo.lock, ethers-contract/Cargo.toml, ethers-contract/ethers-contract-abigen/Cargo.toml, ethers-contract/ethers-contract-abigen/src/util.rs, ethers-contract/ethers-contract-derive/Cargo.toml, ethers-core/Cargo.toml, ethers-middleware/Cargo.toml, ethers-providers/Cargo.toml, ethers-signers/Cargo.toml, ethers/Cargo.toml
It's here finally. I promise I'll start tackling more regular releases & finally a changelog (#164 ...)
=> Release: 0.4

Cargo.lock, ethers-core/Cargo.toml, ethers/Cargo.toml
Add a `legacy` feature to `ethers` and `ethers-core`
=> feature: add legacy feature to ethers crate

Cargo.toml
as title - was introduced in #398
=> fix: make packages default members so they get executed on unit tests

.github/workflows/ci.yml, README.md, ethers-providers/src/lib.rs, examples/abigen.rs, examples/contract_human_readable.rs, examples/contract_with_abi.rs, examples/ens.rs, examples/ipc.rs, examples/watch_blocks.rs, scripts/examples.sh
=> ci: run examples in CI

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, README.md
=> chore: add changelog

CHANGELOG.md, ethers-core/src/utils/solc.rs
as title, forgot the changelog + add an extra example
=> chore: add changelog for #427 changes

CONTRIBUTING.md
`cargo fmt --all-features` -> `cargo fmt --all`
=> fix cargo fmt command in Contributing.md

Cargo.lock, ethers-core/Cargo.toml
as title, unblocks the release process
=> chore: bump ethabi

CHANGELOG.md, Cargo.lock, Cargo.toml, ethers-contract/Cargo.toml, ethers-contract/ethers-contract-abigen/Cargo.toml, ethers-contract/ethers-contract-derive/Cargo.toml, ethers-core/Cargo.toml, ethers-middleware/Cargo.toml, ethers-providers/Cargo.toml, ethers-signers/Cargo.toml
=> release: 0.5.3

ethers-core/src/utils/solc.rs
Allow to explicitly set the `--combined-json` option for `solc`
=> feat: allow to configure combined-json

ethers-core/src/utils/solc.rs
Add additional general solc `Contract` type.
=> feat: add general solc contract types

Cargo.lock, Cargo.toml, ethers-etherscan/Cargo.toml, ethers-etherscan/resources/UniswapExchange.sol, ethers-etherscan/src/lib.rs
Add etherscan.io client,
Ref #485
=> feat: add etherscan client crate

Cargo.lock, ethers-solc/Cargo.toml, ethers-solc/README.md, ethers-solc/src/artifacts.rs, ethers-solc/src/cache.rs, ethers-solc/src/compile.rs, ethers-solc/src/config.rs, ethers-solc/src/lib.rs, ethers-solc/src/utils.rs, ethers-solc/test-data/dapp-sample/lib/ds-test/demo/demo.sol, ethers-solc/test-data/dapp-sample/lib/ds-test/src/test.sol, ethers-solc/test-data/dapp-sample/src/Dapp.sol, ethers-solc/test-data/dapp-sample/src/Dapp.t.sol, ethers-solc/test-data/hardhat-sample/contracts/Greeter.sol, ethers-solc/test-data/hardhat-sample/node_modules/hardhat/console.sol, ethers-solc/test-data/sample/contracts/Greeter.sol, ethers-solc/tests/project.rs
provide a way to configure a project root with cache support.
=> feat: improved solc management

Cargo.lock, ethers-solc/Cargo.toml, ethers-solc/src/compile.rs, ethers-solc/src/lib.rs
=> feat: add solc svm find support

ethers-providers/src/transports/common.rs, ethers-providers/src/transports/ipc.rs
Ensures that the initiator of a channel receives result, even if it's an error
=> fix: send error back

.github/workflows/ci.yml, ethers-providers/src/transports/common.rs, ethers-solc/src/artifacts.rs, examples/contract_with_abi.rs, examples/ipc.rs, examples/ledger.rs, examples/yubi.rs
=> fix: failing test and check --all-targets in ci

ethers-solc/src/compile.rs, ethers-solc/src/config.rs, ethers-solc/src/lib.rs
=> feat: more allow paths integration

ethers-solc/src/compile.rs, ethers-solc/src/remappings.rs
=> fix: only find if path exists

Cargo.lock, ethers-solc/Cargo.toml, ethers-solc/src/artifacts.rs, ethers-solc/src/compile.rs, ethers-solc/src/config.rs, ethers-solc/src/error.rs, ethers-solc/src/lib.rs, ethers-solc/src/remappings.rs, ethers-solc/test-data/test-contract-remappings/lib/bar/src/Bar.sol, ethers-solc/test-data/test-contract-remappings/src/Foo.sol
Ports over the logic from [here](https://github.com/gakonst/dapptools-rs/blob/master/dapptools/src/utils.rs#L47)
=> feat: auto-detect solc remappings

ethers-solc/src/lib.rs
Previously, we'd always auto-detect the solc version. We currently have a [bug](https://github.com/gakonst/ethers-rs/pull/593) with automatic solc detection when there's conflicting version imports across deps, so as a temp-fix, we let the user manually specify the solc version. This was observed when we were trying to test with [tinlake](https://github.com/centrifuge/tinlake).
=> feat(solc): allow specifying solc version even if auto-detect enabled

.gitignore, ethers-contract/src/multicall/mod.rs, ethers-core/src/types/chain.rs, ethers-etherscan/src/lib.rs, scripts/examples.sh
I want to use this library to interact with polygon and avalanche too. 
I've added chain definitions for the networks and testnets, as well as block explorer API's 
I couldn't find a mutlicall contract on avalanche yet.
=> add support for polygon and avalanche

README.md
Officially document our strategy wrt wasm and ffi
Add a readme note
=> docs: add note about wasm and ffi to readme

README.md
Added a note about the extra networks in the readme
=> update readme for polygon and avalanche

ethers-core/src/types/chain.rs, ethers-core/src/utils/mod.rs, ethers-core/src/utils/moonbeam.rs, ethers-etherscan/src/lib.rs, examples/moonbeam_with_abi.rs
Add utils for polkadot's [moonbeam](https://moonbeam.network/) chain
* chain ids
* dev keys
* example
=> feat: add moonbeam support

ethers-solc/Cargo.toml
does what it says on the tin 😂
=> fix: specify home-dep as non-wasm instead of x86-only

ethers-solc/src/lib.rs
=> feat(solc): add clean up function

ethers-solc/src/cache.rs, ethers-solc/src/lib.rs
=> docs: more docs and verbose tracing

ethers-solc/src/compile.rs
=> fix(solc): add allow paths to async compile

.github/workflows/ci.yml
=> ci: bump solc 0.8.10

ethers-solc/src/artifacts.rs, ethers-solc/src/lib.rs
Adding some helpers for EvmVersion. Those will be useful when configuring the `SolcConfig` before compiling a `Project`. This is the `ethers-rs` PR to fix https://github.com/gakonst/foundry/issues/202
=> fix: naming and default impl

.github/workflows/ci.yml
we install solc multiple times sigh
=> ci: bump solc everywhere

Cargo.lock, ethers-solc/Cargo.toml, ethers-solc/src/artifacts.rs, ethers-solc/src/config.rs, ethers-solc/src/error.rs, ethers-solc/src/lib.rs, ethers-solc/src/mock.rs, ethers-solc/src/project_util.rs, ethers-solc/tests/project.rs
Add utils for `ethers-solc` to easily create temp workspaces we can also use in foundry.
=> feat(solc): add workspace utils

Cargo.lock, ethers-core/Cargo.toml, ethers-core/src/abi/human_readable.rs
Bumps Ethabi to support user defined error types https://github.com/rust-ethereum/ethabi/pull/251. Release is not out yet https://github.com/rust-ethereum/ethabi/issues/252
=> feat: new ethabi for error types

ethers-solc/src/config.rs, ethers-solc/src/remappings.rs
=> chore(solc): add display impl for PathsConfig

ethers-solc/src/compile.rs
New release https://github.com/ethereum/solidity/releases/tag/v0.8.11
no breaking changes
=> chore(solc): bump latest solc version

Cargo.lock, ethers-contract/ethers-contract-abigen/Cargo.toml, ethers-contract/ethers-contract-abigen/src/lib.rs, ethers-contract/ethers-contract-abigen/src/util.rs
scan folder recursively to make it compatible with `ethers-solc` artifacts output
=> feat(abigen): search json recursively

ethers-solc/src/cache.rs, ethers-solc/src/lib.rs, ethers-solc/src/utils.rs
provide more context in traces to make debugging easier
=> chore(solc): more verbose traces

ethers-solc/src/artifacts.rs
https://docs.soliditylang.org/en/v0.8.10/natspec-format.html#user-documentation
=> fix(solc): devdoc methods is object

ethers-signers/README.md
links were broken & added `trezor` item to list
=> update ethers-signers README links

ethers-solc/src/resolver.rs
detect, but allow cyclic imports,
tested against https://github.com/nftlabs/nftlabs-protocols
=> fix(solc): allow cyclic imports

ethers-solc/src/artifacts.rs
Add various helper types for dealing with contract's bytecodes
=> feat(solc): add more contract utility types and functions

ethers-solc/src/config.rs, ethers-solc/src/lib.rs
Some foundry tooling needs to check if allowed lib paths is empty
Implement the method
=> Implement `is_empty` for `AllowedLibPaths`

Cargo.lock, ethers-contract/ethers-contract-derive/src/abigen.rs, ethers-contract/ethers-contract-derive/src/call.rs, ethers-core/src/abi/human_readable.rs
fix ethabi breaking change on master
=> chore(deps): bump ethabi master

ethers-providers/src/transports/mod.rs
=> chore: silence unused ws macro

Cargo.lock, ethers-providers/src/provider.rs, ethers-solc/src/resolver.rs
somehow an ignored test broke...
=> chore(deps): bump solang

examples/uniswapv2.rs
=> Docs: add abigen uniswapv2 example

ethers-solc/src/compile.rs, ethers-solc/src/resolver.rs
Ref https://github.com/gakonst/foundry/issues/442
take lock in tests when installing a missing solc.
=> fix(solc): take installer lock before installing

ethers-solc/src/remappings.rs
Add same derives to RelativeRemapping
=> chore(solc): add ord derive

ethers-solc/src/cache.rs, ethers-solc/src/compile.rs, ethers-solc/src/config.rs, ethers-solc/src/error.rs, ethers-solc/src/lib.rs, ethers-solc/src/project_util.rs, ethers-solc/src/remappings.rs, ethers-solc/tests/project.rs
**Breaks Interface**
**Do not merge until** https://github.com/gakonst/foundry/pull/297 is ready
=> chore(solc): add more convenience functions

ethers-providers/Cargo.toml
resolves an issue discussed here: https://github.com/gakonst/foundry/pull/605
=> fix(ethers-providers): make http crate required

ethers-solc/src/artifacts.rs, ethers-solc/src/config.rs
Ref PR https://github.com/gakonst/foundry/pull/644
Ref Issue https://github.com/gakonst/foundry/issues/611
They should be written to file, only if selected on settings. But it still doesn't feel good to be here... Suggestions?
=> feat/ethers-solc: write outputs (asm, ir...) to file, if selected

Cargo.lock, ethers-solc/src/resolver.rs
=> fix(solc): bump solang

ethers-etherscan/Cargo.toml
=> fix: bump ethers-solc version

ethers-solc/src/compile/project.rs
=> chore: rm no longer necessary todo

CHANGELOG.md, ethers-core/src/types/chain.rs, ethers-etherscan/src/lib.rs
Add Arbitrum mainnet and testnet to the list of known chains/block explorers
=> feat(chain): add arbitrum support

ethers-solc/src/artifact_output.rs, ethers-solc/src/artifacts.rs
=> feat: implement Artifact for serde_json

ethers-solc/src/compile/mod.rs, ethers-solc/src/report.rs, ethers-solc/src/resolver.rs
add another message if we fail to resolve a file.
=> feat(solc): report on unresolved imports

ethers-etherscan/src/contract.rs
=> FIX: Revert Constructor Arguments Renaming

ethers-core/src/types/ens.rs
=> chore: cargo --fix

ethers-solc/src/lib.rs, ethers-solc/src/project_util.rs, ethers-solc/tests/project.rs
Add helper functions to compile specific files with the project settings that can be individual source files or even files outside the source dir.
=> feat(solc): add helper functions to compile standalone files

ethers-contract/ethers-contract-abigen/src/lib.rs
=> docs(abigen): improve abigen type docs

ethers-contract/ethers-contract-abigen/src/source.rs, ethers-etherscan/src/contract.rs, ethers-etherscan/src/errors.rs
Close #960
Add a check that returns a more verbose error if contract was not verified
=> feat: add contract code not verified check

ethers-providers/src/provider.rs
Sometimes the resolver returns an empty Bytes.
In those cases we shouldn't go forward, otherwise `decode_bytes` will panic.
=> handle case where the data from the resolver is empty

ethers-solc/src/resolver/mod.rs
Add test to ensure regex capturing of curly bracket import statements works
=> test(solc): add capture test for curly bracket imports

ethers-contract/tests/abigen.rs
Closes #960
Add another test case
=> test(abigen): add etherscan test case

ethers-contract/ethers-contract-abigen/src/multi.rs
don't generate empty shared_types module
=> fix(abigen): dont generate empty shared_types module

ethers-signers/Cargo.toml
=> update trezor-client to v0.0.5 release

ethers-core/src/types/bytes.rs
Parsing hex strings into bytes, serde impl exists.
=> feat(ethers-core/Bytes): impl FromStr

ethers-solc/src/resolver/mod.rs
Skip checksum verification in offline mode
=> fix(solc): respect offline mode

ethers-solc/src/remappings.rs
Additional helper functions to deal with Remapping/RelativeRemapping
=> feat(solc): remapping helper functions

ethers-solc/src/artifacts/mod.rs
Fix https://github.com/gakonst/foundry/issues/897
Comply with solidity json spec
=> fix(solc): use correct types

ethers-solc/src/cache.rs, ethers-solc/src/compile/project.rs
Optimized change detection needs additional work, for example contract level outputs.
Needs followup for contract level output config.
Revert parts of #998
=> revert: use simple change filter again

examples/contract_human_readable.rs
=> fix: use correct artifact api

ethers-solc/src/compile/mod.rs, ethers-solc/src/remappings.rs, ethers-solc/src/report.rs
Add on solc install error report
=> feat: add solc install error report

ethers-core/src/types/log.rs
this is literally just little docstring fixes because i forgot what the transaction receipt address field was and the docstring here said "H160". also fixed 2 typos lol
=> Tiny docstring nitpicks (this sent me on a yellowpaper odyssey, so i'm fixing it for the next poor soul)

.github/workflows/ci.yml, examples/contract_human_readable.rs, examples/moonbeam_with_abi.rs, scripts/examples.sh
Close #1036
<s>apparently the step hang due to missing permissions `chmod +x ./scripts/examples` solved this</s>
Also added a separate build examples step to catch breaking changes, couple of our examples were not working
=> fix(examples): adjust breaking changes and detect failures in ci

ethers-solc/src/compile/mod.rs
new solc release https://github.com/ethereum/solidity/releases/tag/v0.8.13
no breaking changes
=> chore(solc): new 0.8.13 release

ethers-solc/src/project_util/mock.rs, ethers-solc/tests/mocked.rs
Closes #1048
This happened because the test changed _all_ files (sources +libs) regardless of whether lib files were actually used by a source file. 
So the test failed if we changed a lib file that was not needed by a source file, resulting in a skipped compilation.
Modify only files that are used by source files to test that recompilation works.
=> fix(solc): only modify files that are required to compile the project

examples/watch_blocks.rs
I was searching how to get the timestamp and block number from this example and it turns out I need to make another call, so I'm showing this in the example so ppl can find it more easily.
=> Examples/watch_block: show how to retrieve block metadata

ethers-etherscan/src/contract.rs
Given contract source code is not useful in the case of unverified contracts
have the contract_source_code method return an error in the case if the item.abi
has the "Contract source code not verified" string.
Uncomment unit test ignore and run test:
`cargo test --lib ethers-etherscan -- get_error`
=> chore(etherscan): Return error for unverified contracts

ethers-core/src/types/transaction/response.rs
=> fix(core/Transaction): remove debug print

Cargo.lock
Update `svm-rs` and `svm-rs-builds` (Includes the latest `v0.8.13` solc release)
=> chore(ethers-solc): update svm-rs and svm-rs-builds

ethers-core/src/types/transaction/eip2718.rs
=> feat(core/TypedTransaction): add helper for calculating max cost of tx

Cargo.lock
Update svm version (includes 0.8.12 and 0.8.13 metadata for linux-aarch64)
=> chore: update svm

ethers-solc/src/compile/mod.rs
useful to track this down https://github.com/gakonst/foundry/issues/1069
=> chore: add some solc checksum traces

ethers-solc/src/cache.rs, ethers-solc/src/config.rs
Closes #1094 
Includes all project paths in the cache so that changed project paths are detected and trigger a recompile
=> feat(solc): include project paths in cache

Cargo.lock, ethers-solc/Cargo.toml
0.1.11 supports custom error reverts
=> chore(deps): bump solang-parser 0.1.11

ethers-solc/Cargo.toml, ethers-solc/tests/project.rs
Add test to check multiline imports are resolved correctly.
=> test: add multiline flatten test

Cargo.toml
makes it easier to figure out the `legacy` feature is required for certain examples:
```console
cargo run -p ethers --example contract_with_abi                                                                                                                                                                           
error: target `contract_with_abi` in package `ethers` requires the features: `legacy`
Consider enabling them by passing, e.g., `--features="legacy"`
```
=> chore: add examples with required features

ethers-solc/src/report/mod.rs, ethers-solc/src/resolver/mod.rs
only notify the reporter with unique unresolved paths to not spam the reporter implementation
=> fix(solc): only notify about unresolved import once

ethers-etherscan/src/contract.rs, ethers-solc/src/artifacts/mod.rs, ethers-solc/src/lib.rs, ethers-solc/src/resolver/mod.rs
This changes will allows `forge verify-contract` to submit contract verification using `standard-input-json` format to etherscan.
=> feat(solc): Add standard-json-input

Cargo.lock
Issue: https://github.com/gakonst/foundry/issues/1116
Fix: https://github.com/roynalnaruto/svm-rs/pull/40
Now bumping svm-rs version in ethers-rs
=> fix: bump up svm

ethers-core/src/types/fee.rs
reward field of FeeHistory is optional 
https://docs.alchemy.com/alchemy/apis/ethereum/eth_feehistory
=> fix: eth_feehistory reward is optional

ethers-solc/src/config.rs, ethers-solc/src/utils.rs, ethers-solc/tests/project.rs
[Foundry issue #796](https://github.com/foundry-rs/foundry/issues/796)
Introduce consistent spacing on the final flattened string.
CC: @mattsse @onbjerg
=> fix(solc): flatten consistent spacing

ethers-core/src/utils/anvil.rs, ethers-core/src/utils/mod.rs
Adds bindings for https://github.com/foundry-rs/foundry/pull/1037
This is basically a copy of the existing Ganache struct, but I think it will be easier to maintain two separate impl than combining them somehow
=> feat: add anvil bindings

ethers-contract/src/lib.rs
=> feat: make stream mod public

ethers-providers/src/transports/common.rs
Silence dead code warnings for methods only used via some features, allow was the easiest solution here
=> chore: silence unused warnings

ethers-solc/src/compile/mod.rs, ethers-solc/src/compile/project.rs, ethers-solc/src/lib.rs, ethers-solc/src/resolver/mod.rs
async feature no longer required here since we're using svm-rs blocking
=> chore(solc): remove async feature requirement

ethers-solc/src/artifacts/output_selection.rs
If an empty output is requested, we're currently providing:
`"Contract.sol": {}`
however the docs say
> Contract level (needs the contract name or "*")
this makes sure that an empty output selection for a file is always serialized as `"*": []`, which means "for all contracts in this file, include nothing in the output"
=> fix(solc): use correct empty output selection

ethers-etherscan/src/errors.rs, ethers-etherscan/src/lib.rs
Adds a `ClientBuilder` to configure the etherscan client
=> feat(etherscan): add ClientBuilder type

ethers-core/src/utils/moonbeam.rs
=> chore(core): update moonbeam url

Cargo.lock, ethers-etherscan/Cargo.toml, ethers-etherscan/src/errors.rs, ethers-etherscan/src/lib.rs, ethers-etherscan/src/utils.rs
[Foundry Issue #1567](https://github.com/foundry-rs/foundry/issues/1567)
Added ability to lookup solc version with build metadata
=> feat(etherscan): lookup solc build metadata

ethers-contract/ethers-contract-abigen/src/contract/methods.rs, ethers-contract/ethers-contract-abigen/src/rawabi.rs
Don't generate deploy functions if bytecode is empty (`bin: "0x"`)
=> fix: filter out empty bytecode

ethers-solc/src/compile/output/contracts.rs, ethers-solc/src/compile/output/mod.rs, ethers-solc/src/compile/output/sources.rs
Add missing functions to strip/join paths of sources and contracts
cc @onbjerg
=> feat(solc): add strip and join functions to sources and contracts

ethers-core/src/types/block.rs
Add missing Deserialize impl for `BlockId`
=> feat: add eip-1898 deserialize for BlockId

Cargo.lock, ethers-solc/Cargo.toml, ethers-solc/src/resolver/parse.rs, ethers-solc/src/utils.rs
=> fix(dep): update & lock solang

CHANGELOG.md, ethers-providers/src/provider.rs, ethers-providers/src/pubsub.rs, examples/subscribe_logs.rs
Load previous logs and stream it back to the user before establishing
a new stream for streaming future logs.
Closes #988
=> feat(providers): load previous logs before subscribing

ethers-solc/src/artifact_output/configurable.rs, ethers-solc/src/compile/output/mod.rs
include the `id` in the artifact in order to recover the `SourceFile` of the artifact
=> feat(solc): include id in artifact

ethers-contract/src/log.rs, ethers-contract/tests/common/derive.rs, ethers-core/src/abi/human_readable/lexer.rs, ethers-core/src/abi/struct_def.rs, ethers-core/src/types/block.rs, ethers-core/src/types/log.rs, ethers-core/src/types/proof.rs, ethers-core/src/types/signature.rs, ethers-core/src/types/trace/filter.rs, ethers-core/src/types/trace/mod.rs, ethers-core/src/types/transaction/eip2718.rs, ethers-core/src/types/transaction/eip2930.rs, ethers-core/src/types/transaction/response.rs, ethers-core/src/types/txpool.rs, ethers-providers/src/erc.rs, ethers-signers/src/wallet/mnemonic.rs, ethers-solc/src/compile/output/sources.rs, ethers-solc/src/remappings.rs, ethers-solc/src/resolver/parse.rs, ethers-solc/src/sourcemap.rs
fix new clippy lints on nightly `cargo +nightly clippy --fix --all-features -Z unstable-options`
=> chore(clippy): fix newest nightly lints

ethers-solc/src/report/mod.rs
make it easier to get a solc compiler in/out dump, install the `SolcCompilerIoReporter` by default in the basic reporter
=> feat(solc): install solc io reporter in basic reporter

ethers-solc/src/artifacts/mod.rs
Closes #1303
remove viaIR for pre 0.7.5
=> fix(solc): remove viaIR for older versions

ethers-providers/src/pending_escalator.rs, ethers-providers/src/pending_transaction.rs
All PRs are getting littered with github actions warning annotations
Fix the warnings
=> chore: fix wasm warnings

CHANGELOG.md, ethers-core/src/types/transaction/eip2718.rs
`as_*_ref` are already implemented but `as_*_mut` were missing
=> feat(core): Add `as_*_mut` methods on `TypedTransaction`

.cargo/audit.toml, .github/workflows/audit-on-push.yml
There are currently active [security advisories](https://gist.github.com/Genysys/3fc5201beed276e399d7b2edb974751c) on the repo. It would be great to have them actively monitored in order to remediate them. 
- Add `audit-on-push.yaml` to run `cargo-audit`
=> feat(ci): adds cargo audit workflow

ethers-solc/src/remappings.rs
Closes https://github.com/foundry-rs/foundry/issues/1797
fixes an edge case for nested contract dirs: `src/lib`
having contracts in `src/lib/A.sol` and `src/B.sol` could lead to a wrong remapping with the name `lib`.
this is fixed by adding an additional check
=> fix(solc): improve remappings autodetection

ethers-core/src/types/block.rs
=> feat: add display impl for BlockNumber

ethers-etherscan/Cargo.toml
`ethers-solc` only used for tests
=> chore(deps): make ethers-solc dev dep

ethers-core/src/types/transaction/response.rs
adds lossless serde roundtrip test for a tx receipt for a contract creation tx against an alchemy receipt
Ref https://github.com/foundry-rs/foundry/issues/1874
=> test: add tx receipt roundtrip test

Cargo.lock, ethers-solc/Cargo.toml
use latest solang-parser release
=> chore(deps): bump solang_parser 0.1.14

ethers-core/src/types/block.rs
add some convenience impls for `BlockNumber`
=> chore: add blocknumber convenience impls

ethers-middleware/src/signer.rs
The previous behavior never changes the tx chain id if it is `None`, since the tx is cloned inside the match statement.
Move the tx clone outside the match statement.
Adds a test setting the tx chain id to `None`, with a `1337` chain id on the signer, ensuring that the transaction encoding and signature are changed properly.
=> fix(middleware): use signer chain when tx is None

ethers-core/Cargo.toml
This PR bumps ethabi version required to close https://github.com/foundry-rs/foundry/issues/1432 .
=> chore: bump ethabi version

ethers-core/src/types/transaction/response.rs
ensure we're serializing/deserializing tx lossless and nonce correct
Ref https://github.com/foundry-rs/foundry/issues/1868
0 nonce is serialized as `0x0` https://github.com/foundry-rs/foundry/issues/1868#issuecomment-1156440633
=> test: add tx serde roundtrip test

ethers-solc/src/compile/mod.rs
update test to latest solc release https://github.com/ethereum/solidity/releases/tag/v0.8.15
=> chore: update latest solc release test

ethers-middleware/tests/gas_oracle.rs
fix test to use the initial base fee of 1000000000
=> test: use default initial base fee

Cargo.lock, ethers-solc/Cargo.toml
solc `v0.8.15` was added in the latest release of `svm-rs`, hence updating here.
=> chore: update svm-rs and svm-rs-builds

ethers-providers/src/provider.rs
previously `feeHistory` was evaluated with `Result::or` so both versions where executed regardless, which is redundant all newer cases.
only send fallback serialization request if first attempt resulted in an error
=> perf: only fallback to old feeHistory request on error

ethers-core/src/types/chain.rs
=> fix: add missing chain id match arms

Cargo.lock, ethers-solc/Cargo.toml
The latest `svm-rs` includes installing `solc` binary from zip files, specifically for windows machines and solc <= 0.7.1
- https://github.com/roynalnaruto/svm-rs/pull/50
=> chore: update svm-rs

ethers-core/src/abi/human_readable/lexer.rs, ethers-core/src/types/block.rs, ethers-core/src/types/trace/mod.rs
add human readable function parser, also ran clippy fix
needs followup to phase out `ethabi::Reader`
=> feat: add human readable function parser

ethers-contract/tests/abigen.rs, ethers-core/src/abi/codec.rs, ethers-core/src/abi/mod.rs, ethers-core/src/abi/tokens.rs, ethers-core/src/types/bytes.rs
add some missing imples for the `ethers::Bytes` new type
=> chore(core): convenience impls for Bytes

ethers-core/src/types/transaction/eip2718.rs
add util function to return mut gas so we can do `tx.gas_mut().take()`
=> chore: add gas_mut function

ethers-solc/src/compile/output/contracts.rs, ethers-solc/src/compile/output/mod.rs
Add more iterator options for `VersionedContracts` and make them available on `AggregatedCompilerOutput`.
=> feat(solc): add more contract iter helper functions

ethers-solc/src/artifacts/mod.rs
when applying the `base_path` also strip it from the model_checker's paths
=> fix(solc): apply base path to model checker contracts

ethers-core/src/types/transaction/response.rs
impl `Ord` for TransactionReceipt that compares block number and index in transaction
=> feat(core): impl Ord for receipt

ethers-contract/src/event.rs
clarify stream function difference
=> docs(contract): improve EventStream docs

Cargo.lock, ethers-solc/Cargo.toml
upgrade solang for use in foundry formatter
=> chore(deps): solang 0.1.16

ethers-core/src/utils/anvil.rs
allow setting the fork-block-number explicitly
=> feat: add --fork-block-number setter for anvil bindings

ethers-etherscan/src/lib.rs
add Sepolia endpoint
- https://docs.etherscan.io/getting-started/endpoint-urls
I want to verify contract on Sepolia test network using foundry
=> feat: add Sepolia endpoint

ethers-solc/tests/project.rs
=> chore(clippy): make clippy happy

Cargo.lock, ethers-solc/Cargo.toml
=> chore: bump svm-rs-builds

ethers-core/src/abi/human_readable/lexer.rs
Closes https://github.com/foundry-rs/foundry/issues/2176
`abi-encode constructor(...)` failed to parse the function
while this is not entirely correct to parse constructor as `Function` it severely simplifies things
=> fix: parse constructor as function

ethers-core/src/utils/anvil.rs, examples/anvil_fork.rs
provide a way to set the path to the anvil executable, and add forking example
=> chore: add Anvil::at and anvil example

ethers-solc/src/artifact_output/configurable.rs, ethers-solc/src/lib.rs
Closes #1495 
fix broken links
=> docs: fix broken doc links

examples/geth_trace_transaction.rs
=> fix: only run tracing example if env var is set

ethers-contract/tests/it/abigen.rs, ethers-contract/tests/solidity-contracts/sale.json, ethers-core/src/abi/codec.rs, ethers-core/src/abi/mod.rs, ethers-core/src/abi/tokens.rs
bump tuple limit in macros to support rather large types
=> feat: bump abi/token tuple limit

Cargo.lock, ethers-solc/Cargo.toml
this should finally fix failing docs.rs builds -.-
=> chore(deps): bump svm-builds

ethers-core/src/types/serde_helpers.rs, ethers-core/src/types/transaction/eip712.rs
in #[1510](https://github.com/gakonst/ethers-rs/pull/1510) some things required edition 2021, this makes it compatible with 2018 again
=> fix: make compatible with edition2018

ethers-core/src/types/chain.rs
=> fix: add missing moonbase fromstr

ethers-signers/src/wallet/mod.rs
=> Fix CI: Lint

.github/workflows/ci.yml, ethers-contract/ethers-contract-abigen/src/contract/structs.rs, ethers-contract/ethers-contract-abigen/src/multi.rs, ethers-contract/ethers-contract-abigen/src/rawabi.rs, ethers-contract/ethers-contract-abigen/src/util.rs, ethers-contract/ethers-contract-derive/src/utils.rs, ethers-contract/tests/it/common/mod.rs, ethers-contract/tests/it/contract.rs, ethers-core/src/abi/struct_def.rs, ethers-core/src/types/i256.rs, ethers-etherscan/src/account.rs, ethers-etherscan/src/gas.rs, ethers-etherscan/src/transaction.rs, ethers-middleware/src/signer.rs, ethers-middleware/tests/gas_oracle.rs, ethers-providers/src/transports/ws.rs, ethers-signers/src/wallet/mod.rs, ethers-signers/src/wallet/private_key.rs, ethers-solc/src/cache.rs, ethers-solc/src/filter.rs
remove pinned nightly for lint job that was added due to a regression 72dfc52ec041f4368a00aa9a27305f777ec710d8
fix clippy lints: `cargo +nightly clippy --fix -Z unstable-options`
=> ci: rm pinned nightly

ethers-solc/src/report/mod.rs, ethers-solc/src/resolver/mod.rs
Closes https://github.com/foundry-rs/foundry/issues/2526
improve output:
* only include remappings once
* include file paths where occurred in
=> refactor(solc): improve error message for unresolved imports

Cargo.lock, ethers-solc/Cargo.toml
=> dep(solang-parser): 0.1.17

ethers-solc/src/config.rs
add helper function(s) to check whether a file is part of a library
https://github.com/foundry-rs/foundry/pull/2504
cc @onbjerg
=> feat(solc): add lib inclusion function

ethers-providers/src/provider.rs
add helper function to set interval without consuming the Provider
=> feat: add set_interval helper function

ethers-core/src/abi/codec.rs, ethers-core/src/abi/mod.rs
add Abi related trait impls to `str` where possible
=> feat(abi): add missing str abi trait impls

ethers-contract/src/lib.rs
#1564 followup with reports of filters
=> chore(abigen): reexport filter

ethers-contract/ethers-contract-abigen/src/filter.rs
auto import failed me and selected the wrong Regex -.-
=> fix(abigen): use correct str Regex

ethers-solc/src/remappings.rs
make errors more useful
ref https://github.com/foundry-rs/foundry/issues/2626
=> chore(solc): improve remapping errors

ethers-signers/src/wallet/mod.rs, ethers-signers/src/wallet/private_key.rs
I needed clone for other DigestSigner implementation, and this simplifies the code.
Derive Clone on Wallet
=> Derive Clone on Wallet

ethers-etherscan/src/lib.rs
add missing aurorascan/etherscan API endpoints
=> chore: add aurora etherscan endpoints

README.md
There was a typo on the README.md file
Change "...ensure your code *if* properly formatted with..." to "...ensure your code *is* properly formatted with..."
Not necessary (I think), just a single-character typo :)
=> fix: typo on README.md

ethers-solc/src/compile/mod.rs
new release, no breaking changes that concern ethers-solc https://github.com/ethereum/solidity/releases/tag/v0.8.16
=> chore: update max solc version 0.8.16

ethers-core/src/types/trace/filter.rs
https://github.com/foundry-rs/foundry/issues/2656 shows, `Trace` does not include `error` if null
skip error if None
=> chore: skip none trace error

Cargo.lock, ethers-solc/Cargo.toml
Update SVM crates (svm-rs and svm-rs-builds) which include support for solc v0.8.16.
=> chore: update svm crates

ethers-solc/src/project_util/mod.rs, ethers-solc/tests/project.rs
make it easy to checkout and compile a repo via `TempProject`
useful for writing tests for https://github.com/gakonst/ethers-rs/pull/1567
cc @onbjerg
=> feat(solc): add helper to checkout temp projects

ethers-solc/src/project_util/mod.rs, ethers-solc/tests/project.rs
fixes failing test introduced in https://github.com/gakonst/ethers-rs/pull/1580 by correctly stripping `.sol` suffix from contract name /file anme
=> fix(solc): strip .sol suffix

ethers-core/src/types/chain.rs, ethers-etherscan/src/lib.rs
move etherscan URLs to `Chain` impl so they can be used on its own.
required for https://github.com/foundry-rs/foundry/pull/2616
* add `Chain::etherscan_urls` function
=> feat: add etherscan urls function

ethers-core/src/types/trace/mod.rs
Forge also needs PartialEq on TraceType.
I was too dumb to see this the first time, so I had to make two PRs. Sorry.
Add PartialEq to TraceType
=> feat(TraceType+PartialEq): added PartialEq to TraceType

ethers-solc/src/project_util/mod.rs
add project-util helper functions to create test/script contract files
=> feat(solc): add missing helper functions

ethers-solc/tests/project.rs
Add test for https://github.com/foundry-rs/foundry/issues/2726
ensure changing the optimizer triggers rebuild
=> test(solc): ensure trigger rebuild on settings change

ethers-etherscan/src/lib.rs
add smol helper to adjust cache path
=> chore(etherscan): add set cache helper

ethers-solc/src/error.rs, ethers-solc/src/resolver/mod.rs
Improve error if we try to read a file from a bad symlink
add new error variant
=> chore(solc): improve io error for bad symlinks

ethers-etherscan/src/source_tree.rs
Some paths from Etherscan may be absolute and just doing `output_directory.join(sanitized_path)` replaces the entire output path with the absolute path from Etherscan.
Strip the leading `/` from absolute paths, forcing them to be relative.
See https://github.com/foundry-rs/foundry/issues/2792
=> fix: sanitize absolute paths from etherscan

ethers-core/src/types/trace/geth.rs
https://github.com/foundry-rs/foundry/pull/2868
=> feat(core): more derives for geth trace structs

ethers-contract/tests/it/abigen.rs, ethers-contract/tests/solidity-contracts/large_tuple.json
Add test that abigen! can handle large tuples
ref https://github.com/gakonst/ethers-rs/issues/1640
=> test: add large tuple test

Cargo.lock, ethers-signers/Cargo.toml
=> chore: bump eth-keystore

ethers-solc/src/artifacts/mod.rs
Closes https://github.com/foundry-rs/foundry/issues/3012
use correct model for `metadata.settings.libraries`, which differs from `input.settings.libraries`
=> fix(solc): use correct model for metadata libraries

ethers-solc/src/artifacts/mod.rs
address [foundry#2996](https://github.com/foundry-rs/foundry/issues/2996)
serialize `viaIR` entry in `MetadataSettings`
=> fix(solc): serialize `viaIR` setting

ethers-core/src/types/chain.rs
support `from_str("mumbai") => Chain::PolygonMumbai`
=> chore: match standalone mumbai for chain

ethers-contract/ethers-contract-abigen/src/contract.rs, ethers-contract/ethers-contract-abigen/src/contract/structs.rs, ethers-contract/ethers-contract-abigen/src/lib.rs, ethers-contract/src/lib.rs
export types required for fixing https://github.com/foundry-rs/foundry/issues/2722
=> chore: export abi related types

CHANGELOG.md, Cargo.toml, ethers-contract/Cargo.toml
https://t.me/ethers_rs/20102?thread=20045
Add `abigen` to the default features in `ethers` and `ethers-contract`
=> chore: add abigen to default features

ethers-solc/src/compile/mod.rs
https://blog.soliditylang.org/2022/09/08/solidity-0.8.17-release-announcement/
no model changes
=> chore: bump max solc 0.8.17

ethers-etherscan/src/lib.rs
provide a way to see the response if we failed to deserialize it into a json `Response`
this will make it possible to see the response if it's not a json Error object, which apparently can happen: Ref https://github.com/foundry-rs/foundry/issues/3209
=> chore(etherscan): log response data on error

ethers-etherscan/src/errors.rs, ethers-etherscan/src/lib.rs
add another error variant to handle `Sorry, you have been blocked by Cloudflare` error
=> feat(etherscan): add blocked by cloudflare error

Cargo.lock, examples/ethers-wasm/.gitignore, examples/ethers-wasm/Cargo.toml, examples/ethers-wasm/README.md, examples/ethers-wasm/package.json, examples/ethers-wasm/src/lib.rs, examples/ethers-wasm/webpack.config.js, examples/ethers-wasm/yarn.lock
Compilation always failed for `examples/ethers-wasm` with deprecation warning and missing features
- bump all crates and yarn deps
- add `serde_wasm_bindgen`
- add Anvil script and update README
- add missing console feature from `websys`
- fmt
tested on Win 10 with anvil and yarn
=> fix: WASM example

ethers-contract/src/contract.rs, ethers-core/src/types/ens.rs, ethers-core/src/types/transaction/eip2718.rs, ethers-core/src/types/transaction/request.rs, ethers-middleware/src/transformer/ds_proxy/mod.rs, ethers-providers/src/ens.rs, examples/ens.rs
@gakonst https://t.me/ethers_rs/20599
- fix `impl Encodable for NameOrAddress` wrong cmp order
- add as_X -> X by cloning to NameOrAddress
- add to_addr to TransactionRequest
- add more impls and cleanup
=> feat(core): add utility methods to NameOrAddress

ethers-core/src/types/chain.rs, ethers-etherscan/src/lib.rs
=> feat: add arbitrum-goerli

ethers-contract/src/contract.rs, ethers-contract/src/factory.rs
https://t.me/ethers_rs/20735?thread=20735
=> contract: return `Arc<M>` instead of `&M`

ethers-core/src/types/transaction/eip2718.rs, ethers-core/src/types/transaction/request.rs
Closes #1732
fixes some issues around signed transaction rlp decoding.
* Use conditional stream size depending on chain_id
* fix `TypedTransaction::decoded_signed` to support legacy transactions: replace the wrong `is_data()` check and treat lists as legacy transactions
cc @Rjected 
imo the rlp decode_unsigned/decode_signed are a bit confusing. especially since the unsiged variant is the default, which would lead to wrong chain ids (37 instead 1 for mainnet). Not sure what to do about it.
need to make this very clear in the docs at least.
=> fix: legacy signed rlp decoding

ethers-core/src/types/chain.rs
drop polygon- prefix from Chain::Mumbai display impl
=> chore: format polygon-mumbai as mumbai

ethers-core/src/types/transaction/response.rs
forgot to remove an unwrap used while debugging
=> chore: rm unwrap

ethers-solc/src/compile/output/mod.rs
add helper function to iterate over artifact+version
=> feat(solc): add versioned artifacts helper

ethers-etherscan/Cargo.toml, ethers-etherscan/src/contract.rs, ethers-etherscan/src/lib.rs, ethers-etherscan/src/utils.rs, ethers-etherscan/src/verify.rs
=> feat(etherscan): parse SourceCode field

ethers-core/src/utils/units.rs
Refs: #1746 
Have added other units such as macro, kilo, tera, babbage, shannon, etc.
-   [X] Added Tests
=> feat: added more ethereum units

ethers-contract/ethers-contract-abigen/src/lib.rs
Closes #1770
we used the file stem when generating from file which can contain `.t`, `.sol`
drop everything after first `.`
=> fix(abigen): remove trailing test,script markers

ethers-solc/src/project_util/mock.rs
fix compile issue, re `Box<dyn>`
=> fix: impl default manually for mock project

ethers-solc/src/artifacts/mod.rs
Solidity 0.8.18 (unreleased) will introduce an option to completely remove the CBOR metadata from the bytecode. This PR adds that option here.
See `appendCBOR` in https://docs.soliditylang.org/en/develop/using-the-compiler.html#input-description
Needed by https://github.com/foundry-rs/foundry/pull/3481
=> Add option to disable CBOR metadata in bytecode.

ethers-core/src/types/mod.rs
make this accessible, useful for H256 <-> U256 conversions
cc @rkrasiuk 
=> chore: reexport BigEndianHash

ethers-contract/src/multicall/mod.rs, ethers-core/src/types/chain.rs, ethers-etherscan/src/lib.rs
Gnosis launched a new testnet called Chiado
Adding support to Chiado testnet
=> Adding chiado support

ethers-contract/src/multicall/mod.rs
=> fix Build issue

ethers-core/src/types/mod.rs
=> Expose U512 among `ethers-core::types`

CHANGELOG.md, Cargo.lock, ethers-core/Cargo.toml, ethers-core/src/utils/mod.rs
Fixes #1822.
For function `parse_units` replace usage of `rust_dec::Decimal` with alternative.
=> Fixes: #1822

.github/workflows/ci.yml
ref https://github.com/gakonst/ethers-rs/pull/1808#issuecomment-1291091964
blocked by #1808 for docs CI, #1812 for lints CI
=> ci: add doc CI

ethers-core/src/types/trace/filter.rs
ref https://github.com/foundry-rs/foundry/issues/3552
add error enum for the `error` field in `Trace`
=> feat: add TraceError enum

Cargo.toml, ethers-contract/src/multicall/mod.rs, ethers-core/src/types/mod.rs, ethers-core/src/utils/mod.rs, ethers-middleware/tests/signer.rs, scripts/examples.sh
should fix ~all~ most broken CI from last commits;
see https://github.com/gakonst/ethers-rs/pull/1844#issuecomment-1308126811 for failing txpool test;
~looks like [here](https://github.com/gakonst/ethers-rs/actions/runs/3425007628/jobs/5705345370) different tests sent transactions too close to eachother, but it doesn't happen always~ https://github.com/gakonst/ethers-rs/pull/1847#issuecomment-1308703933
=> fix: failing CI

ethers-solc/src/utils.rs
https://github.com/gakonst/ethers-rs/actions/runs/3433299836/jobs/5723485668
#1812: 
Cannot replicate locally, I assume it was just a nightly clippy bug
=> fix: broken regex

ethers-providers/src/transports/retry.rs
=> fix: better retry timing

ethers-contract/ethers-contract-abigen/src/multi.rs
<!--
Summarize the solution and provide any necessary context needed to understand
the code change
closes:#1867
=> fix(abigen): make compatible with older rust versions

ethers-providers/src/transports/retry.rs
Add additional retry check. Discovered here https://github.com/foundry-rs/forge-std/actions/runs/3522606847/jobs/5905780661
cc @mds1
=> feat: add another rate limit retry check

ethers-core/src/utils/mod.rs
Add missing, useful derive impls for ParseUnit
=> chore: add missing ParseUnit impls

ethers-providers/src/transports/retry.rs
some providers send invalid JSON RPC in error case `id = null`.
this will handle the serde error and try to extract the JsonRpcError and whether to retry.
cc @mds1
=> feat(provider): check for serde error with missing req id

ethers-contract/ethers-contract-abigen/src/multi.rs
=> fix(abigen): rm wrong brackets

ethers-core/src/types/chain.rs
Should I update changelog for such a small change?
=> feat: impl Serialize for Chain

ethers-providers/src/transports/retry.rs
Add another rate limit related error code
=> feat: add infura error code to retry detection

ethers-signers/src/aws/mod.rs
https://github.com/foundry-rs/foundry/issues/67#issuecomment-1335669167
Changed the AwsSigner so that it no longer borrows the KmsClient
cc @prestwich 
=> refac: change awsSigner to own kmsclient

.github/PULL_REQUEST_TEMPLATE.md
With the current PR template contributors cannot specify if a new feature is backward compatible.
I updated the PR checklist to include the "breaking changes" checkbox. This can help maintainers to better organize the CHANGELOG, and have a better overview of incoming changes.
=> ci: Added a new checkbox to the PR checklist

CHANGELOG.md, ethers-contract/src/multicall/mod.rs, ethers-contract/tests/it/contract.rs
=> add_calls and call_array for Multicall

ethers-core/src/utils/geth.rs
make it configurable whcih geth bin to use.
=> feat: make geth executable configurable

CONTRIBUTING.md
=> (docs): add clippy command

Cargo.toml
`ethers-etherscan/ethers-solc` can't get enabled from `ethers`
https://t.me/ethers_rs/23359
=> fix: ethers-etherscan solc feature

ethers-etherscan/src/contract.rs, ethers-etherscan/src/utils.rs
=> fix(etherscan): source code ser/de

ethers-solc/src/artifacts/ast/mod.rs
Some additional cleanup required to unblock https://github.com/foundry-rs/foundry/pull/3899
=> fix: reexport some ast types again

.pre-commit-config.yaml
broken file introduced in #1942
=> chore: rm broken pre commit yaml

ethers-solc/src/artifacts/ast/mod.rs
last AST revert PR...
foundry build now passes with patched ethers, should have done this the first time...
this was a bit annoying
=> fix: reexport SourceLocation

.gitignore
https://github.com/gakonst/ethers-rs/pull/1972
=> chore: gitignore .pre-commit-config.yaml

ethers-middleware/src/gas_oracle/mod.rs, ethers-middleware/src/gas_oracle/polygon.rs
Fixes https://github.com/foundry-rs/foundry/issues/3973
Introduced here https://github.com/gakonst/ethers-rs/pull/1944
use correct U256 constant
cc @DaniPopes 
=> fix: gwei wei wrong u256 constant

ethers-solc/benches/compile_many.rs, ethers-solc/src/artifacts/ast/mod.rs, ethers-solc/src/compile/mod.rs, ethers-solc/src/resolver/mod.rs, examples/middleware/examples/create_custom_middleware.rs
=> chore: clippy

examples/middleware/examples/builder.rs
=> fix(examples): deprecated gas oracle

ethers-contract/ethers-contract-abigen/Cargo.toml, ethers-contract/ethers-contract-derive/Cargo.toml, ethers-core/Cargo.toml, ethers-core/ethers-derive-eip712/Cargo.toml, ethers-etherscan/Cargo.toml, ethers-middleware/Cargo.toml, ethers-providers/Cargo.toml, ethers-signers/Cargo.toml, ethers-solc/Cargo.toml, examples/ethers-wasm/Cargo.toml
=> chore: update all rust editions to 2021

ethers-solc/src/error.rs, ethers-solc/src/resolver/mod.rs, ethers-solc/src/utils.rs
Ref https://github.com/foundry-rs/foundry/issues/4003
path resolution is platform dependent and can be case-sensitive.
This adds another check to improve the error message in such cases 
=> feat(solc): improve error on case mismatch

ethers-contract/src/contract.rs, ethers-contract/src/event.rs, ethers-contract/src/stream.rs
=> fix(contract): doctests

book/SUMMARY.md, book/providers/mock.md, examples/README.md, examples/providers/examples/mock.rs, examples/providers/examples/ws.rs
=> docs: mock-provider

ethers-solc/src/compile/mod.rs
fixes #2004 
Need some guidance on creating test(s) and updating docs
=> fixed issue#2004 parsing solc verison with trailing newlines

ethers-etherscan/src/lib.rs
Etherscan allows 1 request per 5 seconds if the API key is not defined
Make API key optional
=> feat(etherscan): Allow `ClientBuilder` to create `Client` without API key

ethers-contract/src/call.rs
wasm futures are not Send
https://github.com/gakonst/ethers-rs/actions/runs/4028701493/jobs/6925861112
=> fix: add cfg to IntoFuture preventing Send

ethers-core/src/types/log.rs
=> feat: add convenience impl From Log

ethers-contract/ethers-contract-abigen/src/contract/common.rs, ethers-contract/ethers-contract-abigen/src/contract/errors.rs, ethers-contract/ethers-contract-abigen/src/contract/events.rs, ethers-contract/ethers-contract-abigen/src/contract/methods.rs, ethers-contract/ethers-contract-abigen/src/contract/structs.rs, ethers-contract/ethers-contract-abigen/src/util.rs
=> refactor(abigen): inline docs

ethers-core/src/types/block.rs, ethers-core/src/types/ens.rs
Upstreaming from foundry-cli/cast helper parsers
=> feat(core): more type parsing

ethers-core/src/types/other.rs
allows to actually insert something here
=> feat: add DerefMut for OtherFields

ethers-solc/src/compile/mod.rs
bumps latest solc version test.
all the failing test jobs are horrible because we continue to miss things like this.
=> chore: bump solc test 0.8.18

ethers-core/src/types/trace/geth.rs
add some from impls for new enums
=> chore: add convenient from impls

ethers-etherscan/src/errors.rs, ethers-etherscan/src/lib.rs
=> chore: add etherscan page not found error

ethers-core/src/types/chain.rs
Closes #2124
use arbiscan URLs since others are down
closes https://github.com/foundry-rs/foundry/issues/4302
=> chore: use arbiscan urls for arbitrum goerli

ethers-contract/ethers-contract-derive/src/lib.rs
Human readable ABI example was missing.
Added an example.
This fixes #2134
=> abigen: Add human readable ABI example in documentation

ethers-core/src/utils/geth.rs
Introduce additional config to enable debug api endpoint.
=> Start Geth with debug api endpoint 

ethers-core/src/types/chain.rs, ethers-etherscan/src/lib.rs
#2171 was merged without rustfmt. This formats the changes
=> fmt: run rustfmt

Cargo.lock, ethers-solc/Cargo.toml, ethers-solc/src/compile/mod.rs
includes 0.8.19 
cc @roynalnaruto 
=> chore: bump svm-rs

Cargo.lock
fix locked broken svm-rs release
=> chore: update svm in Cargo.lock

ethers-etherscan/src/utils.rs
[ethereum/solc-bin](https://github.com/ethereum/solc-bin):
> The content is mirrored to https://binaries.soliditylang.org/ where it can be easily downloaded over HTTPS without any authentication, rate limiting or the need to use git.
=> feat(etherscan): use binaries.soliditylang.org

README.md
http:// to https:// on Celo link in README.md
=> http:// to https:// on Celo link

ethers-signers/src/wallet/private_key.rs
=> test: add parse pk test

ethers-solc/src/artifacts/mod.rs
add `OptimizerDetails::is_empty` 
=> feat(solc): add is_empty fn for structs of Options

.github/workflows/ci.yml, src/lib.rs
don't builds dep docs
FYI @DaniPopes 
only warn broken doc links, because importing readme from sub crates with doc links breaks.
=> ci: build without deps

.github/workflows/deps.yml, deny.toml
=> fix(deps): allow MIT-0, allow CC0-1.0 exceptions

Cargo.lock, ethers-solc/Cargo.toml
Upgrade solang-parser to `0.2.3`
Ref https://github.com/foundry-rs/foundry/pull/4477
=> dep(solc): solang-parser 0.2.3

ethers-providers/src/rpc/transports/ws/manager.rs, ethers-providers/src/rpc/transports/ws/mod.rs
WsClient wasn't actually Debug: https://github.com/foundry-rs/foundry/actions/runs/4304979076/jobs/7506772579
unclear why this even compiles tbh.
implemented debug manually
=> chore(ws): add some docs and impl debug

ethers-core/src/types/chain.rs
=> feat: add Boba chain

ethers-providers/src/toolbox/log_query.rs
as title, this is a false positive
=> chore: allow clippy false positive

ethers-contract/ethers-contract-derive/src/event.rs
followup to https://github.com/gakonst/ethers-rs/pull/2263#pullrequestreview-1342557925
forgot a `#`...
sorry about that @FrankieIsLost 
=> fix(abigen): fix missing ident #

ethers-solc/src/resolver/mod.rs, ethers-solc/tests/project.rs
Closes https://github.com/foundry-rs/foundry/issues/4594
checks if the file's version is valid
cc @aathan
add check that the requirement is satisfied by at least one known version
=> feat(solc): improve error diagnostic

ethers-solc/Cargo.toml
removed by accident during refactoring
=> fix(solc): features

ethers-contract/src/lib.rs, ethers-core/src/lib.rs
Missed due to build failing either way for the `generic_array` problem. Sorry about this
See: <https://github.com/gakonst/ethers-rs/actions/runs/4546190395/jobs/8014511517>
=> fix: duplicate feature declaration

.git-blame-ignore-revs
=> chore: ignore another rev

ethers/Cargo.toml
=> add legacy-ws feat to meta crate

Cargo.lock, ethers-solc/Cargo.toml, ethers-solc/src/resolver/parse.rs
=> chore: update solang-parser

ethers-solc/src/config.rs, ethers-solc/src/remappings.rs
Temporarily ignore the tests that fail only on windows due to #2347
=> test: ignore windows remapping tests

ethers-core/src/types/serde_helpers.rs
Closes https://github.com/gakonst/ethers-rs/issues/2353
=> test: add deserialize test

ethers-core/src/utils/mod.rs
Fix another clippy lint i introduced to master again
=> lint: clippy return statements

Cargo.lock, ethers-signers/Cargo.toml, ethers-signers/src/ledger/app.rs, ethers-signers/src/trezor/app.rs
Removes cyclical dependency:
`ethers-signers` <-> `ethers-contract(-derive)`
CC @gakonst was this the one that messes up releases?
=> test: remove eip712 tests for ethers-signers

Cargo.lock, Cargo.toml, ethers-providers/Cargo.toml, ethers-signers/Cargo.toml, ethers-solc/Cargo.toml
Fixes [RUSTSEC-2023-0034](https://rustsec.org/advisories/RUSTSEC-2023-0034) ([CI](https://github.com/gakonst/ethers-rs/actions/runs/4841024805/jobs/8627024518?pr=2386))
```sh
cargo upgrade
cargo update
```
=> chore(deps): bump all dependencies

Cargo.lock, ethers/Cargo.toml
The `ethers` crate doesn't have tests anymore, and in the future they will be added as a separate crate.
=> chore: remove unused dev dependencies on ethers

README.md, book/getting-started/start_a_new_project.md, ethers-providers/README.md
=> docs: update README.md and book ethers versions

bin/run_all_examples
Build all examples before running any one of them
- also build only once by using the '--examples' flag
=> chore: update examples script

Cargo.lock, ethers-signers/Cargo.toml, ethers-signers/src/trezor/app.rs
=> chore: bump trezor-client to 0.1.0

.github/workflows/ci.yml, ethers-contract/src/lib.rs, ethers-core/src/abi/mod.rs, ethers-middleware/src/signer.rs, ethers-providers/src/rpc/provider.rs, ethers-providers/src/rpc/transports/ws/mod.rs, ethers-providers/src/stream/tx_stream.rs, ethers-providers/tests/it/main.rs, ethers-providers/tests/it/provider.rs, ethers-solc/Cargo.toml, ethers-solc/src/artifacts/mod.rs, ethers-solc/src/compile/project.rs
=> chore: update CI and fix clippy

ethers-contract/src/contract.rs
Remove unused trait constraints. Use `D::new` to replace `event_with_filter` for `fn event`
=> improve `ContractInstance` impls

ethers-etherscan/src/verify.rs
Closes #2307
The library currently does not support proxy contract verification on
Etherscan.
Implemented the proxy verification endpoint using the etherscan Client module
and existing patterns present there.
=> feat: verification and status check for proxy contracts

ethers-core/src/types/signature.rs
=> fix: avoid payload moving

.github/workflows/book.yml, .github/workflows/ci.yml, .github/workflows/deps.yml
=> ci: add timeout to all jobs

ethers-contract/ethers-contract-abigen/Cargo.toml, ethers-contract/ethers-contract-abigen/src/contract.rs, ethers-contract/ethers-contract-abigen/src/lib.rs, ethers-contract/ethers-contract-abigen/src/verbatim.rs
Print the parsed ABI as tokens into a constructor function
=> feat(abigen): do not re-parse ABI at runtime

ethers-solc/src/compile/mod.rs
=> chore: rustfmt

ethers-core/src/utils/geth.rs
the `unused_port` is a bit hacky.
this sets the port to 0 and lets the os choose, then extracts the chosen port from the ouput
=> fix: let geth chose ports by default

ethers-etherscan/src/contract.rs, ethers-etherscan/src/utils.rs, ethers-etherscan/tests/it/contract.rs
=> fix(etherscan): `SourceCode` deserialization

ethers-solc/Cargo.toml
=> chore(deps): bump svm-rs

ethers-solc/src/resolver/mod.rs
error will include the hashes
ref https://github.com/foundry-rs/foundry/issues/5601
=> chore: include error in log message

ethers-contract/ethers-contract-abigen/src/contract.rs, ethers-core/src/abi/human_readable/mod.rs
Don't bubble up errors with `eyre` because they do not get displayed in `Display` impl (used by macros)
=> chore: improve ABI parser and Abigen errors

ethers-providers/src/rpc/transports/ws/mod.rs, ethers-solc/src/artifact_output/mod.rs, ethers-solc/src/compile/output/mod.rs
Borrowed versions of `into_artifacts`
=> feat(solc): add more borrowed artifact iterators

ethers-contract/src/contract.rs, ethers-contract/src/event.rs, ethers-contract/src/factory.rs, ethers-contract/src/multicall/mod.rs, ethers-core/src/utils/anvil.rs, ethers-core/src/utils/ganache.rs, ethers-core/src/utils/geth.rs, ethers-middleware/src/builder.rs, ethers-middleware/src/lib.rs, ethers-middleware/src/transformer/ds_proxy/mod.rs, ethers-solc/src/compile/project.rs
`rustdoc::redundant_explicit_links`
=> chore: fix new rustdoc lints

ethers-core/src/types/chain.rs
Add support for `Holesky` chain id.
See https://github.com/eth-clients/holesky
=> feat: holesky

ethers-contract/src/multicall/constants.rs
Base and Base Goerli are already supported in `ethers` and the multicall contract is already deployed to both of them on the same address.
Added Base and BaseGoerli to `MULTICALL_SUPPORTED_CHAIN_IDS`
=> feat(multicall): add support for Base mainnet and Goerli

ethers-contract/Cargo.toml, ethers-contract/tests/it/abigen.rs
Circular dependency
cc @gakonst
=> chore: remove ethers-signers from ethers-contract dev-dependencies

ethers-etherscan/src/account.rs
Closes #2612
deserializes methodid correctly
@DaniPopes
=> fix: deserialize methodId as bytes

ethers-core/src/types/chain.rs
add new etherscan urls for hoelsky
=> feat: add new holesky etherscan urls

ethers-signers/Cargo.toml
Refs: https://github.com/foundry-rs/foundry/pull/5979
=> chore(deps): pin protobuf to 3.2.0

ethers-core/src/types/signature.rs
=> test: add recover test

ethers-core/src/types/fee.rs
ref geth
https://github.com/ethereum/go-ethereum/blob/0004c6b229b787281760b14fb9460ffd9c2496f1/internal/ethapi/api.go#L84-L88
=> fix: allow missing base fee and reward vecs

ethers-core/src/types/chain.rs
Viction is a growing L1 chain that launched recently. It isn't currently supported by ethers-rs.
Added Viction to the `Chain` enum.
=> feat(chain): add viction

ethers-solc/src/compile/mod.rs
=> chore: bump solc check

ethers-providers/src/middleware.rs
=> fix return value of get_transaction_by_block_and_index

ethers-core/src/types/block.rs
I need this to use these as keys of a HashMap
=> Add Hash to BlockId

ethers-providers/Cargo.toml, ethers-providers/src/rpc/connections.rs, ethers-providers/src/rpc/transports/ws/manager.rs
Outdated enr version.
Bump enr version. 
=> Bump enr version

ethers-core/src/types/chain.rs
Add support for the Elastos  mainnet.
=> feat(chain): add elastos networks

README.md
Updates deprecation notice as the process has completed
It may also be an idea to mark `ethers-rs` as a public archive if it is no longer being maintained
=> chore: update deprecation notice
